### ISSUE TITLE
Azure TableUtilities is not exported

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-storage-node#101]
Per the docs of azure storage, you need to use the entity generator in order to insert a new item to azure table storage. Looking at azure.js, TableUtitlities is not exported. It should be a small fix. 

This [issue](https://github.com/Azure/azure-sdk-for-node/issues/1507) was filed by a customer in azure-sdk-for-node repo

**Comment by yaxia** [comment]
@amarzavery The TableUtilities is exported at: https://github.com/Azure/azure-storage-node/blob/master/lib/azure-storage.js#L47
You can use ```TableUtilities.entityGenerator``` to generate the table entities.
