### ISSUE TITLE
define max size limit for Azure blob stream i.e. truncate the file

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-storage-node#103]
I am not sure if this is a `feature request` or if there is already some options available.

I am using `createBlockBlobFromStream` and I want to define a max size for the file. File should get uploaded to blob and if the max size is reached then it should be truncated.

For ex. if I am uploading a `80 Mb` fiile and I specify max size to be `50 Mb` then only `50 Mb` of the file should be uploaded to blob. (required for video uploads)

Please see the [stackoverflow question](http://stackoverflow.com/questions/29841688/define-size-limit-for-azure-blob-stream-i-e-truncate-the-file) for more details.

**Comment by amarzavery** [comment]
https://github.com/Azure/azure-sdk-for-node/issues/1410

**Comment by yaxia** [comment]
@amarzavery Thanks for raising the issue. It has been noted and we will have it in a later release.

**Comment by amarzavery** [comment]
@yaxia If you look at the original bug posted on azure-sdk-for-node https://github.com/Azure/azure-sdk-for-node/issues/1410, some one from the storage team gave the same response six months ago and it has not been fixed yet. Can you provide a timeline for fixing this issue?

**Comment by yaxia** [comment]
Please get the latest release (0.7.0) for the fix. Thanks.
