### ISSUE TITLE
Large write streams can silently corrupt the global agent pool.

### ISSUE THREAD

**Issue by toddtarsi** [Azure/azure-storage-node#104]
What I've seen occurring is that the block blob stream updates conclude and emit close properly, but the stream and the request act as corrupt entries in the global Agent pool, causing any additional api calls against blobService to accumulate in as unconverted request entries that never complete.

Reproduction steps:
I take the below image, and upload it as a stream using the code below.
After this upload completes, any stream read operations against the blobService hang indefinitely, silently causing the blobService to become nonfunctional.

This issue has been tested in Ubuntu v14.04, as a VM in Azure.
The Node Version is 0.10.36.

````
        function(name, data, _cb, opt_options){
          var self = this;
          var failed = false;
          var on_complete = single_complete(_cb);
          var datastream = stream_from_data(data);
          // Will never lose data as our transaction blob will only grow.
          var blob_stream = blobService.createWriteStreamToBlockBlob(
            self.name,
            '' + name,
            opt_options || {}
          );
          datastream.body.pipe(blob_stream);
          blob_stream.on('close', function(){
            if(failed) return;
            on_complete();
          });
          blob_stream.on('error', function(err){
            failed = true;
            if(isTempError(err)) return setTimeout(function(){
              self.retry('__update', 2, name, data, on_complete);
            }, 5000);
            else api.util.throw(err);
          });
          function single_complete(cb){
            var finished = false;
            return function(r){
              if(finished) return;
              finished = true;
              cb(r);
            }
          }

      function stream_from_data(text){
          var input_buffer = new Buffer(text, 'binary'); // or fs.readFileSync(imagepath, 'binary')
          var s = new stream.Readable();
          s._read = function(){}; // Stream implementor
          s.push(input_buffer);
          s.push(null);

          return {
            body: s,
            length: input_buffer.length
          };
        };
      }

````

The image itself is also attached.

What is working for me as a fix, but probably needs a little bit of the MS polish, is my fork, which separates stream invocations into their own http.Agent each time. I've written the changes into a single commit, only about 5 or 6 different lines. Sorry, I didn't write any code for figuring out the proper protocol.

https://github.com/toddtarsi/azure-storage-node/commit/e93bcfe84995517bc666b71a5b8786aea09a2424

Also, I am not 100% positive, but I believe this is the issue underlying your issue:

https://github.com/request/request/issues/1793 

Thank you, and let me know if there is anything else you'd like to see from me.
- Todd

PFA Image used in issue reproduction 
![failingupload](https://cloud.githubusercontent.com/assets/4707505/11679961/8ad20bac-9e1a-11e5-803f-7392513f0621.png)

**Comment by yaxia** [comment]
@toddtarsi Thanks for raising the issue. We are working on a fix and will have it in a later release.

**Comment by yaxia** [comment]
Please get the latest release (0.7.0) for the fix. Thanks.
