### ISSUE TITLE
util.inspect on Node.js 5.x.x Causing Issues

### ISSUE THREAD

**Issue by atom0s** [Azure/azure-storage-node#111]
I have a project that we use this module in. Upon making a request to **createContainerIfNotExists**, the project continues to execute as if the call happened but it does not. The module will eventually get to this line and stop:

    self.logger.log(Logger.LogLevels.DEBUG, 'FINAL REQUEST OPTIONS:\n' + util.inspect(finalRequestOptions));

Calling util.inspect lands up eventually getting to this following block of code within node's util.js:

    function ensureDebugIsInitialized() {
      if (Debug === undefined) {
        const runInDebugContext = require('vm').runInDebugContext;
        Debug = runInDebugContext('Debug');
      }
    }

The last line, Debug = runInDebugContext('Debug'); lands up never returning and the promise that called it never returns/ends. This completely causes all debugging for the app that makes use of your module to stop working.

**Comment by yaxia** [comment]
@atom0s I cannot repro the issue as you described. The request options are printed as expect. Could you please share more about your code of calling the API? Thanks.

**Comment by atom0s** [comment]
With node v5.4.1 this error persists. It is a known error/issue on Node's issue tracker as well here:
https://github.com/nodejs/node/issues/4440

Our project makes use of this in a manner like this:



    var azure = require('azure-storage');
    var blobService = azure.createBlobService();

    module.exports.createContainer = function createContainer(container, callback) {
        blobService.createContainerIfNotExists(container, { publicAccessLevel: 'container' }, function (err, result, response) {
            callback(err, result);
        });
    }

    ....

    <ModuleName>.createContainer('images', function (err, result) {

Which lands up getting into azure-storage-node's code which calls the above logging feature causing the crash.

**Comment by yaxia** [comment]
I see. I can repro it with step-by-step debug and get no problem when just continue to run the code in the debug mode. It looks like a nodejs debugger issue.

**Comment by tSreeram** [comment]
I also faced similar util.inspect issue. But after upgrade to NodeJS 5.6 (latest) the debugger issue is resolved.

**Comment by yaxia** [comment]
@tSreeram Thanks for sharing. @atom0s I am going to close the issue. Please feel free to reopen it if the latest Nodejs doesn't work for you. Thanks.
