### ISSUE TITLE
ETIMEDOUT errors while accessing azure blob storage during Load Test

### ISSUE THREAD

**Issue by prashanthmadi** [Azure/azure-storage-node#112]
I was getting connection timeout errors while trying to access azure blob storage during load test from linux VM.

Error : nucleus@nucleus-perf-singlebox:~/logs/job-server-ddp$ grep -A 8 -win "ETIMEDOUT" *.1
nucleus-server-6.log.1:7116:: { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
nucleus-server-6.log.1:7117:2015-12-09T23:34:04.837Z
ERROR ERROR - 'Error: connect ETIMEDOUT
nucleus-server-6.log.1-7118-    at Object.Future.wait (/home/nucleus/Deployment/5bc8f578e70c25a908213f108efa63f02300ab08/programs/server/node_modules/fibers/future.js:398:15)
nucleus-server-6.log.1-7119-    at packages/meteor/helpers.js:119:1
nucleus-server-6.log.1-7120-    at makeReadStream (packages/core/server/lib/blobs/azure/azureBackend.js:128:1)
nucleus-server-6.log.1-7121-    at Object.makeReadStream (packages/core/server/lib/blobs/azure/azureBackend.js:26:1)
nucleus-server-6.log.1-7122-    at makeReadStream (packages/core/server/lib/blobs/blobs.js:336:1)
nucleus-server-6.log.1-7123-    at Object.Core.blobs.makeReadStream [as makeBlobReadStream](packages/core/server/lib/blobs/blobs.js:158:1)
nucleus-server-6.log.1-7124-    at Object.keyEntry.crypto.makeBlobReadStream (packages/imaging/lib/crypto/getStudyBucketCrypto.js:182:1)
nucleus-server-6.log.1-7125-    at readBytesAsync (packages/imaging/processors/p10ChunkProcessor/helpers/readBytesAsync.js:17:1)

Could you help us with further troubleshoot process.

**Comment by yaxia** [comment]
Could you please add the following line when you create the blob service client to enable the verbose log and share the results again? Thanks.
``` javascript
  var azure = require('azure-storage');
  var blobService = azure.createBlobService(.../* storage account info */);
  blobService.logger.level = azure.Logger.LogLevels.DEBUG;  
  ...
```

**Comment by elmalto** [comment]
Hi I am running into the same issue when copying many files. I tried setting the timeout to 600000, but it does not do me any good...

```
[D] Uploading main/bower_components/angular/package.json encoding undefined
[2016-05-04T20:40:44.948Z]debug : FINAL REQUEST OPTIONS:
{ url: 'https://*.blob.core.windows.net:443/test/main/bower_components/angular/package.json?timeout=600000',
  method: 'PUT',
  headers:
   { 'content-type': 'application/json',
     'x-ms-blob-type': 'BlockBlob',
     'content-length': 572,
     'cache-control': 'public, max-age=31530000',
     'x-ms-client-request-id': '...',
     'user-agent': 'Azure-Storage/0.3.3 (NODE-VERSION v4.4.3; Darwin 15.4.0)',
     'x-ms-version': '2014-02-14',
     'x-ms-date': 'Wed, 04 May 2016 20:40:44 GMT',
     accept: 'application/atom+xml,application/xml',
     'Accept-Charset': 'UTF-8',
     authorization: '...' },
  encoding: undefined }
>> Error while copying to azure Error: connect ETIMEDOUT 40.78.112.72:443
```

Anything I can do?

**Comment by hasonmsft** [comment]
@elmalto , could you try the latest package instead of 0.3.3?
