### ISSUE TITLE
There is no export for SharedAccessSignature (and others) from 'azure-storage' module used in main module

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-storage-node#118]
Please refer to the issue filed by the customer in node sdk

https://github.com/Azure/azure-sdk-for-node/issues/1616

**Comment by amarzavery** [comment]
@yaxia - It would be nice if you could respond to the customer in the node sdk where the actual issue was filed.

**Comment by yaxia** [comment]
@amarzavery The feature has been deprecated when we release azure-storage 0.1.0 on 2014.06.12. 
Please check the change log [here](https://github.com/Azure/azure-storage-node/blob/master/ChangeLog.txt#L202).
