### ISSUE TITLE
Some datatypes for queried table entity properties aren't explicitely given

### ISSUE THREAD

**Issue by craxal** [Azure/azure-storage-node#121]
When using the API to query tables (`queryEntities`), certain datatypes aren't explicitly given (`Entity<T>.$` is not defined):
- `Edm.Int32`
- `Edm.Double`
- `Edm.Boolean`

Granted, the property values are automatically converted to the appropriate JavaScript primitives, but that means we have to explicitly check for those datatypes ourselves, otherwise the datatype gets interpreted as `Edm.String`.

Unless I'm missing something, it would be far more preferable to always set the datatype.

**Comment by yaxia** [comment]
For now, we added the odata.type annotation according to the spec [here](https://msdn.microsoft.com/en-us/library/azure/dn535600.aspx). We do have an issue reported at https://github.com/Azure/azure-storage-node/issues/40 . We are working on a full solution for it. Please stay tuned, thanks.

**Comment by yaxia** [comment]
https://github.com/Azure/azure-storage-node/issues/40 is fixed in version 1.0. Other types can be determined from [the type detection heuristics](https://msdn.microsoft.com/en-us/library/azure/dn535600.aspx). So we will close this issue.
