### ISSUE TITLE
An unhandled exception occurred

### ISSUE THREAD

**Issue by Uma-Mahesh** [Azure/azure-storage-node#122]
I wrote a file service to download a file from "FileStorage". I want the sent the file stream in response. Below is my code snippet. 

```
var option = new Object();
	option.disableContentMD5Validation = true;
	option.maximumExecutionTimeInMs = 20 * 60000;
	option.timeoutIntervalInMs = 20 * 6000;

fileService.getFileToStream(shareName, dirPath, fileName, response, option, function(error, result, res) {
		if(!error) {
			if(res.isSuccessful) {
				console.log(result);
        console.log(res);
        console.log("Success!");
      }
		}
});
```

More frequently I am getting below error. 

> ERROR
> An unhandled exception occurred. Error: Can't set headers after they are sent.
>     at ServerResponse.OutgoingMessage.setHeader (http.js:679:11)
>     at ServerResponse.res.setHeader (D:\home\site\wwwroot\node_modules\express\node_modules\connect\lib\patch.js:59:22)
>     at ServerResponse.res.set.res.header (D:\home\site\wwwroot\node_modules\express\lib\response.js:518:10)
>     at addDefaultHeaders (D:\home\site\wwwroot\node_modules\azure-mobile-services\runtime\request\requesthandler.js:590:9)
>     at ServerResponse.<anonymous> (D:\home\site\wwwroot\node_modules\azure-mobile-services\runtime\request\requesthandler.js:299:13)
>     at ServerResponse._.wrap [as end] (D:\home\site\wwwroot\node_modules\underscore\underscore.js:692:22)
>     at Request.onend (stream.js:66:10)
>     at Request.EventEmitter.emit (events.js:126:20)
>     at IncomingMessage.Request.onRequestResponse.strings (D:\home\site\wwwroot\App_Data\config\scripts\node_modules\azure-storage\node_modules\request\request.js:1153:12)
>     at IncomingMessage.EventEmitter.emit (events.js:126:20)

I implemented this with ref of [Ref](http://stackoverflow.com/a/33230238/1147434).

How to overcome this issue.

**Comment by hasonmsft** [comment]
Thanks for raising this issue. We'll try to reproduce this issue from our side and get you updated about the status. At the same time, may I know
    1. What's the version of the azure storage & express module you are using? 
    2. What's size of the file approximately?

**Comment by yaxia** [comment]
It looks that you call `writeHead` with status code 200 which prevents later setting header. You might want to follow the patterns like:

- writeHeader, then no headers can be set.
- res.setHead, then res.end

Could you share more codes where the response is used, especially the `setHeader` calls and the event handlers of the server response?

**Comment by Balajipss** [comment]
Hi @yaxia,

We are using Spring MVC. Please find the below code

`RequestConfig requestConfig = RequestConfig.custom().setConnectTimeout(100 * 1000).build();
		          HttpClient client = HttpClientBuilder.create().setDefaultRequestConfig(requestConfig).build();
		          HttpGet get=new HttpGet(testGuideUrl);
		            
		          get.setHeader("sharename","sharename");
		          get.setHeader("directorypath","directorypath_of_our_application");
		          get.setHeader("filename","App_Name_Test_Guide.json");
		          get.setHeader("X-MS-RANGE-GET-CONTENT-MD5","false");
		          get.setHeader("X-ZUMO-APPLICATION","AppKey");
		            
		          httpResponse=client.execute(get);
		          testguide=getTestGuideObject();`

**Comment by Uma-Mahesh** [comment]
Hi @hasonmsft ,

The azure storage version we are using is `0.7.0` and the express version is `4.13.3`. 
The size of the file is less than 1 MB.

**Comment by yaxia** [comment]
@Balajipss Are you talking about the same issue which Uma mentioned [here](http://stackoverflow.com/questions/33215170/sending-stream-of-data-in-response-node-js-azure-file-service-using-node-js/33228769#33228769)? I've updated the answer in the thread as well. Please refer to the sample code there.

**Comment by vinjiang** [comment]
@Uma-Mahesh @Balajipss , we assume the issue is addressed. If not, please reopen this issue to let us know. Thanks!
