### ISSUE TITLE
Outdated examples - blobuploader

### ISSUE THREAD

**Issue by alokrajiv** [Azure/azure-storage-node#124]
The entire example of blobuploader is outdated. 

> azure-storage-node/examples/blobuploader/

Many functions have been changed ex.

> .createBlobService().getBlobUrl

**Comment by alokrajiv** [comment]
I'm interested to write another updated example actually.

**Comment by yaxia** [comment]
@alokrajiv Thanks for your interests and contribution in the library. We will create a dev branch and open for public PRs. Please stay tuned.

**Comment by hasonmsft** [comment]
@alokrajiv , we manually take your PR and the sample is updated.
