### ISSUE TITLE
SAS tokens created from table names with upper-case letters do not work

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-storage-node#129]
SAS tokens created from table names with upper-case letters via this library do not work.

The table name should be lower-cased before signing. See https://msdn.microsoft.com/en-us/library/azure/dn140255.aspx:
> •The canonicalizedresouce portion of the string is a canonical path to the signed resource. It must include the service name (blob, table, queue or file) for version 2015-02-21 or later, the storage account name, and the resource name, and must be URL-decoded. Names of blobs must include the blob’s container. **Table names must be lower-case.**

**Comment by hasonmsft** [comment]
Thanks for raising this issue. 

As the table name is explicitly passed to the API by caller, you can toLowerCase the table name parameter before calling the API as a workaround. 

TableService.prototype.generateSharedAccessSignature = function (table, sharedAccessPolicy)

We'll fix this in next release and get you updated after it's ready.

**Comment by StephenWeatherford** [comment]
Right, already did that workaround, so we're not blocked by this. Thanks!

Sent from my Windows Phone
________________________________

**Comment by hasonmsft** [comment]
@StephenWeatherford , this issue has been fixed in the latest version. You can try it out - [PUBLIC NOTICE: Azure Storage Node 0.10.0 Release](https://github.com/Azure/azure-storage-node/issues/138)
