### ISSUE TITLE
QueueService.getMessages has the possibility to hang.

### ISSUE THREAD

**Issue by toddtarsi** [Azure/azure-storage-node#130]
I'm not sure what the exact conditions are that results in this, but I've seen it happen at high utilization and very low utilization. It seems very intermittent, so I'm not sure of the exact source of the issue.

Very rarely, queueService.getMessages won't return ever.

I intend to wrap this call in a timeout, to retry if it delays overly long. Is there an internal timeout mechanism that I would be better off using?

Thanks as always, sorry to not have many details on the issue this time around. Rather than trying to trace it all the way through, I'm just going to wrap the call.

**Comment by hasonmsft** [comment]
@toddtarsi , please check out the documentation of the queueService API from http://azure.github.io/azure-storage-node/QueueService.html#getMessages 

You may want to set options.timeoutIntervalInMs & options.maximumExecutionTimeInMs.

**Comment by toddtarsi** [comment]
Thank you very much for the tip @hasonmsft. Will use this option as a guard and close.
