### ISSUE TITLE
PDF Damaged on upload

### ISSUE THREAD

**Issue by Leeh91** [Azure/azure-storage-node#131]
I'm trying to upload some pdf file and it returns success on finish. But when I check the files It says they're damaged.

**Comment by yaxia** [comment]
@Leeh91 You might want to check the issue [here](http://stackoverflow.com/questions/33269923/saving-blob-might-be-data-returned-by-ajax-call-to-azure-blob-storage-creates/33348584#33348584). If it doesn't help, would you please elaborate a bit more about your environment and the API you called for uploading? It would be better if you can share the code snippet.
