### ISSUE TITLE
Large test file

### ISSUE THREAD

**Issue by jacobludriks** [Azure/azure-storage-node#133]
the file azure-storage\test\recordings\blobservice-uploaddownload-tests.nock.js is quite large - nearly 70mb. is there a way to exclude this when pulling the npm package? it's completely blown out my project size.

**Comment by hasonmsft** [comment]
@jacobludriks , thanks for raising this issue. We'll exclude the test files from NPM package in next release.

**Comment by hasonmsft** [comment]
@jacobludriks ， the test files are excluded from the latest NPM package. You can try it out - [PUBLIC NOTICE: Azure Storage Node 0.10.0 Release](https://github.com/Azure/azure-storage-node/issues/138)
