### ISSUE TITLE
Signature for shouldRetry in .d.ts is incorrect

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-storage-node#139]
Currently says (0.9):

shouldRetry(statusCode: number, retryData: RetryPolicyFilter.IRetryContext): void;

I believe it should be:

shouldRetry(statusCode: number, requestOptions: RetryPolicyFilter.IRetryRequestOptions): void;

**Comment by yaxia** [comment]
Good catch. We will update, thanks. @hasonmsft

**Comment by hasonmsft** [comment]
@StephenWeatherford , this issue has been fixed in the latest release. Could you try it out?
