### ISSUE TITLE
withFilter should have strongly-typed overrides in blob/queue/table/fileService in definitions file

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-storage-node#141]
Right now in TypeScript, if you want to use withFilter, you have to cast the return value, e.g.:

    blobService = <azureStorage.BlobService>blobService.withFilter(retryPolicy);

blobService.withFilter should return a blob service, not a generic storage service.  Etc. for the other services.

**Comment by hasonmsft** [comment]
@StephenWeatherford , thanks for raising this issue. Will address this in next release

**Comment by hasonmsft** [comment]
@StephenWeatherford , this issue has been fixed in the latest release. Could you try it out?
