### ISSUE TITLE
SpeedSummary code throws error that cannot be caught

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-storage-node#143]
One way to reproduce this problem (there are likely others) is to call getBlobToLocalFile or getBlobToStream when you don't have enough disk space for the blob to be downloaded to the local drive.  Eventually the following code will trigger:

SpeedSummary.prototype.getAutoIncrementFunction = function(size) {
  var self = this;
  return function(error, retValue) {
    if(error) {
      throw error;  <<<<<<<<<<<<<<<<<<<<   ERROR THROWN HERE
    } else {
      var doneSize = 0;
      if((!retValue && retValue !== 0) || isNaN(retValue)) {
        doneSize = size;
      } else {
        doneSize = retValue;
      }
      self.increment(doneSize);
    }
  };
};

Seems like you shouldn't be throwing errors at all in your node.js code (you do a lot in preconditions), but this case certainly shouldn't be happening.

The exception does not get handled, and the caller has no way to handle it whatsoever, so the getBlobToLocalFile/getBlobToStream call never calls its callback.

Callback at the exception:

(anonymous function) (C:\Repos\Storag…dsummary.…:172)
onwriteError (_stream_writable.js:301)
onwrite (_stream_writable.js:322)
WritableState.onwrite (_stream_writable.js:89)
(anonymous function) (fs.js:1875)
strWrapper (fs.js:619)

NOTE: We're currently working around this by modifying the storage client's code, and using getBlobToStream instead of getBlobToLocalFile, but it would be nice to remove that hack eventually.

CURRENT WORK-AROUND:
function _patchSpeedSummary(speedSummary: azureStorage.common.streams.speedsummary.SpeedSummary, onError: (error: any) => any) {
    // Work around a bug in azure client lib where exceptions thrown in SpeedSummary cannot be caught
    var getAutoIncrementFunction = (<any>speedSummary).getAutoIncrementFunction;
    (<any>speedSummary).getAutoIncrementFunction = (size: number) => {
        var f = getAutoIncrementFunction.call(speedSummary, size);

        return (error, retValue) => {
            try {
                return f(error, retValue);
            } catch (error) {
                onError(error);
            }
        }
    };
}

**Comment by hasonmsft** [comment]
@StephenWeatherford thanks for raising this issue. Will address this in next release.

**Comment by hasonmsft** [comment]
@StephenWeatherford , this issue has been fixed in the latest release. Could you try it out?
