### ISSUE TITLE
[Refining] Use `endpoint_suffix` instead of the complete uri in BlobService/TableService/..

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-storage-node#147]
```
function BlobService(storageAccountOrConnectionString, storageAccessKey, host, sasToken)
```

When creating a blobservice in AzureChinaCloud, I need to input the complete uri for the parameter `host`. For instance, `binxi041402sa.blob.core.chinacloudapi.cn`.
However, in azure-storage-python, I only need to input `endpoint_suffix` as the host base. For instance, `core.chinacloudapi.cn`.

Here is a proposal to use `endpoint_suffix` instead of the complete uri. Do you guys think if it makes sense?

**Comment by hasonmsft** [comment]
@bingosummer , Thanks for raising this issue. We'll triage this and try to address it in upcoming releases.

**Comment by hasonmsft** [comment]
@bingosummer , we added the support for endpoint suffix in the latest version. 

You can specify the endpoint suffix when calling the constructor. 
`function BlobService(storageAccountOrConnectionString, storageAccessKey, host, sasToken, endpointSuffix)`

And you can also define the endpoint suffix in the connection string:
```
DefaultEndpointsProtocol=[http|https];
AccountName=myAccountName;
AccountKey=myAccountKey;
EndpointSuffix=mySuffix;
```
