### ISSUE TITLE
Upload to container with two hyphen characters fails without error.

### ISSUE THREAD

**Issue by samkelleher** [Azure/azure-storage-node#148]
Literally, an identical configuration, uploading to the same storage account, same code, one to a container called 'original-files' and the other 'original-files-dev'. The -dev one is used during development.

The upload to container 'original-files' works fine.

The upload to container 'original-files-dev', an otherwise identical container, fails. Any container name that I then go on to create, that contains more than one hyphen charcter will fail. If I create one without two hyphens, the same code works.

No exception is thrown. But nothing is ever written to the stream, thus the thread just sits there forever.

```
const writeStream = blobService.createWriteStreamToBlockBlob(
                containerName,
                fileName,
                {
                    contentSettings: {
                        contentType: contentType,
                        cacheControl: cacheControl
                    }
                }
            );
```

**Comment by hasonmsft** [comment]
@samkelleher , may I know what's the SDK version you are using? I cannot repro this issue with the latest version.

**Comment by samkelleher** [comment]
Hi @hasonmsft  - I'm using azure-storage v0.10.0 on node 5.10.1 running in OSX on the new resource managed storage accounts in Azure (not the ones marked legacy).

I thought it might be a code issue with the way babel is working for me, but identical code will work on the same storage account with a container with one hyphen, and then fail with one using two.

My immediate issue is resolved since I started using a container name with just a single name; so I'll close this issue as not sure what further use I can be.  I guess look out for any additional reports. It's certainly an unusual one.
