### ISSUE TITLE
Saving entity as string changes the data type to double if the value is numeric

### ISSUE THREAD

**Issue by ukluk** [Azure/azure-storage-node#150]
The entity has a string field declared as:
        public string OfferUPC { get; set; }

Here is snippet to inset:

`campaignEntity.OfferUPC = "12345" `

But after inspecting the row with code I get "12345.0"
And browsing with the Azure Explorer, the type is a double

**Comment by hasonmsft** [comment]
@ukluk , from the code snippet you provided, you are inserting the row using C#, right? And browsing using [Azure Explorer (http://storageexplorer.com/)]?

**Comment by ukluk** [comment]
Correct: insert with C#, browse with tool. But It appears that the problem is with the new Azure explorer tool and not with the SDK.


Not only I browsed the table, but also updated a flag, and then the string fields in the entity that had numeric values converted to Double.


Suspect that the serializer is infering the type.


I will try to replicate tomorrow and share my results.


Thx


Get Outlook for Android






On Mon, May 9, 2016 at 7:35 PM -0700, "Haibo Song" <notifications@github.com> wrote:





@ukluk , from the code snippet you provided, you are inserting the row using C#, right? And browsing using [Azure Explorer (http://storageexplorer.com/)]?

---

**Comment by ukluk** [comment]
Haibo, If I am posting to the wrong group, let me know, but I saw a similar entry regarding doubles and strings with TableStorage and Node.JS


I have a table that reads different using 2 off-the-shelf tools

My table stores coupons, if I look it with Nudesic Storage explorer, the data types are correct, please see the image:
[cid:image003.png@01D1AA97.2131F200]

But if you use the Microsoft Azure Storage Explorer the types are changed from string to double where the string is numeric

[cid:image006.png@01D1AA97.2131F200]

The real problem is when I use C# to read entities my offer code reads like 113215.0

The problem is not in the tool but the SDK. I am going to downgrade the NuGet and see if that fixes the issue, but letting you know that the serializer is doing some type inferring ignoring the defined type selected.

Hope this helps.

Uri Kluk


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by hasonmsft** [comment]
@ukluk , I already forwarded the request to Azure Explorer team. If you didn't get response, could you open an issue on the [storage explore github](https://github.com/Azure/deco ) for help?
