### ISSUE TITLE
[Typescript typings] Create a better version of type definitions 

### ISSUE THREAD

**Issue by SomaticIT** [Azure/azure-storage-node#152]
Hi,

I use the `azure-storage` library for many projects and I also use `typescript` in many of these.

The actual typescript definitions ([source](https://github.com/Azure/azure-storage-node/blob/master/lib/azure-storage.d.ts)) are not reliable and are really difficult to maintain.

During my development I always hacked the _source_ declarations and adapted it to my project so I decided to build a new [typings](https://github.com/typings/typings) project to host a better version of `azure-storage-node` type definitions.

The project is available at https://github.com/typed-contrib/azure-storage-node.
It is built by following the same architecture as the javascript sources and it is tested over the source samples and library tests.

This project can evolve in two way:
- It can be merged with this repository so maintenance of both javascript and typings can be centralized.
- It can live as side of this project by removing the actual definitions and add a link in the documentation to explain how to obtain the type definitions for `azure-storage` module.

What do you think is the better solution ?

Thanks.

**Comment by hasonmsft** [comment]
@SomaticIT , thank you for your great idea. We are evaluating this internal and will get you updated when we get a conclusion about the solution.

**Comment by mikeesouth** [comment]
Any update on this?

**Comment by mikeesouth** [comment]
I would suggest adding: `"typings": "dist/aurelia-history.d.ts"` to package.json in order for typescript to find the typings correctly when using node module resolution. @hasonmsft do you agree? I can submit a PR if you want.

**Comment by hasonmsft** [comment]
@mikeesouth , sure, your contribution is warmly welcome.

**Comment by andrewconnell** [comment]
Hmm... when I submitted that PR#177 for the `package.json` to add `typings`, I didn't realize that the other nested typings would be included. So... when I import this, I get a TON of duplicate identifiers if I'm using a more recent version of the Node.js type def.

Shouldn't the dependencies be removed from `/typings`?

**Comment by xumx** [comment]
Please remove the /typings/node from the repository.

**Comment by XiaoningLiu** [comment]
```/typings/node``` is still useful for TypeScript@1.*.* environment, where latest ```@types/node``` definition cannot compile successfully with some TypeScript v1 versions.

I'm not sure how many customers still depends on TypeScript@1, but removing ```/typings/node``` is a potential breaking change for them.

Currently, ```/typings/node``` should not have influences when you depends on ```@types/node``` and use latest typescript v2 version. 

So we will still keep it here, and remove it in next major version.
