### ISSUE TITLE
doesTableExist null ref's if there's an error

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-storage-node#153]
CODE: responseObject.tableResult.statusCode = responseObject.response.statusCode;
ISSUE: responseObject.response is null when an error occurs and throws

See below:

TableService.prototype._doesTableExist = function (table, primaryOnly, optionsOrCallback, callback) {
  var userOptions;
  azureutil.normalizeArgs(optionsOrCallback, callback, function (o, c) { userOptions = o; callback = c; });

  validate.validateArgs('doesTableExist', function (v) {
    v.string(table, 'table');
    v.tableNameIsValid(table);
    v.callback(callback);
  });

  var options = extend(true, {}, userOptions);

  if(primaryOnly === false) {
    options.requestLocationMode = RequestLocationMode.PRIMARY_OR_SECONDARY;
  }

  var webResource = WebResource.get('Tables(\'' + table + '\')');
  RequestHandler.setTableRequestHeadersAndBody(webResource);

  var processResponseCallback = function (responseObject, next) {
    responseObject.tableResult = {};
    responseObject.tableResult.isSuccessful = responseObject.error ? false : true;
    responseObject.tableResult.statusCode = responseObject.response.statusCode;   **<<<<< responseObject.response is null when an error occurs**
    responseObject.tableResult.TableName = table;

**Comment by hasonmsft** [comment]
@StephenWeatherford , thanks for raising this issue. We'll address it in the next release.

**Comment by hasonmsft** [comment]
@StephenWeatherford , this issue has been fixed in the latest version. Could you please try it out?
