### ISSUE TITLE
getUrl method for table service

### ISSUE THREAD

**Issue by pcibraro** [Azure/azure-storage-node#156]
The TableService class does not have a getUrl method (equivalent to the one we have in the BlobService), so it's impossible to infer a direct url to the table when SAS and CORS are used.

**Comment by hasonmsft** [comment]
@pcibraro , thanks for raising this. We'll try to address it in next release.

**Comment by hasonmsft** [comment]
@pcibraro , we added the `getUrl` for `TableService` in the latest version 1.3.0.
