### ISSUE TITLE
sasSample does not work

### ISSUE THREAD

**Issue by pcibraro** [Azure/azure-storage-node#159]
I am not being able to run the sasSample included with the code. All the calls simply return 400 (bad request) when used against the storage emulator. Have something changed in the code or it could be an issue with the emulator ? Thanks

**Comment by hasonmsft** [comment]
@pcibraro , thanks for raising this issue. We acknowledged that this is an Azure Storage NodeJS library issue about emulator. Should be working fine against the live service. We'll try to address this in upcoming releases. Will get you updated about the status.

**Comment by vinjiang** [comment]
It's now fixed in 1.1.0. Thanks!
