### ISSUE TITLE
Javascript sdk for browsers

### ISSUE THREAD

**Issue by blrchen** [Azure/azure-storage-node#160]
I am looking for a pure javascript client side sdk which can run in browser. 

Run browserify on azure storage node sdk package is an option but current the output bundled is too large (3mb) which is not acceptable for web applications.

Any plan to have a pure javascript sdk for browsers which has full set of blockblob features with a reasonable size?

**Comment by gubyy** [comment]
+1

**Comment by XiaoningLiu** [comment]
@blrchen @gubyy Currently, there is privew version of the storage javascript client library. The size if around 1.3MB after minify, and will reduce the size in future versions. Welcome to have a try!

https://github.com/Azure/azure-storage-node
https://aka.ms/downloadazurestoragejs
