### ISSUE TITLE
Case for blob or file metadata property names not preserved

### ISSUE THREAD

**Issue by craxal** [Azure/azure-storage-node#163]
If I set a metadata property named "UPPERCASE" to a blob or file, I can confirm that it's saved in Azure exactly as I typed it. However, if I retrieve the metadata, I get "uppercase" back.

This is a serious issue, because multiple metadata set operations can change existing data unexpectedly. As above, if I want to add a metadata property, I have to know what metadata already existed and reset it, otherwise I delete everything. But retrieving the metadata mangles the existing metadata property names.

My understanding is that this is an underlying Node problem. The argument is, because HTTP headers are supposed to be case-insensitive, Node just converts everything to lowercase. But when the user is expecting his metadata properties (sent as headers) to be preserve as entered, we've got this issue.

**Comment by hasonmsft** [comment]
@craxal , thanks for raising this issue. We'll address this issue in the upcoming releases.

**Comment by hasonmsft** [comment]
@craxal , this issue has been addressed in the latest version. **Note** that this fix is only applicable for Node 0.12 or higher version.
