### ISSUE TITLE
List Files and Directory Segmented Does not retrieve last Modified date of files

### ISSUE THREAD

**Issue by rparikh-argus** [Azure/azure-storage-node#164]
I have used **listFilesAndDirectoriesSegmented** for retrieving list of files within a directory. I can't find a way to get last modified date except calling another method **getFileproperties** for each file. Is there any other way to achieve this?

**Comment by hasonmsft** [comment]
@rparikh-argus , unfortunately, this is the only way for you to achieve this. Refer to the REST API doc of [List Directories and Files](https://msdn.microsoft.com/en-us/library/azure/dn166980.aspx), the API doesn't return the last modified date of the files.
