### ISSUE TITLE
createFileFromStream without stream length

### ISSUE THREAD

**Issue by justincy** [Azure/azure-storage-node#166]
I would to use the `fileService.createFileFromStream()` method without having to specify the stream length, that way I could do this:

``` js
fileService.createFileFromStream('taskshare', 'taskdirectory', 'taskfile', request.get('/download/some/file'), function(error, result, response) {
  if (!error) {
    // file uploaded
  }
});
```

But since I have to know the stream length in advance, I can't just pipe the file download response. Instead I have to download the entire file and calculate its length at which point I might as well be using one of the other file creation methods.

**Comment by hasonmsft** [comment]
@justincy , for azure file, when creating the file, the length is required, refer to [Create File REST API] (https://msdn.microsoft.com/en-us/library/azure/dn194271.aspx ) for more detailed information. 

when using request module, you can get the content-length from the response header first before piping the response stream to the createFileFromStream API. Please let me know if this helps.

**Comment by mjaggard** [comment]
According to the REST API documentation, the required field is "x-ms-content-length" which means the "maximum size for the file, up to 1 TB" - does that mean that you could use the code listed here and just specify 1 TB for this value? In my use case, I want to upload from a source where I definitely don't know the size up front.
