### ISSUE TITLE
Tough-cookie package vulnerability

### ISSUE THREAD

**Issue by freakyfriday** [Azure/azure-storage-node#167]
There is a vulnerability in the tough-cookie package used by the current request package version 2.69.0

See https://nodesecurity.io/advisories/130

Please upgrade the  request package to version 2.74.1 as this uses the tough-cookie package 2.3.0 which doesn't have the above mentioned vulnerability.

**Comment by hasonmsft** [comment]
@freakyfriday , thank your for reporting this. We'll upgrade this request package.

**Comment by hasonmsft** [comment]
@freakyfriday , this issue has been addressed in the latest version.

**Comment by freakyfriday** [comment]
thank you :-)
