### ISSUE TITLE
Issues using Typescript and Webpack

### ISSUE THREAD

**Issue by mikeesouth** [Azure/azure-storage-node#168]
Hi,

I'm trying to use this lib in a typescript + webpack project. I've installed the module:
`npm install azure-storage --save`

When running webpack build I get errors in a lot of files from the library, there are two types of errors:
For .json files:

```
ERROR in ./~/azure-storage/~/har-validator/lib/schemas/pageTimings.json
Module parse failed: C:\projects\foo\node_modules\azure-storage\node_modules\har-validator\lib\schemas\pageTimings.json Unexpected token
You may need an appropriate loader to handle this file type.
| {
|   "type": "object",
|   "properties": {
|     "onContentLoad": {
 @ ./~/azure-storage/~/har-validator/lib/schemas/index.js 13:15-44
 @ ./~/azure-storage/~/har-validator/lib/index.js
 @ ./~/azure-storage/~/request/lib/har.js
 @ ./~/azure-storage/~/request/request.js
 @ ./~/azure-storage/~/request/index.js
 @ ./~/azure-storage/lib/common/services/storageserviceclient.js
 @ ./~/azure-storage/lib/common/common.js
 @ ./~/azure-storage/lib/azure-storage.js
 @ ./~/azure-storage-simple/dist/index.js
 @ ./src ^\.\/.*$
 @ ./~/aurelia-loader-webpack/dist/commonjs/aurelia-loader-webpack.js
 @ multi aurelia
```

For .js files:

```
ERROR in ./~/azure-storage/~/form-data/lib/form_data.js
Module not found: Error: Can't resolve 'fs' in 'C:\projects\foo\node_modules\azure-storage\node_modules\form-data\lib'
 @ ./~/azure-storage/~/form-data/lib/form_data.js 7:9-22
 @ ./~/azure-storage/~/request/request.js
 @ ./~/azure-storage/~/request/index.js
 @ ./~/azure-storage/lib/common/services/storageserviceclient.js
 @ ./~/azure-storage/lib/common/common.js
 @ ./~/azure-storage/lib/azure-storage.js
 @ ./~/azure-storage-simple/dist/index.js
 @ ./src ^\.\/.*$
 @ ./~/aurelia-loader-webpack/dist/commonjs/aurelia-loader-webpack.js
 @ multi aurelia
```

A third error for .js files is like this:

```
ERROR in ./~/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\projects\foo\node_modules\forever-agent'
 @ ./~/forever-agent/index.js 7:10-24
 @ ./~/azure-storage/~/request/request.js
 @ ./~/azure-storage/~/request/index.js
 @ ./~/azure-storage/lib/common/services/storageserviceclient.js
 @ ./~/azure-storage/lib/common/common.js
 @ ./~/azure-storage/lib/azure-storage.js
 @ ./~/azure-storage-simple/dist/index.js
 @ ./src ^\.\/.*$
 @ ./~/aurelia-loader-webpack/dist/commonjs/aurelia-loader-webpack.js
 @ multi aurelia
```

I'm using aurelia but I don't think it is related to the aurelia loader.
Any help is appreciated.

**Comment by mikeesouth** [comment]
It seems like installing `fs`, `tls` and `net` is required (i.e. `npm install fs tls net --save`). These packages are dependencies. Shouldn't these be declared as dependencies? I'm not actually using node.js, just npm. Maybe node.js would install fs, tls and net?
I don't know how to figure out the json problem though:
```
ERROR in ./~/azure-storage/~/har-validator/lib/schemas/pageTimings.json
Module parse failed: C:\projects\foo\node_modules\azure-storage\node_modules\har-validator\lib\schemas\pageTimings.json Unexpected token
You may need an appropriate loader to handle this file type.
| {
|   "type": "object",
|   "properties": {
|     "onContentLoad": {
 @ ./~/azure-storage/~/har-validator/lib/schemas/index.js 13:15-44
 @ ./~/azure-storage/~/har-validator/lib/index.js
 @ ./~/azure-storage/~/request/lib/har.js
 @ ./~/azure-storage/~/request/request.js
 @ ./~/azure-storage/~/request/index.js
 @ ./~/azure-storage/lib/common/services/storageserviceclient.js
 @ ./~/azure-storage/lib/common/common.js
 @ ./~/azure-storage/lib/azure-storage.js
 @ ./~/azure-storage-simple/dist/index.js
 @ ./src ^\.\/.*$
 @ ./~/aurelia-loader-webpack/dist/commonjs/aurelia-loader-webpack.js
 @ multi aurelia
```

**Comment by mikeesouth** [comment]
Solved the json problem. I moved the json loader to an earlier position/index in the webpack config. It was added after the javascript/typescript loader, it need to be before.

One question remains though, why isn't `fs`, `tls` and `net` declared as dependencies to `azure-storage` if they are in fact dependencies?

**Comment by hasonmsft** [comment]
@mikeesouth , fs, tls and net are NodeJS built-in modules which doesn't need explicit dependency declaration. 

BTW, thanks for raising this issue. We'll evaluate this and see how we can improve this in the future and will get you updated about the status.

**Comment by mikeesouth** [comment]
@hasonmsft I edited my comment above, manually installing `fs`, `tls` and `net` does not help. I still get this error:
```
ERROR in ./~/azure-storage/~/form-data/lib/form_data.js
Module not found: Error: Can't resolve 'fs' in 'C:\projects\foo\node_modules\azure-storage\node_modules\form-data\lib'
 @ ./~/azure-storage/~/form-data/lib/form_data.js 7:9-22
 @ ./~/azure-storage/~/request/request.js
 @ ./~/azure-storage/~/request/index.js
 @ ./~/azure-storage/lib/common/services/storageserviceclient.js
 @ ./~/azure-storage/lib/common/common.js
 @ ./~/azure-storage/lib/azure-storage.js
 @ ./~/azure-storage-simple/dist/index.js
 @ ./src ^\.\/.*$
 @ ./~/aurelia-loader-webpack/dist/commonjs/aurelia-loader-webpack.js
 @ multi aurelia
```

I do not use Node.js but I use their package system npm. I would assume that it would be easy to allow this library to work without implicitly requiring that Node.js is used as the server? I'm actually using ASP.NET Core as the server and trying to use Azure Storage from my typescript frontend.

I also tried adding this to my webpack config as suggested in other (similar) threads but it does not help:
```
node: {
  fs: 'empty'
}
```

Any ideas are welcome.

**Comment by hasonmsft** [comment]
@mikeesouth , the webpack works fine from my side. If you meet the error - `module not found: Error: Cannot resolve module 'browserify-fs'`, run `npm install browserify-fs`. 

Here is my result and configuration for your reference: 
Result:
```
E:\tmp\webpacktest>webpack
Hash: 9057c910d20f69785140
Version: webpack 1.13.1
Time: 2710ms
    Asset     Size  Chunks             Chunk Names
bundle.js  3.65 MB       0  [emitted]  main
   [0] ./index.js 62 bytes {0} [built]
    + 404 hidden modules
```

-  package.json:
```
{
  "name": "webpacktest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "azure-storage": "^1.1.0"
  },
  "devDependencies": {
    "json-loader": "^0.5.4",
    "webpack": "^1.13.1"
  }
}
```

- webpack.config.js:
``` 
module.exports = {
     entry: './index.js',
     output: {
         path: '.',
         filename: 'bundle.js'
     },
     module: {
          loaders: [
              { test: /\.json$/, loader: 'json-loader' }
          ]
      },
     resolve: {
         extensions: ['', '.webpack.js', '.web.js', '.js']
     },
     node:{
        console: 'empty',
        fs: 'empty',
        net: 'empty',
        tls: 'empty'
    }
 };
```

- index.js
```
var storage = require('azure-storage');
console.log(storage);
```

**Comment by mikeesouth** [comment]
I was using webpack2, maybe it is related to that version? Unfortunately I am on vacation and cannot test this issue at the moment. It can also be related to how aurelia-loader-webpack works but I don't think so. I may revisit this in a couple of weeks.
Thanks for the help so far @hasonmsft

**Comment by jahmaiosullivan** [comment]
Running into the same issue. Doing this fails, which is interesting:

`  var fs = require('fs');
  var azure = require('azure-storage');`

fs resolves to empty as expected by my webpack config:

`node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  },`


But the immediate call to ` var azure = require('azure-storage');` fails on the following line:
`var fs = require('fs');` inside azure-storage/lib/common/util/util.js.

The error is:

`Uncaught Error: Cannot find module "fs"webpackMissingModule @ util.js?0823:17(anonymous function) @ util.js?0823:17(anonymous function) @ util.js?0823:598(anonymous function) @ main-0f62f26….js:8041__webpack_require__ @ main-0f62f26….js:556fn @ main-0f62f26….js:87(anonymous function) @ common.js?c280:19(anonymous function) @ main-0f62f26….js:8035__webpack_require__ @ main-0f62f26….js:556fn @ main-0f62f26….js:87(anonymous function) @ tableservice.js?ee5a:22(anonymous function) @ tableservice.js?ee5a:1329(anonymous function) @ main-0f62f26….js:7993__webpack_require__ @ main-0f62f26….js:556fn @ main-0f62f26….js:87(anonymous function) @ azure-storage.js?d76b:42(anonymous function) @ main-0f62f26….js:7987__webpack_require__ @ main-0f62f26….js:556fn @ main-0f62f26….js:87toggle @ postsActionCreators.js?a5be:33(anonymous function) @ bindActionCreators.js?91d9:7handleClick @ NavItem.js?efbf:75handleClick @ SafeAnchor.js?38e9:92ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js?6b31:70executeDispatch @ EventPluginUtils.js?0958:89executeDispatchesInOrder @ EventPluginUtils.js?0958:112executeDispatchesAndRelease @ EventPluginHub.js?c6b1:44forEachAccumulated @ forEachAccumulated.js?b898:25processEventQueue @ EventPluginHub.js?c6b1:229runEventQueueInBatch @ ReactEventEmitterMixin.js?8a20:18handleTopLevel @ ReactEventEmitterMixin.js?8a20:29handleTopLevelImpl @ ReactEventListener.js?2365:73perform @ Transaction.js?6dff:138batchedUpdates @ ReactDefaultBatchingStrategy.js?ef70:63batchedUpdates @ ReactUpdates.js?ce09:98dispatchEvent @ ReactEventListener.js?2365:150
polling-xhr.js?533a:250 XHR finished loading: GET "http://localhost:3000/ws/?EIO=3&transport=polling&t=LQQZWGe".Request.create @ polling-xhr.js?533a:250Request @ polling-xhr.js?533a:163XHR.request @ polling-xhr.js?533a:91XHR.doPoll @ polling-xhr.js?533a:121Polling.poll @ polling.js?1450:119Polling.doOpen @ polling.js?1450:63Transport.open @ transport.js?e5ed:78Socket.open @ socket.js?5e31:230Socket @ socket.js?5e31:111Socket @ socket.js?5e31:37Manager.open.Manager.connect @ manager.js?0a19:214(anonymous function) @ manager.js?0a19:524`

**Comment by hasonmsft** [comment]
@jahmaiosullivan , I'm using webpack 1.13.1 and it works fine from my side for `"azure-storage": "^1.1.0"` . Please refer to my last comment and have a try?

**Comment by vinjiang** [comment]
Feel free to let us know if further assistance required.
