### ISSUE TITLE
When using a filter and development account, request URLs end up with extra instances of the account name

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-storage-node#174]
In this code...

StorageServiceClient.prototype._getPath = function (path) {
  if (path === null || path === undefined) {
    path = '/';
  } else if (path.indexOf('/') !== 0) {
    path = '/' + path;
  }

  if (this.usePathStyleUri) {
    path = '/' + this.storageAccount + path;   <<< this.storageAccount ends up in the string multiple times
  }

  return path;
};

**Comment by hasonmsft** [comment]
@StephenWeatherford , thanks for raising this. It's a valid issue and will be fixed in next release.

**Comment by hasonmsft** [comment]
@StephenWeatherford , this issue has been fixed in the latest version 1.3.0.
