### ISSUE TITLE
Error when reading an added queue message: "The input is not a valid Base-64 string as it contains a non-base 64 character"

### ISSUE THREAD

**Issue by samuelkilada** [Azure/azure-storage-node#176]
Queue items added in nodeJs by means of this module following the steps in this article (https://azure.microsoft.com/en-us/documentation/articles/storage-nodejs-how-to-use-queues/) are added but fail to be read by other services, even with any kind of message like "Hello World".

This didn't used to happen for me, but I think the latest version is now causing it ("1.2.0").

If I use the cloud explorer in Visual Studio and manually add an item to the queue, like "hello", it shows up just fine. But if I add a queue item using queueSvc.createMessage, it gets added, but in Visual Studio in the cloud explorer when I refresh the queue to see the new message I get:

"The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters."

**Comment by samuelkilada** [comment]
Very sorry. I searched all over the internet and somehow never found this error until posting mine:

https://github.com/Azure/azure-storage-node/issues/165

**Comment by samuelkilada** [comment]
I take it back, it was worth it for me to post this. :) There's no documentation anywhere on how to use the QueueMessageEncoder so you can set your own encoder options, so you have to sift through the module code and figure it out. Here's the solution that worked for me:

```
var azure = require('azure-storage');
var queueSvc = azure.createQueueService(
    [STORAGE_ACCOUNT_HERE],
    ACCESS_KEY_HERE);
queueSvc.messageEncoder = new azure.QueueMessageEncoder.TextBase64QueueMessageEncoder();
```

**Comment by davidbetz** [comment]
Yep, that solution worked. Thanks.

**Comment by mpseidel** [comment]
@samuelkilada thanks so much for posting this - saved me a buch of headache here :)
