### ISSUE TITLE
TypeScript definition errors

### ISSUE THREAD

**Issue by irakliy81** [Azure/azure-storage-node#178]
There seem to be some errors in the `azure-storage.d.ts` file. A couple that I noticed are:
1. `createWriteStreamToBlockBlob()` - should return a `Stream` but is marked as returning `void`
2. `generateSharedAccessSignature()` - optional `headers` parameter is not marked as optional

**Comment by hasonmsft** [comment]
@irakliy81 , thanks for raising this issue. Will update the type definition file.

**Comment by irakliy81** [comment]
great! Thanks! One more issue I noticed:

`QueueMessageResult.dequeueCount` should probably be a `number` but is marked as `string`

**Comment by hasonmsft** [comment]
@irakliy81 , currently we keep the `QueueMessageResult.dequeueCount` as string as we didn't convert it to `number`. But it's a good point that this should be a `number`. We'll change the product code accordingly.

**Comment by hasonmsft** [comment]
@irakliy81 , all the issues has been fixed in the latest version 1.3.0.

**Comment by irakliy81** [comment]
Thanks! These seem to be in order now - but I found one more:

For `createQueueService()` method, `host` parameter should be optional - but it is listed as required.

**Comment by hasonmsft** [comment]
@irakliy81 , thanks for the finding. Will address this in the future release. If you like, you can create a PR and it's warmly welcome.

**Comment by Pyo25** [comment]
Hi @hasonmsft & @irakliy81,

It's been awhile since the issue was raised but I opened a tiny PR that fixes it:
https://github.com/Azure/azure-storage-node/pull/240
