### ISSUE TITLE
Bug with creating Account SAS when using a connection string instead of storage account name.

### ISSUE THREAD

**Issue by gmantri** [Azure/azure-storage-node#181]
Documentation for generateAccountSharedAccessSignature states that we can either use a storage account name or a connection string for creating an Account SAS. The process works perfectly fine when you specify storage account name however if connection string is used, Account SAS fails.

Essentially what is happening is that when you specify a connection string, instead of extracting the account name from the connection string and using it for computing signature, the code uses the entire connection string.

2 Possible solutions:

1. Easy one would be to update the documentation and say that only account name is supported.

2. Fix the code to properly extract the account name from the connection string and use that in SAS computation.

**Comment by hasonmsft** [comment]
@gmantri , it should works for passing connection string for creating an account SAS. Please make sure you pass `null` to the `storageAccessKey` parameter (second parameter) as below. 

`var token = azure.generateAccountSharedAccessSignature('[ConnectionString]', null, sharedAccessPolicy);`

**Comment by gmantri** [comment]
Thank you for your prompt response. I just tried it and it works just fine if I pass null for storage account key.
