### ISSUE TITLE
Test Suite: Make nock recordings reusable.

### ISSUE THREAD

**Issue by svnlto** [Azure/azure-storage-node#183]
I'm currently developing and running tests against my personal azure blob storage account. I'd like to optimise this scenario by being able to require (at least some) of the tests/or nock recordings and reuse them in my own test suite. 

Could you perhaps point me in the right direction?

**Comment by hasonmsft** [comment]
@svnlto , currently our test recording is based on the test case files. It means that each test cases file will have a test recording file. And our test cases has some logic for random id generation. To make sure it can play back correctly, we also has some logic to handle it and the logic depends on the test cases sequence. Refer to [test-suite.js](https://github.com/Azure/azure-storage-node/blob/master/test/framework/test-suite.js) for the detailed implementation. 

Our recording files cannot be used directly in your own test suite as it's depends on our suite. :) You can refer our implementation to record your HTTP traffics for your own suite.
