### ISSUE TITLE
Internal Azure-Storage Error? "Unhandled rejection StorageError: The property value exceeds the maximum allowed size (64KB)."

### ISSUE THREAD

**Issue by samuelkilada** [Azure/azure-storage-node#184]
I've run into this issue where, when doing tableService.queryEntities, an error that does not crash my server but which cannot be caught is occurring:

The query I'm running is simply:

`var query = new azure.TableQuery()
                .where('PartitionKey eq ?', partitionKey);`

...where partition key is simply a short id string. I KNOW that's not the issue. Here's the error:

> Unhandled rejection StorageError: The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.
> RequestId:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> Time:2016-08-23T23:19:20.0555529Z
>     at Function.StorageServiceClient._normalizeError (....\node_modules\azure-storage\lib\common\services\storageserviceclient.js:1108:23)
>     at TableService.StorageServiceClient._processResponse (....\node_modules\azure-storage\lib\common\services\storageserviceclient.js:691:50)
>     at Request.processResponseCallback [as _callback](....node_modulesazure-storagelibcommonservicesstorageserviceclient.js:294:37)
>     at Request.self.callback (....\node_modules\request\request.js:187:22)
>     at emitTwo (events.js:87:13)
>     at Request.emit (events.js:172:7)
>     at Request.<anonymous> (....\node_modules\request\request.js:1044:10)
>     at emitOne (events.js:77:13)
>     at Request.emit (events.js:169:7)
>     at IncomingMessage.<anonymous> (....\node_modules\request\request.js:965:12)
>     at emitNone (events.js:72:20)
>     at IncomingMessage.emit (events.js:166:7)
>     at endReadableNT (_stream_readable.js:913:12)
>     at nextTickCallbackWith2Args (node.js:442:9)
>     at process._tickCallback (node.js:356:17)

It seems to be impossible to catch this error no matter how I try / catch it. My query, as far as I can tell, is still returning my results, but the error gets auto-logged to the console.

**Comment by hasonmsft** [comment]
@samuelkilada, we cannot repro this issue from our side. And looks like you are using Promise, right? If you can share the code to repro this issue, it'll be helpful for us to help.

**Comment by samuelkilada** [comment]
Sure thing:

```
this.findEntitiesByPartition = function(table, partitionKey) {
    return new Promise(function(resolve, reject) {
        try {
            var query = new azure.TableQuery()
                .where('PartitionKey eq ?', partitionKey);

            runTableQuery(table, query)
                .then(function(results) {
                    return resolve(results);
                })
                .catch(function(err) {
                    return reject(err);
                });
        } catch (err) {
            return reject(err);
        }
    });
}

function runTableQuery(table, query) {
    return new Promise(function(resolve, reject) {
        try {
            var allResults = [];

            function getResults(err, result, response) {
                try {
                    if (err) {
                        if (!response) {
                            return reject(new Error('No response object in Azure request.'));
                        } else {
                            if (response.statusCode == 404) {
                                return resolve([]);
                            } else {
                                return reject(err);
                            }
                        }
                    } else {
                        for (var i = 0; i < result.entries.length; i++) {
                            allResults.push(result.entries[i]);
                        }
                        if (result.continuationToken) {
                            runQuery(result.continuationToken);
                        } else {
                            return resolve(allResults);
                        }
                    }
                } catch(err) {
                    return reject(err);
                }
            }

            function runQuery(continuationToken) {
                try {
                    tableService.queryEntities(table, query, continuationToken, getResults);
                } catch (err) {
                    return reject(err);
                }
            }

            runQuery();
        } catch (err) {
            return reject(err);
        }
    });
}
```

**Comment by hasonmsft** [comment]
Still cannot repro from our side. Try to dump more info from response as the error is a server error? 
```
                       if (!response) {
                            return reject(new Error('No response object in Azure request.'));
                        } else {
////////////////////////
console.log(response);
////////////////////////
                            if (response.statusCode == 404) {
                                return resolve([]);
                            } else {
                                return reject(err);
                            }
                        }
```

**Comment by samuelkilada** [comment]
Logging just shows that it indeed succeed (I've shortened the long list of Objects that I actually got):

> { isSuccessful: true,
  statusCode: 200,
  body:
   { 'odata.metadata': 'https://xxx.table.core.windows.net/$metadata#tableNameHere',
     value:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  headers:
   { 'cache-control': 'no-cache',
     'transfer-encoding': 'chunked',
     'content-type': 'application/json;odata=minimalmetadata;streaming=true;charset=utf-8',
     server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
     'x-ms-request-id': 'xxxxxxxxxxxxxxxxxxxxxx',
     'x-ms-version': '2015-12-11',
     'x-content-type-options': 'nosniff',
     date: 'Wed, 24 Aug 2016 04:46:19 GMT',
     connection: 'close' },
  md5: undefined }

**Comment by hasonmsft** [comment]
@samuelkilada , you mean that you are getting error with 200 response together?

**Comment by samuelkilada** [comment]
That's correct. The actual response returns 200, but the error appears in the console right afterward. It's really odd.

**Comment by hasonmsft** [comment]
Is the `console.log(response)` in the `if(err) {}` clause? 

And from the error message, this error happens you insert an entity instead of query entities. Refer to [https://msdn.microsoft.com/en-us/library/dd179338.aspx] (https://msdn.microsoft.com/en-us/library/dd179338.aspx) for more detailed information. 

Do you have any code that will insert entity to Azure Table Service and try to review the code?

**Comment by samuelkilada** [comment]
I just checked again and confirmed that the "if (err)" section is never happening because there is no err. Sorry for the confusion, I did not put the response log in the err section like you suggested, I put it in the non-err section. Basically, no error is firing but that strange unhandled exception stills logs in the console.

I've also encountered this issue when I had the server initializing tables each time it started. If the table already existed, it should have just failed silently (because it was a create if not exists operation), but it would occasionally log an unhandled exception to the console and I believe there was no way for me to catch it myself, just like is happening now.

Do you mean that the error happens when you insert an entity because this method is expecting a query only and no inserting? As far as I can tell from looking at it, it's just querying. I'm starting to wonder if one  of the entities being returned (there are over 1000) is corrupt, but there's no way to know which one.

**Comment by hasonmsft** [comment]
Let's ignore the create table issue and focus on the entity query here. :) If you want, you can open another GitHub issue for tracking. 

From the error message, it should NOT happen when querying entities because invalid entities cannot be inserted successfully into Azure Table Service. If the server return the entities back, there won't be any error like this because client won't do this validation during de-serialization. 

I'm supposing there are some other code is inserting/updating entity to Azure Table service in the same server process and the sometimes the input is invalid which cause the error.

**Comment by samuelkilada** [comment]
I'm quite certain no other code is doing an insert. This bug just reared its head in another place in my program just now. It's another table that has less than 500 items. I was adding items to it as part of testing and then suddenly saw that error when querying the table for the full list! I deleted a bunch of items and the error went away. It has 400ish and it's working fine. It would seem that simply deleting a bunch of items made it go away. There's something weird going on in the azure-storage module when returning a long list of items from a table.

**Comment by samuelkilada** [comment]
Yep, this is bizarre, but the error only returns when there are exactly 459 entities in the table and you do a query for them all!

**Comment by samuelkilada** [comment]
Any leads on this strange issue? I'm quite certain now that it is directly dependent on the number of items in a table when a query is made. As far as I can tell it is not hurting the entries that are being returned (though I'm not positive), but it is still worrisome to see that error.

**Comment by hasonmsft** [comment]
@samuelkilada , we'll try to repro this issue from our side. And at the same time, please confirm that if you are getting the error in the console, the code will hit the ' if (err) ', right?

**Comment by samuelkilada** [comment]
As I mentioned before, that's why this error is so weird. It is occurring when there is a success response, not in the "if (err)". It's also not something I'm logging myself, it appears to be the azure-storage module that is logging it internally. Thanks for looking into this.

**Comment by samuelkilada** [comment]
I'm guessing no one has been able to reproduce this? :)

**Comment by hasonmsft** [comment]
@samuelkilada , may I know if any further assistance can we provide? If not, we'll close this issue. Thanks for raising this and let us know in case of any other feedbacks.
