### ISSUE TITLE
CreateTableIfNotExists not work. ERROR: The value for one of the HTTP headers is not in the correct format

### ISSUE THREAD

**Issue by boydc2014** [Azure/azure-storage-node#185]
var azure = require('azure-storage');

var name = ‘XXX’;
var key = "XXX"
var azureTable = azure.createTableService(name, key);

azureTable.createTableIfNotExists('TestTable', function(error, result, response) {
  if (!error) {
    // result contains true if created; false if already exists
  } else {
    console.log(error);
  }
});

First example failed with Error:
{ [StorageError: The value for one of the HTTP headers is not in the correct format.
RequestId:bbea5532-0002-0071-7e74-fe88ea000000
Time:2016-08-25T01:58:35.9479577Z]
  name: 'StorageError',
  message: 'The value for one of the HTTP headers is not in the correct format.\nRequestId:bbea5532-0002-0071-7e74-fe88ea000000\nTime:2016-08-25T01:58:35.9479577Z',
  code: 'InvalidHeaderValue',
  statusCode: 400,
  requestId: 'bbea5532-0002-0071-7e74-fe88ea000000' }

**Comment by boydc2014** [comment]
More information:

QueryEntities works as expected. But createTableIfNotExists just won't work.

**Comment by hasonmsft** [comment]
@boydc2014 ， what's the SDK version you are using.

**Comment by boydc2014** [comment]
@hasonmsft version 1.20 

{
  "name": "azure-storage",
  "author": {
    "name": "Microsoft Corporation"
  },
  "version": "1.2.0",
  "description": "Microsoft Azure Storage Client Library for Node.js",
  "tags": [
    "azure",
    "storage",
    "sdk"
  ],
  "keywords": [
    "node",
    "azure",
    "storage"
  ],
  "main": "./lib/azure-storage.js",
....

**Comment by boydc2014** [comment]
@hasonmsft 
I just use npm install azure-storage to start.

Just checked that 1.1.0 works and 1.2.0 failed

**Comment by suzhiyang** [comment]
I have the same issue as above

**Comment by hasonmsft** [comment]
@boydc2014 , @suzhiyang, I cannot repro this issue from my side with both 1.1.0 and 1.2.0 with Node v4.2.4. 

What's the node version you are using?

**Comment by hasonmsft** [comment]
@boydc2014 , @suzhiyang, you are using Azure China or global Azure?

**Comment by boydc2014** [comment]
@hasonmsft I'm using node 4.4.5

>node --version
v4.4.5

Azure global, but ms internal version, is this a problem?

**Comment by suzhiyang** [comment]
nodejs --version
v4.2.6
Ubuntu 16.04 LTS

**Comment by hasonmsft** [comment]
@boydc2014 ， @suzhiyang ， how about the question  I asked above? you are using Azure China or global Azure?

**Comment by boydc2014** [comment]
@hasonmsft  I said Global Azure, via ms.portal.azure.com

**Comment by boydc2014** [comment]
Solved by switching to a new storage account. 
Confirmed by @hasonmsft that the original  storage account doesn't not support new x-ms-version header yet.
