### ISSUE TITLE
TypeScript type definition file

### ISSUE THREAD

**Issue by Cecildt** [Azure/azure-storage-node#19]
Hi,

Can someone please create a TypeScript type definition for this module?

Thanks!

**Comment by freakyfriday** [comment]
+1 vote

**Comment by codeandcats** [comment]
Bump!

Unfortunately [the definition](https://github.com/borisyankov/DefinitelyTyped/blob/master/node-azure/azure.d.ts) in DefinitelyTyped does not appear to be correct to the point where I'm struggling to create even a simple query.

**Comment by Judahh** [comment]
+1 vote

**Comment by irakliy81** [comment]
+1

**Comment by craxal** [comment]
Another +1.

**Comment by yaxia** [comment]
Thanks for voting on this. We are working on this request and will have it in a later release.

**Comment by codeandcats** [comment]
:+1:

**Comment by yaxia** [comment]
We just release the preview TS definition file with 0.8.0. Would you please take a try?
We’d love to hear from you. Thanks.

**Comment by StephenWeatherford** [comment]
Thanks for creating the definition file!  However, it does have a lot of issues and incomplete types (esp. types for the various method options).  Here are some of the specific issues I've found:

azureStorage.generateDevelopmentStorageCredendentials 
misspelled, should be:
azureStorage.generateDevelopmentStorageCredentials

export function generateDevelopmentStorageCredendentials(proxyUri: any): string;
should be:
export function generateDevelopmentStorageCredendentials(proxyUri?: string): string;

missing CopyBlobOptions for use in startCopyBlob

Many functions are missing their polymorphic versions.  Example:
  abortCopyBlob(container: string, blob: string, copyId: any, optionsOrCallback: any, callback: any): void;
Should be:
  abortCopyBlob(container: string, blob: string, copyId: any, optionsOrCallback: any, callback: any): void;
  abortCopyBlob(container: string, blob: string, copyId: any, callback: any): void;

Should be more specific about the type of the callback argument
Should have specific options types (e.g. CopyBlobOptions)

getUrl(container: string, blob: string, sasToken: any, primary: any): url.Url;
should return string
blob, sasToken, primary should be optional (blob is optional when getting the url of a container)
sasToken/primary should be string/boolean
expected: getUrl(container: string, blob?: string, sasToken?: string, primary?: boolean): string;

missing SharedAccessPolicy

generateSharedAccessSignature(container: string, blob: string, sharedAccessPolicy: any, headers: any): any;
headers should be optional

TableAccessPolicy doesn't seem to be accessible

{Table,Blob,etc}Service.host is missing


queryEntities returns QueryEntitiesResult in its callback, which is defined as:
          export interface QueryEntitiesResult<T> {
            entities: T[];
            continuationToken?: TableContinuationToken;
          }
But in reality, the entities are in an "entries" property, not an "entities" property

            export interface BlobResult {
              name: string;
              containerName: string;
              metadata?: { [key: string]: string; };
BlobResult.name isn't correct, it actually returns "blob" (at least getBlobProperties does):
            export interface BlobResult {
              blob: string;
              containerName: string;
              metadata?: { [key: string]: string; };

Many functions specify args as required that should be marked optional.

**Comment by yaxia** [comment]
@StephenWeatherford Thanks for the feedbacks. We've already been working on the issues you mentioned and will address them before GA.

**Comment by SofianHn** [comment]
ping

**Comment by chandanch** [comment]
Hello Is the Typescript version created??

**Comment by yaxia** [comment]
@chandanch  If you mean the TypeScript definition file, please check the file: https://github.com/Azure/azure-storage-node/blob/master/lib/azure-storage.d.ts. If you mean the library totally written by TypeScript, we don't have it yet.

**Comment by chandanch** [comment]
When will the Typescript library be ready? We have an application built using Angular2 and this app will access the blob storage to get the static images and text files. Is there an angular2 version of the library?
Any docs or links on it?

**Comment by prakas** [comment]
is the typescript library ready ?

**Comment by yaxia** [comment]
@chandanch @prakas It sounds you are looking for the library purely written by TypeScript or AngeularJS. We don't have those libraries yet and there is no ETA on it. Could you please share details why the TS definition file doesn't work for your scenarios? Thanks.

**Comment by prakas** [comment]
The TS definition file you have here works perfect, but I was looking into something that i can directly install from typings(definitely typed) during build process like other dependencies.

**Comment by wilzbach** [comment]
> directly install from typings(definitely typed) during build process like other dependencies.

or in other words, could you please add it to the typings registry?

**Comment by chandanch** [comment]
@yaxia The link you provided says 404 
https://github.com/Azure/azure-storage-node/blob/master/lib/azure-storage.d.ts.

**Comment by chandanch** [comment]
@yaxia The link that you provided says 404:

https://github.com/Azure/azure-storage-node/blob/master/lib/azure-storage.d.ts.

**Comment by prakas** [comment]
@chandanch use this link
https://github.com/Azure/azure-storage-node/blob/master/typings/azure-storage/azure-storage.d.ts

**Comment by chandanch** [comment]
Thanks @prakas 

Its also available in DefinetelyTyped here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node-azure/azure.d.ts

**Comment by yaxia** [comment]
The updated link to the TypeScript definition file is here: 
https://github.com/Azure/azure-storage-node/blob/master/typings/azure-storage/azure-storage.d.ts

Closing this issue. Please feel free to open new ones if you find any issues. Thanks.
