### ISSUE TITLE
Are Requests Over HTTPS?

### ISSUE THREAD

**Issue by samuelkilada** [Azure/azure-storage-node#190]
This is more of a question than an issue, but I can't find info on this anywhere. Does this module make connections to your Azure Storage account over https by default? If it defaults to http, is there a way to configure this?

Thanks,
Sam

**Comment by hasonmsft** [comment]
Yes, it's default to https. And you can use [connection string](https://azure.microsoft.com/en-us/documentation/articles/storage-configure-connection-string/) in which also you can set the protocol.

**Comment by samuelkilada** [comment]
Thank you!
