### ISSUE TITLE
Please upgrade your underscore dependency

### ISSUE THREAD

**Issue by mvines** [Azure/azure-storage-node#191]
Currently this project depends on [underscore 1.4.4](https://github.com/Azure/azure-storage-node/blob/41f12719732137861b88edfaba6afb8766cf8483/package.json#L29), which is [really old](https://github.com/jashkenas/underscore/releases/tag/1.4.4) and is missing useful fixes such as [this](https://github.com/jashkenas/underscore/commit/68bb747a1349b215752fdf8b1b2ad1667f1f8a0d).

I locally switched to [underscore 1.8.3](https://github.com/jashkenas/underscore/releases/tag/1.8.3), the [latest](https://www.npmjs.com/package/underscore) on npmjs it seemed ok, although I didn't perform an exhaustive test.

**Comment by hasonmsft** [comment]
@mvines , thanks for your feedback. We'll evaluate it and test it.

**Comment by jiacfan** [comment]
@mavines, we have already upgraded underscore to 1.8.3. Thanks for trying!
