### ISSUE TITLE
AccessCondition namespace missing from typings declaration file

### ISSUE THREAD

**Issue by kenhowardpdx** [Azure/azure-storage-node#192]
The issue is when trying to access a function the AccesCondition namespace.

```
let accessConditions = azure.AccessCondition.generateIfNoneMatchCondition('*');
```

**Comment by hasonmsft** [comment]
@kenhowardpdx , thanks for raising this issue. We'll fix it in upcoming releases.

**Comment by hasonmsft** [comment]
@kenhowardpdx , this issue has been fixed in the latest release. Please try it out.
