### ISSUE TITLE
error TS2656: Exported external package typings file azure-storage.d.ts is not a module

### ISSUE THREAD

**Issue by dennis-yemelyanov** [Azure/azure-storage-node#193]
I'm trying to reference the azure-storage module from TypeScript and getting this error during compilation: 

`import * as azure from "azure-storage";`

> error TS2656: Exported external package typings file 'node_modules/azure-storage/typings/azure-storage/azure-storage.d.ts' is not a module. Please contact the package author to update the package definition.

I'm using version 1.3.0 of azure-storage and 1.8.10 of TypeScript compiler.

**Comment by hasonmsft** [comment]
@dennis-yemelyanov , thanks raising this issue. Will take a look into this. At the same time, could you change the azure-storage back to 1.2.0 and import the type definition file manually to use it in your project.

**Comment by kapil-ms** [comment]
I am facing the same issue. Any updates on the fix for this ?

**Comment by hasonmsft** [comment]
@dennis-yemelyanov , @kapil-ms , I updated the azure-storage package locally and verified it. 

Here is my test env configuration: 

`tsconfig.json`: 
```
	"compilerOptions": {
		"target": "es5",
		"sourceMap": true,
		"outDir": "built",
		"noEmitOnError": true,
		"module": "commonjs"
	},
```

And I run the `typings install dt~node --global` & `typings install dt~node-uuid --global` to install the typescript dependency of azure-storage. 

Please let me know if this approach works for you or not. If it looks good, I'll prepare a release soon.

**Comment by rahul251993** [comment]
@hasonmsft  i am facing same issue.. when will you update the azure-storage package?

**Comment by hasonmsft** [comment]
@dennis-yemelyanov , @rahul251993 , please try out the latest package 1.3.1. This issue should be fixed. Any issues, please let me know.

**Comment by hasonmsft** [comment]
@dennis-yemelyanov , @rahul251993 , we fixed another type script issue for the uuid dependency in the latest version 1.3.2. Could you help try it out and let us know in case of any issues?
