### ISSUE TITLE
StorageError: Cannot create property 'ServiceEndpoint' on string ' '

### ISSUE THREAD

**Issue by JohnRoyNZ** [Azure/azure-storage-node#194]
When I try to call 'listBlobsSegmented' or 'listContainersSegmented' as well as a variety of other calls I am getting a response which includes both the desired information but also this error:

StorageError: Cannot create property 'ServiceEndpoint' on string ' '

This is happening every time and I have tried many different things to see a difference. 

Can someone please point out what may be going on here?

**Comment by mirobers** [comment]
Hi, thanks for reporting this. Could you share the following info? If you don't feel comfortable sharing your account name on the internet, feel free to email the info to ascl at Microsoft dot com.
* Storage account name (NOT the key)
* Client library version
* Request ID if available

**Comment by JohnRoyNZ** [comment]
I have just sent an email to that address with the requested details.

Looking forward to your reply.

**Comment by hasonmsft** [comment]
@JohnRoyNZ , could you also dump&share the response in the callback to narrow down if it's a client side issue or server side issue?

**Comment by XiaoningLiu** [comment]
@JohnRoyNZ @mirobers Hey, is the issue still there?

**Comment by per-lind** [comment]
I'm experiencing the same issue using the javascript client library in my frontend but not from my node backend when using the same code and sas token.

Was there ever an explanation for this?

Error message in browser:
`StorageError {name: "StorageError", message: "Cannot create property 'ServiceEndpoint' on string ''", code: "Cannot create property 'ServiceEndpoint' on string ''", statusCode: 200, requestId: "00b71191-b01e-0014-1d08-ee0d1e000000", …}
code
:
"Cannot create property 'ServiceEndpoint' on string ''"
message
:
"Cannot create property 'ServiceEndpoint' on string ''"
name
:
"StorageError"
requestId
:
"00b71191-b01e-0014-1d08-ee0d1e000000"
statusCode
:
200
stack
:
"StorageError: Cannot create property 'ServiceEndpoint' on string ''↵    at Function.StorageServiceClient._normalizeError (webpack-internal:///./src/components/azure-storage.blob.js:909:224)↵    at BlobService.StorageServiceClient._processResponse (webpack-internal:///./src/components/azure-storage.blob.js:761:289)↵    at Request.processResponseCallback [as callback] (webpack-internal:///./src/components/azure-storage.blob.js:713:898)↵    at exports.IncomingMessage.eval (webpack-internal:///./src/components/azure-storage.blob.js:498:2707)↵    at emitNone (webpack-internal:///./src/components/azure-storage.blob.js:7643:167)↵    at exports.IncomingMessage.emit (webpack-internal:///./src/components/azure-storage.blob.js:7647:8)↵    at endReadableNT (webpack-internal:///./src/components/azure-storage.blob.js:8871:92)↵    at afterTickTwo (webpack-internal:///./src/components/azure-storage.blob.js:8609:955)↵    at Item.run (webpack-internal:///./src/components/azure-storage.blob.js:7839:96)↵    at drainQueue (webpack-internal:///./src/components/azure-storage.blob.js:7838:527)"
__proto__
:
Error`

**Comment by XiaoningLiu** [comment]
@per-lind Can you share a code sample which can reproducing this issue?

**Comment by per-lind** [comment]
Here is one example of the code that is causing this:

`	  import * as azure from './azure-storage.blob';
      const containerName = 'iot-data'
    
      const blobUri = 'https://peliiot.blob.core.windows.net'
      const blobSAS = 'st=2018-05-17T17%3A04%3A52Z&se=2018-05-17T19%3A29%3A52Z&sp=rl&sv=2017-07-29&sr=c&sig=QfJwVeIKJiedwg%2FxU8W3BuykzSjOq5q6SqkBOUlv4rw%3D'

      const blobService = azure.createBlobServiceWithSas(blobUri, blobSAS)
      blobService.listBlobsSegmented(containerName, null, function(err, result) {
        if (err) {
            console.log("Couldn't list blobs for container %s", containerName);
            console.error(err);
        } else {
            console.log('Successfully listed blobs for container %s', containerName);
            console.log(result.entries);
            console.log(result.continuationToken);
        }
        console.log(result);
        });`

This is how I generate the SAS in the backend (using the library from npm):

`    const sharedAccessPolicy = {
        AccessPolicy: {
            Permissions: azure.BlobUtilities.SharedAccessPermissions.READ+ azure.BlobUtilities.SharedAccessPermissions.LIST,
            Start: startDate,
            Expiry: expiryDate
        }
    };
    
    const token = blobService.generateSharedAccessSignature(containerName, null, sharedAccessPolicy);`

**Comment by XiaoningLiu** [comment]
@per-lind 

I cannot reproduce this issue with following steps. Can you have a look?

1. Generate a SAS token with the sample code you provided on Node.js
2. Chrome open https://dmrelease.blob.core.windows.net/azurestoragejssample/samples/sample-blob.html
3. Press 'F12' and open the developer console, execute following codes:
![image](https://user-images.githubusercontent.com/6889160/40227157-4888a78c-5ac0-11e8-9f35-d8b4e0a20945.png)

**Comment by per-lind** [comment]
@XiaoningLiu 
I changed my code and added the library as a global reference in index.html instead of importing it and that made the error go away. Maybe webpack was my problem?

**Comment by XiaoningLiu** [comment]
Not sure. I don't know your project configuration. I can have a quick debugging if you can share your project code (if possible).
