### ISSUE TITLE
"Peek Message" operation failing on secondary endpoints

### ISSUE THREAD

**Issue by gmantri** [Azure/azure-storage-node#195]
When I try to peek messages from a queue at its secondary location, I get the following error:

> This operation can only be executed against the primary storage location.

Essentially the issue is that when listing messages from a secondary location, one must specify `requestLocationMode` option along with `locationMode` option. If `requestLocationMode` is not specified, then it is assigned `Primary` location by default. If `requestLocationMode` is specified with proper value, then this error goes away.

**Comment by hasonmsft** [comment]
@gmantri , thanks for raising this issue. We'll look into this to see how we can improve this. For now, please keep what you did by setting both `requestLocationMode` and `locationMode`.

**Comment by hasonmsft** [comment]
@gmantri , this issue has been fixed in 1.4.0 release.
