### ISSUE TITLE
Deleting 10K+ Entities from Azure Storage Table

### ISSUE THREAD

**Issue by prashanthmadi** [Azure/azure-storage-node#196]
I have a Azure Table Storage where the PartitionKey is set to a DeviceID and the RowKey is set to an EventID.  
I'm attempting to delete all the entries for a single DeviceId.  We didn’t found an inherent way to do this using the Azure-Storage MPM module.  Here are two options available:

(1) Delete a single entry using PartitionKey and RowKey
(2) Perform a batch operation of multiple delete operations.  Batch operations (Entity Group Transactions) are limited to 100 entities

The number of entities we might be deleting at one time could exceed 10,000.
We are using Node.js library version is v1.2.0 ----> https://www.npmjs.com/package/azure-storage

The only functions related to deleting entities that they can find are: 
  deleteEntity() in TableService 
  deleteEntity() in TableBatch 

Both only appear to let reference a single entity to delete at a time (must specify PartitionKey and RowKey). 
The TableBatch also appears to be limited to 100 operations per batch. 

Is there any other approach to deleting large quantities of entries? 
Possibly a query based approach similar to retrieving the entities? (TableQuery).

**Comment by yaxia** [comment]
If I understand correctly, you are trying to delete all the entities with a specific PartitionKey which is DeviceID here.

The option 1 works but it is too slow. 
We should go with option 2 and you need to take care of:
1.	The limit of a batch is 100
2.	The limit of entities returned from a query is 1000

Following code shows the logic (could have bug in it). **Please be noted the code is NOT tested and NOT optimized for concurrency control, DON’T use them just by copy/paste.**

```javascript
var azure = require('azure-storage');
var TableQuery = azure.TableQuery;
var TableBatch = azure.TableBatch;
var tableService = azure.createTableService();

var tableName = '' // Your table name
var partitionKey = '' // Your partition key
var query = new TableQuery().where(TableQuery.stringFilter('PartitionKey', TableUtilities.QueryComparisons.EQUAL, partitionKey));

function queryEntitiesAndDelete (continuationToken) {
  tableService.queryEntities(tableName, tableQuery, continuationToken, function (error, result) {
    var current = 0;

    function deleteInBatch () {
      var batch = new TableBatch();
      for ( ; current < result.entries.length; ) {
        batch.deleteEntity(result.entries[current]);
        current++;

        if (batch.size == 100) {
          break;
        }
      }

      if (batch.size > 0) {
        tableService.executeBatch(tableName, batch, function(error, result) {
          // Handling result and errors here
        });
      }
    }

    for (current = 0; current < result.entries.length; ) {
      deleteInBatch(current); // This function will start a batch operation, you might want to control the current operation number if the entries number is large
    }

    if (result.continuationToken) {
       queryEntitiesAndDelete(result.continuationToken) 
    }
  }
}

queryEntitiesAndDelete(null)
```
