### ISSUE TITLE
Error in azure-storage and 'createBlockBlobFromStream'

### ISSUE THREAD

**Issue by rahul251993** [Azure/azure-storage-node#197]
Azure storage shows an error on installing and also if you use Microsoft azure blob storage and try to upload stream then azure storage shows error. Cannot implement "createBlockBlobFromStream" because of error in blobservice.js file in azure-storage package regarding stream.pause() and stream.resume().

**Comment by hasonmsft** [comment]
@rahul251993 , stream.pause and stream.resume are supported by Node. Refer to [the doc of Node 0.10](https://nodejs.org/docs/latest-v0.10.x/api/stream.html) and [the doc of Node 4.5](https://nodejs.org/dist/latest-v4.x/docs/api/stream.html). Please let me know what's the node version you are using and how to repro the error you get.

**Comment by rahul251993** [comment]
@hasonmsft  I am using npm webshot to capture html and return image as stream and then trying to upload to blob storage using "createBlockBlobFromStream". please refer to my code: 

var stream = webshot(html, { siteType: 'html', streamType: 'png' });
var blobService = azure.createBlobService();
blobService.createBlockBlobFromStream(containerName, blobName, stream, 100000, function (error, result, response) {
      if (!error) {
        console.log('Stream Uploaded Sucessfully');
      }
    });

and it return error of stream.pause() and stream.resume() is not a function..

**Comment by hasonmsft** [comment]
@rahul251993 , got it. Looks like the webshot doesn't return standard NodeJS ReadableStream. I think you have 2 workaround for this: 

1. webshot to local temp file first and upload from the file stream
2. wrap the webshot stream with a standard memory stream and upload to blob from it.
