### ISSUE TITLE
Table Query hangs on network issue even with timeouts

### ISSUE THREAD

**Issue by sedouard** [Azure/azure-storage-node#200]
Hey there!

It seems that if you run a long table query and experience a network issue while the query happens (either continuing with a continuation token or without) the callback is never called with an `err` object.

The repro is easy. Do a query that takes more than a few seconds:

``` js
var query = new azureStorage.TableQuery()
.top(100)
.where('PartitionKey == ?', partitionKey)
.and('Timestamp >= ?date?', sinceMoment.toDate());
// turn off your internet connection when this request is made
return table.queryEntities(targetTableName, query, token, {maximumExecutionTimeInMs: 60000, timeoutIntervalInMs: 60000}, (err, result) => {
  // callback is never called with err
});
```

I would expect that since I set `maximumExecutionTimeInMs` and `timeoutIntervalInMs` that I would receive an error callback in 60 seconds. However that is not the case.

The production issue we're having is that our crawler (which crawls Azure tables) hangs. So we have to resort to triggering an exception using `setTimeout` in our application code.

Shouldn't this happen in the SDK?

**Comment by sedouard** [comment]
ping -- anyone watching issues here? any plans to add client side timeouts?

**Comment by hasonmsft** [comment]
@sedouard , we'll look into this issue and plan the fix. Thanks for reporting this. :)

**Comment by murraybauer** [comment]
Please fix, we're running in Azure Functions and could generate a big bill :-) as usage is billed per 100ms

**Comment by sedouard** [comment]
@hasonmsft  this should be pretty simple to fix.

@murraybauer a quick workaround is to wrap your query request in a `setTimeout`. Here's a sample of my production code, where `BbPromise` is `bluebird` and `queryEntitiesAsync` is a promised version of the standard `queryEntities` function:

```js
_queryTableWithTimeout(tableService, tableName, query, continuationToken, timeout) {
        return new BbPromise((resolve, reject) => {
            var p = tableService.queryEntitiesAsync(tableName, query, continuationToken, null);
            setTimeout(() => {
                if (p.isFulfilled()) {
                    // request was successful and resolved. no reason to reject promise
                    return;
                }
                // azure storage still hasn't responded! :-(. Reject the promise since
                // azure-storage-node sdk will not execute the callback
                reject('Azure table request timed out');
            }, timeout || 240000);
            p.then(result => {
                // this is executed the second the request is completed
                resolve(result);
            });
        });
    }
```

**Comment by murraybauer** [comment]
thanks @hasonmsft got it working.

**Comment by hasonmsft** [comment]
@sedouard , @murraybauer , we added the support for client side timeout per request to address this issue in the 2.0.0 release. Could you try it out? For more detailed information, please refer to the change log. :)

**Comment by murraybauer** [comment]
thanks @hasonmsft the implementation/config options looks good. 

I'm tied up atm and won't get a chance to modify an existing project, but will use going forward.
