### ISSUE TITLE
createBlockBlobFromText hangs when passed null or undefined 'text' arg

### ISSUE THREAD

**Issue by geoffpatehutch** [Azure/azure-storage-node#203]
myBlobService.createBlockBlobFromText(myContainerName, myBlobName, null, function (error, result) {
};

or

myBlobService.createBlockBlobFromText(myContainerName, myBlobName, undefined, function (error, result) {
};

Callback is never invoked

**Comment by hasonmsft** [comment]
@geoffpatehutch, thanks for reporting this. Will look into this and plan fix.

**Comment by hasonmsft** [comment]
@geoffpatehutch , this has been fixed in the 1.4.0 release.
