### ISSUE TITLE
Block Id is generated incorrectly

### ISSUE THREAD

**Issue by rscreene** [Azure/azure-storage-node#205]
I have been seeing occasional InvalidBlockList errors when using the createWriteStreamToBlockBlob() method,

Investigation revealed that the problem was that the blockId was being generated that contained a decimal point (eg. ".95c06ec-000000").  I'm guessing that the server rejects the request because the blockId is not base64.

My solution to this is to fix the generateBlockIdPrefix() method as follows:
```
BlobService.prototype.generateBlockIdPrefix = function () {
  var prefix = Math.floor(Math.random() * 0x100000000).toString(16);
  return azureutil.zeroPaddingString(prefix, 8);
};
```

Is it worth submitting this simple change as a Pull Request?

**Comment by hasonmsft** [comment]
@rscreene , thanks for raising this. Your contribution is always welcome and worthy. :)
