### ISSUE TITLE
createBlockBlobFromText always sets content type to text/plain

### ISSUE THREAD

**Issue by mmoskal** [Azure/azure-storage-node#206]
The _uploadBlobFromText function here https://github.com/Azure/azure-storage-node/blob/master/lib/services/blob/blobservice.js#L4518 which is called from createBlockBlobFromText always sets the content type to text/plain. This is regardless if one is set in options, or if I pass a buffer or a string. Even with string, I could want say text/html or application/javascript. Maybe text/plain is a good default, but the user choice shouldn't be overridden.

Thanks!

**Comment by hasonmsft** [comment]
@mmoskal , thanks for raising this. We'll fix it in upcoming releases.

**Comment by hasonmsft** [comment]
@mmoskal , this has been fixed in the 1.4.0 release.
