### ISSUE TITLE
typings file failure with --noImplicitAny

### ISSUE THREAD

**Issue by mmoskal** [Azure/azure-storage-node#207]
The `generateAccountSharedAccessSignature` functions lacks returns type:

https://github.com/Azure/azure-storage-node/blob/master/typings/azure-storage/azure-storage.d.ts#L8779

Also, the `RetryPolicyFilter` interface has a constructor (which is treated as a function returning any). It should be a class or shouldn't have a constructor.

https://github.com/Azure/azure-storage-node/blob/master/typings/azure-storage/azure-storage.d.ts#L7159

**Comment by hasonmsft** [comment]
@mmoskal , thanks for raising this issue. We'll fix it in upcoming releases.

**Comment by hasonmsft** [comment]
https://github.com/Azure/azure-storage-node/pull/224

**Comment by hasonmsft** [comment]
@mmoskal , it's already addressed in the 1.4.0 release.
