### ISSUE TITLE
UUID issue for typings definition

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-storage-node#208]
Say I have a single typescript file using azure-storage module:

```
import { TableService } from "azure-storage";
```

After using typings to install node module, and compile with tsc, it will outputs:

```
node_modules/azure-storage/typings/azure-storage/azure-storage.d.ts(5168,32): error TS2304: Cannot find name 'UUID'.
node_modules/azure-storage/typings/azure-storage/azure-storage.d.ts(5168,68): error TS2304: Cannot find name 'UUID'.
node_modules/azure-storage/typings/azure-storage/azure-storage.d.ts(5345,68): error TS2304: Cannot find name 'UUID'.
```

In typings/globals/node-uuid, there does include a definition of UUID, but it's under __NodeUUID namespace. Thus in my project, even if I install node-uuid with typings, it will get the same error.

Looks like the fix could be in two ways:
1 Add following line in azure-storage.d.ts:

```
import UUID = __NodeUUID.UUID;
```

  In this case, if user's project includes typings for node-uuid, it will work properly.

2 Remove all UUID reference in azure-storage.d.ts:
For now there're 3 occurances.

```
    Line 5168:           function Guid(value: UUID|string|Buffer): EntityProperty<UUID>;
    Line 5345:         guidFilter(propertyName: string, operation: string, value: UUID | string): string;
```

We could make it a string and leave a comment for that. Also note for Line#5168, when users pass in a string for now, property '_' stores a string, but from the interface it was a 'UUID':
https://github.com/Azure/azure-storage-node/blob/b12cd980d4bea4058d4bbb85a583ed7146b60d8f/lib/services/table/tableutilities.js#L140

**Comment by hasonmsft** [comment]
@karataliu , does this https://github.com/Azure/azure-storage-node/issues/193 help?

**Comment by karataliu** [comment]
No, that error still occurs. and i'm already on version 1.3.1.

**Comment by craxal** [comment]
I'm also encountering this issue, but I'm using TypeScript 2.0, not typings.

**Comment by keerthanakumar** [comment]
Having the same issue. Is there any fixes expected for this?

**Comment by hasonmsft** [comment]
@karataliu , @keerthanakumar , @craxal , this issue has been fixed in the latest version 1.3.2. Please try it out and let us know in case of any issues.

**Comment by karataliu** [comment]
@hasonmsft Just tried v1.3.2 and it works well for me. Thanks!

**Comment by hasonmsft** [comment]
@karataliu , it's great to hear the issue is resolved. Please let us know in case of any other issues.

**Comment by craxal** [comment]
Finally got around to trying it, and it looks resolved to me. Thanks!

**Comment by karataliu** [comment]
Closing this as fixed.
