### ISSUE TITLE
Incorrect casing for "seconds"

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-storage-node#210]
I now this may seem minor, but it bugs me every time I see it.  For the download/upload speed measurements, "MB/S" is incorrect, it should be "MB/s" ("s" is the internationally-recognized abbreviation for second", see https://en.wikipedia.org/wiki/Second).

Thanks!

**Comment by hasonmsft** [comment]
@StephenWeatherford , thanks for raising this. We'll fix it in upcoming releases.

**Comment by hasonmsft** [comment]
@StephenWeatherford , this has been fixed in 1.4.0 release.
