### ISSUE TITLE
Issues with creating queue messages with Arabic text

### ISSUE THREAD

**Issue by erikschlegel** [Azure/azure-storage-node#213]
I'm noticing some varying behavior with creating queue messages with Arabic text using azure-storage version 1.3.1 as opposed to 0.8.0. When I invoke the code snippet below using version 1.3.1, the created queue message is this "���qꮢڮ���q���O�z���*��j��\���y�ڶ������m5��t�^��N9�]�����ڮ�ٞ�Ơz������X��������m����iǛ���o�mۥ�h������,���ﭶ�M���5�Z��ڮ����j��ڮ��ڙꮢڮ��C�j��j��bv�������|����~y�^t��-��-r�����)���-��-�Mz�]>�t������4�J��ڮ�؝��-��-��8��uߞuם?�n������y�N���-"

If I run that same code block using version 0.8.0 the arabic queue message is created with no issue. Not sure if I now have to explicitly set UTF 8 encoding via the queue service. 

```
queueSvc.createMessage(MESSAGE_QUEUE, JSON.stringify(message), (error, result, response) => {
            if (error) {
                RaiseException(`Azure Queue push error occurred [${JSON.stringify(pageName)}]. error [${error}]`);
            }else{
                messageCount++;

                if(messageCount % 300 === 0){
                    logger(`Wrote ${messageCount} messages to output queue.`);
                }
            }

            return callback();
        });
```

**Comment by cloudbeatsch** [comment]
this is weird but it definitely looks like an encoding issue. I suggest you decode using UTF8, if this fails I would use the QueueClient binding and retrieve the message from there

**Comment by hasonmsft** [comment]
There is a breaking change before to support custom encoders. Refer to https://github.com/Azure/azure-storage-node/blob/master/test/services/queue/queueservice-tests.js#L437 for how to set the encoder. 


> QUEUE
The encodeMessage flag of QueueService has been replaced by messageEncoder which support TextBase64QueueMessageEncoder, BinaryBase64QueueMessageEncoder, TextXmlQueueMessageEncoder and custom implementation of QueueMessageEncoder.
