### ISSUE TITLE
Environment vars validator checks only connection string

### ISSUE THREAD

**Issue by peterblazejewicz** [Azure/azure-storage-node#221]
The required environment variables are set to connection string key only while the docs mention optional account name and access key variables:
https://github.com/Azure/azure-storage-node#running-tests
https://github.com/Azure/azure-storage-node/blob/master/test/framework/test-suite.js#L36

Because only connection string is validated the internal check in test will always fail when user sets account name and access key:
https://github.com/Azure/azure-storage-node/blob/master/test/framework/test-suite.js#L98-L102

That is the probable reason why users are unable to run tests with account name and access key environment variables set (like with my case: #217)

Thanks!

**Comment by hasonmsft** [comment]
@peterblazejewicz , thanks for raising this. We'll fix it in upcoming releases.

**Comment by hasonmsft** [comment]
@peterblazejewicz , we already updated the README.md to only support connection string. Could you try with connection string variable?
