### ISSUE TITLE
Typings are not up to date

### ISSUE THREAD

**Issue by Schaemelhout** [Azure/azure-storage-node#225]
The typings in [azure-storage.d.ts](https://github.com/Azure/azure-storage-node/blob/da53d6c1428250e085bf3afe522a83a4b212505e/typings/azure-storage/azure-storage.d.ts) are not the same (newer) as the ones downloaded from npm when using the latest version (1.3.2).

**Comment by hasonmsft** [comment]
@Schaemelhout , I cannot repro this issue from my side. Could you clean your local npm cache and re-install to have a try?

**Comment by Schaemelhout** [comment]
Still no luck I'm affraid, I clean my cache using `npm cache clean` and reinstalled using `npm install azure-storage`.
In the folder `typings/azure-storage` the file `azure-storage.d.ts` has 8871 lines of code, while the one on the master branch only has 5670...

**Comment by hasonmsft** [comment]
@Schaemelhout , they are the same. All of them has 8871 lines of code. Could you double confirm? 

_master: 8871 lines (8438 sloc)  712 KB_

**Comment by vinjiang** [comment]
Feel free to let us know if any further assistance required.
