### ISSUE TITLE
BlobService.prototype._uploadContentFromChunkStream passes wrong parallelOperationThreadCount value to ChunkAllocator constructor

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-storage-node#226]
See marked line.

BlobService.prototype._uploadContentFromChunkStream = function (container, blob, blobType, chunkStream, streamLength, options, callback) {
...
var parallelOperationThreadCount = options.parallelOperationThreadCount || this.parallelOperationThreadCount;
...
  var allocator = new ChunkAllocator(sizeLimitation, options.parallelOperationThreadCount, { logger: this.logger });   <<<<<<< Should be using local parallelOperationThreadCount, not options.parallelOperationThreadCount

Thx.

**Comment by hasonmsft** [comment]
@StephenWeatherford , thanks for raising this. We'll fix it in upcoming releases.

**Comment by hasonmsft** [comment]
@StephenWeatherford , this issue has been fixed in the 1.4.0 release.
