### ISSUE TITLE
'error TS2428: All declarations of 'EntityProperty' must have identical type parameters' when using TypeScript 2

### ISSUE THREAD

**Issue by mattmazzola** [Azure/azure-storage-node#230]
I tried to upgrade to Typescript 2.0.10, but there is new compilation error.
`typings/modules/azure-storage/index.d.ts(5707,22): error TS2428: All declarations of 'EntityProperty' must have identical type parameters.`

I was able to fix it by manually editing the file:
```
    export interface EntityProperty {
        <T>(): EntityProperty<T>;
    }
``` 
TO:
```
    export interface EntityProperty<T> {
        <T>(): EntityProperty<T>;
    }
```
but this isn't a real solution.

Steps to reproduce:
1. I installed the typings using this command:
`typings install -S npm~azure-storage`
2. Build using typescript 2
`tsc`

I noticed that typings is installing version 0.10.0 although the actual library source is at 1.2.0 which likely fixes the issue.

```
{
  "resolution": "main",
  "tree": {
    "src": "https://raw.githubusercontent.com/typed-contrib/azure-storage-node/9ccffd354cf5d59934c7b750da72f7d29fe4b6d1/typings.json",
    "raw": "registry:npm/azure-storage#0.10.0+20160903154543",
    "main": "lib/azure-storage.d.ts",
    "name": "azure-storage",
    "type": "typings"
  }
}
```
Couple solutions that might work:
1. Update typings registry to use the latest version.
2. Update library to specify `types` property in `package.json` so it can ship types with itself (I think this is recommended if the library is written in TypesScript otherwise ship separately)

Also, when I tried to use the newer method to install types for TypeScript 2:
`npm install -D @types/azure-storage` it said the package did not exist.  It would be nice to support this so automatic type resolution works in VSCode.

**Comment by hasonmsft** [comment]
@mattmazzola , thanks for raising this issue. We'll look into this and get back to you.

**Comment by sromovskypeter** [comment]
No progress on this issue?

**Comment by Farokhcpu** [comment]
I fixed the issue and created a pull request. 
At least, I think I have solved it.
