### ISSUE TITLE
JSdoc doesn't work

### ISSUE THREAD

**Issue by sebakerckhof** [Azure/azure-storage-node#232]
According to: http://azure.github.io/azure-storage-node/#toc12

Running `grunt jsdoc` generates the documentation, but this throws all kind of errors.
There are modules missing (taffydb & marked) which are not in the package.json dev dependencies and then you get a bunch of other errors.

**Comment by hasonmsft** [comment]
@sebakerckhof , thanks for raising this. This is already fixed in the PR https://github.com/Azure/azure-storage-node/pull/220. Could you try the latest dev branch? We'll working on the release and will be merged to master branch soon.

**Comment by hasonmsft** [comment]
@sebakerckhof , this issue has been fixed in master branch also together with 1.4.0 release.

**Comment by sebakerckhof** [comment]
Yep, thanks
