### ISSUE TITLE
getBlobToText() Failure With Large Blobs

### ISSUE THREAD

**Issue by geneh** [Azure/azure-storage-node#234]
`getBlobToText` fails intermittently when run from Azure Web Jobs with blobs over 20 MB with the following error (the callback is not called): 
```
D:\Program Files (x86)\nodejs\6.9.1\node.exe: c:\ws\src\util.h:309: Assertion `(buf_) != (nullptr)' failed.
```

The message below is not printed in this case:
``` 
blobService.getBlobToText(container, blob, (error, text) => {
  console.log('Text length:', text.length);
});
```
The workaround is using `getBlobToStream` instead.

Should the callback be called in this case?
Is there blob size limitation for using `getBlobToText`?

**Comment by hasonmsft** [comment]
@geneh , thanks for raising this. We'll look into this.

**Comment by XiaoningLiu** [comment]
There is no limitation from on the SDK level. According to your error message, it seems a Node.js buffer related error. There are memory usage limitation especially for a 32 bit Node.js version. For large blobs, please do use ```getBlobToStream``` or other stream similar methods.

We will close this issue if no further updates, please feel free to open when you meet it again.

**Comment by geneh** [comment]
Thanks!
