### ISSUE TITLE
KeyVault encryption integration

### ISSUE THREAD

**Issue by murdockcrc** [Azure/azure-storage-node#236]
Hi,

Related to this article:
https://docs.microsoft.com/en-us/azure/storage/storage-client-side-encryption#encryption-and-decryption-via-the-envelope-technique

Are these KV integration capabilities for blob upload also available on the NodeJS SDK? The article only notes .NET, Java and Python.

**Comment by hasonmsft** [comment]
@murdockcrc , this item is not available for NodeJS SDK now. But it's in our backlog. We'll get you updated when it's ready.

**Comment by doodlefolks** [comment]
Is there an ETA on this feature? I'm currently using node crypto module, but this is much preferred.

**Comment by abhijeetahuja** [comment]
do we have any ETA yet?

**Comment by yaxia** [comment]
+@XiaoningLiu and @jiacfan to comment.
