### ISSUE TITLE
queryEntities maxResults / PageSize

### ISSUE THREAD

**Issue by 1N50MN14** [Azure/azure-storage-node#243]
Looking at `queryEntities()` I see it only accepts `table`, `query`, and `continuationToken` arguments. 

How else do I pass `maxResults` to the query headers to determine each page size?

**Comment by hasonmsft** [comment]
`TableQuery` has a method `top` which you can determine the items to fetch (aka page size).

**Comment by 1N50MN14** [comment]
Thanks @hasonmsft for some reason I confused it with SQL-like `limit` - so to double check, I `top` acts as "pageSize" where I can iterate through the results by passing the continuation token, until I get no results correct? also are there any edge cases I need to be aware of?

**Comment by hasonmsft** [comment]
@1N50MN14 , yes, you are right. You can iterate through the result by passing the continuation token, until you get the result without no continuation token. :)

**Comment by 1N50MN14** [comment]
Cool that was too easy ;) Thanks again, closing issue
