### ISSUE TITLE
Queue trigger and event receiver 

### ISSUE THREAD

**Issue by hussamEddinAlhendi** [Azure/azure-storage-node#248]
Is there away to dequeue message automatically once added to storage queue (using event receivers or triggers functions such as QueueTriggerAttribute in C#.

using infinite loops to get messages is performance issue and cause error(Error: getaddrinfo ENOTFOUND)

**Comment by hussamEddinAlhendi** [comment]
@hasonmsft Is there any tutorial to use QueueTrigger in https://github.com/Azure/azure-webjobs-sdk-script

**Comment by hasonmsft** [comment]
@hussamEddinAlhendi , does https://github.com/Azure/azure-webjobs-sdk-script/tree/dev/sample/QueueTrigger help?
