### ISSUE TITLE
getUrl() may add duplicate ? in front of the SAS Token

### ISSUE THREAD

**Issue by XiaoningLiu** [Azure/azure-storage-node#255]
For getUrl(), there will be a duplicate **?** in the generated url. As a result, the url will fail to the authentication.

For example, **%3F** is added after **?**
```
queueService.getUrl('queue', '?xx=xx')
"https://myaccount.queue.core.windows.net/queue?%3Fxx=xx"
```

**Comment by avodovnik** [comment]
@XiaoningLiu is this closed with a solution, or is the solution to simply remove the "?" in the sas token, i.e. 

`queueService.getUrl('queue', 'xx=xx')`

Thanks.
