### ISSUE TITLE
.from missing from Azure.TableQuery

### ISSUE THREAD

**Issue by atrauzzi** [Azure/azure-storage-node#262]
```
        const query = new Azure.TableQuery();
        console.log(query.where); // [Function]
        console.log(query.from); // undefined
```

Using 1.2.0-preview via TypeScript.

cc. https://github.com/Azure/azure-sdk-for-node/issues/2040

**Comment by hasonmsft** [comment]
@atrauzzi , thank you for reporting this issue. We'll take a look and get back to you. Or PR is welcome. :)

**Comment by hasonmsft** [comment]
@atrauzzi , the .from method is already removed from the TableQuery. Refer to https://github.com/Azure/azure-storage-node/blob/master/lib/services/table/tablequery.js for more detailed information.

**Comment by atrauzzi** [comment]
_"already"_?

I'm saying it's missing.  Why was it removed?

**Comment by hasonmsft** [comment]
@atrauzzi , the API of the TableService is already changed and this function is not needed anymore. To query entities from a table, you need to pass the table name in the first parameter `table` instead of constructing TableQuery and call `.from()`. 
```
TableService.prototype.queryEntities = function (table, tableQuery, currentToken, optionsOrCallback, callback) {
```

**Comment by vinjiang** [comment]
Feel free to let us know if further assistance needed.
