### ISSUE TITLE
Please make PrepareMetaData and UploadBlock part of blob storage (!)

### ISSUE THREAD

**Issue by 1N50MN14** [Azure/azure-storage-node#264]
I spent a whole day writing a node module I was going to publish for direct / chunked uploading to Azure Storage only to encounter the error `The specified resource does not exist` when making a request to `/PrepareMetaData`.

Apparently, `PrepareMetaData` and `UploadBlock` are some sort of "Logic App" actions which I need to create.  

My first thought (having used S3 thus far): WTF is Logic App and why are those not built-in HTTP(s) endpoints. 

My second thought: Fair Enough, go add a Logic App, click on Pricing details in the portal which takes me here: https://azure.microsoft.com/en-us/pricing/details/app-service/?amp%3Bclcid=0x409

My third thought: Why does this page show pricing for "App Service - Create web and mobile apps for any platform" - I'm doing that, just not using "App Service".  Assuming "Logic App" was renamed to "App Service", let's look at the pricing details.

My fourth thought: Too complicated! Instances? I don't need that! I just want to upload to my Azure Blob Storage! Might just as well run my own machines and drop direct uploads all together.

My final thought: No wonder I could not find any published modules for direct / chunked uploading of files.

Team, please make those "actions" built into blob containers so we don't have to deal with this stuff.. love Azure, but these kind of things need to be transparent for users. 

In the meantime, re-writing using `appendBlob` REST API and md5 integrity check.

**Comment by XiaoningLiu** [comment]
Thanks for your reporting! Azure Storage currently doesn't have a ```PrepareMetaData``` REST API, https://docs.microsoft.com/en-us/rest/api/storageservices/azure-storage-services-rest-api-reference 

Please commit this feature request on azure feedback and vote it up! https://feedback.azure.com/forums/217298-storage
