### ISSUE TITLE
azure-storage Storage error: bad request

### ISSUE THREAD

**Issue by kaushik-hemant** [Azure/azure-storage-node#268]
Downloading and uploading files from storage gives StorageError: BadRequest, using nodejs client (azure-storage), please respond with any solution.

**Comment by hasonmsft** [comment]
@kaushik-hemant , could you provide more detail for the error? 

1. What's the version of the azure-storage package you are using? 
2. Could you provide some network trace or get the client-side telemetry by turning on the DEBUG log? 
```
var storage = require('azure-storage');
…
blobService.logger.level = storage.Logger.LogLevels.DEBUG;
```

**Comment by kaushik-hemant** [comment]
enabled logging what should i have to share?

**Comment by hasonmsft** [comment]
@kaushik-hemant , you can share me the console output.

**Comment by kaushik-hemant** [comment]
Request: 
[2017-02-16T09:14:37.970Z]debug : FINAL REQUEST OPTIONS:
{ url: 'https://abc.blob.core.windows.net:443/asset-0184b983-4f0d-417b-8e0c-4c85d3e488ca/iPhone8-InnovativeScreen_201702141318120247.mp4',
  method: 'HEAD',
  headers: 
   { 'x-ms-client-request-id': '56dd6d40-f428-11e6-b505-9f0e51346ae0',
     'user-agent': 'Azure-Storage/1.4.0 (NODE-VERSION v4.5.0; Windows_NT 10.0.14393)',
     'x-ms-version': '2015-12-11',
     'x-ms-date': 'Thu, 16 Feb 2017 09:14:37 GMT',
     accept: 'application/atom+xml,application/xml',
     'Accept-Charset': 'UTF-8',
     'content-type': '',
     'content-length': 0,
     authorization: 'SharedKey abc+TPmhP+rvYygr/UBufoywFkep+UG13gjm0BM9Pyg=' },
  encoding: undefined }

**Comment by kaushik-hemant** [comment]
Response: [2017-02-16T09:14:39.820Z]debug : RESPONSE:
{ error: 
   { [StorageError: BadRequest]
     name: 'StorageError',
     message: 'BadRequest',
     code: 'BadRequest',
     statusCode: 400,
     requestId: '7bc69b64-0001-005f-1535-88cc68000000' },
  response: 
   { isSuccessful: false,
     statusCode: 400,
     body: '',
     headers: 
      { 'transfer-encoding': 'chunked',
        vary: 'Origin',
        server: 'Microsoft-HTTPAPI/2.0',
        'x-ms-request-id': '7bc69b64-0001-005f-1535-88cc68000000',
        date: 'Thu, 16 Feb 2017 09:14:37 GMT',
        connection: 'close' },
     md5: undefined } }
some error occured in downloading blob having ID : 60377
{ [StorageError: BadRequest]
  name: 'StorageError',
  message: 'BadRequest',
  code: 'BadRequest',
  statusCode: 400,
  requestId: '7bc69b64-0001-005f-1535-88cc68000000' }

**Comment by hasonmsft** [comment]
@kaushik-hemant , that's the name of your storage account?

**Comment by kaushik-hemant** [comment]
Actually in a node application, i am downloading files from storage to local directory while calling the method **getBlobToLocalFile** above comments shows the request and response which is bad request but all things are configured properly like connection string and all.

Can you please elaborate as in response there is no such message like where the issue is?

**Comment by hasonmsft** [comment]
It only said it's a BadRequest in the response and no detailed information for the reason. If you can provide the account name, we can take a look at the server side for more detailed reason

```
response:
 { isSuccessful: false,
 statusCode: 400,
 body: '',
 headers:
 { 'transfer-encoding': 'chunked',
 vary: 'Origin',
 server: 'Microsoft-HTTPAPI/2.0',
 'x-ms-request-id': '7bc69b64-0001-005f-1535-88cc68000000',
 date: 'Thu, 16 Feb 2017 09:14:37 GMT',
 connection: 'close' },
 md5: undefined } }
```

**Comment by kaushik-hemant** [comment]
also media storage streaming video taking lot of time, accountname is kazastreammediaserv

**Comment by hasonmsft** [comment]
@kaushik-hemant , got the error. Looks you have some upper case character in your account name. Please double check.

**Comment by kaushik-hemant** [comment]
no uppercase letter its kazastreammediaserv

**Comment by hasonmsft** [comment]
The first character 'K' is uppercase??? Please double check. From the server log, the account name is Kazastreammediaserv

**Comment by kaushik-hemant** [comment]
no its lowercase i know the naming issues with storage name

**Comment by kaushik-hemant** [comment]
i think some other issue causing bad request
