### ISSUE TITLE
Make it clearer in the docs what keys are available for the headers (naming convention inconsistence)

### ISSUE THREAD

**Issue by renatoargh** [Azure/azure-storage-node#270]
Since there are inconsistences among the casing patterns I suggest that you make it clear in the docs what are the possible keys for the headers hash. I spent a lot of time trying to figure out how to set `contentDisposition` header, looked for it at the examples folder, and finally browsed through the source code to find out that for this specific setting I have to start with lower case.

Thanks for the awesome job!

```
  var possibleHeaders = {
    contentDisposition: 'foo',
    cacheControl: 'foo',
    contentType: 'foo',
    contentEncoding: 'foo',
    contentLanguage: 'foo'
  }

  // notice that AccessPoliciy hash have all keys starting with uppercase
  const signature = blobService.generateSharedAccessSignature(container, blob, {
    AccessPolicy: {
      Permissions: azure.BlobUtilities.SharedAccessPermissions.READ,
      Start: new Moment().utc().subtract(5, 'minutes').toDate(),
      Expiry: new Moment().utc().add(5, 'minutes').toDate()
    }
  }, possibleHeaders)
```

**Comment by hasonmsft** [comment]
@renatoargh , thanks for raising this. We'll update the doc accordingly.

**Comment by hasonmsft** [comment]
From the documentation, it already list the available keys for the `headers`. http://azure.github.io/azure-storage-node/BlobService.html#generateSharedAccessSignature__anchor
