### ISSUE TITLE
Adaptable to work in browser?

### ISSUE THREAD

**Issue by joewood** [Azure/azure-storage-node#28]
I've been trying to run **browserify** on the azure-storage package to see if a running version of API could be run in the browser for CORS access to the blob service.  This would also be useful for Cordova based apps.  So far these are the issues/workarounds that I've hit:
* node version check breaks. This uses `process.version` ( in the azure-util module). I hacked this to return a sensible value if `process.version` is **undefined**.
* The calls to `readFileSync` fail. The **brfs** transform for browserify does not fix the issue (the AST parsing cannot rewrite the code because it goes through an indirection). It's used in two places, one for the MIME type loading and the other for loading the **packages.json** (which is just a version export). 
* I ended up using **browserify-mime** to replace the **mime** dependency at bundle time using **remapify**.  This seems to have worked, but I'm still testing.

Could these fixes be added to the node package to support a in-browser compatible build?

**Comment by aauberg** [comment]
Has there been any movement on this issue? I would like to see the same in-browser compatible build that @joewood was working on.

**Comment by jensgorm** [comment]
I absolutely concur. I would love to use a browser-compatible version of the package for use in a Cordova app.

**Comment by jasonlfunk** [comment]
Does anyone know a workaround here? How can this be used in the browser?

**Comment by gangsir** [comment]
We are fixing the above reported issues and will release a fix soon.

**Comment by yaxia** [comment]
The latest release 0.7.0 can work with Browserify. Please take a try, thanks.
