### ISSUE TITLE
CORS / Blob / 206 partial content

### ISSUE THREAD

**Issue by 1N50MN14** [Azure/azure-storage-node#280]
I'm uploading files using the SDK to a container, which has CORS enabled (pretty much * all over), been experiencing a weird situation where GET requests on video files get cancelled.

Here's an example which you can copy & paste straight into the browser:
Thumbnail - works consistenly:
https://twirmstoragedev.blob.core.windows.net/filter-overlays/vid-7a245149-a782-4d20-898a-530ff0827942-90x160.jpeg

Video - if it does load, hit refresh again, request will fail due to 206 partial content error:
https://twirmstoragedev.blob.core.windows.net/filter-overlays/vid-7a245149-a782-4d20-898a-530ff0827942-450x800.mp4

As you can see from the response headers, I have the content type set correctly:
`Content-Type:video/mp4`

However, if I use the token based "Download" link from the portal, I'm able to consistenly load the video. 

Very puzzled with this one, even tried to download the whole thing as a blob via XHR request, same thing here I'm not able to consistenly download the file; tested using Chrome, Safari and Firefox. Any advice?

Thanks

**Comment by hasonmsft** [comment]
@1N50MN14 , I tried to download the mp4 file to local disk and it cannot be played. Something wrong with the mp4 file?

**Comment by 1N50MN14** [comment]
@hasonmsft Not really, the reason it didn't play is because for some reason blob storage aborted the download at some point. If you try to download the file using `wget` or `curl` you'll see that it works fine. Anyway, I "resolved" the issue by mapping my blob storage to a CDN and that seems to consistenly work..

**Comment by hasonmsft** [comment]
I tried downloading in browser directly and curl. Still cannot open the downloaded mp4 file.

**Comment by 1N50MN14** [comment]
That's strange... the file plays perfectly fine here..  what's the downloaded file size? also could you please try to download the same file through https://media.twirm.net/filter-overlays/vid-7a245149-a782-4d20-898a-530ff0827942-450x800.mp4 ?

**Comment by hasonmsft** [comment]
1,093,466 bytes. Still doesn't work when downloading from media.twirm.net

**Comment by 1N50MN14** [comment]
That's strange, doesn't work as it doesn't open at all? (the video itself is black)

**Comment by hasonmsft** [comment]
On Windows, when clicking the play button, it get paused immediately. And on MAC, I'm promoted that the media file cannot be opened.

**Comment by 1N50MN14** [comment]
So weird.. the video itself was generated on Azure Functions (which runs Windows I think), the video works on both Linux and Mac for me.. could you please try to download another file using curl https://twirmstoragedev.blob.core.windows.net/filter-overlays/vid-20c22307-c16c-42b2-8944-a163109f5953-450x800.mp4 ?

**Comment by hasonmsft** [comment]
Still no good luck on both Windows and MAC

**Comment by 1N50MN14** [comment]
I've seen weird... ok just manually uploaded a video https://twirmstoragedev.blob.core.windows.net/tmp/3.mp4 

(if it does work, then it would've been worth the download time)

**Comment by hasonmsft** [comment]
This one works fine.

**Comment by 1N50MN14** [comment]
hehe thank you :) 

Ok then I guess something must be off with either ffmpeg on Azure Functions or the upload itself... basically the other videos are resized / cropped variations. I need to test on completely different machines, should I keep the issue open or close it for now and cc you for further updates?

**Comment by hasonmsft** [comment]
Sure. Feel free to close this issue for now and get us updated

**Comment by 1N50MN14** [comment]
Cool, thank you, closing for now
