### ISSUE TITLE
BlobService.createBlockBlobFromText encodes blob name in URL format when it is already properly escaped 

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-storage-node#288]
In my example I am passing a string for a blob name that I have already escaped using encodeURIComponent(). The URL created for the blob for REST access is then escaped again (specifically the '%' characters). I don't think this should be default behavior if the blob name is correctly escaped to begin with.

**Comment by amarzavery** [comment]
https://github.com/Azure/azure-sdk-for-node/issues/2104

**Comment by XiaoningLiu** [comment]
Hi @doodlefolks, the library will escape the blob name by default. Actually, it's hard for a library to judge whether the blob name is escaped by customers or the customers just set that blob name. It's not a library's job. You'd better to decode the blob name first.
