### ISSUE TITLE
Easier way to defect retry policy requests conflicting with a previous timeout that actually succeeded

### ISSUE THREAD

**Issue by jasmcc** [Azure/azure-storage-node#290]
We've encountered a somewhat surprising issue when making calls with an if-match under heavy CPU, network traffic, and the default retry policy.

**Setup**
On AzureTable, call ExecuteAsync to update an entity with a provided eTag.

Very rarely, the following will happen:
1. From the storage client library perspective, the call to the storage account times out, so it retries.
2. However, the call actually succeeded on the storage account, the reply was just never received, or not received in time.
3. As a result, the update attempt conflicts, as the eTag is changed from the previous request.

I suppose this is inevitable with any retry policy in some form, but it's pretty surprising to track down if you don't know about it in advance.

We work around it by storing a Guid.NewGuid() on all requests in a property and checking if it matches when we get a conflict exception that includes a retry.

The code is surprisingly complicated, however.  Is there some way for the library and service to detect this sort of scenario itself?

**Comment by XiaoningLiu** [comment]
@jasmcc 

Sorry for the late reply. Thanks for taking time for such detailed investigation. Sounds the issue is rare and the root cause is related to the server side latency. I think we better check out what makes such latency happen.

Please provide the request_ids for such requests when you come into this issue next time, we can help check what is going on the server side. Then we can locate the core issues.

**Comment by jasmcc** [comment]
Thanks, I'll add some logging code to grab the request identifier.  It may take a while, it's rare without a dedicated load test.

I suspect it's not a table service issue, as:
1. The write is succeeding on the server on the first try.
2. We are nowhere near the scale limits on table usage.
3. Our service calling to table is at 80%-100% of CPU and tons of network traffic.

So my suspicion is that it's either the underlying network connection getting treated as timeout due to congestion or something due to await scheduling & CPU starvation on the VM.  "Don't be so aggressive about overscheduling your VM" is an obvious workaround, but it's still a thing.

**Comment by vinjiang** [comment]
Feel free to let us know if we can provide further assistance.
