### ISSUE TITLE
Issue with untrimmed space bars in metadata

### ISSUE THREAD

**Issue by tvoloshyn** [Azure/azure-storage-node#296]
Hi developers,

I could be wrong and it well could be that there was something else in my code which caused this issue, but it looks like that there is a signature mismatch when it comes to metadata and untrimmed space bars at the end of a string.

So whenever I supply metadata (strings) which might contain a "trailing spacebar" using `createWriteStreamToBlockBlob` method, I get an error:

**StorageError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.**

Full Error:
`website-0 (err): StorageError: Server failed to authenticate the request. Make s                                              ure the value of Authorization header is formed correctly including the signatur                                              e.
website-0 (err): RequestId:XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
website-0 (err): Time:2017-04-14T13:24:01.7162705Z
website-0 (err):     at Function.StorageServiceClient._normalizeError (/datadriv                                              e/website/code/node_modules/azure-storage/lib/common/services/storageserviceclie                                              nt.js:1174:23)
website-0 (err):     at BlobService.StorageServiceClient._processResponse (/data                                              drive/website/code/node_modules/azure-storage/lib/common/services/storageservice                                              client.js:729:50)
website-0 (err):     at Request.processResponseCallback [as _callback] (/datadri                                              ve/website/code/node_modules/azure-storage/lib/common/services/storageservicecli                                              ent.js:310:37)
website-0 (err):     at Request.self.callback (/datadrive/website/code/node_modu                                              les/azure-storage/node_modules/request/request.js:187:22)
website-0 (err):     at emitTwo (events.js:100:13)
website-0 (err):     at Request.emit (events.js:185:7)
website-0 (err):     at Request.<anonymous> (/datadrive/website/code/node_module                                              s/azure-storage/node_modules/request/request.js:1044:10)
website-0 (err):     at emitOne (events.js:90:13)
website-0 (err):     at Request.emit (events.js:182:7)
website-0 (err):     at IncomingMessage.<anonymous> (/datadrive/website/code/nod                                              e_modules/azure-storage/node_modules/request/request.js:965:12)
website-0 (err):     at emitNone (events.js:85:20)
website-0 (err):     at IncomingMessage.emit (events.js:179:7)
website-0 (err):     at endReadableNT (_stream_readable.js:913:12)
website-0 (err):     at _combinedTickCallback (internal/process/next_tick.js:74:                                              11)
website-0 (err):     at process._tickDomainCallback (internal/process/next_tick.                                              js:122:9)
`

When I trim space bar (one in my case) it seems to be working fine.

Can that be that one of the parties (library/server) does trim metadata values before generating signature and the other one doesn't and therefore there is a mismatch ?

Regards,
T

**Comment by XiaoningLiu** [comment]
@tvoloshyn Sorry for the late response. There maybe some mismatch. Does the metadata **key** or **value** contain the spacebars you mentioned?

According to the Azure Storage authentication guideline, we need trim any white space around the colon in the header.

https://docs.microsoft.com/en-us/rest/api/storageservices/authentication-for-the-azure-storage-services

**Comment by tvoloshyn** [comment]
@XiaoningLiu it's inside the value.

**Comment by vinjiang** [comment]
We assume the doc addressed the questions, if not, please let us know.
