### ISSUE TITLE
listBlobDirectories Method

### ISSUE THREAD

**Issue by dillten** [Azure/azure-storage-node#3]
The .NET API provides the type CloudBlobDirectory to enumerate BlobPrefix objects in the XML return from the server. Example of enumeration:
`AzureContainer.ListBlobs().OfType<CloudBlobDirectory>`
Example of Azure API call made from executing this method:
`https://account.blob.core.windows.net/container?restype=container&comp=list&delimeter=%2F`
Which just lists all blobs with a delimiter - same as listBlobsSegmented with a delimiter passed as an option.

The current azure-storage-node listBlobsSegmented & withPrefix method drop the BlobPrefix objects from the result, as it should. 

I suggest an addition of a listBlobDirectories method to return these results, given a container and prefix.

**Comment by yaxia** [comment]
We will fix this issue in an upcoming release of our module in such a way that we will keep the metadata key as it is when setting the metadata(i.e change the offending line). However, please be noted that the metadata keys retrieved from the service will be converted into lowercase by the http component of Node.js. Please refer to https://github.com/joyent/node/issues/1954 for more information. We also suggest that any application should not rely on the case information in the metadata key. Thanks.

**Comment by dillten** [comment]
Resolved by pull #49. Thanks!!
