### ISSUE TITLE
Azure Storage 2.1.0 breaks with TypeScript 2.3.0

### ISSUE THREAD

**Issue by iandvt** [Azure/azure-storage-node#300]
Just an FYI - TypeScript 2.3.0 was released ~2 hours ago and it breaks this package.

node_modules/azure-storage/typings/azure-storage/azure-storage.d.ts(61,22): error TS2415: Class 'BlobService' incorrectly extends base class 'StorageServiceClient'.
  Types of property 'withFilter' are incompatible.
    Type '(newFilter: IFilter) => () => any' is not assignable to type '(newFilter: IFilter) => StorageServiceClient'.
      Type '() => any' is not assignable to type 'StorageServiceClient'.
        Property 'defaultLocationMode' is missing in type '() => any'.
node_modules/azure-storage/typings/azure-storage/azure-storage.d.ts(8878,35): error TS2300: Duplicate identifier 'AccessConditions'.
node_modules/azure-storage/typings/azure-storage/azure-storage.d.ts(8896,13): error TS2300: Duplicate identifier 'AccessConditions'.

**Comment by XiaoningLiu** [comment]
Thanks for your timely report! @iandvt

**Comment by iandvt** [comment]
Any ETA on a fix for this?

**Comment by XiaoningLiu** [comment]
Already fixed in 2.2.0. Issue could be closed.
