### ISSUE TITLE
can't setencoding('utf-8') on stream created by createReadStream

### ISSUE THREAD

**Issue by andy26nash** [Azure/azure-storage-node#301]
Note: Not a node JS expert so do not rule out incompetence on my part.

Trying to process large files coming from Azure Blob Storage and streaming them through JSONStream but JSONSteam is barfing because of the Byte Order Mark at the start of the file.

So was trying to set the encoding on the stream in the hope that this would remove the BOM. So my code looked something like this...

var blobstream = blobSvc.createReadStream(conf.blob.container, file.name, function (err) {
                if (err) {
                    console.log('problem opening the blob: ', err);
                    process.exit(0);
                } 
            })
blobstream.setEncoding('utf-8')

but when I run this I get

blobstream.setEncoding('utf-8')
                       ^

TypeError: blobstream.setEncoding is not a function.

I can successfully blobstream.pipe(stream); later on so I know blobstream is a valid object.

When I look in the debugger it seems blobstream is a chunkstream.

Should the stream returned by createReadStream behave like a normal stream?

is there another way of reliably removing the BOM if it exists?

**Comment by XiaoningLiu** [comment]
Hi andy26nash, you can create your own readable stream based on the blobStream. By adding a on('data') listener, you can remove the BOM.
