### ISSUE TITLE
createWriteStreamToBlockBlob usage

### ISSUE THREAD

**Issue by jamesdixon** [Azure/azure-storage-node#302]
Hello,

I'm trying to use `createWriteStreamToBlockBlob` to write the contents of a local CSV file to an Azure Blob. Unfortunately, I'm not seeing the blob written to storage as expected and not seeing any errors either. Here's the code I was using:

```js
    const blobService = Azure.createBlobService();
    const readStream = fs.createReadStream('input.csv');
    const blobWriteStream = blobService.createWriteStreamToBlockBlob('backups', 'output.csv');

    // Write contents of local input.csv to output.csv on Azure
    readStream.pipe(blobWriteStream);

    // Output any errors
    blobWriteStream.on('error', (err) => {
        console.log(err);
    });
```

Is my usage of this wrong?

Thanks!

**Comment by jamesdixon** [comment]
@hasonmsft would you be able to provide any insights on this? Much appreciated!

**Comment by XiaoningLiu** [comment]
@jamesdixon Please try to add a callback function to the BlobService.createWriteStreamToBlockBlob. Upload result and errors will be passed through the callback function.

```
const blobWriteStream = blobService.createWriteStreamToBlockBlob('mycontainer', 'myblob', function (error, result, response) {
    if (!error) {
        console.log('blobWriteStream callback');
        console.log(result);
        console.log(response);
    } else {
        console.log('blobWriteStream error');
        console.error(error);
    }
});
```

**Comment by jamesdixon** [comment]
@XiaoningLiu thanks for your response!

Interestingly, the callback never seems to be run for me. I'm running this via a test suite (Ava), so I'm wondering if it has something to do with it.

That said, it works fine if I use a writestream to write to a local file.

Confused!

**Comment by jamesdixon** [comment]
Also, with this method, does the file need to first exist in the container?

**Comment by jamesdixon** [comment]
@XiaoningLiu I dove into the azure storage code and have traced the operation all the way to the `__uploadContentFromChunkStream` method in `blobservice.js` (line 5079), and this appears to be where things stop. The `streamLength` is null and when I log the `speedSummary` at the end, I see the following:

```js
SpeedSummary {
  name: 'output.csv',
  _startTime: 1493842195261,
  _timeWindowInSeconds: 10,
  _timeWindow: 10000,
  _totalWindowSize: 0,
  _speedTracks: [ , , , , , , , , ,  ],
  _speedTrackPtr: 0,
  totalSize: null,
  completeSize: 0 }
```

Unfortunately, I don't see any errors and the callback is never called 😢

**Comment by jamesdixon** [comment]
@XiaoningLiu I'm going to close this for now as I was able to run this code successfully outside of my test framework. Thanks for your help!
