### ISSUE TITLE
Support for copying blobs to a different storage account

### ISSUE THREAD

**Issue by mariecl** [Azure/azure-storage-node#303]
The Azure storage documentation for the Copy Blob operation states:
> Beginning with version 2015-02-21, the source for a Copy Blob operation can be an Azure file in any Azure storage account.

However, I can't find how to specify the account name in the options passed to [BlobService.prototype.startCopyBlob](https://github.com/Azure/azure-storage-node/blob/master/lib/services/blob/blobservice.js#L2097). Am I missing something? Or could support for this feature be added to the SDK?

**Comment by XiaoningLiu** [comment]
Hi Mariecl, you can pass the source blob uri directly with SAS token to the startCopyBlob method.

Beginning with version 2015-02-21, the source object may be a file in the Azure File service. If the source object is a file that is to be copied to a blob, then the source file must be authenticated usign a shared access signature, whether it resides in the same account or in a different account.

Only storage accounts created on or after June 7th, 2012 allow the Copy Blob operation to copy from another storage account.

Here are some examples of source object URLs:

- https://myaccount.blob.core.windows.net/mycontainer/myblob
- https://myaccount.blob.core.windows.net/mycontainer/myblob?snapshot=<DateTime>

When the source object is a file in the Azure File service, the source URL uses the following format; note that the URL must include a valid SAS token for the file:

```
blobService.startCopyBlob('https://sourceaccount.blob.core.windows.net/sourcecontainer/sourceblob?sasString',
 'mycontainer', 'copiedBlob', function (error, result, response) {
    if (!error) {
        console.log('startCopyBlob callback');
        console.log(result);
        console.log(response);
    } else {
        console.log('startCopyBlob error');
        console.error(error);
    }
});
```

**Comment by amit12cool** [comment]
Is it possible to copy between 2 storage accounts? I cannot see any argument in ```startCopyBlob.``` for destination storage account connection string or uri etc.

**Comment by wiltonjunior** [comment]
How could you compose a complete folder?

**Comment by XiaoningLiu** [comment]
SDK only supports API to copy single blob. You need to implement copy folder by your self based on SDK.

 To copy container or account, please refer to AzCopy (commandline tool) or DMlib (.net core based library)

**Comment by amit12cool** [comment]
Is there a way to get a callback on success or failure to copy blob between 2 different storage accounts? At present, startCopyBob I see it just returns the request has been accepted
