### ISSUE TITLE
Unable to connect to CosmosDB with Table API

### ISSUE THREAD

**Issue by jeffwilcox** [Azure/azure-storage-node#307]
While trying to use the Azure Storage Table-compatible preview features of Cosmos DB, we're finding that the Node SDK does not seem to be able to connect - the URLs are being reported as bad from the Cosmos DB endpoint.

There is a "preview" NuGet for the .NET SDK + CosmosDB support, is it not entirely compatible, or should this work?

We're trying to use the table connection string provided by the Azure portal within the DocDB instance. It sets the TableEndpoint to be `https://MYDBNAME.documents.azure.com`, and so debugging the Node SDK around `storageserviceclient.js#307` the final request URL ends up being `https://MYDBNAME.documents.azure.com:443/Tables(%27mytablename%27)", to which the server responds:

Status code 400

Request body
```
{"code":"BadRequest","message":"Request url is invalid.\r\nActivityId: e92e7add-f625-4908-a0de-30fceab1be19"}"
```

**Comment by XiaoningLiu** [comment]
Hi @jeffwilcox , are you looking for the Node.js SDK for CosmosDB/DocumentDB? Please view following links:

https://docs.microsoft.com/en-us/azure/cosmos-db/
https://docs.microsoft.com/en-us/azure/documentdb/documentdb-sdk-node

Currently, Azure Storage Node.js Client Library is not compatible with CosmosDB features.

**Comment by jeffwilcox** [comment]
No, I am not. I am looking for this Node.js SDK for storage to support the Premium Table product introduced at the Build conference.

I'm happy to help contribute an implementation but cannot find information about how the table API built into Cosmos is incompatible with the storage Azure storage APIs... there is a forked Azure Storage .NET SDK that somehow supports it, so I would expect something similar for Node.js.

**Comment by jeffwilcox** [comment]
Closing as it sounds like the Premium Table work is completely separate from the standard storage library. Sorry for any confusion!
