### ISSUE TITLE
security vulnerability with validator versions <3.34.0 >=3.0.0

### ISSUE THREAD

**Issue by sharathbaddam** [Azure/azure-storage-node#308]
I started using snyk.io and nsp(nodesecutiry.io) for my project that uses azure-storage-node and azure-iot-node to find any known risks and vulnerabilities in all the node_modules.

when i ran snyk.io test, it generated a report saying that validator used by azure-storage-node has a known vulnerability to Cross-site Scripting (XSS) in IE9.

here is the link to description in snyk.io :-  https://snyk.io/vuln/npm:validator:20150313

current version of validator is 7.0.0, azure-storage-node uses 3.22.2.

**Comment by sharathbaddam** [comment]
I think there is a open pull request to address this issue :- https://github.com/Azure/azure-storage-node/pull/261

**Comment by XiaoningLiu** [comment]
Thanks @sharathbaddam! The PR looks good!

**Comment by lostintangent** [comment]
@XiaoningLiu Has this issue been resolved/released in v2.2.0?

**Comment by XiaoningLiu** [comment]
Yes, in https://github.com/Azure/azure-storage-node/releases/tag/v2.2.0
