### ISSUE TITLE
TableService.createTableIfNotExists fails if table already exists

### ISSUE THREAD

**Issue by yads** [Azure/azure-storage-node#31]
If you call `createTableIfNotExists` in quick succession, the handler for the createTable call in the `_doesTableExist` callback fails. The problem boils down to the fact that `_doesTableExist` can return false for a bunch of requests. Then when those requests return they will call `createTable`. The handler for this table, checks if the error status code states that the table already exists. It then attempts to set the isSuccessful flag on the response to true. The problem is that on error, the createResponse object is null. See https://github.com/Azure/azure-storage-node/blob/master/lib/services/table/tableservice.js#L663

**Comment by MIJOTHY** [comment]
Any updates/eta for fix?

**Comment by slepox** [comment]
This issue is fixed in 0.4.4 release.
