### ISSUE TITLE
How can I check blob upload progress?

### ISSUE THREAD

**Issue by flickz** [Azure/azure-storage-node#310]

**Comment by XiaoningLiu** [comment]
@flickz A SpeedSummary object is the return value for blob uploading APIs, you can check the upload status from SpeedSummary. 

```
    var speedSummary = blobService.createBlockBlobFromStream('mycontainer', file.name, fileStream, file.size, function(error, result, response) {...}

    setTimeout(function() {
        if (!finishedOrError) {
            var process = speedSummary.getCompletePercent();
            displayProcess(process);
            refreshProgress();
        }
    }, 200);
```

We are also considering to add evens for uploading progress change.

**Comment by janakiramangara** [comment]
@XiaoningLiu Nice work, its working fine. Need to show progress. Unable  to get value from  speedSummary.getCompletePercent();. When your going to add 'events' for this. Please let me know.
thanks.

**Comment by absoludity** [comment]
+1 to enable events for upload progress, and with a finer granularity than the current implementation. The [sample mentions that](https://dmrelease.blob.core.windows.net/azurestoragejssample/samples/sample-blob.html): "By default, the speedSummary.getCompletePercent() only updates progress when a block is uploaded to server.", but then the examples that follow for getting finer grained updates do so by modifying the block size only, so it looks like the update-per-block-upload is not just a default.

**Comment by XiaoningLiu** [comment]
@absoludity `update-per-block-upload` is the default, but the block size can be customized

similar question about this https://github.com/Azure/azure-storage-node/issues/443

**Comment by XiaoningLiu** [comment]
@janakiramangara Added 'progress' event for SpeedSummary from 2.9.100-preview. Will close this issue.

**Comment by flickz** [comment]
Alright well done!!

**Comment by abhishekbhalani** [comment]
@XiaoningLiu Can we get progress on **StartCopyBlob** 
Upload s3 bucket file url to upload directly using `blobclient.prototype.startCopyBlob()` method.
can we get summary or progress data after calling **startCopyBlob** method..

I am using **azurestorageSDK** javascript version **3.x** .

Thanks.

**Comment by abhishekbhalani** [comment]
@flickz do you have idea about my above question? Want to copy blob from Remote URL with progress.
Also want to know if file size is more than 2 GB which method would be best fit. 
Either Rest API or startcopyblob using javascript with having progress event..

kindly help me.
Thanks.

**Comment by shubhampr07** [comment]
i want to track the progress of upload to blob storage and show in progress bar but can't able to find any solution to get the progress of upload in dot net
