### ISSUE TITLE
BlobService.getBlobToLocalFile doesn't handle writeStream errors

### ISSUE THREAD

**Issue by mheggeseth** [Azure/azure-storage-node#311]
Internally, [`BlobService.getBlobToLocalFile`](http://azure.github.io/azure-storage-node/services_blob_blobservice.js.html#sunlight-1-line-5830) calls `getBlobToStream` with a writeable stream pointing to the given local file, however it does not handle errors emitted by that writeable stream, for example, if the file path isn't a file or the containing directory doesn't exist.

This is a pretty big problem because `EventEmitter` `'error'` events with no listeners will [throw an error and end the Node.js process](https://nodejs.org/api/events.html#events_error_events). You can't even try/catch the `.emit('error')` call as seen in this REPL example:
```
> emitter = new events.EventEmitter()
EventEmitter { ... }
> try { emitter.emit('error', new Error("bye")) } catch (er) { console.log("phew, caught it", er); }
Error: bye
    at repl:1:29
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
false
> 
```

After creating, the writeable stream, [`BlobService._getBlobToLocalFile`](http://azure.github.io/azure-storage-node/services_blob_blobservice.js.html#sunlight-1-line-5830) should immediately establish `'error'` and `'open'` listeners for it.
* The `'error'` handler should invoke the callback provided to `getBlobToLocalFile` with the error emitted
* The `'open'` handler should allow the call to `getBlobToStream` to proceed.

Suggestion:
``` javascript
BlobService.prototype._getBlobToLocalFile = function (container, blob, localFileName, optionsOrCallback, callback) {
  var options;
  azureutil.normalizeArgs(optionsOrCallback, callback, function (o, c) { options = o; callback = c; });
  options.speedSummary = options.speedSummary || new SpeedSummary(blob);

  var writeStream = fs.createWriteStream(localFileName, { 'highWaterMark': BlobConstants.MAX_QUEUED_WRITE_DISK_BUFFER_SIZE });

  writeStream.on('error', function errorOnCreate(error) {
    callback(error);
    writeStream.close();
  });

  var self = this;
  writeStream.on('open', function (fd) {
    // now that we have opened, drop the listener above and rely on StorageServiceClient to add one
    writeStream.removeListener('error', errorOnCreate);

    self.getBlobToStream(container, blob, writeStream, options, function (error, responseBlob, response) {
      if (error) {
        if (azureutil.pathExistsSync(localFileName)) {
          // make sure writeStream is closed / destroyed to avoid locking issues
          if (writeStream.close) {
            writeStream.close();
          }

          // If the download failed from the beginning, remove the file.
          fs.unlink(localFileName, function () {
            callback(error, responseBlob, response);
          });
          return;
        }
      }
      callback(error, responseBlob, response);
    });
  });

  return options.speedSummary;
};
```

Additionally, as mentioned above in a code comment [`StorageServiceClient._performRequest`](http://azure.github.io/azure-storage-node/common_services_storageserviceclient.js.html#sunlight-1-line-440) should add an `'error'` handler to `body.inputStream` just like the one that `body.outputStream` has.

**Comment by XiaoningLiu** [comment]
Hey @mheggeseth Thanks for reporting! BlobService.getBlobToLocalFile and FileService.getFileToLocalFile should also have the same issue.

**Comment by gauravagrwl** [comment]
I am seeing the same error  when using blobService.createWriteStreamToBlockBlob.

Node Module:
"azure-storage": "^2.10.2"

Logs:
events.js:183
      throw er; // Unhandled 'error' event
      ^
StorageError: The specified block list is invalid.
RequestId:e3f6b0a7-001e-004c-2e83-a3fbd5000000
Time:2019-01-03T16:46:26.4649224Z
    at Function.StorageServiceClient._normalizeError (/usr/src/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1205:23)
    at BlobService.StorageServiceClient._processResponse (/usr/src/node_modules/azure-storage/lib/common/services/storageserviceclient.js:751:50)
    at Request.processResponseCallback [as _callback] (/usr/src/node_modules/azure-storage/lib/common/services/storageserviceclient.js:319:37)
    at Request.self.callback (/usr/src/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)

**Comment by XiaoningLiu** [comment]
@gauravagrwl I don't think it's a same error. "The specified block list is invalid" usually happens the blob already has existing uncommitted blocks which have different blockid length. You can try to write to another new blob for a try.

**Comment by gauravagrwl** [comment]
Thank You XiaoningLiu for letting me know.
In my scenario i need to over write the blob if exist.
how can i overwrite the blog without getting this error?

Thanks again for looking into it.
