### ISSUE TITLE
getFileToStream does not call callback when file is an image

### ISSUE THREAD

**Issue by t-gacema** [Azure/azure-storage-node#320]
I cannot seem to get getFileToStream tp get me the stream when the file in an image but it does not throw an error either. It simply does not call the callback.

**Comment by XiaoningLiu** [comment]
Hi @t-gacema , can you give more backgrounds? What's the **image** do you refer to?

**Comment by t-gacema** [comment]
whenever i upload a binary image file (png, jpg) through the api and attempt to download it to a stream it does not  call the callback

**Comment by XiaoningLiu** [comment]
@t-gacema 

Are you using the Node.js library or the JavaScript library for browsers? Do other types of files work properly?

We will appreciate it if you can further provide yoru Node.js version, library version or browser version (if in the browser).

**Comment by t-gacema** [comment]
this is in the nodejs version. I think i found something related to this. For some reason I can get a non binary file or blob into a stream if the stream is of type Transform, allowing me to write and read from it. But if the file or blob is of binary type then the call back GetFileToStream/GetBlobToStream wont be called unless the stream is of type Writable.

**Comment by XiaoningLiu** [comment]
Yes, the GetFileToStream/GetBlobToStream APIs need the stream as Writable type.
