### ISSUE TITLE
Add azure functions ENV variable as acceptable input

### ISSUE THREAD

**Issue by anoff** [Azure/azure-storage-node#323]
Due to the limited capabilities of the output bindings I ended up using the `azure-storage` library in my azure function. However to get a valid connection string I have to pass in the string manually 

`const tableService = azure.createTableService(process.env.AzureWebJobsStorage)`

What is your take on adding `AzureWebJobsStorage` to the list of `ENV` variables that gets parsed automatically? It would allow for a more seamless integration into azure functions. Would PR if there is a chance to be accepted

**Comment by XiaoningLiu** [comment]
Thanks @anoff ! Sorry for the limited capabilities of the output bindings. Can you provide more detailed information about the limited capabilities?

For the connection string environment variable. The library currently takes `AZURE_STORAGE_CONNECTION_STRING` as the default connection string environment variable name. We will discuss the possibility for adding a new one. Will reach you if we have conclusions, PRs are welcome after that.

**Comment by anoff** [comment]
As far as I understood the output bindings only allow (multiple) inserts. However remove/update methods are not possible. At least I couldn't figure out how to.. that's why I ended up with the library

**Comment by vinjiang** [comment]
Sorry to hear that. Anyway, feel free to let us know if we can be of any assistance.
