### ISSUE TITLE
Crashing on insertOrReplace Batch - No Error, just quits out

### ISSUE THREAD

**Issue by securityvoid** [Azure/azure-storage-node#324]
I've got a set of code that runs a query of Azure Table Storage, gets the results back, modifies those results and then does a batch.insertOrReplaceEntity to update the files. This is mysteriously crashing with no errors, or anything when that call is made. All I receive is that process exited with an error code 0. 

As far as I can tell it has something to do with the data since it always crashes in the same place, and then I clear the tables and its all recreated and it crashes in a different place. However, I'm really not sure. 

Here is my code:
```
module.exports.updateItems = function(context, items, isRelease){
    "use strict";
    lib_util.logData(context, 'Starting updateItems', 1);
    var deferred = q.defer();
    var table = (isRelease) ? RELEASE_TABLE : PACKAGES_TABLE;
    _this.checkTableExists().then(function(){
        var tableService = azure.createTableService();
        var batch = new azure.TableBatch();

        for(var x = 0; x < items.length; x++){
           batch.insertOrReplaceEntity(items[x]);
        }

        tableService.executeBatch(PACKAGES_TABLE, batch, function (error, result, response) {
            if(error){
                deferred.reject(error);
            } else {
                lib_util.logData(context, 'updateItems Complete');
                deferred.resolve({result: result, response : response, items: items});
            }
        });

    }, function(error){
        deferred.reject(error);
    });

    return deferred.promise;
};
```

Its crashing in the for loop, literally on the call  batch.insertOrReplaceEntity(items[x]) . I've got roughly 30 records I'm attempting to update and its crashing about on record 4 right now.

This is a copy of that record:

`{"PartitionKey":{"$":"Edm.String","_":"webapp-ethical-hacking_ninjutsu-environment"},"RowKey":{"$":"Edm.String","_":"clean-vm_0.02 _all"},"Timestamp":{"$":"Edm.DateTime","_":"2017-07-02T05:19:18.222Z"},"Architecture":{"_":"all"},"Depends":{"_":" "},"Description":{"_":"Simple tool for cleaning up free space before packing up a VM for a class.  \n\n"},"Filename":{"_":"pool/webapp-ethical-hacking/ninjutsu-environment/clean-vm_0.02_all.deb"},"MD5Sum":{"_":"0ef3e6fb6a335f8b7b0b9e7a2bdda6da"},"Maintainer":{"_":"info@cyberninjas.com"},"Package":{"_":"clean-vm"},"Priority":{"_":"extra"},"Provides":{"_":"clean-vm"},"SHA1":{"_":"f924014623c2f8e1d5ccfa6b77fbaaa675a4163b"},"SHA256":{"_":"2403d6245937ea5a36e6f37636f5e903fd6e4425d1d0b53a826c73c81909c18a"},"Section":{"_":"main"},"Size":{"_":986},"Version":{"_":"0.02 "},"isNew":{"_":false},".metadata":{"etag":"W/\"datetime'2017-07-02T05%3A19%3A18.2228902Z'\""}}`

Other Details:
"azure-storage": "^2.2.0",

node --version 
v6.9.2

npm --version
3.10.8

**Comment by XiaoningLiu** [comment]
@securityvoid Sorry for the late response. I tried following lines of code to re-produce the issue. But it doesn't crash on my side.

azure-storage-node: 2.2.1
node --version: v6.10.2

There maybe some rare conditions for the crashing. Could you share the 1 to 3 records before the record 4 has been inserted? 

```
var fileService = azureStorage.createTableService(STORAGE_ACCOUNT, ACCOUNT_KEY);
var batch = new azureStorage.TableBatch();

var entity = { "PartitionKey": { "$": "Edm.String", "_": "webapp-ethical-hacking_ninjutsu-environment" }, "RowKey": { "$": "Edm.String", "_": "clean-vm_0.02 _all" }, "Timestamp": { "$": "Edm.DateTime", "_": "2017-07-02T05:19:18.222Z" }, "Architecture": { "_": "all" }, "Depends": { "_": " " }, "Description": { "_": "Simple tool for cleaning up free space before packing up a VM for a class. \n\n" }, "Filename": { "_": "pool/webapp-ethical-hacking/ninjutsu-environment/clean-vm_0.02_all.deb" }, "MD5Sum": { "_": "0ef3e6fb6a335f8b7b0b9e7a2bdda6da" }, "Maintainer": { "_": "info@cyberninjas.com" }, "Package": { "_": "clean-vm" }, "Priority": { "_": "extra" }, "Provides": { "_": "clean-vm" }, "SHA1": { "_": "f924014623c2f8e1d5ccfa6b77fbaaa675a4163b" }, "SHA256": { "_": "2403d6245937ea5a36e6f37636f5e903fd6e4425d1d0b53a826c73c81909c18a" }, "Section": { "_": "main" }, "Size": { "_": 986 }, "Version": { "_": "0.02 " }, "isNew": { "_": false }, ".metadata": { "etag": "W/\"datetime'2017-07-02T05%3A19%3A18.2228902Z'\"" } };
batch.insertOrReplaceEntity(entity);
```

**Comment by vinjiang** [comment]
Feel free to let us know if further assistance needed.
