### ISSUE TITLE
Security vulnerability with tunnel-agent <0.6.0

### ISSUE THREAD

**Issue by lostintangent** [Azure/azure-storage-node#326]
I'm not sure whether this module is impacted by it, but there is a [known `Uninitialized Memory Exposure` vulnerability](https://snyk.io/vuln/npm:tunnel-agent:20170305) in `tunnel-agent` < `0.6.0`, which `azure-storage` transitively uses via it's dependency on `request`. 

The mitigation is simply to upgrade `tunnel-agent` to `0.6.0` or newer, which the latest version of `request` already depends on.

**Comment by XiaoningLiu** [comment]
Thanks @lostintangent ! Will validate and update if no issues found.

**Comment by XiaoningLiu** [comment]
PR https://github.com/Azure/azure-storage-node/pull/327 has been taken, thanks!
