### ISSUE TITLE
InvalidHeaderValue (fileService.createFileFromText)

### ISSUE THREAD

**Issue by AidanRRR** [Azure/azure-storage-node#331]
Creating a file does not seem to work with the latest version of node and azure storage node?

<Message>
The value for one of the HTTP headers is not in the correct format. RequestId:91c5747c-001a-010d-0188-f96e9a000000 Time:2017-07-10T14:22:57.0906886Z
</Message>
<HeaderName>x-ms-version</HeaderName>
<HeaderValue/>

**Comment by XiaoningLiu** [comment]
Hey @AidanRRR ,

It works fine on my side with 2.2.1. Can you help share a minimum sample of your code which has the problem? 

Best

**Comment by AidanRRR** [comment]
apikeys.js -->
module.exports = {
    sendgrid: '',
    AZURE_STORAGE_CONNECTION_STRING: 'xxx'
}

cvUploader.js (puts a file in azure, but the content is invalid header) -->
var azure = require('azure-storage');
var apiKeys = require('./apikeys');
var fileService = azure.createFileService(apiKeys.AZURE_STORAGE_CONNECTION_STRING);

module.exports = {
    sendCv: function () {
        fileService.createFileFromText('cvs', '', 'aoijaoija.txt', 'test', function (error, result, response) {
            return response;
            /*
            if (!error) {
                console.log(response);
            } else {
                console.log(error);
            }
            */
        });
    }
}

server.js (this calls the function) -->
app.post('/api/cv', function (req, res) {
    //res.send(cvUploader.sendCv());
});

**Comment by AidanRRR** [comment]
Thank you for having a look, XiaoningLiu.

**Comment by XiaoningLiu** [comment]
@AidanRRR 

I tried following codes in following environments and it worked fine. I think the error is related to the file content you passed to the API `createFileFromText`. I cannot find out the root cause without the file content.
* Node.js 6.11.0
* Azure Storage Node.js Client Library 2.21

BTW, what you want to do is to upload a local file to Azure Storage? If so, I'd like to recommend using APIs like `fileService.createFileFromLocalFile` or `fileService.createFileFromStream`. `createFileFromText` is only designed to upload small size of text data.

```
const azureStorage = require('azure-storage');
const fs = require('fs');

var STORAGE_ACCOUNT = "";
var ACCOUNT_KEY = "";

var fileService = azureStorage.createFileService(STORAGE_ACCOUNT, ACCOUNT_KEY);

fileService.createShareIfNotExists('cvs', function (err) {
    if (!err) {
        fileService.createFileFromText('cvs', '', 'aoijaoija.txt', 'test', function (err, res) {
            if (!err) {
                console.log('createFileFromText successfully!');
                fileService.getFileToText('cvs', '', 'aoijaoija.txt', function (err, res) {
                    if (!err) {
                        console.log(res);
                    }
                });
            } else {
                console.log('createFileFromText failed', err);
            }
        });
    } else {
        console.log('Create share failed.');
    }
});
```

**Comment by vinjiang** [comment]
Feel free to ping us if you need further assistance.

**Comment by AidanRRR** [comment]
This worked, thank you, didn't update a response!
