### ISSUE TITLE
Large File upload issue: BlockCountExceedsLimit

### ISSUE THREAD

**Issue by kirikintha** [Azure/azure-storage-node#335]
Hello,

I am using azure-storage node to attempt to upload large files, with "createBlockBlobFromStream" or "createBlockBlobFromLocalFile" or "createWriteStreamToBlockBlob" and I am receiving the same message in all uploads:

`The uncommitted block count cannot exceed the maximum limit of 100,000 blocks.`

I am uploading a 540MB file from the server, and no matter how I set blockSize, or parallelOperationThreadCount, or using the "createBlockBlobFromLocalFile" I am receiving the same message. 

This happens with all of the above methods, in various conditions - I cannot isolate the problem. I know there is a streaming error reported as well with a reported workaround, but I tried that solution as well and did not find any difference.

Debug Log shows this:

```
2017-07-20T02:09:24.760Z]debug : Operation 4 failed. Error StorageError: The uncommitted block count cannot exceed the maximum limit of 100,000 blocks.
RequestId:8702b1af-0001-00eb-31fd-00469d000000
Time:2017-07-20T02:09:24.3894547Z
[2017-07-20T02:09:24.760Z]debug : Fire user call back for operation 4
[2017-07-20T02:09:24.761Z]debug : Stop uploading data as error happens. Error: { Error
    at Function.StorageServiceClient._normalizeError (/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1181:23)
    at BlobService.StorageServiceClient._processResponse (/node_modules/azure-storage/lib/common/services/storageserviceclient.js:736:50)
    at Request.processResponseCallback [as _callback] (/node_modules/azure-storage/lib/common/services/storageserviceclient.js:317:37)
    at Request.self.callback (/node_modules/azure-storage/node_modules/request/request.js:187:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/node_modules/azure-storage/node_modules/request/request.js:1044:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/node_modules/azure-storage/node_modules/request/request.js:965:12)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  name: 'StorageError',
  message: 'The uncommitted block count cannot exceed the maximum limit of 100,000 blocks.\nRequestId:8702b1af-0001-00eb-31fd-00469d000000\nTime:2017-07-20T02:09:24.3894547Z',
  code: 'BlockCountExceedsLimit',
  statusCode: 409,
  requestId: '8702b1af-0001-00eb-31fd-00469d000000' }
```

The code I am using is in credibly simple, nothing special and is based on the same examples you have provided.

Is there any way to alleviate this error, or is there an alternative to uploading large files with this module? Thank you for your help!

**Comment by kirikintha** [comment]
Giving an update here - all of a sudden, it started working. I did not make a code change, but what I did was empty out the container for the blob storage. So, starting with an empty container seems to have made a difference. I wish I could correlate this into an actual test case, but there seems to have been an issue with the REST callback.

I am wondering if there was some sort of bug in uploading the large file with the storage service itself, or that there was some sort of back pressure in the system, caching - something not easily traceable by this module. 

This is an excerpt of the code I am using, if anyone needs additional information on how to use this with promises.

```
upload: function(sas, container, blob, file, contentType) {
        const self = this;
        return new Promise(function(resolve, reject) {
            if (!sas || !container || !blob || !file) {
                reject(new Error('You must supply a container, blob and file to upload'));
            }
            logger.info('Uploading %s to container %s at blob %s', file, container, blob);
            const client = azure.createBlobServiceWithSas(sas.host, sas.sas)
                .withFilter(new azure.ExponentialRetryPolicyFilter());
            //Log level.
            // client.logger.level = azure.Logger.LogLevels.DEBUG;
            const timeout = parseInt(process.env.FILE_UPLOAD_TIMEOUT || 2000);
            //Options
            const options = {
                contentType: contentType || null,
                timeoutIntervalInMs: timeout
            };
            self.speedSummary = client.createBlockBlobFromLocalFile(container, blob, file, options, function(error, result, response) {
                if (error) {
                    reject(error);
                } else {
                    logger.info('Upload Complete %s to container %s at blob %s', file, container, blob);
                    resolve({
                        result: result,
                        response: response
                    });
                }
            });
        });
    },
```

**Comment by XiaoningLiu** [comment]
Hi @kirikintha

 A block blob can include a maximum of 50,000 blocks. Uncommitted blocks should be committed to fulfill the content or data of the blob.  A blob can have a maximum of 100,000 uncommitted blocks at any given time. If these maximums are exceeded, the service returns status code 409 (RequestEntityTooLargeBlockCountExceedsLimit).

Any uncommitted blocks will also be garbage collected if there are no successful calls to Put Block or Put Block List on the same blob within **a week** following the last successful Put Block operation

You may perform many unsuccessful uploadings, which leave huge number of uncommitted blocks for that block blob.

To help solve your problem:
1. Change a container
2. User another blob name
3. Call `BlobService.createBlockBlobFromText(...)` to overwrite the blob which should force GC the uncommitted blocks. This API will try to directly create a block blob instead of creating uncommitted blobs.

Reference: https://docs.microsoft.com/en-us/rest/api/storageservices/put-block

**Comment by kirikintha** [comment]
Hi @XiaoningLiu - Thank for the information! 

I will add in some GC for handling failures when uploading. I think that is a fantastic idea, also I added in a timestamp to my blob names, which seems to also have alleviated the problem. I can also confirm that overwriting the same blob name over and over again was the culprit of my issue. 

Really appreciate the advice, thank you again!
