### ISSUE TITLE
High rate of ETIMEDOUT errors for queue operations

### ISSUE THREAD

**Issue by irakliy81** [Azure/azure-storage-node#337]
I am experiencing a high rate of ETIMEDOUT when making requests to Azure Queues. A bit of context:

I have about a dozen queues which are polled periodically using `getMessage()` method. Each queue is polled roughly once per second - so, total number of requests is about 40K per hour. Sometimes, the request would result in ETIMEDOUT errors. Up until about 24 hours ago, I would get on average 2 - 3 ETIMEDOUT per hour. But starting about 24 hours ago, the rate of such errors has increased 100x - so, now I'm getting about 350 ETIMEDOUT errors per hour.

I'm pretty sure this library is not at fault here - as nothing in the codebase has changed recently. So, it is most likely caused by the some changes to the storage service. But - I'm wondering if there is anything I can do on the library side to address these errors. Specifically:

1. Is there a way to specify retry strategy? It is not as much of an issue for `getMessage()` - but for `createMessage()` or especially `deleteMessage()` - this would be a very desirable functionality
2. Is it possible to reduce the timeout interval? Right now ETIMEDOUT errors come after roughly 20 seconds. Ideally, I'd want to set it to a much lower value (e.g. 2 - 3 seconds).

One other piece of info - even though ETIMEDOUT errors happen on the client, the server doesn't seem to see them. Specifically, ServerTimeoutError metric shows 0 errors in the last 24 hours, while I've actually gotten 7K+ ETIMEDOUT errors on the client side.

Any help/advice is greatly appreciated.

**Comment by XiaoningLiu** [comment]
Hi @irakliy81 

I can help to view the server side log if you provide your storage account name, timestamp and the failed request id returned by server.

There are 2 defaults retry strategies can be applied on queueService object. 
* [ExponentialRetryPolicyFilter](http://azure.github.io/azure-storage-node/ExponentialRetryPolicyFilter.html)
* [LinearRetryPolicyFilter](http://azure.github.io/azure-storage-node/LinearRetryPolicyFilter.html)
```
var AzureStorage = require('azure-storage');
var queueService = AzureStorage.createQueueService().withFilter(new AzureStorage.ExponentialRetryPolicyFilter())
```

Yes, for most library APIs there are options about the server side or client timeout settings. 
* [clientRequestTimeoutInMs](http://azure.github.io/azure-storage-node/QueueService.html#createMessage__anchor)

BTW, it's strange that server side cannot view the ETIMEOUT. Does your client version is 2.2.1 or 2.2.0?

**Comment by irakliy81** [comment]
Hi @XiaoningLiu - thanks for the help!

Originally, I was using 2.1.x version - but upgrading to 2.2.1 didn't seem to change anything. What I did was create a new storage account and moved all my queues to it - and once I started using the new storage account the error rate went back to "normal" (i.e. ~100 errors per day).

The storage account name is `credostore`, and the timeframe is between 08/02 after about 12:30am PST and 08/04 until about 8pm PST. After this time, I migrated my queues to a different storage account. I can't really provide a failed request ID - because there was no response from the server (the request timed out).

Thanks for pointing to the retry strategies. I'll make sure my code uses one of them. Might be a good idea to mention them in the README file - as that's where I was looking for them. Quick question: be default, neither of this policies is used - correct?

**Comment by jiacfan** [comment]
Hi, @irakliy81 

We have released Azure storage node.js client library version 2.5.0 which contains document and sample  optimization for retry policy.
Appreciate any further suggestions for Azure storage node.js client library.

Thanks,
Jiachen
