### ISSUE TITLE
Error: connect ETIMEDOUT 40.68.176.24:443

### ISSUE THREAD

**Issue by Slashmsu** [Azure/azure-storage-node#343]
Hi,
(nodejs)
In one of my tasks I need to download 1 blob from every 200 containers. If I will download every blob step by step it will take a lot of time. I decided to download blobs parallel. So I'm trying to do:

```
let testFunctions = [];

containers.array.forEach( container => {
  testFunctions.push(
        (callback) => {
            that.blobService.getBlobToText(container, 'container/' + date, (error: any, blob: any) => {
                if (blob!== null) {
                    callback(null, blob);
                } else {
                    callback(error, null);
                }
            });
        }
    )
});
    
async.parallel(testFunctions, async (error, blobs) => {
          //Todo
});
```

But after some requests I have got this error:

```
{ Error: connect ETIMEDOUT 1.2.3.4:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '1.2.3.4',
  port: 443 } ,
```
Can you help me to solve this problem or do you know another way how can I download fast blobs frome more than 200 containers?

P.s. I'm using **azure-storage V 2.3.0**

**Comment by jiacfan** [comment]
Hi, @Slashmsu 

The ETIMEOUT error is thrown from TCP level, indicating the network is too busy, and TCP cannot establish connection in time. And in this case downloading data with 200 parallel would be too much for your system and network environment. 

Candidates solution:
a. The parallel - "downloading 200 blobs from different containers at same times" might be too much. Please try to break the parallel into small parallels, for example 200 => 20*10 or 50*4 which fits the network environment, and fulfill the parallels step by step. You can try to monitor the network with some tools, for example, in Windows set performance counters: TCP's "Connection Failures" and "Connection Reset", or catch packages using tools like Wireshark to help the adjustment.

b. Optimize the TCP settings. The default TCP connection timeout duration differs from OS to OS, e.g. 21 seconds in Windows 7 by default, and the ways to optimize TCP settings differs from OS as well. Please try to optimize the network settings if possible.

Best Regards,
Jiachen
