### ISSUE TITLE
commitBlocks accepts an array for blockList argument

### ISSUE THREAD

**Issue by electrachong** [Azure/azure-storage-node#344]
Since the documentation for [commitBlocks](http://azure.github.io/azure-storage-node/BlobService.html#commitBlocks__anchor) does not detail the structure of the `blockList` object argument or give any examples, I decided to try an array of the uncommitted block ids I wanted to commit first.

The client library did not throw an error, and I got a successful response back with the same list I provided in the result:
```
BlobResult {
  container: 'testcontainer',
  name: 'testkey',
  list:
   [ 'f9f5ab8866844e9d9b1bf3ffc8c17229|partNumber00001|subPart00|%%%%%',
     'f9f5ab8866844e9d9b1bf3ffc8c17229|partNumber00002|subPart00|%%%%%',
     'f9f5ab8866844e9d9b1bf3ffc8c17229|partNumber00003|subPart00|%%%%%',
     'f9f5ab8866844e9d9b1bf3ffc8c17229|partNumber00004|subPart00|%%%%%',
     'f9f5ab8866844e9d9b1bf3ffc8c17229|partNumber00005|subPart00|%%%%%' ],
  lastModified: 'Thu, 17 Aug 2017 17:40:00 GMT',
  etag: '"0x8D4E596FC11585F"',
  requestId: 'fe733f3c-0001-008a-097f-1778a2000000',
  contentSettings: { contentMD5: 'PFfcO0tyGmNOVhXHeQ1xwA==' } }
```

However, listing the blocks afterwards showed there were no committed or uncommitted blocks in the block blob after the commit and the block blob itself had a content-length of zero when I tried to get the properties or download the blob itself.

```
Azure result listing blocks after commit {}
Azure response listing blocks after commit { isSuccessful: true,
  statusCode: 200,
  body: { BlockList: { CommittedBlocks: '', UncommittedBlocks: '' } },
  headers:
   { 'transfer-encoding': 'chunked',
     'content-type': 'application/xml',
     'last-modified': 'Thu, 17 Aug 2017 18:44:23 GMT',
     etag: '"0x8D4E59FFA7BF7F5"',
     server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
     'x-ms-request-id': 'b6b37c61-0001-004e-7288-170d9b000000',
     'x-ms-version': '2016-05-31',
     'x-ms-blob-content-length': '0',
     date: 'Thu, 17 Aug 2017 18:44:23 GMT',
     connection: 'close' },
  md5: undefined }
```

I was able to eventually find an example of the expected structure of the blockList argument by digging in the client library source code. However, I would have expected A) a validation error if the expected type of the argument is not an array, or B) if that is not feasible, for the list in the success response to show the effect of the request in the proper format:
```
  list:
 {
     LatestBlocks: [],
     UncommittedBlocks: []
     CommittedBlocks: [],
 },
```
or simply:
```
list: {},
```

Furthermore, it seemed like providing the wrong argument type had a side effect on the blocks available for the blob by removing the uncommitted blocks. The way this call operates doesn't seem to parallel my understanding of the [PUT Block List API](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list) very well, so I advise adding an example in the documentation.

**Comment by electrachong** [comment]
Note that the type of value provided for the `LatestBlocks`, `UncommittedBlocks`, and `CommittedBlocks` are not validated either. You can provide a string or some other value instead of an array and the client library will throw an uncaught error about `blockListJs.LatestBlocks.forEach` not being a function (the value is not an iterable). I'm not sure if the lack of validation at this level is intentional or an oversight.

**Comment by jiacfan** [comment]
Hi, @electrachong 

Thanks for the suggestions, that's really valuable to us! We'll optimize the commitBlocks method and  documentation to provide better using experience.

For "removing the uncommitted blocks", currently, the behavior of commitBlocks is to include empty body if cannot find valid blockList, and this would cause removing uncomittedBlocks as the [https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list](url) mentioned: 

> Given that this block is not included in the next call to Put Block List, the block will effectively be removed from the blob.

Will give update to this thread again when the optimization is done.

Thanks,
Jiachen

**Comment by electrachong** [comment]
Hi @jiacfan ,
Glad to hear your response!
For the "removing the uncommitted blocks", thank you for the clarification. I began to realize the point about removing the uncommitted blocks during a commit when testing the api. However, just a suggestion, it may help to be more explicit in the Put Block List documentation. When I read the same document, I assumed any blocks that were not committed would stay uncommitted, and interpreted "the block will effectively be removed from the blob" to mean just that block would be removed from the committed blocks.

A statement somewhere in the overview at the top to the effect of "Any uncommitted blocks that are not committed will be deleted when a block list is put" would help make this more explicit.

I am still unsure how well the client library method parallels the rest api method even with this knowledge. From my understanding, when you use Put Block List, you can order already-committed blocks with uncommitted blocks as desired in the xml, like in the following:
```
<BlockList>  
  <Uncommitted>ANAAAA==</Uncommitted>  
  <Committed>AQAAAA==</Committed>  
  <Uncommitted>AZAAAA==</Uncommitted>  
</BlockList>  
```

But the client method expects an array for each category, making it impossible to mix blocks from either category. Does this mean I can only commit uncommitted blocks next to each other followed by committed blocks, and latest? This is what I mean when I'm unsure of how to use `commitBlocks` properly. :P

An example of a block list structure that I feel might better follow my understanding of the API method:
```
 list:
  [
    { type: 'Uncommitted', id: 'ANAAAA==' },
    { type: 'Committed', id: 'AQAAAA==' },
    { type: 'Uncommitted', id: 'AZAAAA==' },
  ]
```

**Comment by jiacfan** [comment]
Hi, @electrachong 

Nice to have your feedbacks again!

1. For the uncommitted blocks handling, some introduction in [PutBlock](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block) illustrates the control flow much clearly. We'll add some samples in Node SDK to help the API using!

> After Put Block List is called, all uncommitted blocks specified in the block list are committed as part of the new blob. Any uncommitted blocks that were not specified in the block list for the blob will be garbage collected and removed from the Blob service. Any uncommitted blocks will also be garbage collected if there are no successful calls to Put Block or Put Block List on the same blob within a week following the last successful Put Block operation. If Put Blob is called on the blob, any uncommitted blocks will be garbage collected. 
==

2. When committing both Uncommitted and Committed blocks, currently `commitBlocks` supports the common scenario that leverages `LatestBlocks`, as [PutBlockList](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list):

> Specify the block ID within the Latest element to indicate that the Blob service should first search the uncommitted block list. If the block is found in the uncommitted list, that version of the block is the latest and should be written to the blob. If the block is not found in the uncommitted list, then the service should search the committed block list for the named block and write that block to the blob if it is found. 

For the interesting scenario you mentioned, if it's popular and get votes, we'll plan to add it :) 

Again thanks for the feedbacks!

Best Wishes,
Jiachen

**Comment by electrachong** [comment]
Hi Jiachen,

1. Yes, I missed this important piece of the documentation when reviewing the Put Block api. Thanks for directing me to where the information is outlined clearly.
2. It's true the `LatestBlocks` array should help cover the most common scenarios for committing blocks where you may want to commit both uncommitted and committed blocks. But the examples you plan to add will definitely help, since the approach for using `commitBlocks` differs from the REST api usage.

Thanks for considering the feedback, looking forward to see the improvements.

Best,
Electra

**Comment by jiacfan** [comment]
Hi, @electrachong 

We have released Azure storage node.js client library version 2.5.0 which contains document and example optimization for `commitBlocks` API.
Considering backward compatibility, validation for parameter cannot be changed too much in this minor release. 
Hope you like it, and appreciate any further suggestions for Azure storage node.js client library.

Thanks,
Jiachen

**Comment by electrachong** [comment]
Thank you, cool that the suggestion was incorporated into the latest minor release. :)

I do appreciate the added examples and better documentation of the expected object structure.
Another suggestion is to validate for unexpected parameters in the object. For instance, my co-worker had a typo and wrote:
```
{ UncommitedBlocks: [ ... ] }
```
when specifying the blocks to commit, and of course that had the unfortunate side effect of removing all the blocks.

You could iterate through the keys of the `blockList` object and make sure they all match one of the expected parameters `['UncommittedBlocks', 'CommittedBlocks', 'Latest']` and return an error early instead of sending the request to the server.

Thanks again for taking my comment into consideration!
Best,
Electra

**Comment by jiacfan** [comment]
Hi, @electrachong 

We have discussed such implementation during this minor release change, and considering tightening up such parameters validation could be a **breaking change**, as existing users could take use of `commitBlocks` to set a blob to empty with a casual input, and might have relied on such logic to fulfill some goals, and thus we didn't involve it in this minor release, and make it a candidate for next major release.

At the same time, we are planing API optimizations for next major release, welcome any other suggestions! :)

Thanks,
Jiachen
