### ISSUE TITLE
Support for nativescript

### ISSUE THREAD

**Issue by plaramee1** [Azure/azure-storage-node#345]
well title say it all !

**Comment by jiacfan** [comment]
Hi, @x3r10n 

Thanks for the suggestion! Would you please describe more about your user scenario?

Thanks,
Jiachen

**Comment by x3r10n** [comment]
I am developing site survey application (iOS and Android) with [Nativescript](https://www.nativescript.org/) that will need to store pictures of defective equipments / misplaced machinery. Then other peoples will access these files from a web site I am making with mvc .NET (excellent library you got there to read and write files to azure storage BTW) Then some other peoples need to access the same files from a network shared (SMB 3.0).

So to make it short I want to use [Azure File Storage](https://azure.microsoft.com/en-us/services/storage/files/) and right now the only way to do it is with the REST api that is not super easy to use :( I would love to see a storage SDK support for Nativescript !

Thanks !

**Comment by jiacfan** [comment]
Hi, @x3r10n 

Thanks for providing this requirement, we'll evaluate it, and will give feedback to this thread if we plan to achieve it. 
At same time, this thread will be opened to collect further requirement about native script support.
We welcome every contributor who wish to join us on lighting up such features as well~

Thanks!

**Comment by jiacfan** [comment]
Close as we're moving to [v12 SDK](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage)
