### ISSUE TITLE
deleteBlob vs deleteBlobIfExists different results if blob has uncommited blocks 

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-storage-node#350]
I have run into an issue where using `deleteBlob` and `deleteBlobIfExists` are producing different results.

When using `deleteBlob`, the following code can successfully remove the blob and blocks, and the list blocks function call will return a "specified blob does not exist" error. 
```
async.waterfall([
    next => azureClient.createBlockFromText(
    'testblock', bucketName, objectName, 'content',
    {}, (err, res) => {
        console.log('Putting a block to blob err', err);
        console.log('Putting a block to blob res', res);
        return next();
    }),
    next => azureClient.deleteBlob(bucketName,
    objectName, {}, (err, res) => {
        console.log('Deleting blob err', err);
        console.log('Deleting blob res', res);
        return next();
    }),
    next => azureClient.listBlocks(bucketName, objectName, 'uncommitted', {}, (err, result) => {
        console.log('Listing blocks err', err);
        console.log('Listing blocks res', result);
        return next();
    }),
], done);
```

However, if I try to use `deleteBlobIfExists` in place of `deleteBlob`, the deletion function actually returns a false result and a 404 response, and the list blocks call can successfully list the block created at the beginning of the async waterfall. 

Output when  using `deleteBlob`:
```Putting a block to blob err null
Putting a block to blob res { isSuccessful: true,
  statusCode: 201,
  body: '',
  headers: 
   { 'transfer-encoding': 'chunked',
     'content-md5': 'mgNkuembtIDdJeHwKEyFVQ==',
     server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
     'x-ms-request-id': '6f4bbb33-0001-005d-1b26-1d2997000000',
     'x-ms-version': '2017-04-17',
     'x-ms-request-server-encrypted': 'true',
     date: 'Thu, 24 Aug 2017 22:13:36 GMT',
     connection: 'close' },
  md5: undefined,
  requestServerEncrypted: true }
Deleting blob err null
Deleting blob res { isSuccessful: true,
  statusCode: 202,
  body: '',
  headers: 
   { 'transfer-encoding': 'chunked',
     server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
     'x-ms-request-id': '90ed1138-0001-007a-7126-1d3e53000000',
     'x-ms-version': '2017-04-17',
     date: 'Thu, 24 Aug 2017 22:13:37 GMT',
     connection: 'close' },
  md5: undefined }
Listing blocks err { StorageError: The specified blob does not exist.
 <rest of the error trace> }
Listing blocks res null
```

Output when using `deleteBlobIfExists`:
```Putting a block to blob err null
Putting a block to blob res { isSuccessful: true,
  statusCode: 201,
  body: '',
  headers: 
   { 'transfer-encoding': 'chunked',
     'content-md5': 'mgNkuembtIDdJeHwKEyFVQ==',
     server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
     'x-ms-request-id': '19687e74-0001-0041-2226-1d7bf7000000',
     'x-ms-version': '2017-04-17',
     'x-ms-request-server-encrypted': 'true',
     date: 'Thu, 24 Aug 2017 22:14:22 GMT',
     connection: 'close' },
  md5: undefined,
  requestServerEncrypted: true }
Deleting blob err null
Deleting blob res false
Listing blocks err null
Listing blocks res { UncommittedBlocks: [ { Name: 'testblock', Size: '7' } ] }
```

Is this the intended behavior? If so, could the documentation be modified to explicitly state that uncommitted blobs will not be deleted using the `deleteBlobIfExists` method?

**Comment by JianqinWang** [comment]
Thanks Amar!

**Comment by XiaoningLiu** [comment]
Hi @amarzavery 

It should be by design. The only difference between ```deleteBlobIfExists``` with ```deleteBlob``` is that, ```deleteBlobIfExists``` will try to get whether the blockblob exists, then decides whether executing ```deleteBlob``` or not.

If the blockblob exists,  ```deleteBlobIfExists``` will try to execute ```deleteBlob``` to perform the deletion. Otherwise, if the blockblob doesn't exist (such as we didn't commit the uncommitted blocks), ```deleteBlob``` will never be executed.

**Comment by JianqinWang** [comment]
I'm not fully sure I understand your answer, but right now `deleteBlobIfExists` isn't deleting the blob even though it does exist when there are uncommitted blocks uploaded to it. Are the uncommitted blocks supposed to block the deletion in the `deleteBlobIfExists` function call? Or should it be displaying the same behavior as `deleteBlob`, which deletes the blob and its uncommited blocks?

**Comment by XiaoningLiu** [comment]
@JianqinWang 

Even though there are uncommitted blocks uploaded to a blockblob, but the blockblob **doesn't exist** until someone **commit** these blocks.

**deleteBlobIfExists** will not delete un-existed block blobs.

**Comment by JianqinWang** [comment]
@XiaoningLiu 

Is this behaviour/definition of whether a blockblob 'exists' described in the documentation? If so, can you please link me?
