### ISSUE TITLE
Content Type not being set for createBlockBlobFromFile or createBlockBlobFromLocalFile in 2.0.0-preview

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-storage-node#351]
> Original issue filed by @wjohnsto over here: https://github.com/Azure/azure-sdk-for-node/issues/2244. @hasonmsft  asked @XiaoningLiu to take a look but there is no response from the storage team. Hence filing this issue over here.

When using the SDK to upload a file to blob storage I'm trying to set contentType as follows:

```
storage.createBlockBlobFromFile(container, name, filePath, {
    contentType: 'application/pdf',
    cacheControl: 'no-cache'
}, (error: Error, result: azure.BlobResult, response: azure.WebResponse) => {
    if (isObject(error)) {
        reject(error);
        return;
    }

    resolve(name);
});
```

This used to work in previous versions of the SDK, but it seems that since we updated to 2.0.0-preview it has since stopped working, so now all our blobs are getting `application/octet-stream` as the content type.

Is there some new way to pass in content type, or is there some configuration property I have to set on the blob container?

**Comment by XiaoningLiu** [comment]
Thanks @amarzavery 2.0.0-preview is the version of latest azure-sdk-for-node right?

The API `createBlockBlobFromFile` may have changed because azure-sdk-for-node@2.0.0-preview updated and added the reference to azure-storage@1.3.0. @jiacfan will have a more detailed look.

**Comment by wjohnsto** [comment]
It looks like I need to be using the following options:

```
{
    contentSettings: {
        contentType: 'application/pdf',
        cacheControl: 'no-cache'
    }
}
```

**Comment by jiacfan** [comment]
Hi, @amarzavery 

Firstly, thanks for pointing out this issue!

For azure storage SDK for node (version 1.3.0), The behavior of `createBlockBlobFromFile` when the blob size is < 32 MB is: It will both set content-type as 'application/octet-stream' and x-ms-blob-content-type as user provided value in contentType, i.e. 'application/pdf' in this issue. And azure storage service's behavior: 

> If the client sets both the standard HTTP header and the corresponding property header on the same request, the PUT request uses the value provided for the standard HTTP header, but the value specified for the custom property header is persisted with the blob and returned by subsequent GET requests. 
 
I have tried the issue code with azure storage SDK for node (version 1.3.0 which is currently used in 2.0.0-preview), the content-type persisted with blob would be set to 'application/pdf' and can be get correctly with `getBlobProperties`:

`blobService.createBlockBlobFromLocalFile(containerName, blobName, filePath, {
    contentType: 'application/pdf',
    cacheControl: 'no-cache'
}, function(error, result, response) {
    assert.equal(error, null);
    blobService.getBlobProperties(containerName, blobName, function(error, blob) {
        assert.equal(error, null);
    });
});`

The response get from fiddler for getBlobProperties:
HTTP/1.1 200 OK
Content-Length: 1159267
**Content-Type: application/pdf**
Content-MD5: e/cE4WTKdaMzMqMIny2Zmg==
Last-Modified: Mon, 28 Aug 2017 03:21:27 GMT
Accept-Ranges: bytes
ETag: "0x8D4EDC3DECCB333"
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: c805a908-0001-002f-70ac-1f6c38000000
x-ms-version: 2015-04-05
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
Access-Control-Expose-Headers: x-ms-request-id,Server,x-ms-version,Content-Type,Last-Modified,ETag,Content-MD5,x-ms-lease-status,x-ms-lease-state,x-ms-blob-type,Accept-Ranges
Access-Control-Allow-Origin: *
Date: Mon, 28 Aug 2017 03:21:47 GMT
Connection: close

We'll contact the user, and get it clear in which approach they would get error content-type, and what's their wish.

Thanks,
Jiachen

**Comment by wjohnsto** [comment]
@jiacfan good to know that `createBlockBlobFromLocalFile` is the proper method to call,not `createBlockBlobFromFile`, and to affirm the api for `contentSettings`. I have made adjustments in my code and it is working now.

Thanks! 👍

**Comment by RupamShaw** [comment]
calling createInputAsset and uploading file size 54 mb
````
async function createInputAsset(
  resourceGroup,
  accountName,
  assetName,
  fileToUpload // inputfile ./myMedia/hls_360p/5ec49b911b2011003d2cff50-1/2020-05-28-19-56.mp4 
) {
  console.log("creating input Asset...")
  let asset = await azureMediaServicesClient.assets.createOrUpdate(
    resourceGroup,
    accountName,
    assetName,
    {}
  )
  console.log("createInputAsset asset", asset)
  try {
    let date = new Date()
    date.setHours(date.getHours() + 1)
    let sasInput = {
      permissions: "ReadWrite",
      expiryTime: date,
    }
    let response = await azureMediaServicesClient.assets.listContainerSas(
      resourceGroup,
      accountName,
      assetName,
      sasInput
    )
    let uploadSasUrl = response.assetContainerSasUrls[0] || null
    let fileName = path.basename(fileToUpload)
    let sasUri = url.parse(uploadSasUrl)
    let sharedBlobService = azureStorage.createBlobServiceWithSas(
      sasUri.host,
      sasUri.search
    )
    let containerName = sasUri.pathname.replace(/^\/+/g, "")
    let randomInt = Math.round(Math.random() * 100)
    blobName = fileName + randomInt
    console.log("uploading mp4 to storage blob...")
````

`````
    function createBlobPromise() {
      return new Promise(function (resolve, reject) {
        console.log("input asset name ", assetName, " storagelink name", containerName )
        sharedBlobService.createBlockBlobFromLocalFile(
          containerName,
          blobName,
          fileToUpload,
          async (error, result, response)=> {
            console.log("error",error)
            console.log("response", response)
            console.log("result",result)
            if (error) {
              console.log("before rejecting first start below in deleting input asset ", assetName)
              try {
                await azureMediaServicesClient.assets.deleteMethod(
                  resourceGroup,
                  accountName,
                  assetName
                )
              } catch (err) {
                console.log("error in deleting input asset",assetName)
                throw err
              }
              reject(error);
              // TODO: for code:"ESOCKETTIMEDOUT" connect:false  message:"ESOCKETTIMEDOUT"   need to upload again 
            }
            if (response.statusCode === 201) {
              console.log(`****** ${result.name} file uploaded on Azure Storage ${assetName}` )
              resolve(result.name)
            } else {
              console.log("Status code not 201 it means in storagelink file not uploaded.")
              console.log("not 201 , before rejecting first start below in deleting input asset ", assetName) // if dont delete then multiple mp4 stores in storagelink
              try {
                await azureMediaServicesClient.assets.deleteMethod(
                  resourceGroup,
                  accountName,
                  assetName
                )
              } catch (err) {
                console.log("error in deleting input asset",assetName)
                throw err
              }
              reject(error)
            }
          }
        )
      })
    }
    const name = await createBlobPromise()
    if (name && name !== null && name !== '') {
      console.log("container mp4 name ", name)
    } else {
      throw new Error(`Input asset not created in container ${assetName}`)
    }
  } catch (err) {
    console.log("error in function createInputAsset", err)
    throw err
  }
  console.log("createInputAsset  asset ", asset)
  return asset
}
````

```
package.json
{
  "azure-arm-mediaservices": "^6.0.0",
  "azure-storage": "^2.10.3",
}

````

its   returning response.statusCode is 201)
              console.log(`****** ${result.name} file uploaded on Azure Storage ${assetName}` )
              resolve(result.name)
            } 
* ${result.name}  is undefined
````
 and result only returns {committedBlocks:Array[13] }
````
If upload filesize 20 mb all works fine.

please let me know how to procced.
