### ISSUE TITLE
listContainersSegmented & listBlobsSegmented typings broken

### ISSUE THREAD

**Issue by evanlouie** [Azure/azure-storage-node#352]
Currently the typescript definitions for `listContainersSegmented` and `listBlobsSegmented` adopt the signature of `(... currentToken: common.ContinuationToken, ...): void;`

During first op, currentToken is required to be `null | undefined` but the current type definitions do now allow it.

**Comment by XiaoningLiu** [comment]
Hi @evanlouie 

Thanks for your contribution! 

The change may break Typescript@1.x versions. We planned to take this in next major release and upgrade the Typescript definition file.

**Comment by sweetnavelorange** [comment]
I think this change should be made to other method signatures as well - I ran into it in TableService#queryEntities. I count 20 instances of the comment text "Please use 'null' or 'undefined'" in azure-storage.d.ts, all referring to continuation tokens, none of which can be null or undefined in the method signature.
