### ISSUE TITLE
how to retrieve the addition of two columns and apply a filtering condition?

### ISSUE THREAD

**Issue by aymanhendawy** [Azure/azure-storage-node#359]
Sorry for being newbie for NodeJs and table query, my question's,
How I could create a query which selects the sum/addition of two coloumns 'start' and 'period' , if the addition is greater than a threshold it will take the whole raw, my tries which didn't work is something like this,

var query = new azure.TableQuery();
    total = query.select(['start']) + query.select(['period']);
    query.where('total > ?' , 50000);

or may be something like this,
var query = new azure.TableQuery()
   .where('start + period gt 50000');

but it throws error of '+'.

Thanks

**Comment by jiacfan** [comment]
Hi, @aymanhendawy 

I'm sorry to say that such aggregation query operators like 'SUM' are not yet supported in Azure storage node.js client library.

Walk-arounds might be:
1. Add a column in table to save the sum of 'start' and 'period', perhaps naming 'end'. And directly query the results with:
```
var tableQuery = new TableQuery().where(TableQuery.int64Filter('end', TableUtilities.QueryComparisons.GREATER_THAN, '50000'));
tableService.queryEntities(tableName, tableQuery, null, function (error, result) {
  //...
});
```

2. Query all rows segmented and filter in memory.

3. Query with select operator, get 'PartitionKey', 'RowKey', 'start', 'period', and find out wished 'PartitionKey' and 'RowKey' in memory, compose the query string programmatically and download wished rows.

Wish these can help you to mitigate the issue. 

Thanks,
Jiachen
