### ISSUE TITLE
Saving blob metadata forces keys to lowercase

### ISSUE THREAD

**Issue by kaa** [Azure/azure-storage-node#36]
Hi,

it seems that the nodejs libraries force lowercase metadata keys when storing metadata. According to http://msdn.microsoft.com/en-us/library/azure/hh225342.aspx metadata keys must conform to C# identifiers which are case sensitive, and the dotnet API correctly store metadata keys with their case preserved.

The offending line seems to be at [/lib/common/http/webresource.js:266](https://github.com/Azure/azure-storage-node/blob/master/lib/common/http/webresource.js#L266) 

Of course some incompatibility seems to be built in since metadata is set through headers and the HTTP specs say,

> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.
>
> RFC 2616 - "Hypertext Transfer Protocol -- HTTP/1.1", paragraph 4.2, "Message Headers":

Is this something we should expect to change or something to live with?

**Comment by yaxia** [comment]
We will fix this issue in an upcoming release of our module in such a way that we will keep the metadata key as it is when setting the metadata(i.e change the offending line). However, please be noted that the metadata keys retrieved from the service will be converted into lowercase by the http component of Node.js. Please refer to https://github.com/joyent/node/issues/1954 for more information. We also suggest that any application should not rely on the case information in the metadata key. Thanks.

**Comment by kaa** [comment]
Thanks for the update. I guess I was mostly tripped by the fact that the nodejs and dotnet libraries were functioning differently. 

Now that I look, the REST documentation actually mentions that metadata is really http-headers and inherit all the restrictions and semantics that go with that, I don't know if i just missed it last time or if that was clarified after I checked.

**Comment by ccurrens** [comment]
@yaxia Node 0.12.0 and io.js 1.1.0 (possibly earlier) expose the original-cased [`rawHeaders`](http://nodejs.org/api/http.html#http_message_rawheaders) on the incoming http message. If that was used, the library could preserve case both ways.

**Comment by slepox** [comment]
@kaa , this issue is fixed in latest release 0.4.3 (for node 0.10):
- Fixed an issue that setting metadata keys are converted into lowercase. The metadata keys retrieved from the service will however still be converted into lowercase by the http component of Node.js.(joyent/node#1954)
