### ISSUE TITLE
Unable to create azure.createQueueService() in Azure Function App

### ISSUE THREAD

**Issue by U2AIT** [Azure/azure-storage-node#363]
I want to go through the queue data in Azure storage in a HTTP trigger function App.
I add the "äzure-storage" Node.js package and using following code:
var azure = require('azure-storage');
But either " var queueSvc = azure.createQueueService();" or " var queueSvc = azure.createQueueService(<Storage connection string>);" is failure when execute the function. I got below exception

"reason": "PassThrough",
  "exception": {
    "ClassName": "System.Threading.Tasks.TaskCanceledException",
    "Message": "A task was canceled.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at AzureFunctions.Code.PassThroughRequestManager.<HandleRequest>d__2.MoveNext()",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nThrowForNonSuccess\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Runtime.CompilerServices.TaskAwaiter\nVoid ThrowForNonSuccess(System.Threading.Tasks.Task)",
    "HResult": -2146233029,
    "Source": "mscorlib",
    "WatsonBuckets": null
  }
}

Please advise

**Comment by XiaoningLiu** [comment]
Hi

It's strange that the exception is not a Node.js exception, seems a Function APP runtime exception. 

For other storage services, will the exception happen? Such as azure.createBlobService()

Best

**Comment by U2AIT** [comment]
No, the code "azure.createBlobService()" works fine even in the Bot service Node.js code 

Linda Liu

**Comment by XiaoningLiu** [comment]
Any Node.js runtime exception?

**Comment by vinjiang** [comment]
Feel free to let us know if we can be of any further assistance.
