### ISSUE TITLE
Missing Authorization header on client library

### ISSUE THREAD

**Issue by grbspltt** [Azure/azure-storage-node#364]
Similar issue as #330, #298 

Using Azure Storage JavaScript Client Library 0.2.5-preview.11

CORS configured on the blob container, the upload request from the client library does not appear to properly set the Authorization header on all requests, it will intermittently fail with: 

> 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
> x-ms-request-id:4e589d06-001e-00e7-23b6-42f405000000

URL Params:
> comp:block
> blockid:ZTM4ZTFlMGYtMDAwMDAw
> st:2017-10-11T17:24:43Z
> se:2017-10-11T18:24:43Z
> sp:rwcd
> sv:2016-05-31
> sr:c
> sig:apY9ZLf5wXQvnJmLl5fzv/ 0Xci1uYJuft/h6Ku mTY=
> api-version:2017-04-17

The only way I have been able to work around this is to refresh the page to get a new SAS and try the upload again.  Any help with this would be greatly appreciated.

**Comment by XiaoningLiu** [comment]
Hi @grbspltt 

We don't need authorization header if choose to use the SAS token for the auth. 

Can you check whether the SAS token generated correctly? According to your description, every page refresh, you will get a new SAS token. Is the time period of the SAS token expired?

Best

**Comment by grbspltt** [comment]
I have an azure function that generates the token. It sets the start date 5 min in the past and the expires set to 1 hr.

```
var azure = require('azure-storage'),
  STORAGE_ACCOUNT = process.env.AZURE_STORAGE_ACCOUNT,
  ACCESS_KEY = process.env.AZURE_STORAGE_ACCESS_KEY;

module.exports = function (context, req) {
  context.res = generateSasToken();
  context.done();
};

function generateSasToken() {
  var perms = azure.BlobUtilities.SharedAccessPermissions;
  var blobService = azure.createBlobService(STORAGE_ACCOUNT,ACCESS_KEY);
  // Create a SAS token that expires in an hour
  // Set start time to five minutes ago to avoid clock skew.
  var startDate = new Date();
  startDate.setMinutes(startDate.getMinutes() - 5);
  var expiryDate = new Date(startDate);
  expiryDate.setMinutes(startDate.getMinutes() + 60);
  var permissions = [perms.READ,perms.WRITE,perms.CREATE,perms.DELETE].join('');
  var sharedAccessPolicy = {
    AccessPolicy: {
      Permissions: permissions,
      Start: startDate,
      Expiry: expiryDate
    }
  };
  var sasToken = blobService.generateSharedAccessSignature('dronephotos', undefined, sharedAccessPolicy);
  return {
    token: sasToken,
    expiryDate,
    issDate: startDate
  };
}
```

**Comment by XiaoningLiu** [comment]
Hey

Seems you're using Azure Storage Node.js Client Library in Azure Functions instead of JavaScript Client Library for browsers.

Is this issue always re-produced stably on your side? And refresh will always solve this? 

Can you try to set a larger SAS token expire period? such as start time to 1 day ago, and end time to 1 day expire.

**Comment by grbspltt** [comment]
@XiaoningLiu I'm using the Azure Storage JavaScript Client Library 0.2.5-preview.11 for browsers in my browser code, and the azure-storage NPM library (version 2.2.1) in my azure function.

Not sure how I could say that an intermittent issue is stably re-produced.  I will say that 99% of the time it fails on the first attempt.  After 5-6 refreshes it will work and every subsequent upload will succeed.

I modified the azure function start time and end time to 1 day ago and 1 day in the future.  My first attempt worked so I will test it out over the weekend.

**Comment by XiaoningLiu** [comment]
@grbspltt Thanks! Actually I want to make sure whether the auth error is because of the time gap. If it works as you said, it's true.

**Comment by grbspltt** [comment]
No reported errors so it looks promising.  This part of my app only gets used on the weekends so I'll keep track of this and reopen the issue if it reappears.  Thanks for your help!

**Comment by iamakimmer** [comment]
I'm not sure if this is related, but I just had the same issue today and haven't touched any code in months. I think my server time was off and the headers would say they were expired. Fixing my server time did the truck.

**Comment by grbspltt** [comment]
@iamakimmer I'm using an Azure Function so I don't have any way to set the server time that I know of, but good to know. Thanks.

@XiaoningLiu I got a report yesterday of this error coming up but after 1 refresh they were able to upload files.
