### ISSUE TITLE
StorageError: The value for one of the HTTP headers is not in the correct format.

### ISSUE THREAD

**Issue by Aron4u** [Azure/azure-storage-node#365]
1. thanks for the great library. 

2. im using deleteBlobIfExists or deleteBlob and I'm getting a Error message like:

> StorageError: The value for one of the HTTP headers is not in the correct format.

could it be that its a similar issue as https://github.com/Azure/azure-sdk-for-python/issues/288 ?

**Comment by XiaoningLiu** [comment]
Hi, Can you provide a code sample and more backgrounds for this issue? Such as library version, Node.js runtime version etc.

**Comment by Aron4u** [comment]
azure-storage@2.5.0

```
 const service = createBlobService(AzureStorageConfig.accountName, AzureStorageConfig.accessKey);
    const options: BlobService.DeleteBlobRequestOptions = { deleteSnapshots: 'BLOB_AND_SNAPSHOTS' };
    return new Promise<ServiceResponse>((resolve, reject) => {
      service.deleteBlob(AzureStorageConfig.containerName, fileName, options, (err, response: ServiceResponse) => {
        if (err) {
          reject(err);
        } else {
          resolve(response);
        }
      });
    });
```

> node --version
> v8.5.0

let me know if I can help with more information

**Comment by XiaoningLiu** [comment]
@Aron4u 

I think the value of option `deleteSnapshots` is wrong.
```
var azure = require('azure-storage');
const options: BlobService.DeleteBlobRequestOptions = { deleteSnapshots: azure.BlobUtilities.SnapshotDeleteOptions.BLOB_AND_SNAPSHOTS};
```

**Comment by Aron4u** [comment]
works perfectly. thank you :)

just for future people comming here ...
we are using typescript and the syntax is a little bit diffrent from what XiaoningLiu posted

`import { createBlobService, BlobService, BlobUtilities, ServiceResponse } from 'azure-storage';`

and 
`const options: BlobService.DeleteBlobRequestOptions = { deleteSnapshots: BlobUtilities.SnapshotDeleteOptions.BLOB_AND_SNAPSHOTS }; `

`service.deleteBlob(containerName, fileName, options, (err, response: ServiceResponse) => ...`

**Comment by xtianus79** [comment]
The documentation is very lacking in this area. I am getting the error but there is no good documentation on how to set these things correctly.

**Comment by Aron4u** [comment]
you have example code that's not working?
