### ISSUE TITLE
File Share method for getting list of all files?

### ISSUE THREAD

**Issue by rachelnicole** [Azure/azure-storage-node#369]
Sorry if I'm misreading, but is there any way to retrieve a list of files inside a File Storage?

I'm creating / uploading this way: 

```
fileService.createShareIfNotExists('pixelart', function(error, result, response) {
    var randomName = uuidv4();
    if (!error) {
      console.log('made new file share');
      fileService.createFileFromStream('pixelart','', randomName + '.gif', rs, req.file.buffer.length, function(error, ...result){
        if (error) {
          console.log(error);
        }
        console.log(result);

      }) 
    }
  });
```

But, I'd also like to retrieve a list of the URLs to all the files that are in the same directory so when the web app initially loads & when I update the files I can populate the DOM with the files I have uploaded. 

And I know that if you're doing it manually via this way you CAN get a list of files and directories: https://docs.microsoft.com/en-us/rest/api/storageservices/List-Directories-and-Files?redirectedfrom=MSDN 

But is there any way to do that with the SDK? Trying to get away with not having to write my own authenticator

**Comment by rachelnicole** [comment]
Nevermind! With the help from @fiveisprime I was able to access that data by using the example on this line: https://github.com/Azure-Samples/storage-file-node-getting-started/blob/master/fileSample.js#L190


Feel free to close!

**Comment by jiacfan** [comment]
Hi, @rachelnicole 

Glad to know the good news. Welcome posting thinking here anytime!

Thanks,
Jiachen
