### ISSUE TITLE
Error in Chrome on the azure-storage.blob.js

### ISSUE THREAD

**Issue by fab2903** [Azure/azure-storage-node#370]
In trying to do a Html site, that allows to upload a file to Azure blob. I see this error when a run my app on Google Chrome. 

![image](https://user-images.githubusercontent.com/12189962/31800951-fbfac864-b501-11e7-8fa1-e9bbaedcf4b6.png)

Please let me know if this error is expected.

**Comment by fab2903** [comment]
I debug my HTML and found out the error is on this precise line:  var blobService = AzureStorage.createBlobServiceWithSas(blobStorageUri, sasKey).withFilter(new AzureStorage.ExponentialRetryPolicyFilter());
I'm trying to upload the file from the browser, my application is ASP.Net using MVC but right now I'm just trying to upload the file from the HTML (view) using the javascript functionality.

**Comment by XiaoningLiu** [comment]
Hi, 

Do you include the the `azure-storage.common.js`? 

Here is an online sample for your reference: https://dmrelease.blob.core.windows.net/azurestoragejssample/samples/sample-blob.html

Thanks

**Comment by fab2903** [comment]
Yes I did, but it seems is not retrieving the Azure Storageon the HTML. I will check the example. Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by vinjiang** [comment]
Feel free to let us know if further assistance required.
