### ISSUE TITLE
Cannot find name Buffer.

### ISSUE THREAD

**Issue by ccaymaz** [Azure/azure-storage-node#371]
Hi, When I try to build my application I always get "Cannot find name Buffer." error.  After adding 

`<reference path="../index.d.ts" />` into **azure-storage.d.ts** I could build. 

Looks like azure-storage.d.ts cannot read ./globals/node/index.d.ts

**Comment by XiaoningLiu** [comment]
What's your Node.js & TypeScript version?

**Comment by ccaymaz** [comment]
Hi @XiaoningLiu ,

Node.js s 6.11.4 (latest)
npm -v 3.10.10
Typescript 2.3.3 (also I tried 2.4+) I got the same result.

The issue is really interesting because in my other solution I used webpack and it is working currently.

**Comment by XiaoningLiu** [comment]
Do you still have the same issue with the latest azure-storage-node version?

**Comment by XiaoningLiu** [comment]
Please add ```@types/node``` into your ```package.json``` to load Node.js typing.

I cannot add ```<reference path="../index.d.ts" />``` for now into azure-storage.d.ts because it will break TypeScript 1.6 versions. See https://github.com/jvandemo/generator-angular2-library/issues/9

**Comment by ccaymaz** [comment]
Hey @XiaoningLiu , I tried, but still same result. At least It is not stopping me.

**Comment by XiaoningLiu** [comment]
I cannot re-produce the issue, here are my settings:

TypeScript: 2.7.2
Node.js: 8.10.0
azure-storage: 2.8.1
Dependency to ```@types/node: *```

tsconfig.json
```
{
	"compilerOptions": {
		"target": "es5",
		"sourceMap": true,
		"outDir": "built",
		"noEmitOnError": true,
		"module": "commonjs"
	},
	"types": [
		"node"
	],
	"exclude": [
		"node_modules",
		"dist",
		"built",
		"docs"
	]
}
```

We can further to have a look if you can provide a more detailed sample to re-produce the issue.

**Comment by vinjiang** [comment]
Please let us know if we can be of further assistance.
