### ISSUE TITLE
azure-storage not working with web pack (azure-functions-pack) server side

### ISSUE THREAD

**Issue by danielserrao** [Azure/azure-storage-node#373]
Hi,

I made an Azure Function micro service using Node.js and I'm using the npm module azure-storage to insert files in a Blob Storage.

Locally is working fine, but when deploying to development environment, it is executed a script that executes azure-functions-pack and generate a bundle with the service code and all the required npm modules. Then when making a request to the micro service, it return a status code 500 and in the logs the error is the following:

>     System.Exception : Error: Cannot find module "."
>     at webpackMissingModule (D:\home\site\wwwroot\.funcpack\index.js:238044:68)
>     at Object.<anonymous> (D:\home\site\wwwroot\.funcpack\index.js:238044:147)
>     at __webpack_require__ (D:\home\site\wwwroot\.funcpack\index.js:21:30)
>     ...

I only know that the problem is the azure-storage module because If I comment the "azureStorage = require('azure-storage');" , then start working. I also tried the npm module fast-azure-storage without success and until now I was not able to find a workaround for this problem. The code that uses this module is the following:

```
        const blobSvc = azureStorage.createBlobService(storageConnectionString);
        const writeStream = blobSvc.createWriteStreamToBlockBlob('containerName', fileName);

        return new Promise(function (resolve) {
          writeStream.write(svgString);
          writeStream.on('close', () => {
            resolve('https://' + storageAccount + '.blob.core.windows.net/containerName/' + fileName);
          });

          writeStream.end();
        });
```

The version of azure-storage is 2.6.0. Thanks for any help.

**Comment by jiacfan** [comment]
Hi, @danielserrao 

Thanks for trying this scenario. Azure storage node.js client library hasn't fully supported working with webpack, this item is in our backlog, and we'll investigate it and get back if there is any updates. 

Thanks,
Jiachen

**Comment by MonicaMarques** [comment]
Hi @jiacfan,

Thanks for the response, but after a lot of struggle I discovered that what was causing the problem was the node-chartist module. node-chartist work fine, but when bundling the project with functions pack, it mess up with some of other modules, including azure-storage-node. That is why I thought the source of the problem was azure-storage-node, but it wasn't. Sorry for the trouble.

Kind regards,
Daniel Serrão

**Comment by jiacfan** [comment]
Hi, @MonicaMarques 

Really glad to know this information, and thanks for sharing your progress! This would be helpful for us to evaluate the item "Azure storage node.js client library working with webpack".

Welcome any further discussions!

Thanks,
Jiachen
