### ISSUE TITLE
npm package restructure to provide better bundling support for browser scenario

### ISSUE THREAD

**Issue by matt-psaltis** [Azure/azure-storage-node#375]
Hi there,

I'm looking to use the azure-storage npm package within an Angular5 webpack based scenario.

At the moment I can import the FileService browser component using the following:

`import * as FileService from 'azure-storage/lib/services/file/fileservice.browser';`

This works but I have to manually construct the FileService object using the constructor `new FileService(null, null, uri, token)`. This is because the functions `createFileService` and `createFileServiceWithSas` are exported from the `azure-storage.js` file.

As this file specifically takes the *node dependency chain by requiring the node based modules, this prevents using this file as the entry point to the Azure storage ecosystem from a browser perspective.

I would like to suggest at a minimum including an azure-storage.browser.js module to provide equivalent support.

Ideally the current package structure could use some additional restructuring to make this a whole lot easier for the different scenarios. I should be able to do `import { AzureService } from 'azure-storage/browser';` and have that work without thinking, or at least something to that effect.

Cheers!

**Comment by XiaoningLiu** [comment]
Hi @SaltyDH, thanks! We're going to focus on re-structuring work the Node.js/browser library in the next following months. For better performance, lower footprint, easier deployment. Your suggestion is very valuable for us. : )

**Comment by XiaoningLiu** [comment]
Hi, please try with our latest V10 JS SDK with smaller footprint and better performance! https://www.npmjs.com/package/@azure/storage-blob
