### ISSUE TITLE
Unable to delete File Share

### ISSUE THREAD

**Issue by zwtan** [Azure/azure-storage-node#381]
Hi, I'm using the SDK to do deleteShare() but if file share's name that has '-' eg. 'helloworld-testing' it will return error 'Share name format is incorrect.' wonder if there're any way to delete files for such format.

Thank you.

**Comment by jiacfan** [comment]
Hi, @zwtan 

We tested delete share whose name has '-' works with latest SDK using code:
    ```
var shareService = azure.createFileService("Endpoint");
    var testShareName = "name-test1";
    shareService.createShareIfNotExists(testShareName, function(err) {
        assert.equal(err, null);

        shareService.doesShareExist(testShareName, function(err, existsResult) {
            assert.equal(err, null);
            assert.equal(existsResult.exists, true);

            shareService.deleteShare(testShareName, function(err, out) {
                assert.equal(err, null);
            });
        });
    });
```

Could you share the SDK version and sample code causing the error you are using?

Thanks,
Jiachen

**Comment by zwtan** [comment]
Hi Jiachen,

Thank for the promptly reply. I'm actually using npm install with azure-storage as of 2.6.0.

`
let funcName = 'hello-world'

fileService.deleteShare(funcName, {}, (error, response) => {
				console.log('response: ' + JSON.stringify(response))
				console.log('error: ' + JSON.stringify(error))
				if (error) {
					console.log(`deleteFileStorage err: ${JSON.stringify(error)}`);
					reject(error);
				}
				// If 202 = deleted successful
			  if (response.statusCode === 202) {
			  	resolve(response);
			  } else {
			  	console.log(`deleteFileStorage err: ${JSON.stringify(response)}`);
			  	reject(response);
			  }
			});
`

**Comment by jiacfan** [comment]
Hi, @zwtan 

From our testing, 'hello-world' should be fine for a share name using azure-storage 2.6.0, here is HTTP request and response:

Request:
```
DELETE https://jiacssestg002.file.core.windows.net:443/hello-world?restype=share HTTP/1.1
x-ms-client-request-id: b3db1f30-d5ad-11e7-a22b-77aee1ba8d6e
user-agent: Azure-Storage/2.6.0 (NODE-VERSION v8.7.0; Windows_NT 10.0.15063)
x-ms-version: 2017-04-17
x-ms-date: Thu, 30 Nov 2017 09:06:08 GMT
accept: application/atom+xml,application/xml
Accept-Charset: UTF-8
content-type: 
content-length: 0
authorization: SharedKey <omitted>
host: jiacssestg002.file.core.windows.net:443
Connection: close
```
Response:
```
HTTP/1.1 202 Accepted
Transfer-Encoding: chunked
Server: Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 082124cd-001a-004c-0cba-692a1d000000
x-ms-version: 2017-04-17
Date: Thu, 30 Nov 2017 09:06:08 GMT
Connection: close

0
```
Would you please double check if there is consecutive dashes? Please check [Share Naming Rule](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-shares--directories--files--and-metadata) for details.

Thanks,
Jiachen

**Comment by zwtan** [comment]
Hi Jiachen,

Thank you for the troubleshooting on this matter. Have verify that it working now.

Cheers!
ZW
