### ISSUE TITLE
Problems with large blobs (10Gb)

### ISSUE THREAD

**Issue by lurumad** [Azure/azure-storage-node#387]
Hi, 

We are developing a web application that manage large files (PSB up to 10Gb) and when we are uploading these files we always recieves the same error:

```json
PUT https://xxxxxxxxcpn226pa5vnoa.blob.core.windows.net/scenes/a3e7881d-b886-431e-9644-5b554eaab7aa/90mm_Atlantis_Afternoon_sphere.psb?comp=block&blockid=MDg5NDg0NzgtMDAwMzQx&sv=2017-04-17&sr=c&sig=7iDoryKY8nyUVWp4VRGFIP1A8ydNtkuUlQEkHkzArLw%3D&st=2017-12-13T15:20:18Z&se=2017-12-14T15:25:18Z&sp=cw&api-version=2017-04-17 net::ERR_FILE_NOT_FOUND
startup.bundle.js?=c0gh5z2x95lj697cutvpqkyzv9:1 Uncaught TypeError: Cannot read property 'getAutoIncrementFunction' of null
    at ChunkStreamWithStream.<anonymous> (azure-storage.blob.js?=k3t6a3p5o2bj7mqh2bglod5u8r:7111)
    at ChunkStreamWithStream.EventEmitter.emit (azure-storage.common.js?=yijzqfmvy8am964fztaetjtvyv:37703)
    at ChunkStreamWithStream.ChunkStream._emitBufferData (azure-storage.common.js?=yijzqfmvy8am964fztaetjtvyv:1251)
    at ChunkStreamWithStream.ChunkStream._buildChunk (azure-storage.common.js?=yijzqfmvy8am964fztaetjtvyv:1217)
    at BrowserFileReadStream.EventEmitter.emit (azure-storage.common.js?=yijzqfmvy8am964fztaetjtvyv:37700)
    at readableAddChunk (azure-storage.common.js?=yijzqfmvy8am964fztaetjtvyv:35932)
    at BrowserFileReadStream.Readable.push (azure-storage.common.js?=yijzqfmvy8am964fztaetjtvyv:35891)
    at FileReader.BrowserFileReadStream._fileReader.onloadend (azure-storage.common.js?=yijzqfmvy8am964fztaetjtvyv:363)
    at ZoneDelegate.invoke (polyfills.bundle.js?=thw4y640ea233fojkygkj6anox:1)
    at Object.onInvoke (startup.bundle.js?=c0gh5z2x95lj697cutvpqkyzv9:1)
    at ZoneDelegate.invoke (polyfills.bundle.js?=thw4y640ea233fojkygkj6anox:1)
    at Zone.runGuarded (polyfills.bundle.js?=thw4y640ea233fojkygkj6anox:1)
    at FileReader.<anonymous> (polyfills.bundle.js?=thw4y640ea233fojkygkj6anox:1)
```

Any idea about this error?

Regards!

**Comment by jiacfan** [comment]
Hi, @lurumad 

We cannot simply repo this issue through uploading a 10GB file.

Could you share:
 1. What's the browser you are using, and version of the browser?
 2. What's the version of Azure storage Javascript library you are using? (Please check the top lines of azure-storage.blob.js file to get this version)
 3. Could you try to enable the verbose log and get detailed error messages for this problem, and provide the error messages to us, for how to enable verbose log:
`blobService.logger.level = AzureStorage.Logger.LogLevels.DEBUG; `

Thanks,
Jiachen

**Comment by cdoneshot** [comment]
i have the same issue.
browser:QQ browser(use **chromium53.0.2785.104**)
azure storage lib:**0.2.7-preview.13** 
log:
![image](https://user-images.githubusercontent.com/20412044/34402753-bffef272-ebde-11e7-811c-24f3a1d7e05c.png)

**Comment by BramKleverlaan** [comment]
+1 

I have done some testing and found out that uploading large files in Javascript works in Chrome, but it fails in Edge. Uploading 2 files of 1.5 GB each from MS Edge result in an “XHR error” without any details. I tried this multiple times, but without any success.

Test details
Chrome 1 file of 1.5GB – CPU 7% & memory max 300 MB - Success
Chrome 2 files of 1.5GB each- CPU 7% & memory max 600 MB - Success
Edge 1 file of 1.5 GB – CPU 2% & memory grows with size of file 750MB-  Success
Edge 2 files of 1.5 GB each – CPU 2% & memory grows with size of file 800MB (~50% completed) - Upload blob failed with error: Error: XHR error undefined undefined

Code Snippet
var customBlockSize = file.size > 1024 * 1024 * 32 ? 1024 * 1024 * 4 : 1024 * 512;
blobService.singleBlobPutThresholdInBytes = customBlockSize;
speedSummary = blobService.createBlockBlobFromBrowserFile('myfolder', file.name, file, { blockSize: customBlockSize }, function (error, result, response) {

Any thoughts if and how I could fix this using this library?

**Comment by jiacfan** [comment]
Thanks for reporting the issues!

@BramKleverlaan 
 What's the Edge version and client library version you are using? Is it stable repoed in your side?

@cdoneshot 
Do you have latest QQ browser installed and would this issue get repo again?

As browsers have different implementations, please try to provide stable repo patterns, and we'll try to repo locally and investigate the issues. 

Thanks,
Jiachen

**Comment by cdoneshot** [comment]
@jiacfan 
yes.i have upgrade qq browser to lastest version.

**Comment by jiacfan** [comment]
@cdoneshot 

You are using 10.0 beta or 9.7? The problem can be steady repo with small file like 13MB? We'll check this issue, and give you feedback.

Thanks,
Jiachen

**Comment by BramKleverlaan** [comment]
@jiacfan 
I'm using Microsoft Edge 41.16299.248.0 and azurestoragejs-0.2.7-preview.13.
Yes, it's reproducible.

**Comment by XiaoningLiu** [comment]
Hi @lijunle @cdoneshot @BramKleverlaan 

"XHR Error" usually means a HTTP request based on XHR returned an error event. Such as by network broken, especially when network usage is heavy or poor connection to Azure Storage server. Here is the [code](https://github.com/jhiesey/stream-http/blob/920dd3cd485220a30c8937fa30c1630b34701df1/lib/request.js#L213) throws the error:



I updated the retry policy to enable the retry for "XHR error", **please have a try with following version**:
https://1drv.ms/u/s!AtKGeL9cTFgWgtcqFh9ERDXcF2e6zA

When you create blobService object, please make sure there is a retry policy enabled, such as:

```
var blobService = AzureStorage.createBlobServiceWithSas(blobUri, sas).withFilter(new AzureStorage.ExponentialRetryPolicyFilter(5)); // max retry 5 times for a failed request
```

**Comment by cdoneshot** [comment]
@jiacfan 
i‘m using qqbrowser 9.7(13021) and azurestoragejs-0.2.7-preview.13.
it 's repo.

**Comment by cdoneshot** [comment]
@XiaoningLiu 
I try to use your version and add retryplicyfilter. still error

**Comment by XiaoningLiu** [comment]
@cdoneshot Old version Chromium (QQ browser currently uses a very old Chromium core) has a bug with local file reading, which will failed to GC unused memory, may lead to net::ERR_FILE_NOT_FOUND error.  Refer to https://github.com/jhiesey/stream-http/issues/57

Please try with this version which has a workaround for this issue:
https://1drv.ms/u/s!AtKGeL9cTFgWgtcre3izmixWzq1Buw

**Comment by cdoneshot** [comment]
@XiaoningLiu 

This version seems to works, I tried many times and got no errors。
thanks!

**Comment by XiaoningLiu** [comment]
@cdoneshot Glad to see that! Following versions of SDK will have this fix.
