### ISSUE TITLE
 cannot find module azure-storage error in custom API

### ISSUE THREAD

**Issue by kkapgm** [Azure/azure-storage-node#39]
this is strange, I have been using the below code in my azure mobileServices Custom API for past two months and  it was working good till morning. but now I am getting error - cannot find module azure-storage - at the below line in my custom API  
    var azure = require('azure-storage');
    var retryOperationFilter = new azure.ExponentialRetryPolicyFilter();
    var tableService= azure.createTableService().withFilter(retryOperationFilter);

I do have azure-storage included in my package.json - 
"dependencies": {"tracer": "0.7.3", "colors" : "1.0.3", "lodash" :"2.4.1", "azure-storage": "0.4.1"},

has any change been made to the lib?

**Comment by slepox** [comment]
@kkapgm, 0.4.2 is released recently but we weren't aware of any issue to use 0.4.1, and simply try your code it worked well. Just to confirm, did you run "npm install" in the working directory to get the module?

**Comment by kkapgm** [comment]
@slepox , thanks, like I said, this very code was working fine till yesterday. I don't remember doing npm install, this is in my azure mobile service custom API code (which I manage via git in Webstorm), so I don't think I need to npm install azure-storage there, I assume including it in my azure mobile service's package.json takes care of that...
its working when you try, and no one else seem to have reported, looks like maybe mine is a one-off case, but I am clueless what to do...

**Comment by veena-udayabhanu** [comment]
Were you able to resolve this issue? If not, can you please check where exactly the azure-storage module is installed on your machine? Did you use any special option when you installed it?

**Comment by kkapgm** [comment]
yes, I got it working by doing a manual npm install 'azure-storage' to my mobile service.

I didn't try a manual npm install because, as I remember reading, if I just include the npm module I want to use in my mobile service's ''package.json' , azure mobile service on the server installs it and restarts, and I don't need to install myself manually. And thats what has been happening when my code was working till last week.  Also the other node modules e.g tracer, lodash,  that I have in my package.json, work fine with no manual npm install.

**Comment by steve-movi** [comment]
I've exactly the same issue!

I do have azure-storage included in my package.json - 
"dependencies": {"azure-storage": "*"}

I put the "*" to get always the lastest version but it seems not working well.

My mobile application is not working due to that problem!

**Comment by yaxia** [comment]
This is an issue caused by the old version of npm on the Mobile Service backend (https://github.com/npm/npm/issues/4849). The fix will go live on Mobile Service soon. Before that, we suggest to use the following workaround:
At the root of the source repo, you'll find a **.deployment** file that has:
```
[config]
command = ..\ZumoDeploy.cmd
```
Change it to
```
[config]
command = deploy.cmd
```
And create a **deploy.cmd** next to it containing:
```
set NPM_JS_PATH=%ProgramFiles(x86)%\npm\1.4.9\node_modules\npm\bin\npm-cli.js
..\ZumoDeploy.cmd
```
Then commit both **.deployment** and **deploy.cmd** and push.

**Comment by steve-movi** [comment]
Thank you for your response.
I did a manual npm install and all it's fine now.
But I'm a little bit worrying about reliability of mobile services in Azure
