### ISSUE TITLE
Errors with firebase and typescript

### ISSUE THREAD

**Issue by KatiaKalynchuk** [Azure/azure-storage-node#399]
I'm trying to add firebase to my react-typescript app and I have this:

ERROR in ./node_modules/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Can't resolve 'child_process' in '/Users/katia/Documents/myFiles/React_ts_test_app/node_modules/xmlhttprequest/lib'
 @ ./node_modules/xmlhttprequest/lib/XMLHttpRequest.js 15:12-36
 @ ./node_modules/firebase/index.node.js
 @ ./src/firebase.tsx
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./index.tsx

ERROR in ./node_modules/@firebase/database/dist/cjs/src/nodePatches.js
Module not found: Error: Can't resolve 'request' in '/Users/katia/Documents/myFiles/React_ts_test_app/node_modules/@firebase/database/dist/cjs/src'
 @ ./node_modules/@firebase/database/dist/cjs/src/nodePatches.js 135:159-177
 @ ./node_modules/@firebase/database/dist/cjs/index.node.js
 @ ./node_modules/firebase/database/index.js
 @ ./node_modules/firebase/index.node.js
 @ ./src/firebase.tsx
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./index.tsx

ERROR in ./node_modules/faye-websocket/lib/faye/websocket/client.js
Module not found: Error: Can't resolve 'tls' in '/Users/katia/Documents/myFiles/React_ts_test_app/node_modules/faye-websocket/lib/faye/websocket'
 @ ./node_modules/faye-websocket/lib/faye/websocket/client.js 3:13-27
 @ ./node_modules/faye-websocket/lib/faye/websocket.js
 @ ./node_modules/@firebase/database/dist/cjs/src/nodePatches.js
 @ ./node_modules/@firebase/database/dist/cjs/index.node.js
 @ ./node_modules/firebase/database/index.js
 @ ./node_modules/firebase/index.node.js
 @ ./src/firebase.tsx
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./index.tsx

Who can help me?

**Comment by XiaoningLiu** [comment]
@KatiaKalynchuk Sorry, but does the error relate with azure-storage Node.js client library?
