### ISSUE TITLE
ESOCKETTIMEDOUT error while uploading large file in azure file storage

### ISSUE THREAD

**Issue by AbhishekKaura25** [Azure/azure-storage-node#401]
Hi,

We are getting issue while uploading a large file into azure file storage.  This snippet is working fine till yesterday and this call is only started failing from today onwards. Logs is giving below error.

{"code":"ESOCKETTIMEDOUT","connect":false}

Code snippet:
fileService.createFileFromStream(fileShare, directory, fileName, fileStream, fileByte.length, function(error, result, response) {
                            if (!error) {
                                console.log('File is uploaded to file storage successfully');
                                res.status(201).send({
                                    success: true,
                                    msg: 'File is uploaded to file storage successfully'
                                });
                            } else {
                                console.log('Error occurred while uploading the file in file storage' + JSON.stringify(error));
                                res.status(400).send({
                                    success: false,
                                    msg: 'Error occurred while uploading the file in file storage',
                                    error: JSON.stringify(error)
                                });
                            }
                        });

**Comment by XiaoningLiu** [comment]
Hi @AbhishekKaura25 

If there is no code change on your side, I think there maybe some issues on the network. The socket timeout usually happens when network is poor, or network in heavy usage.

Suggestions on the client library side is to add retry filter, which may help.

```
fileService.withFilter(new AzureStorage.ExponentialRetryPolicyFilter());
```

**Comment by vinjiang** [comment]
Feel free to let us know if further assistance required.
