### ISSUE TITLE
 azure-storage.blob.js:5 Uncaught Error: Cannot find module 'buffer' at s (azure-storage.blob.js:5)

### ISSUE THREAD

**Issue by seguler** [Azure/azure-storage-node#402]
Multiple users have reported this over past couple of months. The issue occurs in the JS where the blob package is imported before the common package. See comments here: https://azure.microsoft.com/en-us/blog/new-azure-storage-javascript-client-library-for-browsers-preview/

Is there any possible resolution to this ?

**Comment by jiacfan** [comment]
Hi, @seguler 

Thanks for bring this topic here. 
In the preview version, user need to import azure-storage.common.js first, and then azure-storage.blob.js. As browser doesn't support Buffer which exists in node.js, and browserify helped to generate 'Buffer' which is suitable for browsers and put it in azure-storage.common.js.
In the coming GA version, considering together with modularizing and splitting support, we may put the common part into blob package, and this would help to solve such problem.

Thanks,
Jiachen

**Comment by XiaoningLiu** [comment]
Latest version 0.2.8-preview.15 drops azure-storage.common.js, from this version importing single JS file azure-storage.blob.js is enough.
