### ISSUE TITLE
Upload file from browser blob url?

### ISSUE THREAD

**Issue by meds** [Azure/azure-storage-node#403]
Firebase Storage has a helpful feature where you can upload files through a blob url: https://firebase.google.com/docs/storage/web/upload-files

I would appreciate if I could do this with azure storage, in fact it feels very hard to upload files from a browser at all and I've been tearing my hear out these past few hours trying to figure out how to get a blob url uploading to azure storage.

**Comment by XiaoningLiu** [comment]
Hi @meds 

What is a `blob url` do you refer to?  An Azure Storage blob URL or Google Cloud blob URL?

**Comment by meds** [comment]
Hey @XiaoningLiu so a blob url in the context I'm describing is a url a browser holds to a local file, it looks like blob:http://localhost:3000/cd8ba70e-5877-4112-8131-91c594be8f1e and if you view it in your local browser it will point to the file that was added.

I use react-dropzone (https://github.com/react-dropzone/react-dropzone) which provides me with a blob url to the file dropped in. So if I drop a photo of pikachu into the drop zone the callback is called with a link to the file in the blob:http://etc,etc format that I can view in the browser locally and javascript can access and process however it wants (i.e. display it in an img tag.


To upload to azure from a blob url I think it should be a matter of reading the blob url into a stream and uploading it to azure using the stream upload function but I'm not sure how to accomplish this easily and haven't succeeded thusfar, firebase simply gives you the ability to upload a blob url to their storage directly..

**Comment by XiaoningLiu** [comment]
Hey @meds 

Currently, there is no specific API to upload from a browser blob URL. We added into our backlog for Azure Storage JavaScript client library.

As a workaround, if the blob size <= 64MB, you can convert the blob url to string and upload by `blobService.createBlockBlobFromText`

```
blobService.createBlockBlobFromText(container, 'browserblob', <string>, (err, res, resp) => {console.log(err, res, resp);})
```

**Comment by meds** [comment]
@XiaoningLiu ah fair enough, though to be honest that's not necessarily a workable solution. I already tried it but the uploaded file was registered as a 'application/octet-stream' by azure instead of an image file so downloading it didn't work right. The file size was also somehow different (smaller) than the file I had originally uploaded..

**Comment by XiaoningLiu** [comment]
@meds The content Type can be set by options of createBlockBlobFromText.

```
blobService.createBlockBlobFromText('taskcontainer', 'myblob', xhr.responseText, {contentSettings: {contentType: "MY_CONTENT_TYPE"}}, (error, result, response)=>{
})
```

For the size, can you compare the size of `xhr.responseText` with the block blob size after uploaded?

**Comment by meds** [comment]
@XiaoningLiu Unfortuantely the uploaded file still doesn't appear correctly and is a few kilobytes smaller than the one I had tried to upload.

Is it possible this is a bug on azures end or just something I'm doing wrong?

**Comment by XiaoningLiu** [comment]
What's the size of `xhr.responseText` before uploading and what's the size of the blob after uploading?

**Comment by meds** [comment]
@XiaoningLiu  I'm not too sure what's going on, xhr.responseText size is usually correct, for example I decided to upload a bmp made of 1 pixel, its size was 60 bytes on desktop, xhr.responseText.length returned 60 but after uploading its size became 66 bytes on azure.

Downloading that bmp it looks like it survived (1 pixel white), the PNGs don't fare so well and are corrupted.

I did a diff with the uploaded bmp (left) and the original, not sure what azure is doing to the file after u[load but doesn't look very pretty...

![image](https://user-images.githubusercontent.com/2121021/35678518-cb006af4-07a7-11e8-963d-2bb8b45aba26.png)

This is the code I used:

```
                    var xhr = new XMLHttpRequest();
                    xhr.open("GET", blobUrl);
                    xhr.responseType = "text";//force the HTTP response, response-type header to be blob
                    xhr.onload = function () {
                        blobService.createBlockBlobFromText('taskcontainer', 'myblob', xhr.responseText,  {contentSettings: {contentType: "image/bmp"}}, (error, result, response)=>{
                            var ok = 0;
                        })
                    }
                    xhr.send();

```

**Comment by XiaoningLiu** [comment]
Sorry for late response. I'm on vocation for previous days. It's quite interesting to have such differences. Can you share the bmp file you used?

**Comment by gl0b** [comment]
I'm having the same behavior with PNG's. They get corrupted while they are processed by **createBlockBlobFromText** method. The workaround I found was passing the image encoded in Base64. So I assume there's some kind of problem with the encoding.

**Comment by olivierchatry** [comment]
So landed here after trying to find a way to generate an upload url. every single cloud provider is supporting this feature, as it sounds very antiquated to upload to your backend so that it can stream to azure blob. 

The way it is done in AWS or GCloud :
- front end ask for backend to upload a file
- backend ask cloud storage provider for an upload URL ( name of the blob whatever ). The URL is signed, and is valid for a given amount of time.
- backend send the URL back to the frontend
- frontend start to upload

I think Azure is the only object storage I know that does not support that. It seems a bit redundant to have to open a stream to the backend that will then stream to the Azure Storage ( twice the amount of byte have to move along for not a lot of purpose ).

Any chance this can happen ?

**Comment by XiaoningLiu** [comment]
Hi, in latest https://www.npmjs.com/package/@azure/storage-blob V10 SDK, you can upload a File/Blob/Unit8Arrary/Text from browser.

**Comment by olivierchatry** [comment]
Still means that I need to use a separate JS file, instead of just doing a HTTP PUT, as far as I understand.

**Comment by XiaoningLiu** [comment]
Single HTTP Put cannot upload a blob more than 256MB. To upload a large blob, recommend to use latest V10 SDK.

**Comment by dingzeyuli** [comment]
@XiaoningLiu Is there an API to upload to blob storage from an external video URL like www.example.com/public.mp4 ?

**Comment by EmmaZhu** [comment]
Hi @dingzeyuli 

Not sure whether you have found answers for the question. You can use `BlobService.startCopyBlob` to copy from a URL to blob.

We have next generation SDK for JS for all azure operations here: https://github.com/Azure/azure-sdk-for-js, blob operations are supported in @azure/storage-blob package. `BlobClient.beginCopyFromURL` in @azure/storage-blob package can be used to copy from a URL to blob.

Thanks
Emma
