### ISSUE TITLE
createFileFromText throws if given an empty string for the text

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-storage-node#405]
FileService.prototype.createFileFromText = function (share, directory, file, text, optionsOrCallback, callback) {
  var userOptions;
  azureutil.normalizeArgs(optionsOrCallback, callback, function (o, c) { userOptions = o; callback = c; });

  validate.validateArgs('createFileFromText', function (v) {
    v.string(share, 'share');
    v.stringAllowEmpty(directory, 'directory');
    v.string(file, 'file');
    **v.exists(text, 'text');**   - should be stringAllowEmpty

**Comment by jiacfan** [comment]
Hi, @StephenWeatherford 

Thanks for the suggestion, this demand is reasonable, and we'll consider to involve it in the coming releases.

Currently, please use CreateFile as a work around when text is empty.

Best Wishes,
Jiachen

**Comment by StephenWeatherford** [comment]
Thanks, will do.

**Comment by jiacfan** [comment]
Close as fixed.
