### ISSUE TITLE
deleteBlob blocks nodejs event loop

### ISSUE THREAD

**Issue by Hubrus** [Azure/azure-storage-node#408]
Given a list of blobs I want to delete them one by one (since there's no batch/bulk delete of blobs in azure storage sdk) without blocking node's event loop or the express server. The deletion is triggered by (and runs on) a request. But although the entire flow is made as async as possible, the express server becomes unresponsive once the deletion starts. Doesn't matter what endpoint of the server i'm calling while deletion is happening, the requests are all pending till the deletion is done.

```
const async       = require('async');
const azure       = require('azure-storage');
const Promise     = require('bluebird');

const blobService = azure.createBlobService(CONFIG.CONNECTION_STRING);

// Endpoint
app.delete(`${BASE_URL}/files/:date`, deleteFiles);

const deleteFiles = async (req, res) => {

  const date = req.params.date;

  await deleteBlobs(date).catch((err) => {

    return res.status(500).send(err);

  });

  res.status(200).send();

};

const deleteBlobs = (date) => {

  return new Promise(async (resolve, reject) => {

    // findFiles calls blobService.listBlobsSegmentedWithPrefix and performs some async.map on the returned entrieds
    const blobNames = await findFiles(date)
      .catch(err => log.error('findFiles failed in deleteBlobs.', err));

    async.each(
      blobNames,
      (blobName, callback) => {

        blobService.deleteBlob(CONTAINER, blobName, (deleteError) => {

          if (deleteError) {

            return callback(deleteError);

          }

          callback();

        });

      },
      err => {

        if (err)  {

          return reject(err);

        }

        resolve();

      });

  });

};
```

In order to make sure is not my code that's blocking, I replaced the `blobService.deleteBlob` call with a setTimeout of 10 seconds and everything flows as expected, delete request being done in a bit over 10 seconds, incoming requests not being blocked.
But somehow calling deleteBlob on a large number of blobs, although the calls are async, everything becomes unresponsive.
I also noticed a progressive increase of time taken by the deletion to complete when deleting a list of blobs. First delete request takes let's say 50ms, next one maybe 60, and after a couple of them it jumps to 150, 300 and so on all the way to maybe over 1s one single delete request.

I've tried to look through the code to see if i can find something that would explain what I'm experiencing but couldn't see anything. Does this behavior make sense?

**Comment by jiacfan** [comment]
Hi, @Hubrus 

For testing deleteBlob async behavior, I used following code:

```
let service = new BlobService("<ConnectionString>")
let container = 'testcontainer';

service.listBlobsSegmented(container, null, function(error, results) {
    assert.equal(error, null);

    async.each(
        results.entries,
        function(blobResult, callback) {
            blobName = blobResult.name;
            console.log("[%s] '%s' start deleting", Date.now(), blobName);
            service.deleteBlob(container, blobName, function(deleteError) {
                if (deleteError) {
                    console.log("[%s] '%s' failed to be deleted %s", Date.now(), blobName, deleteError);
                    callback(deleteError);
                } else {
                    console.log("[%s] '%s' finished deleting", Date.now(), blobName);
                    callback();
                }
            });
        },
        function(err) {
            if (err) {
                console.log('One blob is failed to be deleted.');
            } else {
                console.log('All blobs have been deleted.')
            }
        }
    );
});
```

And the result is **the requests for deletion are not blocked, and can be finished in parallel.**

In your case, the special thing is the delete function is a delegation. And please note deleteBlob is different with setTimeOut in behavior, as deleteBlob will consume network resources, while setTimeOut will not. Please check if there is network parallel connection settings in your code, and ensure there is no limitation in your framework/network/system layer, which might cause this issue.

Best Wishes,
Jiachen

**Comment by Hubrus** [comment]
> Please check if there is network parallel connection settings in your code

I'm having a mere node + express + socket.io app. Nothing to fancy.

>and ensure there is no limitation in your framework/network/system layer, which might cause this issue.

Now that will be a challenge since I have no idea how Azure actually limits my app (the app is deployed in azure with a dev/test subscription).

**Comment by jiacfan** [comment]
As the previous testing deleteBlob async operation itself is not blocking, typically unresponsive is caused when the Node.js event loop is blocked. So would you please add more logs which can help to narrow down the problem? At same time, are you using HTTPs for requests? Could you monitor the CPU utilization, and see if CPU utilization could be the bottleneck, and analyze whether the issue is computing bound or I/O bound.

Best Wishes,
Jiachen

**Comment by Hubrus** [comment]
Ok, so I've managed to measure the event loop delay. Conclusion: is completely frozen during deletion.
```
[9:22:58.839][DEBUG] {"name":"Event Loop Delay","value":168}
[9:23:01.792][DEBUG] {"name":"Event Loop Delay","value":3436}
[9:23:03.229][DEBUG] {"name":"Event Loop Delay","value":5495}
[9:23:04.495][DEBUG] {"name":"Event Loop Delay","value":7106}
[9:23:05.573][DEBUG] {"name":"Event Loop Delay","value":8164}
[9:23:07.557][DEBUG] {"name":"Event Loop Delay","value":9700}
[9:23:08.589][DEBUG] {"name":"Event Loop Delay","value":11032}
[9:23:09.667][DEBUG] {"name":"Event Loop Delay","value":12392}
[9:23:10.870][DEBUG] {"name":"Event Loop Delay","value":13474}
[9:23:11.323][WARNING] Deleting 722 files took 14453ms
```
CPU jumps from 4% to 31% during deletion. Memory is constant at 56%.
> analyze whether the issue is computing bound or I/O bound.

I feel bad to ask this but ... how? 

Function used to measure event loop delay:
```
const startMeasuringEventLoop = function (reportCallback) {

  const startTime = process.hrtime();
  let sampleSum = 0;
  let sampleCount = 0;

  // Measure event loop scheduling delay
  setInterval(() => {

    const elapsed = process.hrtime(startTime);

    sampleSum += elapsed[0] * 1e9 + elapsed[1];
    sampleCount++;

  }, 0);

  // Report custom metric every second
  metricReporterTimer = setInterval(() => {

    const samples = sampleSum;
    const count = sampleCount;

    sampleSum = 0;
    sampleCount = 0;

    if (count > 0) {

      const avgNs = samples / count;
      const avgMs = Math.round(avgNs / 1e6);

      const eventLoopDepay = { name: 'Event Loop Delay', value: avgMs };

      console.log(eventLoopDepay);

    }

  }, 1000);

};
```

**Comment by jiacfan** [comment]
Hi, @Hubrus 

It seems there is computing logic which consumes and blocks event loop.

Would you provided detailed error info get in your code :
`await deleteBlobs(date).catch((err) => {

    return res.status(500).send(err);

  });`

And would you enable the verbose log of XSCL node.js library by:
`
var AzureStorage = require(‘azure-storage’);
var blobService = AzureStorage.getBlobService(…);
blobService.logger.level = AzureStorage.Logger.LogLevels.DEBUG;
`
I'm suspecting if there are a lot of retry logic being executed which blocks the main logic, and want to know what is causing the retry.

For CPU, is it the CPU percentage caused by your program or what you provide is the overall system's CPU usage. Please provide the CPU eat by you program, and would better to drill down into process/thread level.

Best Wishes,
Jiachen

**Comment by Hubrus** [comment]
Found the problem. Actually I'm not sure about the problem but there seems to be a solution. Using `async.eachLimit` with a limit of 10, drops the time needed to delete 1000 blobs from 15 seconds to just 5. So paying attention to the number of async operations spawning at a time, seems to be what will solve the problem. Does it make sense?

Thanks a lot for your help!

**Comment by XiaoningLiu** [comment]
@Hubrus Great! I replied to following StackOverflow similar question. Maybe the same with this one. Node.js provides non-blocking I/O based on a event loop. Too many delete async operations, which creates lots of callback I/O events at a short time. Node.js may serve these events at first, and stuck the Node.js to deal with other incoming HTTP requests events.

https://stackoverflow.com/questions/48564732/deleting-a-list-of-azure-blobs-blocks-express-nodejs/49381365#49381365
