### ISSUE TITLE
Function names in README are invalid / outdated

### ISSUE THREAD

**Issue by tp** [Azure/azure-storage-node#41]
I wanted to use this package to read the contents of a blob and found `getBlockBlobToStream` mentioned in the README.

Turns out that this function does not exist in the code, but there is one called `getBlobToStream`.

I think all the examples should be updated unless the README is ahead of its time and the code is about to change soon.

**Comment by slepox** [comment]
@tp, thanks for raising this issue. We will make README up to date soon.

**Comment by slepox** [comment]
@tp, this is fixed in latest update.
