### ISSUE TITLE
How to get blob directories and blobs in a single request?

### ISSUE THREAD

**Issue by gmantri** [Azure/azure-storage-node#412]
I'm using the latest version of Node SDK. What I want to accomplish is to retrieve list of blob directories and blobs in a single call. Unfortunately I could not find a method in the SDK to do so. 

I found 2 methods: `listBlobDirectoriesSegmentedWithPrefix` (which returns just directories) and `listBlobsSegmentedWithPrefix` (which returns just blobs) and both of them make network request. 

However I noticed that the response contains both `Blobs` and `BlobPrefix`. 

Should I just call `listBlobsSegmentedWithPrefix` and then parse the response to find out blob folders? What's the recommended approach?

**Comment by jiacfan** [comment]
Hi, @gmantri 

Blob directory is actually a virtual directory, and can also be understood as Blob's prefix. Your proposal worth trying, at same time I would like to suggest another approach if you can add yourself's convenience method. 

Please look into the code path, both `listBlobDirectoriesSegmentedWithPrefix` and `listBlobsSegmentedWithPrefix ` calls `_listBlobsOrDircotriesSegmentedWithPrefix`, and the difference is they use different `listBlobType`. To return blob directories and blobs in one call, you can simply add another method which is similar to `_listBlobsOrDircotriesSegmentedWithPrefix`, while parse both `Blobs` and `BlobPrefix`, and return together or separately with two arrays.

Best Wishes,
Jiachen

**Comment by vinjiang** [comment]
Feel free to let us know if further assistance needed.
