### ISSUE TITLE
Can't get a valid SAS token

### ISSUE THREAD

**Issue by F-MyKhi** [Azure/azure-storage-node#414]
Hi,

I'm trying to generate a SAS token with the azure-storage-node@2.8.0 but every generated token fire an error on client side when i try to use it.

> 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)

I'm using **azurestoragejs-0.2.8-preview.14** on client side.

Here is my server code for generating token.

    function generateToken() {    
      var startDate = new Date();
      startDate.setMinutes(startDate.getMinutes() - 1440);
      var expiryDate = new Date(startDate);
      expiryDate.setMinutes(startDate.getMinutes() + 1440);

      var permissions = AzureStorage.FileUtilities.SharedAccessPermissions.READ +
      AzureStorage.FileUtilities.SharedAccessPermissions.WRITE +
      AzureStorage.FileUtilities.SharedAccessPermissions.LIST +
      AzureStorage.FileUtilities.SharedAccessPermissions.CREATE;

      var sharedAccessPolicy = {
        AccessPolicy: {
          Permissions: permissions,
          Start: startDate,
          Expiry: expiryDate,
          Protocols: AzureStorage.Constants.AccountSasConstants.Protocols.HTTPSORHTTP,
          Services: AzureStorage.Constants.AccountSasConstants.Services.FILE,
          ResourceTypes: AzureStorage.Constants.AccountSasConstants.Resources.SERVICE + AzureStorage.Constants.AccountSasConstants.Resources.CONTAINER + AzureStorage.Constants.AccountSasConstants.Resources.OBJECT
        }
      };
   
      return AzureStorage.generateAccountSharedAccessSignature(process.env.AZURE_STORAGE_NAME, process.env.AZURE_STORAGE_KEY, sharedAccessPolicy);
    }

It generates a token who looks like that.
> sv=2017-07-29&ss=f&srt=sco&sp=rwlc&st=2018-02-14T13%3A38%3A17Z&se=2018-02-15T13%3A38%3A17Z&spr=https%2Chttp&sig=RmVmlWlOEf8oxEZoD8ZnH7mqTC72jb7SkK%2BoZCWfQZI%3D

Azure portal token
> sv=2017-04-17&ss=f&srt=sco&sp=rwlc&se=2018-02-15T19:15:58Z&st=2018-02-15T11:15:58Z&spr=https,http&sig=rLEbM%2FvpZWr1zbGD0sc%2BTtkpSJR9MVuTS0syBqijOoQ%3D

The main difference between that token and a token generated from the azure portal is the **sv** parameters.

When i use Azure portal token with my client side code everything work fine, but when i use my server side generated token i just get a 403 error.

Is there a problem with my code? Or is there an issue with my version of the sdk ?
Thanks

**Comment by XiaoningLiu** [comment]
@F-MyKhi There is a bug in above sample code:

Use `expiryDate.getMinutes` instead of `startDate.getMinutes`

```
  var expiryDate = new Date(startDate);
  expiryDate.setMinutes(startDate.getMinutes() + 1440);
```

**Comment by F-MyKhi** [comment]
@XiaoningLiu It works perfectly.
Thanks for your answer :)
