### ISSUE TITLE
potential security vulnerability via an outdated version of request@2.81.0 > hawk@3.1.3 > hoek@2.16.3                         

### ISSUE THREAD

**Issue by alhugot** [Azure/azure-storage-node#415]
Hi,
First, this is a great lib!
Second this is perhaps not the place to report it, please feel free to close the issue, but:

The base version of request specified in the package.json is affected by these security vulnerabilities:
azure-storage@2.8.0 > request@2.81.0 > hawk@3.1.3 > hoek@2.16.3                                                      https://nodesecurity.io/advisories/566  

This issue is just to request that the dependency be upgraded, if that's possible
once this one is fixed, I think:
https://github.com/request/request/issues/2874

Would also be good to have a security badge with:

snyk: https://github.com/snyk/snyk#badge
or
nsp: see https://github.com/dwyl/repo-badges

Thx
Alex

**Comment by jiacfan** [comment]
@alhugot 

Thanks for reporting this information! We'll investigate, upgrade and test the libs to avoid the security vulnerabilities. 

Thanks,
Jiachen

**Comment by pierreca** [comment]
#416 includes an upgrade to the latest request package (and another couple of vulnerabilities). Looking forward to seeing this released.

**Comment by vinjiang** [comment]
It's released already. thanks for your contribution!
