### ISSUE TITLE
Required If-Match header is not set in method ''deleteEntity" of Table Storage

### ISSUE THREAD

**Issue by arafato** [Azure/azure-storage-node#418]
Hi all, 

according to https://docs.microsoft.com/en-us/rest/api/storageservices/delete-entity1 the `If-Match` header is required. It is, however, not set by a call to `deleteEntity`.

**Comment by jiacfan** [comment]
Hi, @arafato 

In [requesthandler.js](https://github.com/Azure/azure-storage-node/blob/master/lib/services/table/internal/requesthandler.js) method `exports.constructEntityWebResource` will set If-Match header properly:
 ```
 if (operation === TableConstants.Operations.DELETE || operation === TableConstants.Operations.REPLACE || operation === TableConstants.Operations.MERGE) {
    webResource.withHeader(HeaderConstants.IF_MATCH, entityResult.getEtag(entityDescriptor) || '*');
  }
```

To delete conditionally based on etag, please set entity['.metadata']['etag'].

Best Wishes,
Jiachen

**Comment by vinjiang** [comment]
Feel free to let us know if further assistance needed.
