### ISSUE TITLE
How to use BLOB Stored Access Policy?

### ISSUE THREAD

**Issue by andrehsmendes** [Azure/azure-storage-node#419]
Hello,
I just curious, how to use the Stored access policy that you generate using the portal? See the image below.
![image](https://user-images.githubusercontent.com/2303503/36743957-90f9fc64-1bb9-11e8-9369-90bc5167fb1e.png)

I have a private blob container and blobs that i want to access using a key, instead of generating one every time i want to access it. 

Point me in the right direction please. 

Thanks!

**Comment by seguler** [comment]
This is a policy created on the service so you can group your SAS tokens, and administer using an access policy. You can later on change the start time, expiry time, or revoke anything if you think the SAS tokens are leaked.. See the full document here: https://docs.microsoft.com/en-us/rest/api/storageservices/establishing-a-stored-access-policy

**Comment by alakiran** [comment]
Is there a way to enforce through an Azure policy only to allow Private(no Anonymous Access) Public access level ?
![image](https://user-images.githubusercontent.com/31290585/40084380-90e0bc60-585c-11e8-8a69-2bca26e95d9b.png)

**Comment by XiaoningLiu** [comment]
@alakiran I didn't understand your question. But a stored access policy is used with SAS tokens.

**Comment by alakiran** [comment]
Sorry, I should have been more clear. We do not want any containers publicly available, Users who want to create the containers, the only option they can choose is to set it to Private (no anonymous access). 

Wondering if there is a way that we can use Azure Policies to enforce this.

**Comment by XiaoningLiu** [comment]
According to https://docs.microsoft.com/en-us/rest/api/storageservices/establishing-a-stored-access-policy, you cannot create a policy for a non-existing container.

If you only want to grant some users the permission to create a private container. You can directly **create service level** SAS token for a container by granting the "create" permission.

See https://docs.microsoft.com/en-us/rest/api/storageservices/constructing-a-service-sas#specifying-the-signed-identifier

**Comment by splowman-FormFast** [comment]
How do you associate a stored access policy to a SAS token.  I already know exactly what an access policy is and what a SAS token is,  However, there are no instructions anywhere that shows in detail *how* to associate them together.
