### ISSUE TITLE
Error when communicating to azure blob storage in a Worker Role

### ISSUE THREAD

**Issue by winsome** [Azure/azure-storage-node#42]
Setup:
node v0.10.21
azure-storage ^0.4.1

I have a node/express app running as a worker role and two storage containers I'm trying to stream files from. When a user requests one of the files, I pick the file from the appropriate blob container and stream it back to the user with the following code: 

    exports.getBlobToStream = function(containerName, fileName, res)
    {
        var blobService = azure.createBlobService();
        blobService.getBlobProperties(containerName, fileName, function(error, properties, status){     		        
            if(error || !status.isSuccessful)
            {
                res.header('Content-Type', "text/plain");
                res.status(404).send("File " + fileName + " not found");
            }
            else
            {
                res.header('Content-Type', properties.contentType);
                res.header('Content-Disposition', 'attachment; filename=' + fileName);
                blobService.createReadStream(containerName, fileName).pipe(res);
            }
        });
    };

I have no problems reading from one of the containers, but when trying to retrieve files from the second I get the following error:

    {
      "code": "ECONNREFUSED",
      "errno": "ECONNREFUSED",
      "syscall": "connect"
    }

Both are configured as `Public Blob` containers and are under the same storage account and are using the same access key. If it makes any difference, that same account has 6 other containers for a total of 8.

This seems similar to an issue posted on the azure-sdk-for-node package here https://github.com/Azure/azure-sdk-for-node/issues/434

The solution that resolved that bug also seems to fix mine: Removing the EMULATED variable from ServiceDefinition.csdef.

**Comment by vinjiang** [comment]
Seems resolved.
