### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by sharathbaddam** [Azure/azure-storage-node#420]
Hello, 

I get "unable to get local issuer certificate" error every time i try to post data to blob storage.

is there any way i can use the ssl certificates with blob storage ?

here the is the error message :- 
`
{ Error: unable to get local issuer certificate    at Error (native)`
`       at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)   `
`       at emitNone (events.js:86:13)`
`       at TLSSocket.emit (events.js:185:7)`
`       at TLSSocket._finishInit (_tls_wrap.js:610:8)`
`       at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }  
`

**Comment by seguler** [comment]
This is Node.js config, or SSL cert issue on your machine. You can verify this by just connecting to any HTTPS service besides Azure Storage.

**Comment by vinjiang** [comment]
Feel free to let us know if further assistance needed.

**Comment by Madaditya** [comment]
Hey, I am also running this on a Node.js application where I can access other HTTPS services without any issues. but with azure-blob-storage npm packadge I would get the below error

FetchError: request to https://<storageacccount>.blob.core.windows.net/<container>?restype=container failed, reason: unable to get local issuer certificate

**Comment by Madaditya** [comment]
> Hey, I am also running this on a Node.js application where I can access other HTTPS services without any issues. but with azure-blob-storage npm packadge I would get the below error
> 
> `FetchError: request to https://<storageacccount>.blob.core.windows.net/<container>?restype=container failed, reason: unable to get local issuer certificate.`
> 
> I tried connecting via the python library and :
> 
> `azure.core.exceptions.ServiceRequestError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)`

Disabling SSl verify was a quick workaround for me and worked!

`const myRequest = require('request').defaults({strictSSL: false})
`

**Comment by BellaLi** [comment]
This works for me.

1. set root ca for globalAgent

const trustedCa = [
    '/etc/ssl/certs/ca-certificates.crt'
];
https.globalAgent.options.ca = [];
for (const ca of trustedCa) {
    https.globalAgent.options.ca.push(fs.readFileSync(ca));
}

2. enable global for storage client.

var fileService = StorageClient.createFileService(saname,sakey,saurl)
fileService.enableGlobalHttpAgent=true
