### ISSUE TITLE
utf-8 encoding error in Chrome when loading azure-storage-blob.js

### ISSUE THREAD

**Issue by Maverick1983** [Azure/azure-storage-node#425]
Hi,
I have this error on localhost for testing upload file on Azure blob storage

![image](https://user-images.githubusercontent.com/20558694/37163897-3b63a164-22f9-11e8-8607-718354b0c082.png)

**Comment by XiaoningLiu** [comment]
Hi @Maverick1983 Which blobService API call leads to this error? Can you share a short sample which can reproduce this error?

**Comment by Maverick1983** [comment]
I have a simple HTML page on localhost and I put this code from Wiki.
The error is displayed when the page is loaded.

```
var blobUri = 'https://xxxx.blob.core.windows.net';
var blobService = AzureStorage.Blob.createBlobServiceWithSas(blobUri, token);
var file = document.getElementById('fileinput').files[0];
var customBlockSize = file.size > 1024 * 1024 * 32 ? 1024 * 1024 * 4 : 1024 * 512;
blobService.singleBlobPutThresholdInBytes = customBlockSize;
var finishedOrError = false;
var speedSummary = blobService.createBlockBlobFromBrowserFile('document', file.name, file, {blockSize : customBlockSize}, function(error, result, response) {
	finishedOrError = true;
	if (error) {
		console.log(error);
		alert("Failed");
	} else {
		alert("Upload successfully");
	}
});
```

**Comment by XiaoningLiu** [comment]
@Maverick1983 It's very strange. Your sample code is very similar to the code provided in the sample-blob.html I cannot reproduce it on my Chrome browser. My Chrome version is 64.0.3282.186 (Official Build) (64-bit) on Windows 10.

Can you try with this online sample? https://dmrelease.blob.core.windows.net/azurestoragejssample/samples/sample-blob.html

1. Enter your account name and SAS token (starting with ?)
2. Click List all containers
3. Select a container
4. Select a file on the file box
5. Click upload

![image](https://user-images.githubusercontent.com/6889160/37199222-f580d6ee-23bb-11e8-89d9-93ab0812d33b.png)

**Comment by XiaoningLiu** [comment]
Also, I think it's a incorrect encoding issue with your environment. You can find that there is no such regular expression mentioned in your error message.

### All regular expressions:
![image](https://user-images.githubusercontent.com/6889160/37200055-99fe3e80-23be-11e8-9918-838b71786e1d.png)

### The regular expression mentioned in your error message:
![image](https://user-images.githubusercontent.com/6889160/37200088-b85294c6-23be-11e8-9bb3-e696f6ff56ca.png)

**Comment by XiaoningLiu** [comment]
Please check azure-storage.blob.js is already utf-8 encoded and decoded in your Chrome.

There are some ways to enforce utf-8 in Chrome mentioned in this issue https://github.com/babel/babel/issues/340

**Comment by Maverick1983** [comment]
@XiaoningLiu Now it's ok.
