### ISSUE TITLE
Why are there _ and $ in the response JSON from tables?

### ISSUE THREAD

**Issue by danielsada** [Azure/azure-storage-node#426]
I'm using queryEntities from the table service, and I get this json object back.
```  { PartitionKey: { '$': 'Edm.String', _: 'Estimator' },
    RowKey: { '$': 'Edm.String', _: 'DeveloperTimes' },
    Timestamp: { '$': 'Edm.DateTime', _: 2018-02-26T05:56:37.434Z },
    Department: { _: '' },
    DesignHours: { _: 0 },
    DeveloperHours: { _: 0 },
    TaskType: { _: '' },
    TestHours: { _: 0 },
    '.metadata': { etag: 'W/"datetime\'2018-02-26T05%3A56%3A37.434867Z\'"' } } ] 
```

Why do we have _ and $ for names for the values and types? What is the rationale behind this? Should I always do....

`response["entries"][0]["DesignHours"]["_"]`
and
```
for(var elem of response["entries"]){
      console.log(elem["DesignHours"]["_"]
}
```
?

Thanks for taking the time to answer to this!

**Comment by jiacfan** [comment]
Hi, @danielsada 

Yes. It's by design. Using _ and $ as key is considering these two names are of less possibility to get collision.

For using, please refer to [tablequerysample.js](https://github.com/Azure/azure-storage-node/blob/master/examples/samples/tablequerysample.js).

Best Wishes,
Jiachen
