### ISSUE TITLE
Object doesn't support this property or method : XMLHttpRequest onerror

### ISSUE THREAD

**Issue by Rajaseeman** [Azure/azure-storage-node#427]
I'm trying to integrate Salesforce VF page(using a Standard controller) with Azure, IE 11 throws below error :

**Object doesn't support this property or method**

But the same page works well on chrome. The following is the library that I have included on the page. https://dmrelease.blob.core.windows.net/azurestoragejssample/bundle/azure-storage.common.js

Error happens in the below code:

```
xhr.onerror = function () {
    if (self._destroyed)
        return
    self.emit('error', new Error('XHR error'))
}
```

https://stackoverflow.com/q/49191475/9466919

**Comment by XiaoningLiu** [comment]
Hi @Rajaseeman , it maybe a compatibility issue for IE11. To help us locate the issue, please provide following messages.

1. What's your azure-storage.blob.js & azure-storage.common.js version? 
2. What's your IE11 version number?
3. Does latest online samples, such as https://dmrelease.blob.core.windows.net/azurestoragejssample/samples/sample-blob.html sample work on your IE11 environment?
4. Can you share a minimum reappearance sample which can stably reproduce this issue? You can share it to us with tools like https://jsfiddle.net/
5. Is able for you to upgrade to latest IE11 version? Currently latest IE11 (11.248.16299, 11.0.51) should work well.

**Comment by XiaoningLiu** [comment]
BTW, the source code which you mentioned in your Stack-overflow comments:

```
I have figured out that the xhr is not initialized in the following code. var xhr = self._xhr = new global.XMLHttpRequest() try { xhr.open(self._opts.method, self._opts.url, true) } catch (err) { process.nextTick(function () { self.emit('error', err) }) return } 
```

belongs to https://github.com/jhiesey/stream-http/ which should provide compatibility for IE11.

https://github.com/jhiesey/stream-http/blob/920dd3cd485220a30c8937fa30c1630b34701df1/lib/request.js#

**Comment by vinjiang** [comment]
Feel free to let us know if further assistance needed.
