### ISSUE TITLE
The blob is empty when using createBlockBlobFromLocalfile to upload a file at 2nd time.

### ISSUE THREAD

**Issue by haiyingdotwang** [Azure/azure-storage-node#428]
I am having a test code which uploads the file to the storage account by using createBlockBlobFromLocalfile. There is no issue when I first call it to upload a binary file (< 10KB). But if I call it twice, I see the blob size is 0  for the 2nd file. If I wait for a long while(> 1 hour) to call this function, the 2nd upload will be success, i.e. the blob size is correct as I check the storage account. I wonder if there is any limitation to call createBlockBlobFromLocalfile.  The test code is as below:

    blobService.createContainerIfNotExists(containerName, {publicAccessLevel : 'blob'}, function(error) {
        if (error) return console.log(error);
        blobService.createBlockBlobFromLocalFile(
                containerName, fileName, fileUploaded, function(err, result, response ) {
            if (err) throw err;
            console.log('response: ', response);
       });
    });

**Comment by XiaoningLiu** [comment]
@haiyingdotwang 

There is no limitation to avoid calling ```createBlockBlobFromLocalfile``` twice. But to avoid race condition, you need make sure the second call is **AFTER** first callback is returned. This is, you'd better not upload to a same blob at the same time concurrently with this API.

**Comment by haiyingdotwang** [comment]
I don't think there is a race condition. My test code basically creates a watcher to a folder, once there is a new binary file copied to that folder, the test code will upload the binary from that folder to the storage account by calling createBlockBlobFromLocalfile.  The problem is: I copied file#1 to the folder, and I saw file#1 was in azure storage account quite soon with the correct file size. After a couple of minutes, sometimes even longer than 10 minutes, I copied the file#2 to the folder, then I saw file#2 in the storage account but the file size 0. Both file#1 and file#2 are using the same container, but different blob names.

**Comment by XiaoningLiu** [comment]
@haiyingdotwang I cannot find the root cause from the description. It sounds like the 2nd file called ```createBlockBlobFromLocalfile``` and created a blob, but the data doesn't send to the server. Does callback method of 2nd file uploading get called? Any errors?

Can you help provide a minimum sample which could reproduce this issue? It could help us locate the issue.

**Comment by haiyingdotwang** [comment]
Thanks a lot for all your answers! I wrap up the code to call createBlockBlobFromLocalfile with setTimeout(), and I see the 2nd file is uploaded successfully.
