### ISSUE TITLE
Javscript Client Library upload with metadata

### ISSUE THREAD

**Issue by damaniosif** [Azure/azure-storage-node#429]
Hi,

When i upload a blob with javascript client library the metadata ars saved with lowercase keys always. There will be a fix for this please?

Thank you

**Comment by XiaoningLiu** [comment]
@damaniosif It's a limitation from browsers, see https://github.com/mirror/chromium/commit/99c274ae8e7d366261dcfb89e0b98e733fb9d5f4

Different browsers currently have different behaviors for cases of HTTP headers sending to servers.
