### ISSUE TITLE
Azure Storage JavaScript client library - strange file names in .zip

### ISSUE THREAD

**Issue by klemensz** [Azure/azure-storage-node#431]
When I download the library from https://aka.ms/downloadazurestoragejs and extract it (on macOS) the filenames look like this: `azurestoragejs-0.2.8-preview.15\bundle\azure-storage.blob.min.js`. 

Is that how it's supposed to be? It looks to me like these should be folders? If I put them in a script tag, the backslashes are interpreted as folders and it won't work.

**Comment by XiaoningLiu** [comment]
@klemensz Yes, they should be folders. Thanks for reporting! The zip file was bundled in Windows command-line, there are some compatibility issues when unzip in MacOS.

We will update the download link with a zip file which works on MacOS. Before that, as a workaround, you can install 3rd unzip APPs on MacOS such as "The Unarchiver" to unzip this file. Or you can  download from following temporary link.

[azurestoragejs-0.2.8-preview.15.zip](https://github.com/Azure/azure-storage-node/files/1846215/azurestoragejs-0.2.8-preview.15.zip)

**Comment by klemensz** [comment]
Thanks!

**Comment by XiaoningLiu** [comment]
References:

https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/mitigation-ziparchiveentry-fullname-path-separator

https://stackoverflow.com/questions/27289115/system-io-compression-zipfile-net-4-5-output-zip-in-not-suitable-for-linux-mac
