### ISSUE TITLE
Upload larger blobs with sas token client library.

### ISSUE THREAD

**Issue by TheAn4rch1st** [Azure/azure-storage-node#432]
I use the following function to upload blob data to azure (Largely the same as the example).
```javascript
uploadToAzure(fileid, sas, file){
      let blobService = AzureStorage.Blob.createBlobServiceWithSas(this.settings.azureBlobEndpoint, sas);
      let customBlockSize = file.size > 1024 * 1024 * 32 ? 1024 * 1024 * 4 : 1024 * 512;
      blobService.singleBlobPutThresholdInBytes = customBlockSize ; 
      let options = {
        blockSize : customBlockSize
      } 
      return blobService.createBlockBlobFromBrowserFile(
        this.settings.azureBlobContainer, fileid.toString(), file, file.size, this.uploadToAzureCallback
      );
  }
```
For smaller files, this works fine. 

However for larger files (>singleBlobPutThresholdInBytes), the library tries to chunk the blob into smaller parts. This it where it goes wrong in my case, as some chunks do no pass the authorization. An `AuthorizationPermissionMismatch` is returned from azure, with the message: `This request is not authorized to perform this operation using this permission. `

In the image below, you can see that some chunks do authenticate correctly, whilst others do not. 

![image](https://user-images.githubusercontent.com/18576933/38506455-3748c39a-3c1a-11e8-8994-1a22b5939981.png)

Is this a bug, or I am doing something wrong?

**Comment by XiaoningLiu** [comment]
Hi @TheAn4rch1st 

I don't think it's a bug. Please check with your SAS token and CORS settings to make sure:

1. SAS token has been granted the corresponding permission to update and put a blob
2. CORS should allow PUT method

You can try to generate an account level SAS token with full permissions for testing purpose.

**Comment by TheAn4rch1st** [comment]
Thanks a lot, I forgot to add the write permissions to the sas token.

I do want to point out though, I had to add the module.exports.createBlobServiceWithSas in the library in order for this to work.

**Comment by XiaoningLiu** [comment]
Hi @TheAn4rch1st 

Can you give more details about "add the module.exports.createBlobServiceWithSas in the library in order for this to work"?

If it's a bug, we need fix it.
