### ISSUE TITLE
When i upload a blob with javascript client library returns ResourceNotFound exception

### ISSUE THREAD

**Issue by AmrTealeb** [Azure/azure-storage-node#435]
I use javascript client library to upload file using this code
var speedSummary = blobService.createBlockBlobFromBrowserFile(container_name, file.name, file, options, 
     function (error, result, response) {        
            if (error) {
                alert('Upload failed, ' + error.message);
                console.log(error);        
            } else {        
                setTimeout(function () { 
                    alert('Upload successfully!');
                }, 1000);        
            }
        });

but i get error.code = "ResourceNotFound", error.statusCode = 404 and error.message = ""The specified resource does not exist.
RequestId:56b699c1-f01e-00b1-4984-d58da1000000
Time:2018-04-16T13:12:45.8650452Z""

Access policy for the container is : Container (Anonymous accessfor containers and blobs)

**Comment by XiaoningLiu** [comment]
Hi @AmrTealeb 

You can enable anonymous, public **read** access to a container and its blobs in Azure Blob storage. By doing so, you can grant **read-only** access to these resources without sharing your account key, and without requiring a shared access signature (SAS).

Sse https://docs.microsoft.com/en-us/azure/storage/blobs/storage-manage-access-to-resources

**Comment by AmrTealeb** [comment]
How i can upload file if i have SasToken?

**Comment by XiaoningLiu** [comment]
Hi @AmrTealeb 

I think your code is ok to work with a SAS token.

You can test your SAS token in following online sample provided:
- https://dmrelease.blob.core.windows.net/azurestoragejssample/samples/sample-blob.html

There maybe something wrong with your SAS token. Please make sure:
1. CORS settings of your storage account have been enabled (see above sample)
2. SAS token is starting with '?' and granted with corresponding permissions
3. You need setup a localhost HTTP server for IE11 and Chrome 56+ when testing on your local machine
4. SAS token start time and expiry time is OK (pay attention to your timezone, by default they are UTC)

The easily way for testing is to generate a account level SAS token in your Azure Portal or Storage Explorer with full permissions, like:

![image](https://user-images.githubusercontent.com/6889160/38845628-f5e6e88e-422a-11e8-8c24-8cf8524a9c9c.png)
