### ISSUE TITLE
Possibility of generating an SAS url with the custom domain mapping

### ISSUE THREAD

**Issue by Kannaj** [Azure/azure-storage-node#437]
Hello,

I've mapped a custom domain to azure blob storage URL. When i execute the below code

```
                            var token = blobService.generateSharedAccessSignature('xxxx', fileName, sharedAccessPolicy)
                            var sasUrl = blobService.getUrl('xxxx', fileName, token);
```

i get a URL with the standard azure ip address (https://xxx.blob.core.windows.net//xxx) - is it possible to generate a URL with the custom domain mapping or should i be doing it manually?

Thanks

**Comment by jiacfan** [comment]
Hi, @Kannaj 

When generating [Account SAS](https://docs.microsoft.com/en-us/rest/api/storageservices/constructing-an-account-sas) or [Service SAS](https://docs.microsoft.com/en-us/rest/api/storageservices/constructing-a-service-sas), the generating logic need account name or canonicalized resource name.

To get a SAS URL with custom domain, please try to generate the SAS with original account URL, e.g. https://yourstorageaccount.blob.core.windows.net/... which includes essential info, i.e. accountname and etc for generating SAS, and then please try to use the generated SAS token, i.e.: ?[SAS-token]. Concatenate the SAS token to your custom domain URL's query part, and have a try.

If there is any further problem, welcome further discussion.

Best Wishes,
Jiachen

**Comment by vinjiang** [comment]
Please let us know if you need further assistance on this.

**Comment by oreporan** [comment]
Hi, same issue here
Not sure what @jiacfan suggested here. 
I'm generating an image URL and I would like to show the custom domain instead of the original blob url (`blob.core.windows.net`)
Do I need to replace this manually?
