### ISSUE TITLE
Using BlobService.getBlobToStream from javascript client SDK

### ISSUE THREAD

**Issue by AmrTealeb** [Azure/azure-storage-node#440]
I am trying to use getBlobToStream from browser, i use the following code but i don't know what to pass here as stream parameter
`blobService.getBlobToText(container, blob, outStream, options, function (error, serverBlob)  {
            if (error) {

            }
            else {

            }
        })`

**Comment by XiaoningLiu** [comment]
@AmrTealeb Please find following examples:

#### `createReadStream` from an existing blob and use event listener to receiving data
```
let readStream = blobService.createReadStream(container, 'hello.txt', (err, res) => {if(!err) {console.log('createReadStream() successfully');}});
readStream.on('data', data => {console.log(data);});
```

#### `getBlobToText` downloads a blob to string
```
blobService.getBlobToText(container, 'hello.txt', (err, res, resp) => {
	if (!err) {
		console.log(res);
    }
});
```

#### `createWriteStreamToBlockBlob` creates a writeStream to an un-existing blockblob and `getBlobToStream` can write an existing blob to the writeStream. It's actually a live copy.
```
let writeStreamToNewBlob = blobService.createWriteStreamToBlockBlob(container, 'newBlob', (err, res) => {if (!err) {console.log('createWriteStreamToBlockBlob successfully!');};});
blobService.getBlobToStream(container, 'hello.txt', writeStreamToNewBlob, (err, res) => {if (!err) {console.log('getBlobToStream successfully');};});
```
