### ISSUE TITLE
Pagination for table storage queries

### ISSUE THREAD

**Issue by snoopdouglas** [Azure/azure-storage-node#441]
Would it be possible to implement either one of:

* An offset parameter for `top`, such that I can call `query.top(M, N)` to get the top `M` results, offset by `N`, similar to SQL `LIMIT`/`OFFSET`;
* Or, a method that could be called like `query.from(rowKey)` that returns results starting from (but possibly excluding) the given `rowKey` (which may be better for very dynamic datasets)

For context, I'm trying to implement an Azure Functions CRUD REST API with pagination such that minimal amounts of memory, bandwidth, etc. are needed.

**Comment by snoopdouglas** [comment]
Related: https://github.com/Azure/azure-storage-node/issues/243

It appears there's a `continuationToken` that could be used, but this is less than ideal due to being stateful; if I were to use this in a Functions app, I'd have to keep making queries until I reached the Nth page.

**Comment by XiaoningLiu** [comment]
Hi @snoopdouglas 

`Query entity` REST API doesn't provide `offset` query parameter. In order to provide `offset` support, Azure Functions need to downloads the whole `M` results and filter `N` results.
https://docs.microsoft.com/en-us/rest/api/storageservices/query-entities

However,  `continuationToken` maybe not `safe`. 
https://stackoverflow.com/questions/21548597/azure-table-storage-continuation-token-lifetime

>From what I understand about continuation token is that it is a marker which if used in a query against table storage will return next set of results from that marker. If I'm not mistaken, you could keep these tokens as long as you want however there's no guarantee that same results will be returned. For example, if new entities are added or some old entities are deleted then you may get different set of result back. Furthermore, table storage service keeps on rearranging the data. If that happens, even though you have not added/removed any entities you may get different set of result back.

**Comment by XiaoningLiu** [comment]
Yeah, for feature request, please go to https://feedback.azure.com/forums/217298-storage and create a new request (or find similar request), and then vote for it!

**Comment by snoopdouglas** [comment]
Will do, thanks!
