### ISSUE TITLE
The generateAccountSharedAccessSignature does not provide a valid sharedaccesssignature

### ISSUE THREAD

**Issue by grubb-2112** [Azure/azure-storage-node#444]
When using the SharedAccessSignature created with the generateAccountSharedAccessSignature method from the sdk, I was receiving an error of 'signature does not match'. I then created my own SharedAccessSignature by following the instructions in azure storage api docs, and it works.

Not sure what I did different, It looks like I am doing the same thing as the sdk.

I'm inserting the code I created. Hopefully, it will help in fixing the method in the sdk.

`			

                    const start = new Date(new Date().getTime() - (15 * 60 * 1000));
			const end = new Date(new Date().getTime() + (30 * 60 * 1000));

			const accountname = process.env.AZURE_STORAGE_ACCOUNT;
			const signedpermissions = 'rwdlac';
			const signedservice = 'b';
			const signedresourcetype = 'co';
			const signedstart = truncateIsoDate(start);
			const signedexpiry = truncateIsoDate(end);
			const signedIP = '';
			const signedProtocol = 'https';
			const signedversion = '2017-07-29';

			const StringToSign =
				accountname + '\n' +
				signedpermissions + '\n' +
				signedservice + '\n' +
				signedresourcetype + '\n' +
				signedstart + '\n' +
				signedexpiry + '\n' +
				signedIP + '\n' +
				signedProtocol + '\n' +
				signedversion + '\n';

			const key = new Buffer(process.env.AZURE_STORAGE_ACCESS_KEY, 'base64');
			let sig = crypto.createHmac('sha256', key).update(StringToSign, 'utf8').digest('base64');

			let sas =
				`sv=${(signedversion)}&ss=${(signedservice)}&srt=${(signedresourcetype)}&sp=${(signedpermissions)}&se=${encodeURIComponent(signedexpiry)}&st=${encodeURIComponent(signedstart)}&spr=${(signedProtocol)}&sig=${encodeURIComponent(sig)}`;

			const sharedAccessSignature: SharedAccessSignature = {
				url: 'https://' + process.env.AZURE_STORAGE_ACCOUNT + '.blob.core.windows.net',
				sas: sas
			};

			const sharedAccessPolicy: storage.common.SharedAccessPolicy = {
				AccessPolicy: {
					Permissions: 'rwdlac',
					Services: 'b',
					ResourceTypes: 'co',
					Start: start,
					Expiry: end,
					Protocols: 'https'
				}
			};

			const asas = storage.generateAccountSharedAccessSignature(process.env.AZURE_STORAGE_CONNECTION_STRING, process.env.AZURE_STORAGE_ACCESS_KEY, sharedAccessPolicy);

			console.log(sas);
			console.log(asas);
```
function truncateIsoDate(date: Date): string {
			return date.toISOString().substring(0, date.toISOString().lastIndexOf('.')) + 'Z';
		}
```

```
sv=2017-07-29&ss=b&srt=co&sp=rwdlac&se=2018-04-27T17%3A51%3A13Z&st=2018-04-27T17%3A06%3A13Z&spr=https&sig=rgI3IGWo63Rqipy%2FypPeQBxsCqAqYfpdd9h9qZheh7g%3D

sv=2017-07-29&ss=b&srt=co&sp=rwdlac&st=2018-04-27T17%3A51%3A13Z&se=2018-04-27T17%3A06%3A13Z&spr=https&sig=N00jIL2RSVvQl1glpb4nM%2Fk%2F3fCA6TpcKFDbT%2F0l59k%3D
```

**Comment by jiacfan** [comment]
Hi, @grubb-2112 

From the latest SAS token you pasted, I noticed:
SAS 1: sv=2017-07-29&ss=b&srt=co&sp=rwdlac&**se=2018-04-27T17%3A51%3A13Z&st=2018-04-27T17%3A06%3A13Z**&spr=https&sig=rgI3IGWo63Rqipy%2FypPeQBxsCqAqYfpdd9h9qZheh7g%3D

SAS 2: sv=2017-07-29&ss=b&srt=co&sp=rwdlac&**st=2018-04-27T17%3A51%3A13Z&se=2018-04-27T17%3A06%3A13Z**&spr=https&sig=N00jIL2RSVvQl1glpb4nM%2Fk%2F3fCA6TpcKFDbT%2F0l59k%3D

Please diff between the first vs second SAS: "se and st are reversed". Could you provide the parameters you are using during generating SAS with node.js SDK, I'm suspecting whether se and st are provided in reverse order. If so, it would cause SAS generated incorrectly.

Thanks
Jiachen

**Comment by grubb-2112** [comment]
I noticed that as well and tried reversing it, but it still didn't work. I had created an account sas on the azure portal. I then made mine to match that one since it worked.

The  version I'm using is azure-storage@2.8.1 with no customization. The parameters are as shown in the code snippet. The connection string and access key are correct and the same for both. Actually, only the account name and the access key are used and both have been double checked.

**Comment by jiacfan** [comment]
Hi, @grubb-2112  

Is there any update for the issue after our last reply? And does the issue still not solved in your side? Otherwise we'll close this issue.

Thanks,
Jiachen

**Comment by kavitha1991dhiman** [comment]
This issue still exists. The SDK still prints st first. I am using the latest "azure-storage": "^2.10.3"
Without SDK - (working)
sv=2018-03-28&ss=b&srt=co&sp=rwdlac&se=2019-07-20T00%3A00%3A00Z&st=2019-07-19T00%3A00%3A00Z&spr=https&sig=i6lWiTGqPolcRwpEYsmg05%2B5ngSFxp%2BVmo%2BlPtOj59E%3D

With SDK - (Not Working)
sv=2018-03-28&ss=b&srt=sco&sp=rwc&st=2019-07-19T00%3A00%3A00Z&se=2019-07-20T00%3A00%3A00Z&spr=https&sig=%2FId7%2B%2Bmf8z671rUaJhbnLkw1HdJIfCWeuU2gN161v8E%3D

**Comment by XiaoningLiu** [comment]
@jiacfan
