### ISSUE TITLE
Do not throw an exception when File is not Found

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [Azure/azure-storage-node#445]
When I do> blobService.getBlobToText and the blob is not found, you are throwing this exception:

HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).

This is unnecessary because my code already receives at the callbackfunction an err and response parameter with the needed information to handle the situation, but my code is unable to catch this exception since it is thrown not on the "calling thread" but on the "callback thread" so to speak. This means that the exception is shown at the browsers console even if I dont want to. 

At a system handling many files with many of them possibly not existing this can be anoying since it prevets me to use the console to log what I do need to be logged. 

My guess is that throwing this exception is unnecesary and it just bothers, since the callback has what we need.

**Comment by XiaoningLiu** [comment]
Hi @Luis-Fernando-Molina 

This library will only pass error from callback, and doesn't throw error.

If you refer to the 404 error message displayed in the browser console, such as Chrome Console.

>In the chrome developer tools, if you click on the gear in the top right, then scroll down, into the console section, there is a "Hide network messages setting".

![image](https://user-images.githubusercontent.com/6889160/39503697-e87e0de6-4df9-11e8-8de8-39fe3fd1a28d.png)

**Comment by Luis-Fernando-Molina** [comment]
Hi XiaoningLiu, thanks for the clarification.
