### ISSUE TITLE
"The provided account key ... is not a valid base64 string"

### ISSUE THREAD

**Issue by GiraffeSlacks** [Azure/azure-storage-node#446]
Hello.

I'm trying to get started with this module (new to Nodejs in general) and I'm getting the following error right off the bat: (I've already rotated the key so it's fine to be shown here.)

    The provided account key AZURE_STORAGE_ACCESS_KEY: ER8yNA/969WJkzuW3qPIPV0cnhcBTRjeX/7Pyk+okRzOfNHfZcYNnk0f/R0db1QQ5v6d/dIUVVCGtbjqpPQA4Q== is not a valid base64 string.

I'm probably doing something wrong but I couldn't find anything in the documentation that says I need to process the key first. It would be great if this module was aware of the format of the keys provided by the Azure portal and accepted them as-is.

**Comment by jiacfan** [comment]
Hi, @GiraffeSlacks 

Nothing should be proceeded before using the key, It might be related to the way setting the environment variable. Could you share the way you are setting env vars? And what's the platform and environment you are using?

The logic to valid a key is as following:
```
exports.isBase64Encoded = function (key) {
  var isValidBase64String = key.match(/^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{4}|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)$/);

  if (isValidBase64String) {
    return true;
  } else {
    throw new SyntaxError('The provided account key ' + key + ' is not a valid base64 string.');
  }
};
```

And normally, the key should pass the matching.

Best Wishes,
Jiachen

**Comment by GiraffeSlacks** [comment]
User error. Really sorry for wasting your time!

**Comment by pankajkhali14** [comment]
@GiraffeSlacks can you please what was missing . how it get resolved?
