### ISSUE TITLE
Large file upload to azure

### ISSUE THREAD

**Issue by SriChindain** [Azure/azure-storage-node#447]
I am referring the upload code as per the below link:
https://dmrelease.blob.core.windows.net/azurestoragejssample/samples/sample-blob.html

I am generating the SAS token at the server side and passing it on to client side. Still i am not happy exposing SAS to user in client side. Is there any better way to do it[I am looking for uploading large files upto 8GB to Azure with progress being able to track]?

**Comment by XiaoningLiu** [comment]
Hi @SriChindain 

I'm afraid that you have to expose "something" to client side if you want a **direct upload connection between client to Azure server**.

"something" can be an Azure Storage key, a SAS token or OAuth token (will support soon). They are used to make sure the user has **permission** to upload a blob to Azure server.

SAS is one of the best choices here.  You can try to generate and grant only the permissions client needed. Such as create a Service Level SAS for a specific blob under a specific container, in a limited time range, or even IP ranges. Grant only the "Create" and "Write" permission are enough for uploading a 8GB block blob.
