### ISSUE TITLE
Is there any method or best practice to check an async copy status from the SDK?

### ISSUE THREAD

**Issue by ruudy-es** [Azure/azure-storage-node#448]
We have noticed that the startCopyBlob just returns a 202 informing us about the correct storage of the copy order.

Like we are copying files between blobs to later delete the file from the origin blob, we need to know when a copy has been end correctly or not.

Thanks!

**Comment by XiaoningLiu** [comment]
Hi @ruudy-es 

Please use `getBlobProperties` for destination blob in a copy operation.

-ms-copy-status: <pending &#124; success &#124; aborted &#124; failed> | Version 2012-02-12 and newer. State of the copy operation identified by x-ms-copy-id, with these values:- success: Copy completed successfully.- pending: Copy is in progress. Check x-ms-copy-status-description if intermittent, non-fatal errors impede copy progress but don’t cause failure.- aborted: Copy was ended by Abort Copy Blob.- failed: Copy failed. See x-ms-copy-status-description for failure details.This header does not appear if this blob has never been the destination in a Copy Bloboperation, or if this blob has been modified after a completed Copy Blob operation using Set Blob Properties, Put Blob, or Put Block List.
-- | --




https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-properties
