### ISSUE TITLE
Convenience query method to traverse the continuation token suggestion

### ISSUE THREAD

**Issue by freakyfriday** [Azure/azure-storage-node#45]
Queries to Azure tables may occasionally return a continuation token for a variety of reasons (see http://blog.smarx.com/posts/windows-azure-tables-expect-continuation-tokens-seriously). The following is an example of how to use the queryEntitiesContinuation extension method to automatically retrieve data when a continuation token is present.

It would be great to see something like this added to the TableService methods so we can automatically traverse the continuation token.

```
var azure = require('azure-storage');

azure.TableService.prototype.queryEntitiesContinuation = function (tableName, query, maxContinuationCount, callback) {

    var tableService = this;
    var data = new Array();
    var countinuationCount = 0;
    var operation = function (tableName, query, continuationToken) {
        tableService.queryEntities(tableName, query, continuationToken, function (error, result) {

            if (!error) {
                if (result.continuationToken) {

                    result.entries.forEach(function (entry) {
                        data.push(entry);
                    });

                    if (maxContinuationCount === null || countinuationCount < maxContinuationCount) {
                        ++countinuationCount;
                        //update top
                        if (query._top !== null) {
                            query._top = query._top - data.length;
                            if (query._top !== 0) {
                                operation(tableName, query, result.continuationToken);
                            } else {
                                callback(error, result);
                            }
                        } else {
                            operation(tableName, query, result.continuationToken);
                        }
                    } else {
                        callback(error, result);
                    }


                } else {

                    data.forEach(function (entry) {
                        result.entries.push(entry)
                    });

                    callback(error, result);
                }
            } else {

                result.entries.push(data);
                callback(error, result);
            }
        });
    };

    operation(tableName, query, null);
};

module.exports = azure;

```

**Comment by hasonmsft** [comment]
@freakyfriday , thank you for your suggestion. We'll evaluate this and get you updated when it's available.

**Comment by trevorfrese** [comment]
@hasonmsft and updates on this? 
I have the same issue and I'm attempting to use @freakyfriday's solution

**Comment by bakotaco** [comment]
I 'solved' this with the following helper function which also conveniently return a Promise.

`const queryAll = tableName => {
  var query = new TableQuery();
  const queryEntities = continuationToken =>
    new Promise((resolve, reject) => {
      tableService.queryEntities(tableName, query, continuationToken, (error, result, response) => {
        if (error) {
          reject(error);
        } else {
          if (result.continuationToken) {
            queryEntities(result.continuationToken).then(nextResult => {
              resolve(result.entries.concat(nextResult));
            })
          } else {
            resolve(result.entries);
          }
        }
      });
    });
  return queryEntities(null);
};`
