### ISSUE TITLE
IE10 compatibility with azure-storage.blob.js

### ISSUE THREAD

**Issue by SriChindain** [Azure/azure-storage-node#451]
I am facing the error on the below line 
var BlobService = require('../lib/services/blob/blobservice.browser'); 
while i am trying to run the code with IE10 compatibility in the file azure-storage.blob.js.

while i am calling AzureStorage.Blob.createBlobServiceWithSas() method, the blob is returned undefined.

Since i am embedding the portion inside the iframe of the sharepoint page[provider hosted app], i cant change the compatibility to IE11. The code works perfectly if i open directly in IE11.

Suggest the resolution to make the azure helper work in IE10.

**Comment by XiaoningLiu** [comment]
Hi @SriChindain , sorry that we only support IE from IE11. BTW what's the error message?

**Comment by SriChindain** [comment]
I have pasted the details of the exception below. Due to which the  AzureStorage.Blob.createBlobServiceWithSas is giving the undefined error. Let us know if there is any way or a workaround that we can use this azure-storage.blob.js in provider hosted app in sharepoint 2013(iframe whose parent loads in IE10) to make this work. Looking forward for your response

Line:
29 var BlobService = require('../lib/services/blob/blobservice.browser'); 
File:
azure-storage.blob.js 
Error:
This browser lacks typed array (Uint8Array) support which is required by `buffer` v5.x. Use `buffer` v4.x if you require old browser support.

**Comment by XiaoningLiu** [comment]
@SriChindain Seems we should we a older version of `buffer`. 

Posted a question for the `buffer` module. https://github.com/feross/buffer/issues/198

**Comment by XiaoningLiu** [comment]
@SriChindain There is a workaround which can downgrade `bufferx5` to `bufferx4` which supports IE10. Please follow following steps to build JS files supporting IE10:

1. Download/Clone this repo to your local disk
2. Download and install Node.js
3. Go to `package.json` and set `browserify` version to `13.3.0`
![image](https://user-images.githubusercontent.com/6889160/40402308-732b4bdc-5e7d-11e8-9dc3-3c725260d040.png)
4. npm install
5. npm run genjs

**Comment by cpwinn** [comment]
Thanks. I'm also developing for SharePoint so I'm stuck with IE10 mode. The steps above do the trick but it would be nice if the master branch of this library supported IE10. Thanks for the help.

**Comment by SriChindain** [comment]
I am building a provider hosted sharepoint app in Visual studio. I am not doing npm build and i do not have package.json to do the changes you suggested.

Also current version of sharepoint we are using in 2013, which has meta tags in the master page with IE10 compatibility set. So, we cant change it.

Can you suggest a workaround which can be worked out in this scenario?

**Comment by cpwinn** [comment]
Your app doesn't need to have npm since the step above will just output a JS file that you can build once then copy into your app.  Here is the IE10 compatible JS file that is produced.
[azure-storage.blob-ie10.min.zip](https://github.com/Azure/azure-storage-node/files/2115858/azure-storage.blob-ie10.min.zip)

**Comment by XiaoningLiu** [comment]
thanks @cpwinn for sharing!

**Comment by SriChindain** [comment]
@XiaoningLiu ,

should i follow the same workaround for the future release as well, or this will be taken care of?

Thanks,

**Comment by XiaoningLiu** [comment]
You need to follow the process to generate IE10 compatible JS files. Sorry for that.
