### ISSUE TITLE
speedSummary.on('progress', function(){}) => .on is not a function

### ISSUE THREAD

**Issue by ckay1988** [Azure/azure-storage-node#456]
Hi guys,

I tried to implement your recent change with eventEmitter to track the uploading status of the blob.
Here's my code ( its an angular 5 app).
```
var speedSummary = blobService.createBlockBlobFromBrowserFile(containerName
        , 'blackbox/' + this.blackBoxFile.name
        , this.blackBoxFile
        , {blockSize : customBlockSize}
        , function(error, result, response) {       
      if (error) {
        that.uploadStatus = -1;
      } else {
        that.pipeLineJobService.start(14, 'blackbox', containerName)
        .subscribe(resp => {
          if (resp) {
            that.uploadStatus = 100;
          } else {
            that.uploadStatus = -1;
          }
        });
        
      }
     });
     speedSummary.on('progress', function () {
      console.log(speedSummary.getCompletePercent());
      var process = speedSummary.getCompletePercent();
      that.uploadStatus = process;
     });
```

It's saying that:

> ERROR TypeError: speedSummary.on is not a function

Can you help me on that? I cloned the version 2.8.3 and built the files on my own.

BR
Christian

**Comment by XiaoningLiu** [comment]
@ckay1988 Please try 2.9.0-preview.

**Comment by ckay1988** [comment]
@XiaoningLiu where can I find that?

**Comment by XiaoningLiu** [comment]
Published to npm just now :)
https://www.npmjs.com/package/azure-storage

**Comment by XiaoningLiu** [comment]
Sorry, I didn't notice that you are using under browsers. Please wait some time until we published JS files to https://aka.ms/downloadazurestoragejs

**Comment by ckay1988** [comment]
yes :). Okay I will wait - till' then I'll use the workaround of v2.8.3. Thx!

**Comment by XiaoningLiu** [comment]
@ckay1988 progress support is released, please try again

**Comment by ckay1988** [comment]
@XiaoningLiu works now! Thx a lot!
