### ISSUE TITLE
AppendBlob

### ISSUE THREAD

**Issue by shiwaniB** [Azure/azure-storage-node#458]
Hi,

I want to upload video file as append blob using Nodejs code.

I used **createAppendBlobFromLocalFile** method to create a new blob , and then appended other video using **appendFromLocalFile**  method.

It works with text file but not with video file.
Any help will be appreciated.

Thanks

**Comment by jiacfan** [comment]
@shiwaniB 

I see the issue is closed, welcome discussion if there is any further problem.

Best Wishes,
Jiachen
