### ISSUE TITLE
Append blob issue

### ISSUE THREAD

**Issue by shiwaniB** [Azure/azure-storage-node#459]
Hi,
I want to upload video file as append blob using Nodejs code.

I am using below code

var azure = require('azure-storage');
var blobService = azure.createBlobService(blobStorageAccountName, blobStorageAccessKey, blobUri);

fs.createReadStream('./test1.avi').pipe(blobService.createWriteStreamToNewAppendBlob(blobContainerName, 'abcdefgh'));

fs.createReadStream('./test2.avi').pipe(blobService.createWriteStreamToExistingAppendBlob(blobContainerName, 'abcdefgh'));

It gives success as well as blob size get increase on the portal. but when I download the blob, it seems that only first video get displayed in media player.

Any help will be appreciated.

Thanks

**Comment by jiacfan** [comment]
Hi, @shiwaniB:

For "it seems that only first video get displayed in media player", different video format should have different metadata info saved with video data, I'm not expert in .avi format, and guessing the metadata is  limiting the video length, so the second video is not shown with downloaded blob. Please ensure the video data is in one of the streaming video type that can meet your requirement.

As you described, API call "gives success as well as blob size get increase on the portal". To ensure the data is uploaded/downloaded correctly, we commonly use MD5. To validate if the data is fully uploaded, please try to calculate MD5 of two concatenated video locally, and compare the MD5 you calculated with the MD5 value calculated by storage SDK. To validate the data is fully downloaded correctly, please use disableContentMD5Validation=false during downloading, and validate if the data is correct. 

Another way to simply validate if the uploaded and downloaded data is correct, is to split the downloaded data at the position of (First video's length), and see if media player can play second part of data.

Best Wishes,
Jiachen

**Comment by XiaoningLiu** [comment]
Your code sample doesn't look good. The 2 pipe operations will start parallel. You need to make sure the 2nd pipe start after 1st pipe operation is finished.
```
var azure = require('azure-storage');
var blobService = azure.createBlobService(blobStorageAccountName, blobStorageAccessKey, blobUri);

var stream = fs.createReadStream('./test1.avi').pipe(blobService.createWriteStreamToNewAppendBlob(blobContainerName, 'abcdefgh'));

stream.on('finish', function() {
 fs.createReadStream('./test2.avi').pipe(blobService.createWriteStreamToExistingAppendBlob(blobContainerName, 'abcdefgh'));
});
```

**Comment by jiacfan** [comment]
@shiwaniB 

Please let us know if there is still problem. Have you tried MD5 validation to see if two files ( concatenated) has been uploaded successfully? And if its media's metadata causing only the first part of video is displayed?

Best Wishes,
Jiachen

**Comment by vinjiang** [comment]
Feel free to let us know if you need further assistance.

**Comment by omersalam** [comment]
Hi. I am trying to append a video on blob using python. Video is already uploaded i want to append upcoming video on same blob.
