### ISSUE TITLE
Entity generation is different for different calls

### ISSUE THREAD

**Issue by mrmckeb** [Azure/azure-storage-node#46]
The entity generator is fine, but seems a little complex - especially when other calls, like deleting or retrieving don't require using it. Why is it needed for inserting? Couldn't this be built into the function for insertion too?

**Comment by yaxia** [comment]
@mrmckeb Do you mean "TableUtilities.entityGenerator"? It is not used in retrieving which only need the partition key and row key to locate the entity. But for other operations such as "insert", "replace", ""delete", "update" and "merge", it is helpful to generate the entity with desired value and type. If we look at the following sample, the generator helps to set each property of the entity. As the entity doesn't have a fixed schema, it's better to provide the functionality for user to generate the entities by himself.
```
var entGen = TableUtilities.entityGenerator;
var entity = {  PartitionKey: entGen.String('part2'),
    RowKey: entGen.String('row1'),
    boolValue: entGen.Boolean(true),
    intValue: entGen.Int32(42),
    dateValue: entGen.DateTime(new Date(Date.UTC(2011, 10, 25))),
};

// Call the table service with the generated entity
```

**Comment by mrmckeb** [comment]
OK, thanks for that information. Since I posted this I've become a lot more comfortable with the entityGenerator. Good answer, @yaxia.
