### ISSUE TITLE
AzureStorage.Blob is not set for client side blob storage?

### ISSUE THREAD

**Issue by daiict218** [Azure/azure-storage-node#462]
I'm using azure for file uploading. I want to integrate blob upload directly from browser to `azure`. According to [this][1] documentation, I need to specify the `<script src="bundle/azure-storage.blob.js"></script>` from my index.html. I'm importing that by `<script src="home/node_modules/azure-storage/browser/bundle/azure-storage.blob.js" defer></script>` in my app but it is throwing me error as `Uncaught ReferenceError: AzureStorage is not defined` 

But in the documentation, it is said that, I'll get `AzureStorage.Blob` globally after importing that. Also I'm using this in my React component as :

```
    import React from 'react';
    
    require('./App.css');
    
    export default class App extends React.Component {
      constructor(props) {
        super(props);
    
        //throwing me error here
        console.log(AzureStorage.Blob);
      }
    
      render() {
        return (
          <h1>Hello World</h1>
        );
      }
    }
```

What am I doing wrong here?
  [1]: https://dmrelease.blob.core.windows.net/azurestoragejssample/samples/sample-blob.html

**Comment by daiict218** [comment]
I've built the client bundle as well and the location in my script tag is correct by I'm still facing this issue.

**Comment by XiaoningLiu** [comment]
@daiict218 Did you solved the issue? Any root cause?

**Comment by daiict218** [comment]
@XiaoningLiu Yes, It was my bad, I wasn't bundling the browser part inside the module.

**Comment by NtierDev** [comment]
@daiict218  We are facing the same issue with Azure file share. Specifics on how you resolved will helpful.

**Comment by LukaICupic** [comment]
Did anybody find a solutin?
