### ISSUE TITLE
Refused to set unsafe header "user-agent" in version 2.9.0-preview

### ISSUE THREAD

**Issue by daiict218** [Azure/azure-storage-node#463]
I'm using version 2.9.0-preview and while uploading I get `Refused to set unsafe header "user-agent"` in every chunk upload request. Seems like we are adding `user-agent` in safe headers from browsers as well. Do we need to remove them or do we have some other work around?

**Comment by jiacfan** [comment]
@daiict218 

What's the environment you are trying 2.9.0-preview, would you share some information of you environment?

Thanks,
Jiachen

**Comment by daiict218** [comment]
Hi @jiacfan, I'm using chrome version 67.0.3396.79

**Comment by jiacfan** [comment]
@SaltyDH and @daiict218 

Thanks for the info and reporting. As checking, 2.9.0-preview doesn’t change user-agent settings codes, this could be a generic issue for Javascript Library on Chrome. 
As your description, the upload request could successfully complete, so will the issue in some extent block your production env? 
We will discuss the issue internally and give feedback in this thread on the mitigation.

Thanks,
Jiachen

**Comment by jiacfan** [comment]
We are planning to disable user-agent setting for browsers environments. Would this meet your requirements? Any more wishes for user-agent support for browser environments?

Thanks,
Jiachen

**Comment by daiict218** [comment]
That would solve the problem @jiacfan. btw Can I take this bug, I want to contribute to open source but haven't yet

**Comment by jiacfan** [comment]
@daiict218 

That would be great! Welcome contributions!

Thanks,
Jiachen

**Comment by SaltyDH** [comment]
> We are planning to disable user-agent setting for browsers environments.

Since the major browsers don't support the override that sounds good to me. Thanks again!

**Comment by daiict218** [comment]
Hi @jiacfan, I've made the PR for this [https://github.com/Azure/azure-storage-node/pull/468/commits/a2da6ba2720c31dfa32e3e9b33f1bd6a3e993569?utf8=%E2%9C%93&diff=split&w=1](url), Please review this

**Comment by daiict218** [comment]
[https://github.com/Azure/azure-storage-node/pull/468](url) @jiacfan, please review this PR

**Comment by daiict218** [comment]
[https://github.com/Azure/azure-storage-node/pull/468/commits/a2da6ba2720c31dfa32e3e9b33f1bd6a3e993569](url) Please review this

**Comment by daiict218** [comment]
@jiacfan I've made a commit #468, please review this.

**Comment by jiacfan** [comment]
@daiict218 

Review is done, and as comments, it'll be merged after 2.10.0 releases. FYI.

Thanks,
Jiachen

**Comment by daiict218** [comment]
This has been merged. Can be tested and closed

**Comment by PeterL1n** [comment]
Now at 2.10.100, I am still receiving the error in console, saying `Refused to set unsafe header "user-agent"`

**Comment by daiict218** [comment]
Hi @PeterL1n, the version 2.10.0 was published before the PR got merged. Hence the code is not there

**Comment by jiacfan** [comment]
Hi, All 

JavaScript library version 2.10.101 will involve the change, and it's under release. 
Will update further when it's released.

Thanks,
Jiachen

**Comment by ChristopherParo** [comment]
@jiacfan is there any chance the browser JavaScript library will be implemented into its own npm?

**Comment by oliviakg** [comment]
@jiacfan - Can you provide an eta on 2.10.101?

**Comment by jiacfan** [comment]
@oliviakg 

The release is in the step - "going through and generate ThirdPartyLicense". Will update here, once we fulfill this legal step and get 2.10.101 published.

Thanks,
Jiachen

**Comment by jitendragarg** [comment]
I hope it is completed soon. Just started using this JS file, and have been banging my head around everywhere. Glad to know, it is not something I have missed. For now, I am going to add a condition to stop adding user-agent on my side.

**Comment by jiacfan** [comment]
Hi, @jitendragarg 

Thanks for the suggestion. And we are proactively following the progress. Will give feedback here once the step get fulfilled.

Best Regards,
Jiachen

**Comment by jitendragarg** [comment]
It works. Although I noted a different problem. Will create a bug for the same.

**Comment by oliviakg** [comment]
@jitendragarg - Thanks! It works for me :)
