### ISSUE TITLE
Support appending from multiple writers to an append blob like the .Net or Java SDK does

### ISSUE THREAD

**Issue by jsnikhil** [Azure/azure-storage-node#467]
The .Net and Java storage SDK support CloudAppendBlob.appendBlock which can be called by multiple writers writing to the same append blob. The node SDK strictly advises against using multi writers for calling methods like createWriteStreamToExistingAppendBlob. Is there a way to do this?

I need to use the SDK in Azure functions which can scale in parallel therefore creating multiple writers.

**Comment by jiacfan** [comment]
Hi, @jsnikhil 

As description in the code, "createWriteStreamToExistingAppendBlob should be used strictly in a single writer scenario because the API internally uses the append-offset conditional header to avoid duplicate blocks". This ensures data integrity, and sorry that parallel uploading append blob or from multiple writer is not supported by design.

Best Wishes,
Jiachen

**Comment by jsnikhil** [comment]
Thanks for the info @jiacfan. What about a Block blob or any other. Looking at the docs for createWriteStreamToBlockBlob, it doesn't specifically recommend a single writer use. Is there a recommended way (external to the SDK) that will allow for multiple writers?

**Comment by jiacfan** [comment]
Hey, @jsnikhil 

For createWriteStreamToBlockBlob, if you looking into the code, internally there is buffer which allows parallel uploading to happen. As the input side is a stream, buffer would help to make data sliced into chunks, and do uploading in parallel.

From my view, one stream is hard to be shared across processes, is it possible for you to partition the upload job(i.e. in chunk level) in highlevel, and for each function just upload part of a blob, e.g. several block of block blob?

Thanks,
Jiachen

**Comment by jsnikhil** [comment]
Thanks for the pointer @jiacfan. I can partition the data and have each function only upload a single partition to its own block file. What is considered a writer in the SDK? Is it the BlobService class? i.e. can I have a single blobService calling appendBlockFromStream() in parallel?

**Comment by jiacfan** [comment]
Hi, @jsnikhil 

For the `Writer`, in `createWriteStreamToBlockBlob` or `createWriteStreamToExistingAppendBlob`, it means a `ChunkStream` i.e. stream writer which is returned to user, it's not `BlobService` class. 
As the [quick start](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-nodejs) and [Getting started](https://github.com/Azure/azure-storage-node), BlobService is where retry policy is set or account info inferred, where you can further invoke APIs like `appendBlockFromStream`. While for uploading data, or maintain the state of date being uploading, you might need to use the writer returned from the method, and add your code for your scenarios.

Thanks,
Jiachen

**Comment by jsnikhil** [comment]
This is a no go and we will be using the Java SDK instead. I think this is a serious limitation of the Node SDK and should be addressed; at least as a feature request. Needing to use multiple writers appending to the same blob file is a very common use case specially from Azure functions or SaaS apps. As I said the [.Net_SDK](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.cloudappendblob.appendblock?view=azure-dotnet#Microsoft_WindowsAzure_Storage_Blob_CloudAppendBlob_AppendBlock_System_IO_Stream_System_String_Microsoft_WindowsAzure_Storage_AccessCondition_Microsoft_WindowsAzure_Storage_Blob_BlobRequestOptions_Microsoft_WindowsAzure_Storage_OperationContext_) and [Java_SDK](https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.storage.blob._cloud_append_blob.appendblock#com_microsoft_azure_storage_blob__cloud_append_blob_appendBlock_final_InputStream_final_long_ ) allows commiting a new block of data to the end of the blob with multiple writers, and I don't see why a design decision was made in this instance to not allow it at all.

If you don't plan on supporting it, this limitation should be explicitly called out in the README file.

**Comment by jiacfan** [comment]
@jsnikhil 

Thanks for the suggestions! I understand your demand. And I wish to explain why the node.js commented not suggesting using multiple writers to append to a same append blob in parallel. As the REST API document illustrated for [append block](https://docs.microsoft.com/en-us/rest/api/storageservices/append-block) operation:

> **This operation supports the use of additional conditional headers to ensure that the API succeeds only if a specified condition is met. For more information, see Specifying Conditional Headers for Blob Service Operations.**

i.e. `x-ms-blob-condition-appendpos` is recommended to be used.

In node.js `createWriteStreamToExistingAppendBlob` method comments, 

> This API should be used strictly in a single writer scenario because the API internally uses the append-offset conditional header to avoid duplicate blocks.
And design like this is wish to ensure the data integrity, that right position is used during appending operation.

Although using multiple writers appending to same blob file is allowed technically, please be aware of the character of append blob, and ensure the data is uploaded at right position as wished. 

For parallel uploading scenarios, block blob is suggested comparing to append blob.

Thanks,
Jiachen

**Comment by jiacfan** [comment]
Hi, @jsnikhil 

There is one more API, might be useful for your use: `appendBlockFromStream`, when you left options.appendPosition as null, it will do append block without pre-condition match. The document of the API is not good enough currently, we'll optimize it further.

We have a discussion internal in the team. And there could be two typical scenarios:

1. Scenario-A: Append data with single writer, when user want to ensure the sequence of data being uploaded.
In this scenario, conditional header is used to ensure the data integrity, and user need to use single writer during the upload. For this scenario, please use APIs like: `createWriteStreamToExistingAppendBlob`, `createWriteStreamToNewAppendBlob`
2. Scenario-B: Append data with multiple writer, when the sequence of data is not seriously important.
E.g. User have logs to uploads, User call Upload A log entity and Upload B log entity in parallel, as the network latency, the arrival time to server of A/B log entity could be different, i.e. the sequence of A/B log entity cannot be ensured. For this scenario, please use API like: `appendBlockFromStream` without pre-condition header set.

Thanks,
Jiachen

**Comment by jsnikhil** [comment]
Thanks @jiacfan. Looks like scenario-B will do the trick here. We will try it and feedback here.

**Comment by jiacfan** [comment]
Hi, @jsnikhil 

v2.10.0 has been released.

Best Wishes,
Jiachen

**Comment by markdernie** [comment]
I am trying to understand exactly what the constraint described as "used strictly in a single writer scenario" actually means. I found this issue and your examples are a little confusing to me, which is probably down to a lack of knowledge on my part but can I just clarify with you as you clearly understand this:
If I am appending to an appendblob, lets say a log file, in system with multiple users, does the single writer statement mean that only one user can write the the blob (in this case the log) at one time. In this particular case lets say the user is a Function app called via HTTP.  If that is what it means, what happens if two users do write to the log at the same time it seem to suggest it might create multiple blocks is correct?

**Comment by XiaoningLiu** [comment]
Hi @markdernie 

"used strictly in a single writer scenario" means you should NOT call `createWriteStreamToExistingAppendBlob` and `createWriteStreamToNewAppendBlob` more than once at the same time (means there should only one running instance for above 2 methods) for SAME append blob.

But you can call `createWriteStreamToExistingAppendBlob` once, and re-use the returned `WriteStream` in different places.

**Comment by markdernie** [comment]
Hi XiaoningLiu

Thanks for the reply, if I am reading it correctly that does seem a very big restriction when it comes to using append blobs for common logging or event stores in an event sourcing architecture. I am not using the specific methods you mention but I assume  the same applies to simpler methods such as appendFromText as they have the same single writer restriction. 
On the final part of your comment I am not looking to multiple write from the same code, i want to write to the same blob from different clients (attached to different user session). It looks like that is not possible because it would not be possible to stop that happening at the same time as each client would be unaware of each other, is that correct?

**Comment by jsnikhil** [comment]
You can use `appendBlockFromText` with an `appendPosition = 0` to just append data to an existing blob; this is only if you don't care the order they are appended. We use this for a scenario where we have multiple writers writing to the same block blob
```
blobService.appendBlockFromText(containerName, blobPath, content,
	{ appendPosition: 0 }, 
	(error) => {
		if (error) {
			reject(error);
		} else {
			resolve(blobPath);
		}
	}
);
```

**Comment by markdernie** [comment]
OK perfect, thanks for the reply. 

I was actually just reading about. It might be a good idea to point the other methods at this method, so in the documentation for appendFromText to say - if you can't guarantee "single writer" is then you should use appendBlockFromText.
Thanks for your help.

**Comment by detuniko** [comment]
@XiaoningLiu @jiacfan @vinjiang 
In my scenario, I have multiple writers that write data (say logs) to an append blob. Order of the writes is not important, as long as all writes succeed.
Which method in .net sdk / rest api should I use for my requirement?
