### ISSUE TITLE
Validator "stringAllowEmpty" should have a more specific error message

### ISSUE THREAD

**Issue by jeffwilcox** [Azure/azure-storage-node#47]
Hi,
While trying to debug a customer application, we realized that the error they were receiving was not phrased as clearly as it could be.

The argument validator being called by tableServiceInstance `retrieveEntity` calls in to `stringAllowEmpty`, which checks that it is a string type (empty is OK). The code of the validator is here: https://github.com/Azure/azure-storage-node/blob/master/lib/common/util/validate.js#L386

Unfortunately the app was using an integer in JavaScript and not a string; we kept looking for the argument and it was not undefined, implying it should work...

Perhaps the error message could be more clear, right now it says the argument is missing, when really is it is potentially that the argument is _of the wrong type_.

Thanks.

**Comment by slepox** [comment]
This is fixed in release 0.4.4.
