### ISSUE TITLE
Need documentation and examples for file upload & download using request/response

### ISSUE THREAD

**Issue by graham-sportsmgmt** [Azure/azure-storage-node#472]
Over the past week I've been struggling with numerous issues related to reading and writing files to Azure Storage using node/express.  We are adding a document management tool to our product suite.

There is no documentation available for developers using this method of accessing storage with the sdk.  I've had to piece this together from the sdk spec, a half dozen StackOverflow questions, and some great help on StackOverflow from Jerry Liu.

Please add documentation for web developers to effectively use the azure-storage-node sdk with a restful API written in node/express, including:

- Setting metadata as part of the inbound upload request
- Listing files/blobs with search parameters
- Writing custom headers as part of the response for outgoing filename manipulation
- Error handling

I am happy to contribute to this effort, but I'm afraid our code still isn't feature-complete and I have outstanding questions.

**Comment by jiacfan** [comment]
@graham-sportsmgmt 

Thanks for providing feedback! This is valuable for user experience enhancement, and I'll bring this info to the team soon.

Happy to discuss questions you met, and thanks for any contributions!

Thanks,
Jiachen
