### ISSUE TITLE
is live streaming from azure blob possible

### ISSUE THREAD

**Issue by shiwaniB** [Azure/azure-storage-node#475]
My usecase is to upload live streamimg mjpeg or mp4 converted data to azure blob storage.
And display it on html using blob url.

is there any way to achieve this functionality?

**Comment by jiacfan** [comment]
Hi, @shiwaniB 

As "[Deciding when to use Azure Blobs](https://docs.microsoft.com/en-us/azure/storage/common/storage-decide-blobs-files-disks)" described, Block blob is an ideal feature for massive scale unstructured data storage. And is good to use when you want your application to support streaming, and be able to access application data from anywhere.

And I also find some link you might be interested in "[Streaming MP4 video files in Azure Storage containers (Blob Storage)](https://blog.thoughtstuff.co.uk/2014/01/streaming-mp4-video-files-in-azure-storage-containers-blob-storage/)".

And SDK can help you to upload/download (piece/all) of the data using Azure storage.

Best Wishes,
Jiachen

**Comment by shiwaniB** [comment]
Hi @jiacfan 

"upload live stream continuously on azure blob"  meaning is I don't want to upload and play mp4 (video file with start and end time)  to azure storage blob.

But the use case is to upload live camera images continuously to azure blob, so that user can view it on html as a live stream.

Thanks,
Shiwani

**Comment by jiacfan** [comment]
Hi, @shiwaniB 

For uploading live stream continuously, please try APIs like: `appendFromStream`, `createWriteStreamToExistingAppendBlob` for append blob, it can easily help you to append data to existing append blobs.

And here is some personal suggestion FYI, to view the blob in html as a live stream, or with some extended functions, I think you might need some 3rd party support in browser side, which can get blob with range header specified properly, and do error handling or react properly when the data is exhausted and retry the request again with some policies.

Best Wishes,
Jiachen

**Comment by omersalam** [comment]
Hi @shiwaniB 

Have you got any luck doing that? I am trying to do the same. Let me know if you have any luck achieving this.
