### ISSUE TITLE
Give MJPEG stream as input to azure blob using Nodejs

### ISSUE THREAD

**Issue by komalpharate** [Azure/azure-storage-node#476]
Hi,
I have mjpeg stream which I want to send to azure blob. 
ex. Content Type- multipart/x-mixed-replace

will access this blob in browser .
is it possible?

**Comment by jiacfan** [comment]
Hi, @komalpharate 

Is the question whether you can upload an azure blob, and set content-type with "multipart/x-mixed-replace", and during getting the resource you can get the data with correct content-type once set?

If this is the question, the answer is 'Yes'.

You can upload the data with SDK and set ContentType correspondingly, and when you download the data, the ContentType you set will be returned in the [header](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob).

Best Wishes,
Jiachen

**Comment by komalpharate** [comment]
Thank you for the quick reply.
Will try and let you know.

**Comment by jiacfan** [comment]
Hi, @komalpharate 

Is there any further question, and can this issue be closed?

Thanks,
Jiachen

**Comment by komalpharate** [comment]
Hi
You can close the issue. I had to change requirements so couldn't test the above suggested setup.
Thank you

**Comment by jiacfan** [comment]
Hi, @komalpharate 

Thanks for the info!

Best Regards,
Jiachen
