### ISSUE TITLE
Deprecation warning on Node 10

### ISSUE THREAD

**Issue by goncharov** [Azure/azure-storage-node#479]
Hi,
`azure-storage-node` uses a deprecated `new Buffer()` constructors and causes deprecation warnings:

```js
DeprecationWarning: The Buffer() and new Buffer() constructors are not recommended for use due to security and usability concerns. Please use the new Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() construction methods instead.
```

**What is desired behavior**

`azure-storage-node` should not use deprecated constructor on Node versions where safe replacement is available

**Comment by XiaoningLiu** [comment]
@goncharov Thanks for reporting!

We will try to make a fix in next release. At the same time, it's a great opportunity for you to make a contribution!

**Comment by lannonbr** [comment]
I believe this should be closed since Suz's PR was merged in that resolves this.
