### ISSUE TITLE
Allowing getting properties of a deleted blobs

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-node#480]
Currently, the only way we can get properties of a deleted blob, such as "deleted time", "remaining retention days", is to list blobs using that blob's full name as prefix. It is very inconvenient if there are many other blobs share that prefix. 

Is it possible to make `getBlobProperties` able to get properties of deleted blobs? It would be very helpful if this feature can be added, Thanks.

**Comment by jiacfan** [comment]
Hi, @JasonYeMSFT 

Thanks for providing feedback, and welcome discussion.

You know [get blob properties](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-properties) requires the URL of blob. And for deleted blob, only if user kept deleted blob's URL themselves, then they have the ability to get deleted blob's URL, and use this blob to get deleted blob's property. It could be hard for user to keep so, and I guess that's the reason deleted blob is designed to be listed with list API, and once listed you can get the property of the blob at same time.

Suggest to use [options.include] and [options.maxResults]  with include={**deleted**} and maxResults set to 1(considering it's ordered with Alphabets) during using [list API](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs), and this can help to filter out unrelated blobs.

Thanks,
Jiachen

**Comment by vinjiang** [comment]
Please let us know if any further assistance required.
