### ISSUE TITLE
publish client library on npm

### ISSUE THREAD

**Issue by FelschR** [Azure/azure-storage-node#482]
Do we really need to copy-paste the client library into our projects?!

I can't imagine a reason why this shouldn't be possible.

**Comment by jiacfan** [comment]
Hi, @FelschR 

Would you share more details about your question?

For azure storage node.js library, you can get the package by:
`npm install azure-storage`

Thanks,
Jiachen

**Comment by jiacfan** [comment]
Yes, @richardszalay. Thanks for the suggestion, and we fully understand this, and we're going to support it in the new typescript client library with new architecture, it's being developed, and can fully support NPM import. We will share more about it's public preview status once it's ready.

Thanks,
Jiachen

**Comment by richardszalay** [comment]
That's great, @jiacfan , thanks for the fast reply! I look forward to checking out the new version when it's released.

Richard

**Comment by XiaoningLiu** [comment]
@richardszalay https://github.com/Azure/azure-storage-node/issues/507

**Comment by XiaoningLiu** [comment]
@richardszalay Our initial plan is to GA new library this year. The preview has full support for Azure Storage 2018-03-28 API version and features. But during preview, potential breaking changes may have, according to customer feedback.

**Comment by XiaoningLiu** [comment]
10 SDK has already GAed, will close this issue.
