### ISSUE TITLE
Can I start uploading video (or asset) where it was left due to network connection?

### ISSUE THREAD

**Issue by daiict218** [Azure/azure-storage-node#483]
I'm using this library to upload a video on azure data storage from the browser (client). I'm using this following way:

```
const azureUploadDetails = azureBlobService.createBlockBlobFromBrowserFile(container, uploadPath, file, { blockSize: +blockSize || MIN_CHUNK_SIZE }, error => {
          const contentToProcess = {
            Bucket: container,
            fileName: file.name,
            mimeType: fileType,
            Key: uploadPath,
          };

          if (_isEmpty(error)) {
            //Process content etc.
          } else {
            reject(error);
          }
        });

        azureUploadDetails.on('progress', () => {
          that.onProgress({ percent: azureUploadDetails.getCompletePercent() });
        });
      }));
```

However sometimes my file is too large and I'm generating a `SAS_TOKEN` for 2 hours and my upload is not finished in 2 hours. In such a case, one of the chunk upload call will fail and my user has to again initiate the upload. What I want to do is, re-fetch the `SAS_TOKEN` and retry the upload from the same point, it has been left off. (This could occur due to a network error as well). Is this already been supported?

**Comment by jiacfan** [comment]
Hi, @daiict218 

Sorry that this scenario is not supported yet, Would it be possible for you to create different expiry time SAS according to the file length, in that case it would help to mitigate the failure you mentioned.

Thanks,
Jiachen

**Comment by daiict218** [comment]
Hi @jiacfan, can we have this feature request? I can work on that.

**Comment by jiacfan** [comment]
Hi, @daiict218 

Welcome any kinds of contribution, and welcome share your idea and design on this feature.

Thanks,
Jiachen

**Comment by jiacfan** [comment]
Close as no feedback is collected for months.
