### ISSUE TITLE
azure-storage issue after upgrading to angular 6

### ISSUE THREAD

**Issue by felixanand** [Azure/azure-storage-node#484]
Hi, I was using angular 4 and azure-storage worked like a breeze. But when I upgraded my version to Angular 6, I am getting the following errors during compilation. Can you please help out.

**ERROR in ./node_modules/azure-storage/lib/common/signing/hmacsha256sign.js
Module not found: Error: Can't resolve 'crypto' in 'C:\Code\GIT\SMCProjX\XX.TeT.SMCProjX\XX.TeT.SMCProjX.UI\node_modules\azure-storage\lib\common\signing'
ERROR in ./node_modules/azure-storage/lib/common/streams/filereadstream.js
Module not found: Error: Can't resolve 'fs' in 'C:\Code\GIT\SMCProjX\XX.TeT.SMCProjX\XX.TeT.SMCProjX.UI\node_modules\azure-storage\lib\common\streams'
ERROR in ./node_modules/azure-storage/lib/services/blob/blobservice.node.js
Module not found: Error: Can't resolve 'fs' in 'C:\Code\GIT\SMCProjX\XX.TeT.SMCProjX\XX.TeT.SMCProjX.UI\node_modules\azure-storage\lib\services\blob'
ERROR in ./node_modules/azure-storage/lib/services/file/fileservice.node.js
Module not found: Error: Can't resolve 'fs' in 'C:\Code\GIT\SMCProjX\XX.TeT.SMCProjX\XX.TeT.SMCProjX.UI\node_modules\azure-storage\lib\services\file'
ERROR in ./node_modules/azure-storage/lib/common/request-wrapper/request.browser.js
Module not found: Error: Can't resolve 'http' in 'C:\Code\GIT\SMCProjX\XX.TeT.SMCProjX\XX.TeT.SMCProjX.UI\node_modules\azure-storage\lib\common\request-wrapper'
ERROR in ./node_modules/azure-storage/lib/common/streams/batchoperation.js
Module not found: Error: Can't resolve 'http' in 'C:\Code\GIT\SMCProjX\XX.TeT.SMCProjX\XX.TeT.SMCProjX.UI\node_modules\azure-storage\lib\common\streams'
ERROR in ./node_modules/azure-storage/lib/common/request-wrapper/request.browser.js
Module not found: Error: Can't resolve 'https' in 'C:\Code\GIT\SMCProjX\XX.TeT.SMCProjX\XX.TeT.SMCProjX.UI\node_modules\azure-storage\lib\common\request-wrapper'
ERROR in ./node_modules/azure-storage/lib/common/streams/batchoperation.js
Module not found: Error: Can't resolve 'https' in 'C:\Code\GIT\SMCProjX\XX.TeT.SMCProjX\XX.TeT.SMCProjX.UI\node_modules\azure-storage\lib\common\streams'
ERROR in ./node_modules/azure-storage/lib/common/services/storageserviceclient.js
Module not found: Error: Can't resolve 'os' in 'C:\Code\GIT\SMCProjX\XX.TeT.SMCProjX\XX.TeT.SMCProjX.UI\node_modules\azure-storage\lib\common\services'
ERROR in ./node_modules/azure-storage/lib/common/streams/batchoperation.js
Module not found: Error: Can't resolve 'os' in 'C:\Code\GIT\SMCProjX\XX.TeT.SMCProjX\XX.TeT.SMCProjX.UI\node_modules\azure-storage\lib\common\streams'
ERROR in ./node_modules/azure-storage/lib/services/file/fileservice.core.js
Module not found: Error: Can't resolve 'path' in 'C:\Code\GIT\SMCProjX\XX.TeT.SMCProjX\XX.TeT.SMCProjX.UI\node_modules\azure-storage\lib\services\file'**

**Additional Information**
Angular CLI: 6.0.8
Node: 8.11.3
OS: win32 x64
Angular: 6.0.9

**Comment by jiacfan** [comment]
Hi, @felixanand 

This seems a general dependency error. Is there similar dependency issue for other module in your project?

Would you have a try on [Javascript library](https://github.com/Azure/azure-storage-node#azure-storage-javascript-client-library-for-browsers)?

Thanks,
Jiachen

**Comment by mortenalbertsen** [comment]
I also get the 
`ERROR in ./node_modules/azure-storage/lib/common/streams/filereadstream.js
Module not found: Error: Can't resolve 'fs' in <path>`
@jiacfan: Any suggested resolutions?

**Comment by jiacfan** [comment]
Hi, @mortenalbertsen 

Do you still have the problem?  Would this be a problem caused by the work bench is not clean? And would you have a try on [Javascript library](https://github.com/Azure/azure-storage-node#azure-storage-javascript-client-library-for-browsers) as well?

Thanks,
Jiachen

**Comment by Khdoop** [comment]
Same errors, Angular 6.

**Comment by jiacfan** [comment]
Hi, @Khdoop 

Yes, would you check if this is an issue caused by dependency conflict? At same time we have [azure-storage-js](https://github.com/Azure/azure-storage-js) in preview which has cleaner dependency, and has tested latest webpack integration. Welcome try.

Thanks,
Jiachen

**Comment by XiaoningLiu** [comment]
Could you try with the latest @azure/storage-blob library? which supports async methods, promise and await. 

You can import @azure/storage-blob via npm, and it should be able to work with Angular 6.
