### ISSUE TITLE
When SAS permission is "rcl", unexpected behavior

### ISSUE THREAD

**Issue by PeterL1n** [Azure/azure-storage-node#485]
In my use case, I wish users with SAS token to be able to write but not override any existing blob within the container. So when generating the SAS token, I selected permissions: "rcl" -read, create, and list.

The behavior then becomes weird. Using the browser js, this allows users to upload non-existing small files (small as several kbs), and prevents overriding existing files by returning a "UnauthorizedBlobOverwrite". However, when testing uploading non-existing large files (large as 3gb), it returned "AuthorizationPermissionMismatch", where I expected it to succeed.

The error was 403 
```
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:4e23e8a7-501e-0096-4d4a-22ae07000000
Time:2018-07-23T06:00:28.7935735Z</Message></Error>
```

I believe it is a bug because why would smaller files be accepted but large files are unauthorized?

**Comment by PeterL1n** [comment]
Also, I want to know what is the right way to generate a SAS token that only allows read, list, and upload new blobs. I need to prevent users from deleting and overriding existing blobs. Since the SAS is given to other people, I cannot rely on them to use headers to prevent an override. It has to be done on the SAS level. Is permission "rcl" the correct one to use?

**Comment by XiaoningLiu** [comment]
Hi @PeterL1n 

It's an excepted behavior. Let's me explain.

I'm guessing you are using APIs like `uploadBrowserFileToBlockBlob` etc. For similar uploading APIs, there is a threshold property of `blobService` objects, called `singleBlobPutThresholdInBytes`. The default value is 32MB. (max is 256MB)

When a file is smaller than this value, the data will be uploaded via a single [PUT BLOB](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob) request. This request needs `c` permission.

When a file is lager than this value, the data will be split to data blocks, uploading blocks by  [PUT BLOCK](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block) requests, and finally [PUT BLOCK LIST](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list) request, which requires `w` permission.

`'l` is a permission for a container, you can generate a blob level SAS token to have more grained permission control.

**Comment by XiaoningLiu** [comment]
@PeterL1n As far as I know, the answer is yes only for block blobs smaller than 256MB, `c` can do what you want.

But there are some other work around. For example, you can generate a blob SAS with 2 hours expired time. When someone uploads a block blob with the SAS at the first time, once it finishes, you can create a lease for the blob with longer lease period, then the blob cannot be modified without the leaseID.
