### ISSUE TITLE
Get appendBlob block number

### ISSUE THREAD

**Issue by frankShih** [Azure/azure-storage-node#487]
Hi all, 

In http://azure.github.io/azure-storage-node/BlobService.html
I find  `appendFromText(container, blob, text [, options], callback)` and  `appendBlockFromText(container, blob, content [, options], callback)`

I know that each blob has at most 50000 blocks(about 200GB?), so I'm wondering: 

1. How can I get current block count for a certain appendBlob? 
    I know blockBlob has listBlock(), and there is something like REST API that can get info from storage, but I just can't find what I want
2. If I use `appendBlockFromText`, it means that I can only call it 50000 times for each appendBlob? What about `appendFromText`, can I call it as many times as I want until reach the maximum storage limit? 

Besides, is there any way I can check whether a blob is being written?

Please give me some suggestions, thanks.

**Comment by jiacfan** [comment]
Hi, @frankShih 

Q; How can I get current block count for a certain appendBlob?
A: As the [AppendBlock](https://docs.microsoft.com/en-us/rest/api/storageservices/append-block) and [GetBlob](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob) rest api, there is response header `x-ms-blob-committed-block-count` which can help you to get current block count of a certain appendBlob.

Q: If I use appendBlockFromText, it means that I can only call it 50000 times for each appendBlob? What about appendFromText, can I call it as many times as I want until reach the maximum storage limit?
A: Yes, you can only call it 50000 times, as description of [AppendBlock](https://docs.microsoft.com/en-us/rest/api/storageservices/append-block):

> Each block can be a different size, up to a maximum of 4 MB. A maximum of 50,000 appends are permitted for each append blob. The maximum size of an append blob is therefore slightly more than 195 GB (4 MB X 50,000 blocks). If you attempt to upload a block that is larger than 4 MB, the service returns HTTP status code 413 (Request Entity Too Large). The service also returns additional information about the error in the response, including the maximum block size permitted in bytes. If you attempt to upload more than 50,000 blocks, the service returns the BlockCountExceedsLimit error (HTTP status code 409 – Conflict).

Q: Is there any way I can check whether a blob is being written?
A: Please use request header `x-ms-blob-condition-appendpos`, if the append position is not as expected(i.e. the blob is being written), there would be error returned.

Best Regards,
Jiachen

**Comment by frankShih** [comment]
Hi, @jiacfan 

First of all, thanks for your reply.

One more question, if I just want to write my logs to web-storage, does it make any differences between using appendBlockFromText and appendBlockFromText? Since both of these function can only be called 50000 times for each blob. Correct me if I am wrong.

**Comment by jiacfan** [comment]
Hi, @frankShih 

I think you mean `appendBlockFromText` and `appendFromText`, `appendBlockFromText` always use append blob.

For `appendFromText` it will always check the `x-ms-blob-condition-appendpos`, and should be used with single writer. And for `appendBlockFromText`, it can be used with multiple writers, when sequence of the data to be appended is not important.

Best Regards,
Jiachen

**Comment by frankShih** [comment]
Hi, @jiacfan 

First of all, thanks for your help.

According to your suggestion, if I want to append a blob intensively (from multiple servers), I should always need to send a REST request to confirm no one is writing the blob, then I can use the sample code from [https://docs.microsoft.com/zh-tw/azure/storage/blobs/storage-quickstart-blobs-nodejs?view=azure-node-latest] to append a blob?

Since I try to send dozens of append request (blobService.appendFromText) from the same host at the same time. I observe that only 50% or even fewer requests appending the blob successfully, however, I don't get any error... 

Below is the sample code:
`
const appendBlob = (filePath, msg, res) => {
    const sourceFilePath = path.resolve(filePath);
    const blobName = path.basename(sourceFilePath, path.extname(sourceFilePath));

    return new Promise((resolve, reject) => {
        const startTime = Date.now()
        blobService.appendFromText(CONTAINER_NAME, blobName, msg, err => {
            if (err) {
                reject(err);
            } else {
                resolve({ message: `Update of '${blobName}' complete` });
            }
            console.log("time elasped(ms): "+(Date.now()-startTime));
        });
    });
};
`
And I always get the message in "resolve"...

**Comment by jiacfan** [comment]
Hi, @frankShih 

As previous suggested:
For `appendFromText` it will always check the x-ms-blob-condition-appendpos internally, and should be **used with single writer**. And for `appendBlockFromText`, it can be **used with multiple writers, when sequence of the data to be appended is not important**.

So please ensure **whether the sequence of data is important**. And use single or multiple writers correspondingly.

In the case append with single writer, i.e. using `appendFromText`, you don't need to send REST request additionally, in-side the method `appendFromText`, it will use getBlobProperty to fetch the contentLength, and use it as `x-ms-blob-condition-appendpos`, and check whether the position to append is as expected.

So please ensure the method is used in a proper approach. E.g. using `apendFromText` in multiple servers(multiple writer) would not be suggested approach.

For the error you mentioned, would you please collect the HTTP status code and error message(e.g. using fiddler to check) when append failure happened as you observed, this would be helpful for us to investigate further.

Thanks,
Jiachen

**Comment by frankShih** [comment]
Hi, @jiacfan

Thanks for your suggestion, and my issue is solved.

However, another issue has happened. When I try "stress testing" (append / upload blobs intensively),
I get the following error:
`
(node:17184) UnhandledPromiseRejectionWarning: Upload of 'XXX' failed
StorageError: The append position condition specified was not met.
RequestId:517ba1c0-101e-000b-7a00-403ec6000000
Time:2018-08-30T01:24:22.9435970Z
    at Function.StorageServiceClient._normalizeError (C:\NodeDataCollector\node_modules\azure-storage\lib\common\services\storageserviceclient.js:1198:23)
    at BlobService.StorageServiceClient._processResponse (C:\NodeDataCollector\node_modules\azure-storage\lib\common\services\storageserviceclient.js:744:50)
    at Request.processResponseCallback [as _callback] (C:\NodeDataCollector\node_modules\azure-storage\lib\common\services\storageserviceclient.js:317:37)
    at Request.self.callback (C:\NodeDataCollector\node_modules\request\request.js:185:22)
    at Request.emit (events.js:125:13)
    at Request.<anonymous> (C:\NodeDataCollector\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:125:13)
    at IncomingMessage.<anonymous> (C:\NodeDataCollector\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:217:13)
    at IncomingMessage.emit (events.js:130:15)
(node:17184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
`

**Comment by jiacfan** [comment]
Hi, @frankShih 

The error `The append position condition specified was not met` shows the position to append is not as expected. Would there be case that you are uploading to same blob simultaneously？

createAppendBlobFromLocalFile upload an append blob sequentially (i.e. with no parallel), and internally it invokes appendBlock method, and uses `appendPosition`(`x-ms-blob-condition-appendpos`) to check whether the position to append is as expected, in order to ensure data integrity. 

Best Regards,
Jiachen

**Comment by frankShih** [comment]
Hi, @jiacfan

I have checked my code that I call createAppendBlobFromLocalFile sequentially (after getting the response from uploadBlob, call it again). 

For example, I create blob B1, B2 and B3 sequentially. At the meanwhile,  I append text to these blobs.
But sometimes I try appendBlockFromText intensively, it shows "BlobNotFound" error even if I already get the uploadBlob response. 

Or, shouldn't I call createAppendBlobFromLocalFile (different file names) at the same time?

**Comment by jiacfan** [comment]
Hi, @frankShih 

Please double ensure `appendBlockFromText` is called after corresponding `createAppendBlobFromLocalFile` is fulfilled, i.e. check response of createAppendBlobFromLocalFile indicates creating append blob successfully. (And is `uploadBlob` you described equal to `createAppendBlobFromLocalFile `?)

Calling `createAppendBlobFromLocalFile` transferring different local files to **different** blobs is fine.

Thanks,
Jiachen
