### ISSUE TITLE
createBlockBlobFromBrowserFile does not provide way to renew a shared upload URL

### ISSUE THREAD

**Issue by absoludity** [Azure/azure-storage-node#492]
When uploading a large file to an Azure storage account via a Shared Access Signature uri, I don't see a callback or other method to be able to renew the SAS.

This means that you will always have failed uploads if one block of the upload starts after the SAS expiry - which is bound to happen for either large uploads or slow bandwidth, the only current work-around of which is to set a very large expiry, reducing the security of the SAS.

It looks like people have been generating new SAS's during a block upload for sometime using the REST API - see http://sanganakauthority.blogspot.com/2014/08/using-sas-renew-sas-and-rest-api-to.html . It would be great to have this supported in `azure-storage-node`, rather than removing azure-storage-node to do the REST implementation.

Thanks!

**Comment by jiacfan** [comment]
Close as no feedback is collected for months.
