### ISSUE TITLE
Image Upload to azure container

### ISSUE THREAD

**Issue by kalps1993** [Azure/azure-storage-node#493]
Hello Guys,

I'm not able to upload image on azure container from the reactjs.
Please help me as soon as possible.

Please see my code below and correct me where I'm wrong.
///code start
const azure = require('azure-storage');
    const blobService = azure.createBlobService(my connecting string );
     const container = 'designclub13';
    const task = 'Image Upload';
    const filename =image.jpeg;

blobService.createContainerIfNotExists(container, error => {
      if (error) return console.log(error);
      blobService.createBlockBlobFromLocalFile(
        container,
        task,
        filename,
        (error, result) => {
          if (error) 
            {
              return console.log(error);
            }
            else{
             // console.dir(result, { depth: null, colors: true });
             console.log("Image uploaded");
            }
          
        }
      );
    });
//code end

Thanks in advanced..

**Comment by kalps1993** [comment]
Hi, @jiacfan 

I used createBlockBlobFromBrowserFile but it show me an error like below attached file.

![imaeguploaerror](https://user-images.githubusercontent.com/41891476/43562862-d7ded458-963c-11e8-8ffd-b4c120bd9205.png)

And when i used createBlockBlobFromLocalFile the it is shown an error like below attached file.

![createblobfromtextfile](https://user-images.githubusercontent.com/41891476/43562951-4e211d6a-963d-11e8-8385-7a499871f490.png)

Please help me to solve this problem.

Thanks & Regards,
Kalpesh Gohil
.

**Comment by daiict218** [comment]
Hi @kalps1993, you'll need to bundle the browser's module of azure-storage first as mentioned [here](https://github.com/Azure/azure-storage-node/tree/master/browser). Alternatively you can import the function without bundling as :

`const azure = require('azure-storage/browser/azure-storage.blob.export');`

**Comment by kalps1993** [comment]
Hello @daiict218 ,

Thank you for your response.

When i used  const azure = require('azure-storage/browser/azure-storage.blob.export'); then it will shown an error like below image.
![untitled](https://user-images.githubusercontent.com/41891476/43569529-59b942e8-9655-11e8-81ed-5e5cba03bc6d.png)


Thanks & Regards
Kalpesh Gohil

**Comment by daiict218** [comment]
this seems to be an issue of invalid file? Can you try uploading some other file?

**Comment by vinjiang** [comment]
Feel free to let us know if you need further assistance.
