### ISSUE TITLE
Getting property of local blob container created by Azure Storage Emulator never returns when emulator is off

### ISSUE THREAD

**Issue by JasonYeMSFT** [Azure/azure-storage-node#494]
To reproduce the bug:
1. use Azure Storage Emulator to create a local blob container and get its connection string and its container name.
2. Create a blob service by `new azureStorage.BlobService(connectionString)`
3. On that blob service, call `getContainerProperties(container, someCallBack)` with `someCallBack` as a function that either does something with the response and deal handle the error

Expected behavior:
When emulator is on, it passes the properties of the container to the callback. When emulator is off, it passes an error that will be handled to the callback.

Actual behavior:
When emulator is on, it is working as expected. When emulator is off, the last function call never enters the callback. This is a confusing behavior and we hope it can fixed. An existing work around is to set a timeout for the function call, but it is not ideal because there are people whose machine has complicated anti-virus/scanning mechanisms that make each web request taking very long time.

**Comment by jiacfan** [comment]
@JasonYeMSFT 

Thanks for reporting the issue, we'll do some investigation, and provide response.

Thanks,
Jiachen

**Comment by jiacfan** [comment]
@JasonYeMSFT 

We tried some run with latest node.js library, and didn't get the repro, when the enumerator is Off, there would be error `Error: connect ECONNREFUSED 127.0.0.1:10000`.

Does the issue still repro in your side? Would you provide more about your configurations and environment?

At same time, options.operationExpiryTime or options.maximumExecutionTimeInMs should help in this case, FYI.

Thanks,
Jiachen
