### ISSUE TITLE
Can't resolve 'fs' in '[...]/node_modules/azure-storage/lib/services/file'

### ISSUE THREAD

**Issue by bastoune** [Azure/azure-storage-node#496]
I would like to upload a file from a html form using webpack & reactjs

As soon as i import azure-storage in some of my file I get this error

```ERROR in ./node_modules/azure-storage/lib/services/file/fileservice.node.js
Module not found: Error: Can't resolve 'fs' in '[...]/node_modules/azure-storage/lib/services/file'
 @ ./node_modules/azure-storage/lib/services/file/fileservice.node.js 20:9-22
 @ ./node_modules/azure-storage/lib/azure-storage.js
 @ ./src/app/Services/Config/azure.js
 @ ./src/app/Services/Config/index.js
 @ ./src/app/App.jsx
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?[...]
```

Here are first lines of my code :

```
import AzureStorage from 'azure-storage'

const fileUri = 'https://MY-CONTAINER.blob.core.windows.net'
const sasToken = 'MY-SAS-TOKEN'

export const AzureFileService = AzureStorage.File.createFileServiceWithSas(fileUri, sasToken)
export default AzureFileService
```

**Comment by XiaoningLiu** [comment]
hi @bastoune 

Do you import azure-storage from npm package? Currently, please download our JS bundled files to be used in your browser applications.

https://aka.ms/downloadazurestoragejs

**Comment by bastoune** [comment]
Yes I do.
Thanks for the help, finally I decided to re-write the XHR Calls I need.

**Comment by chenxizhang** [comment]
> Yes I do.
> Thanks for the help, finally I decided to re-write the XHR Calls I need.

I found the same error, how to solve this?
