### ISSUE TITLE
Long delay when using createWriteStreamToBlockBlob

### ISSUE THREAD

**Issue by brownbl1** [Azure/azure-storage-node#500]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
2.10.1

### What's the Node.js/Browser version?
8.9.4

### What problem was encountered?
There is an unaccounted for delay between the last `stream.on('data')` event and the `on('finish')` event. The delay is shorter for small files but quite large for larger files. 

### Steps to reproduce the issue?
Here is the code I am using:
```js
const sendStream = (stream, sasString) => {
  const sasUrl = new URL(sasString)
  const [container, ...rest] = sasUrl.pathname.slice(1).split('/')

  const blobService = azure.createBlobServiceWithSas(
    sasUrl.origin,
    sasUrl.search
  )

  // blobService.singleBlobPutThresholdInBytes = 2048 * 2048

  return new Promise((resolve, reject) => {
    const writeStream = blobService.createWriteStreamToBlockBlob(
      container,
      rest.join('/'),
      {
        blockSize: 1e8,
        parallelOperationThreadCount: 10,
      },
      error => error && reject(error)
    )

    const startTime = new Date()
    let endTime = new Date(),
      bytes = 0,
      i = 0
    stream
      .on('data', chunk => {
        bytes = bytes + chunk.length
        i++
        endTime = new Date()
        console.log(`received ${bytes} total bytes - ${i}`)
      })
      .pipe(writeStream)
      .on('finish', () => {
        console.log('start:', startTime.toTimeString())
        console.log('end:', endTime.toTimeString())
        console.log('finish:', new Date().toTimeString())
        resolve()
      })
      .on('error', reject)
  })
}
```

### Have you found a mitigation/solution?
I have tried to debug exactly what is going on between those two events. My understanding was that `createWriteStreamToBlockBlob` would send data to azure as the stream is being read instead of waiting to read the entire thing. It would be helpful to have some sort of progress event for large files (over 1GB). 

At the very least, is there a way to enable some sort of logging to help me understand how I could optimize this upload?

**Comment by brownbl1** [comment]
For example, my latest timing with a 100 MB file is:
start: 11:10:35
end: 11:10:36
finish: 11:13:01

**Comment by XiaoningLiu** [comment]
Hi @brownbl1,

Delay is excepted according to your network situation. When you get last 'data' event and update `endTime`, it means the data is read from disk and cached into memory. At this moment, the data needs to be updated to storage server. There may be more data cached into the memory according to your network.

For your first example, it takes about 1 second to read 100MB from disk to memory cache. But it takes 2+ mins to finish the uploading.

There is a public website built by some Azure lovers, you can used it testing your storage upload speed and latency.

http://www.azurespeed.com/Azure/Upload

At the same time, you can use `createBlockBlobFromStream()`, which will return a `SpeedSummary` object, there is a `progress` event.

```
speedSummary.on('progress', function () {
    var process = speedSummary.getCompletePercent();
    displayProcess(process);
});
```

And you can enable the debug log, by
```
blobService.logger.level = "debug"
```

**Comment by brownbl1** [comment]
Thanks for your clarifying comments!
