### ISSUE TITLE
Uploading using SasToken & createBlockBlobFromBrowserFile duplicates containerName in path

### ISSUE THREAD

**Issue by joelburke** [Azure/azure-storage-node#502]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
2.10.1

### What's the Node.js/Browser version?
Node 8.11.3

### What problem was encountered?
When using AzureStorage.Blob.createBlobServiceWithSas with createBlockBlobFromBrowserFile, the container name gets duplicated into the path incorrectly.  Instead of `[container]/imports/fileName` it is placed in `[container]/[container]/imports/fileName`.

I think this is because the container name is specified in the token AND the call to createBlockBlobFromBrowserFile.

Example from below, where `epoch` is the container name: 
Desired path to uploaded file: `epoch/FileImports/20180815012317347-000025732-upload.xlsx`
Actual path to uploaded file:  `epoch/epoch/FileImports/20180815012317347-000025732-upload.xlsx`

### Steps to reproduce the issue?
Generate Token for Blob

```javascript
var sas = {
        uri: '',
        token: '',
        expireDate: ''
    };
var blobService;
$.ajax({
    type: "POST",
    url: "@Url.Action("GetToken", "Sas")",
    async: false,
    success: function (data) {
        sas.uri = data.Uri;
        sas.token = data.Token;
        sas.expireDate = data.ExpireDate;
        blobService = AzureStorage.Blob.createBlobServiceWithSas(sas.uri, sas.token);

    }
});

var blockSize = file.size > 1024 * 1024 * 32 ? 1024 * 1024 * 4 : 1024 * 512;
var options = {
    blockSize : blockSize
};

blobService.singleBlobPutThresholdInBytes = blockSize;
fileName = prefixWithTimestamp + '-' + userId + '-' + file.name; //example: FileImports/20180815012317347-000025732-upload.xlsx
//containerName = epoch
blobService.createBlockBlobFromBrowserFile('epoch',
    fileName,
    file,
    options,
    (error, result) => {
        if (!error) {
            alert('success');
        }
    });

```

c# endpoint to return token
```c#
[HttpPost]
public ActionResult GetToken()
{
	//Parse the connection string and return a reference to the storage account.
    CloudStorageAccount storageAccount =
        CloudStorageAccount.Parse(_storageConnectionString);

    //Create the blob client object.
    CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();

    //Get a reference to a container to use for the sample code, and create it if it does not exist.
    //_blobContainerName = epoch
    CloudBlobContainer container =
        blobClient.GetContainerReference(_blobContainerName);
            
    //Set the expiry time and permissions for the container.
    //In this case no start time is specified, so the shared access signature becomes valid immediately.
    var sharedAccessExpiryTime = DateTimeOffset.UtcNow.AddHours(hoursToExpire);
    SharedAccessBlobPolicy sasConstraints =
        new SharedAccessBlobPolicy
        {
            SharedAccessExpiryTime = sharedAccessExpiryTime,
            Permissions = SharedAccessBlobPermissions.List | SharedAccessBlobPermissions.Write
        };

    //Generate the shared access signature on the container, setting the constraints directly on the signature.
    string sasContainerToken = container.GetSharedAccessSignature(sasConstraints);

    //Return the URI string for the container, including the SAS token.    
    return new SasDto { Uri = container.Uri.ToString(), Token = sasContainerToken, ExpireDate = sharedAccessExpiryTime.ToString() };
}
```

### Have you found a mitigation/solution?
No, other than leaving the uploaded file in the incorrect location.

**Comment by jiacfan** [comment]
Hi, @joelburke 

Welcome to discuss the problem.

Would you describe how you use `createResourceName`? As I know `createResourceName` is used internally in method `generateSharedAccessSignature`, and I see it's not used in your sample code.

Thanks,
Jiachen

**Comment by joelburke** [comment]
@jiacfan I do not use it.  I was digging through the source code and noticed `createResourceName`.  By changing it, it seems to have the 'fixed' the issue I was having.  I was considering submitting a PR, but wanted to submit an issue and get feedback before doing so, in case I was doing something incorrectly in my implementation.

**Comment by jiacfan** [comment]
@joelburke 

As you know, `createResourceName` is only used by `generateSharedAccessSignature`, and `generateSharedAccessSignature` is not used in your code, could you illustrate more about how `createResourceName` can help to solve your problem?

At same time `createResourceName` 's behavior is by design currently.

Thanks,
Jiachen

**Comment by gmantri** [comment]
@joelburke I think the issue is in the code and not SDK. Essentially `AzureStorage.Blob.createBlobServiceWithSas` expects the URI to be that of the storage account i.e. `https://account-name.blob.core.windows.net` however you're using blob container's URI (`https://account-name.blob.core.windows.net/epoch`) there. That's why the container name is repeated twice. From your API, you should simply return storage account's blob endpoint and you should not see this error.

**Comment by gmantri** [comment]
@joelburke For #2, you don't have to do anything special. CloudStorageAccount has a property called [`BlobEndpoint`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.cloudstorageaccount.blobendpoint?view=azure-dotnet). You can simply use that.

**Comment by joelburke** [comment]
@gmantri Excellent!  I missed this.  Consider this issue closed with another case of "User Error" ;)
