### ISSUE TITLE
ANNOUNCEMENT: The new Azure Storage SDK for JavaScript

### ISSUE THREAD

**Issue by seguler** [Azure/azure-storage-node#507]
Hello everyone!

We'd like to announce that we are working on a completely new SDK for Storage, based on TypeScript. With this new SDK, we'd like to address many of the long-standing requests such as:

- Async/Promise support
- More up to date TypeScript definitions
- Webpack support through NPM
- HttpClient injection
- Http Pipeline policies to better manpuilate HTTP requests and responses

The new SDK follows the V10 architecture announced earlier with the [Go](https://github.com/Azure/azure-storage-blob-go) and [Java SDKs](https://github.com/Azure/azure-storage-java/tree/New-Storage-SDK-V10-Preview). The SDK will be hosted at https://github.com/Azure/azure-storage-js and you can review the initial design in the following PR: https://github.com/Azure/azure-storage-js/pull/1

The preview release is scheduled for September 2018, and will support Blob storage only in the first release. 

@XiaoningLiu @RikkiGibson @JeffreyRichter 

Thanks!

**Comment by christiannwamba** [comment]
@seguler was this finally released?

**Comment by JeffreyRichter** [comment]
Yes, the new library is released.
