### ISSUE TITLE
xmlbuilder 0.4.3 security issue

### ISSUE THREAD

**Issue by npapp** [Azure/azure-storage-node#509]
I just wanted to leave a note for you about a security issue (Regular Expression Denial of Service) in the xmlbuilder version you use.

They fixed the issue here:
https://github.com/oozcitak/xmlbuilder-js/commit/bbf929a8a54f0d012bdc44cbe622fdeda2509230#diff-932aadb1c67754c23df1fe0c40af1319R52

(our security scanning tool found this issue, because we use your library)

**Comment by jiacfan** [comment]
Hi, @npapp 

Thanks for reporting the issue, we'll investigate it and try to fix it in recent release.

Thanks,
Jiachen

**Comment by jiacfan** [comment]
Close as fixed.
