### ISSUE TITLE
what is the recommended version of node for the sdk

### ISSUE THREAD

**Issue by sushilbaid** [Azure/azure-storage-node#51]
I could not find the compatibility details about node versions & sdk. Hence, opening the issue to get the details.

I have been using it with node 0.10.33 & azure-storage 0.3.3 for last couple of months & found it very stable & no performance issues. Recently I am trying to upgrade to node 0.12 and azure-storage 0.4.3 find high CPU usage & socket hang errors. 

While I am looking into the issues, I wanted to check the compatibility of the sdk with node current version 0.12?

**Comment by yaxia** [comment]
@sushilbaid Thanks for bring it to us. Would you please share some more information:
* What are the current and previous CPU usage/socket hang-up number?
* Which functions and options were you using?
* Was the socket hang error: “Error: socket hang up” from http.js or something else?

**Comment by sushilbaid** [comment]
@yaxia thanks for follow up. My current production setup is node 0.10.33, azure-storage 0.3.3, solr 4.7.2

In current setup - cpu usage goes high but occasionally. does not remain there. no socket hang ups.

tableclient.insertEntity is in the code path. Also the test code was making many more parallel calls (order of 500) where as in the upgraded setup I changed code to reduce the parallel calls to order of 50.

yes from http.

I would like to put disclaimer that I have not got to the root cause. bcos this code was working fine on earlier setup  - I was checking for the compatibility of azure-storage and node 0.12.

**Comment by yaxia** [comment]
Thanks for the information. We will keep an eye on it.
As to your concern about the compatibility, yes, azure-storage is compatible with Nodejs 0.12.
