### ISSUE TITLE
The chunk divided from createBlockBlobFromBrowserFile is not expected

### ISSUE THREAD

**Issue by daiict218** [Azure/azure-storage-node#510]
### Which service(blob, file, queue, table) does this issue concern?
For blob service

### Which version of the SDK was used?
v2.9.0-preview

### What's the Node.js/Browser version?
Browser version : Version 68.0.3440.106 Google Chrome

### What problem was encountered?
The chunk division is not expected. I tried uploading a 17MB file on azure-storage and send a chunk size of 3MB in `createBlockBlobFromBrowserFile` but instead multiple chunks, only 1 call is being made of 17MB chunk

### Have you found a mitigation/solution?
No

**Comment by XiaoningLiu** [comment]
@daiict218 Please customize `blobService.singleBlobPutThresholdInBytes = customBlockSize`. By default, blob smaller than 32MB will be uploaded via 1 call. You need a smaller threshold value.

**Comment by daiict218** [comment]
Thanks @XiaoningLiu
