### ISSUE TITLE
ServicePropertiesResult.parse doesn't handle undefined/null

### ISSUE THREAD

**Issue by xt0rted** [Azure/azure-storage-node#511]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
2.10.0

### What's the Node.js/Browser version?
Not sure, found the issue in 1.4.1 of the Storage Explorer which is version 2.0.0 of Electron

### What problem was encountered?
The request is succeeding but `responseObject.response.body.StorageServiceProperties` is `undefined`
https://github.com/Azure/azure-storage-node/blob/d7b7e16f7d7e08852f4fa1fb477acbdf0cc281d7/lib/common/services/storageserviceclient.js#L1084

This causes the following method to throw https://github.com/Azure/azure-storage-node/blob/d7b7e16f7d7e08852f4fa1fb477acbdf0cc281d7/lib/common/models/servicepropertiesresult.js#L455-L487

### Steps to reproduce the issue?
Call `ServicePropertiesResult.parse()` with an `undefined` or `null` value

### Have you found a mitigation/solution?

Check the `servicePropertiesXml` for `undefined`/`null` and return `{}` instead of continuing to check for it's properties.

### More information

I'm using the Storage Explorer against 2.6.5 of Azurite via Docker. When I try to delete a blob from it nothing happens. After digging into this more I found the issue looks to be coming from the node sdk.

Original conversation https://github.com/Microsoft/AzureStorageExplorer/issues/60#issuecomment-417809216

**Comment by xt0rted** [comment]
cc @edwin-huber in case this is actually an Azurite implementation issue

**Comment by jiacfan** [comment]
Hi, @xt0rted 

Thanks for reaching us.

As you described, the issue happens when using `getAccountServiceProperties` API(inner Storage Explorer) against 2.6.5 of Azurite. You know as REST api of [GetBlobServiceProperties](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-service-properties), the `StorageServiceProperties` would not be undefined/null.
@XiaoningLiu as well, is `GetBlobServiceProperties` in Azurite a to-fulfill function in 2.6.5 version?

Thanks,
Jiachen

**Comment by XiaoningLiu** [comment]
@xt0rted please open an issue in Azurite repo, according to Azure Storage REST API design, the `StorageServiceProperties` cannot be null.

**Comment by xt0rted** [comment]
I reported this in the Azurite repo

**Comment by edwin-huber** [comment]
Thanks, yes, we need to fix up the API, there are still a number of missing features an properties in responses.
