### ISSUE TITLE
Why are the results of getMessage in an array with one instance of QueueMessageResult ?

### ISSUE THREAD

**Issue by jtara1** [Azure/azure-storage-node#512]
### Which service(blob, file, queue, table) does this issue concern?
queue

### Which version of the SDK was used?
azure-storage@2.10.1

### What's the Node.js/Browser version?
7.10.1

output from a console.log from within the callback for getMessage would look something like this 
```
[ QueueMessageResult {
    messageId: '123',
    insertionTime: 'Tue, 04 Sep 2018 21:29:18 GMT',
    expirationTime: 'Tue, 11 Sep 2018 21:29:18 GMT',
    popReceipt: '123=',
    timeNextVisible: 'Tue, 04 Sep 2018 21:29:48 GMT',
    dequeueCount: 1,
    messageText: '{"msg":"hi"}' } ]
```

when would the length of the array be greater than 1?

**Comment by jiacfan** [comment]
Hi, @jtara1 

Thanks for reaching us, as the definition of REST API [Get Messages](https://docs.microsoft.com/en-us/rest/api/storageservices/get-messages), user can define `numofmessages` in URI parameter, in this case there will be multiple queue messages returned, and SDK is mapping to this REST API definition.

In node.js client library, user can get multiple messages with one call using code like following:
`queueService.getMessages(queueName, { numOfMessages: 2 }, function (error, messages) {
...
}`

Best Regards,
Jiachen
