### ISSUE TITLE
[Question] Resume createBlockBlobFromLocalFile when it breaks for any reason

### ISSUE THREAD

**Issue by vohtaski** [Azure/azure-storage-node#513]
I am using `createBlockBlobFromLocalFile` to upload big files (upto 10-12GB).
The library breaks the file into blocks, then uploads them and commits the blocks into a blob.

If the process of uploading breaks for any reason and I start the function again on the same file, it starts from the beginning (for example when 8GB out of 10GB were already downloaded)

Is it the intended behaviour? Do I have to implement myself resuming and blocks management if I want to resume upload after a failure from where it stopped or there is such functionality already?

**Comment by XiaoningLiu** [comment]
Hi @vohtaski 

Yes, it's intended behavior. Recommend enabling retry mechanism to avoid such breaking. You can can define maxRetries, retry intervals and etc. 

```
exponentialRetryPolicyFilter = new ExponentialRetryPolicyFilter();
const blobService = blobService.withFilter(exponentialRetryPolicyFilter);
```

There are 4 parameters for `ExponentialRetryPolicyFilter` constructor.
```
* @param {number} [retryCount=3]            The client retry count.
* @param {number} [retryInterval=30000]     The client retry interval, in milliseconds.
* @param {number} [minRetryInterval=3000]   The minimum retry interval, in milliseconds.
* @param {number} [maxRetryInterval=90000]  The maximum retry interval, in milliseconds.
```

**Comment by vohtaski** [comment]
Thanks a lot for your answer!

Will it retry to upload only missing blocks or will it try to upload from the beginning (if the file is 10GB)?
