### ISSUE TITLE
Invalid types on listBlobsSegmented

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-storage-node#515]
`listBlobsSegmented`'s TypeScript type interface only accepts `ContinuationToken`, but [the docs](https://docs.microsoft.com/en-us/javascript/api/azure-storage/azurestorage.services.blob.blobservice.blobservice?view=azure-node-latest#listblobssegmented) claim the function can accept `null` or `undefined`.  Type interface should be updated to accept `ContinuationToken | null | undefined` to maintain type safety.

The issue was filed incorrectly in the node sdk repo https://github.com/Azure/azure-sdk-for-node/issues/3544. Filing it over here, on behalf of the customer.

I have also experienced this problem. The type definitions needs to be updated. I am currently forcefully typecasting continuationToken to `undefined as any` for the first call to listBlobsSegmented().

**Comment by jiacfan** [comment]
Hi, @amarzavery 

Thanks for reaching us. Yes, this should be optimized. And we'll involve it in next release. 

Best Regards,
Jiachen

**Comment by jiacfan** [comment]
_Status Update_

As this breaks grammars of typescript@1.x which we are currently supporting. This change will be kept temporarily, and will be add in next major release. Add related PR as well,  #378.

Thanks,
Jiachen

**Comment by jiacfan** [comment]
Close as no feedback is collected for months.
