### ISSUE TITLE
Process.version is undefined

### ISSUE THREAD

**Issue by AndreaCorda01** [Azure/azure-storage-node#516]
### Which service(blob, file, queue, table) does this issue concern?

Loading the module

### What's the Node.js/Browser version?

$ node --version
v10.1.0
con vuejs client

### What problem was encountered?
![slack-imgs](https://user-images.githubusercontent.com/3968938/45298334-7c9f9880-b508-11e8-822e-4cbe72ee3982.png)

process.version is undefined and receive an error when the interpret call split of undefined

### Steps to reproduce the issue?

just call the component 
`const azureStorage = require("azure-storage")
`
### Have you found a mitigation/solution?
no

**Comment by carlosanjos** [comment]
@AndreaCorda01 Have you found a solution for this error?

**Comment by AndreaCorda01** [comment]
@carlosanjos No, to solve the problem I removed the library and I used REST APIs

**Comment by XiaoningLiu** [comment]
Please use @azure/storage-blob for browser projects.
