### ISSUE TITLE
Exception when storage is not available

### ISSUE THREAD

**Issue by gluwer** [Azure/azure-storage-node#517]
### Which service(blob, file, queue, table) does this issue concern?
table

### Which version of the SDK was used?
2.10.1

### What's the Node.js/Browser version?
Node.js 8.x

### What problem was encountered?
    responseObject.tableResponse.statusCode = responseObject.response.statusCode;
                                                                      ^

TypeError: Cannot read property 'statusCode' of null
    at processResponseCallback (..\node_modules\azure-storage\lib\services\table\tableservice.js:539:71)

There is an exeception when there is no storage response because storage is not available. If storage is up but returns error, all works fine.

### Steps to reproduce the issue?

Do not start local Storage Emulator and try to create storage table.

### Have you found a mitigation/solution?

Normally not a big issue, but if storage will bot be available (not a HTTP error) this will likely go to unhandledExceptions.

**Comment by XiaoningLiu** [comment]
Thanks @gluwer 

Thanks for reporting! You are right, `response.statusCode` should not be undefined when there is for a normally setup emulator.

Mark this as an error handling enhancement into the backlog.
