### ISSUE TITLE
MOVING FILES? IS IT POSSIBLE?

### ISSUE THREAD

**Issue by andrehsmendes** [Azure/azure-storage-node#518]
Hello,

What would be my options if i want to MOVE files with azure-storage-node?

I'm currently using Azure Files.

Regards

**Comment by XiaoningLiu** [comment]
Hi @andrehsmendes , you can use the async file copy. http://azure.github.io/azure-storage-node/FileService.html#startCopyFile__anchor

Or you can use tools `AzCopy` to move files instead of a SDK.

**Comment by andrehsmendes** [comment]
@XiaoningLiu great, thank you.
