### ISSUE TITLE
Hash mismatch error in `getBlobToText(...)`

### ISSUE THREAD

**Issue by chriskuech** [Azure/azure-storage-node#519]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
2.10.1

### What's the Node.js/Browser version?
8.11.3

### What problem was encountered?
Text blob could not be downloaded using `BlobService.getBlobToText(...)` due to md5 mismatch.  Based on posts online for this error, I believe the function is not inferring the file encoding and parsing the blob with the wrong encoding.

[This SO post](https://stackoverflow.com/questions/30609691/hash-mismatch-integrity-check-failed-with-azure-blob-storage) recommends using HTTPS and `disableContentMD5Validation: true`; however, I am still getting the issue.

### Steps to reproduce the issue?
1. Create `BlobService` instance from connection string
1. Create blob storage container with UTF32 blobs
1. Get blob objects using `BlobService.listBlobsSegmented(...)`; observe MIME is application/octet-stream
1. Read UTF32 blob using `BlobService.getBlobToText(...)`; observe hash mismatch error
1. Add `disableContentMD5Validation: true` option to `getBlobToText(...)`; observe content-length mismatch error

### Have you found a mitigation/solution?
No

**Comment by jiacfan** [comment]
Hi, @chriskuech 

Thanks for reaching us.

Would you please illustrate how you upload UTF32 encoded contents, are you using `createBlobBlobFromStream`.

Would you try to use `getBlobToStream` correspondingly, and do decoding after get raw data?

For `getBlobToText` API, it uses `utf8` for encoding. In more details, when it get's data from response, it's in Buffer type, and toString() uses `utf8` to transfer to text and return to user.

Best Regards,
Jiachen

**Comment by chriskuech** [comment]
I create and upload the files using PowerShell, which uses `utf32` by default.  To resolve, I will just change my PowerShell code.  Based on your description, it sounds like md5 is calculated on the `utf8` string--is this correct?  Also sounds like this is a js issue, not azure-storage-node issue, since js doesn't support `utf32` strings?

**Comment by jiacfan** [comment]
Hi, @chriskuech 

That's great to know that you can solve it in your code.
For other discussions: 
- MD5 is typically calculated based on raw bytes, e.g. text is encoded to raw bytes, and MD5 is calculated based on raw bytes given. 
- azure-storage-node currently doesn't support inject encoding for request.body for `getBlobToText`, to achieve the full encode/decode flexibility, user need to use `getBlobToStream`, and sometimes need to use other packages for proper encoding/decoding.

Thanks,
Jiachen
