### ISSUE TITLE
extend 1.2.1 security issue

### ISSUE THREAD

**Issue by npapp** [Azure/azure-storage-node#521]
Hey, it's me again, I just want to leave another note for you about a security issue (Prototype pollution attack due to Modification of Assumed-Immutable Data) in the extend version you use.

They fixed the issue here:
https://github.com/justmoon/node-extend/pull/48

(our security scanning tool found this issue, because we use your library)

**Comment by XiaoningLiu** [comment]
@npapp Thanks for reporting! Will update to latest extend version.

**Comment by XiaoningLiu** [comment]
In 2.10.3, it updates to latest extent version, thanks for reporting!
