### ISSUE TITLE
Naming schmea not valid for static sites

### ISSUE THREAD

**Issue by itpropro** [Azure/azure-storage-node#522]
https://github.com/Azure/azure-storage-node/blob/d7b7e16f7d7e08852f4fa1fb477acbdf0cc281d7/lib/common/util/validate.js#L185

As static sites containers are generated with a $ sign at the beginning, the following example would work instead of the marked:
  if (name.match(/^([$a-z0-9]+(-[a-z0-9]+)*)$/) === null) {
    return new SyntaxError(util.format('%s name format is incorrect.', typeName));
  }

**Comment by XiaoningLiu** [comment]
Hi 

`$web` should be already escaped in `containerNameIsValid`

https://github.com/Azure/azure-storage-node/blob/d7b7e16f7d7e08852f4fa1fb477acbdf0cc281d7/lib/common/util/validate.js#L197

```javascript
  var nameError = getNameError(containerName, 'Container');

  if (!nameError || containerName.match(/^(\$root|\$logs|\$web)$/)) {
    callback();
    return true;
  } else {
    return fail(nameError);
  }
```
