### ISSUE TITLE
Download all images inside folder created in blob container

### ISSUE THREAD

**Issue by ppriyank40** [Azure/azure-storage-node#528]
Hello,
I am uploading image in Blob storage folder wise. Now, after uploading i want to download all images in that particular folder only. So, for that i have used listBlobsSegmented but its getting all the folders list only. So, how can i achieve this functionality?

### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
Azure Storage JavaScript Client Library 0.2.8-preview.15

**Comment by XiaoningLiu** [comment]
Hi @ppriyank40 ,

Sorry for the late response, we have a holiday last week. Seems you are working for a browser application? If so, it's difficulty to download all images inside folder for a browser application. But what you can do is to display all download links of all blobs inside a folder.

Another question you mentioned "but its getting all the folders list only". `listBlobsSegmented` should list blobs correctly, can you provide sample code for this issue?

**Comment by XiaoningLiu** [comment]
Since this issue is long time no response, we will close this issue. Please re-open it if you have further information.
