### ISSUE TITLE
I'm recieving intermittent "Error: NotFound" when attempting to stream files from Azure storage blobs.

### ISSUE THREAD

**Issue by jrthib** [Azure/azure-storage-node#53]
I'm not sure where to even start with debugging this. It is intermittent in the sense that sometimes the files stream correctly, and sometimes the same file returns a "NotFound" error. Any ideas?

I've confirmed that both the file and the container exist. The storage container that I'm uploading to is geo-redundant. Is there a delay between when the file is uploaded and becomes available for reading? I'm usually firing these operations immediately after one another.

File uploaded to azure container -> create read stream -> stream the file and parse it's contents line-by-line.

```
            var readStream = blobService.createReadStream(container, filename, function(err) {
                if(err) {
                    logger.error({err: err});
                    done(err);
                } else {
                    csv.fromStream(readStream, {
                        headers: true,
                        objectMode: true,
                        ignoreEmpty: true
                    })
                    .on('data', readLine)
                    .on('error', handleError)
                    .on('end', handleEnd);
                }
            });
```

**Comment by hasonmsft** [comment]
@jrthib , is this still a blocker for you? From your description of this issue, the geo-replication latency should be the root cause of your issue. 

And to debug this, you can turn on the DEBUG log to collect more info. 

blobService.logger.level = 'debug';

http://azure.github.io/azure-storage-node/BlobService.html#toc5
