### ISSUE TITLE
Unable to view a specific blob using listBlobsSegmentedWithPrefix function

### ISSUE THREAD

**Issue by shraboin** [Azure/azure-storage-node#530]
### Which service(blob, file, queue, table) does this issue concern?

Blob
### Which version of the SDK was used?
1.3.2

### What's the Node.js/Browser version?

4.6.2
### What problem was encountered?

Unable
### Steps to reproduce the issue?
 [Seeing the blob in Portal](https://shraboinarmstorage.blob.core.windows.net/support/PortalOutput-good.png)

Output from Console: 
GET https://e5c74294eaf04cca90cedmgt.blob.core.windows.net/installers?restype=container&comp=list&prefix=&delimiter=%2F&marker=&maxresults=30&include=metadata&_=1538579308511 403 (This request is not authorized to perform this operation using this permission.)

GET https://e5c74294eaf04cca90cedmgt.blob.core.windows.net/installers?restype=container&comp=list&prefix=&delimiter=%2F&marker=2!100!MDAwMDI5IUVkZ2VTZXJ2ZXItYmFkMWE1YjNhLVNoaW0uemlwITAwMDAyOCExNjAxLTAxLTAxVDAwOjAwOjAwLjAwMDAwMDBaIQ--&maxresults=30&include=metadata&_=1538579310906 403 (This request is not authorized to perform this operation using this permission.)
(ignore the 403s)

[Output from Node JS](https://shraboinarmstorage.blob.core.windows.net/support/NodeJsBad.png)

Strange enough when they add a blob they can see that newly added blob but the blob in question still does not show up:
[Node JS not working](https://shraboinarmstorage.blob.core.windows.net/support/NodeJsBad2.png)
[Storage explorer](https://shraboinarmstorage.blob.core.windows.net/support/storageExplorer.png)

Here is there code sample:
`const availableVersions = managementBlobs.listBlobsInContainer(installerContainer);

self.listBlobsInContainer = function (containerName, prefix) {
  return listBlobsInContainer(self.context, containerName, prefix);
};

function listBlobsInContainer(context, containerName, prefix, baseBlobService) {
  try {
    let maxRetries = 5;
    baseBlobService = baseBlobService || getBlobService(context);
    return execRetryOp(`listBlobsInContainer('${containerName}', '${prefix}')`, () => {
      return listBlobsInContainerSync(containerName, prefix, baseBlobService);
    }, maxRetries);
  } catch (err) {
    logger.error(`listBlobsInContainer(${containerName}, ${prefix}): ${util.inspect(err)}`);
    throw err;
  }
}

function listBlobsInContainerAsync(containerName, prefix, baseBlobService, callback) {
  callback = Core.makeOnceContext()(callback);
  baseBlobService.listBlobsSegmentedWithPrefix(containerName, prefix, null, callback);
}

Blobservice.js

BlobService.prototype.listBlobsSegmentedWithPrefix = function (container, prefix, currentToken, optionsOrCallback, callback) {
  this._listBlobsOrDircotriesSegmentedWithPrefix(container, prefix, currentToken, BlobConstants.ListBlobTypes.Blob, optionsOrCallback, callback);
};
`

### Have you found a mitigation/solution?
We are looking for a root cause

I am a support engineer for Azure Storage. This is for case 118100319148559 on behalf of Ben Hagaman <bhagaman@statrad.com>. You can reach me shraboin@Microsoft.com

**Comment by XiaoningLiu** [comment]
@shraboin Sorry for the late response, we had a holiday last week.

The question is "cannot list all blobs under a container?" If so, please make sure the `containuationToken` is not null. If not null, it means the list results are not complete, please send another list operation with this token, to get following results.
