### ISSUE TITLE
Documentation for queues should contain something about Base64 encoding

### ISSUE THREAD

**Issue by graham-sportsmgmt** [Azure/azure-storage-node#532]
I've just wasted a lot of time trying to figure out how to pass a message from the sdk into a queue then get picked up by a Queue Trigger Azure Function.  The Function was not running due to message formatting (error below).

In the end I needed to manually base64 encode the message, but the sdk docs mentioned nothing about this.  It might be nice to mention this in the docs that the default is for listeners to expect base64.  It would be even better to do this base64 encoding for us using an option in the sdk.

Code used to encode and send:

```
  options.message = Buffer.from(options.message).toString('base64');

  queueService.createMessage(options.queue, options.message, function(err, results, response){

    console.log(`Message queued:\n${JSON.stringify(options,null,2)}\nError:\n${JSON.stringify(err,null,2)}\nResults:\n${JSON.stringify(results,null,2)}\nResponse:\n${JSON.stringify(response,null,2)}`);

    callback(err);

  });
```

Error message from Queue Listener Function:

> [10/6/2018 4:23:28 PM] System.Private.CoreLib: Exception while executing function: Functions.Q-Emailer. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'myQueueItem'. System.Private.CoreLib: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

**Comment by XiaoningLiu** [comment]
@graham-sportsmgmt sorry for the inconvenience.

There is no strict rule to base64 encode message content. According to https://docs.microsoft.com/en-us/rest/api/storageservices/put-message , XML escape or base64 are both ok.

```
A message must be in a format that can be included in an XML request with UTF-8 encoding. To include markup in the message, the contents of the message must either be XML-escaped or Base64-encode. Any XML markup in the message that is not escaped or encoded will be removed before the message is added to the queue.
```

But seems Azure Function defaults needs a base64 encoded string. We can add some document as tips.

**Comment by graham-sportsmgmt** [comment]
I tried the XML escape and it didn't work for me.  Regardless this guide should probably show either Base64 or XML escaping, as the current code sample has neither and won't work as it stands.
