### ISSUE TITLE
How to upload a file using SAS URL

### ISSUE THREAD

**Issue by Coobik** [Azure/azure-storage-node#534]
HI all,

I have a SAS URL I got from Azure container registry (getBuildSourceUploadUrl)

URL looks like this:
https://weumanagedXX.blob.core.windows.net/CONTAINER_REGISTRY_ID/source/201810100000/UUID.tar.gz?sv=2018-03-28&sr=b&sig=SIGNATURE&se=2018-10-10T16%3A12%3A07Z&sp=cw

How can I use Azure Storage client lib for node.js to upload a file having just that URL?
I cannot find a way to do so with BlobService as it requires specifying container and other things.
Thanks!

**Comment by XiaoningLiu** [comment]
@jiacfan may help you with the legacy azure-storage package.

My recommendation is to use the new released @azure/storage-blob package, in this package you can:
https://www.npmjs.com/package/@azure/storage-blob

```javascript
const { BlockBlobURL, StorageURL, AnonymousCredential, uploadFileToBlockBlob } = require("@azure/storage-blob");

const blockBlobURL = new BlockBlobURL("yourBlobSASURL", StorageURL.newPipeline(new AnonymousCredential()));

uploadFileToBlockBlob(Aborter.none, localFilePath, blockBlobURL, {
    blockSize: 4 * 1024 * 1024, // 4MB block size
    parallelism: 20, // 20 concurrency
    progress: ev => console.log(ev)
}).then(() => {console.log("Upload Finished");});
```
