### ISSUE TITLE
What is the best way to get the latest record belonging to a partition key?

### ISSUE THREAD

**Issue by DanaEpp** [Azure/azure-storage-node#539]
Can someone recommend the best solution for getting the latest record belonging to a partition key? Since there is no .orderBy() option... what is the best approach?

In C# I would probably do something like:

`var latestRecord = results.OrderByDescending(r => r.Timestamp).FirstOrDefault();`

What would the equivalent be when using this node library for Table Storage?

**Comment by XiaoningLiu** [comment]
Sorry for the late response, but I'm afraid there is no such API provided by Table server. 

As of today, Table Service does not support Order By. Please see the list of supported LINQ Operators here: https://msdn.microsoft.com/en-us/library/azure/dd135725.aspx.

What you would need to do is fetch the data (which will be sorted by PartitionKey and RowKey) and the apply sorting on client side.
