### ISSUE TITLE
Address 1 security vulnerability and 10 outdated npm dependencies [Opened by bitHound]

### ISSUE THREAD

**Issue by Cecildt** [Azure/azure-storage-node#54]
bitHound discovered [validator isURL Regular Expression Denial of Service](https://nodesecurity.io/advisories/validator-isurl-denial-of-service) security vulnerability and 10 outdated npm dependencies. For details go to [bitHound](https://www.bithound.io/github/Azure/azure-storage-node/dependencies/npm).

**Comment by slepox** [comment]
validator module is updated to 3.22.2 in release 0.4.4.
