### ISSUE TITLE
ERROR TypeError: crypto.createHmac is not a function

### ISSUE THREAD

**Issue by dineshPallapa** [Azure/azure-storage-node#543]
### Which service(blob, file, queue, table) does this issue concern?
blob service

### Which version of the SDK was used?
"azure-storage": "2.5.0",

### What's the Node.js/Browser version?
v8.12.0
angular 5

### What problem was encountered?
ERROR TypeError: crypto.createHmac is not a function
      at HmacSha256Sign.sign 
      at SharedKey.signRequest 
      at BlobService.StorageServiceClient._buildRequestOptions 
      at operation 
      at eval 
      at BlobService.filter 
      at BlobService.StorageServiceClient._performRequest 
      at BlobService.StorageServiceClient.performRequest 
      at BlobService._doesContainerExist 
      at BlobService.doesContainerExist 

### Steps to reproduce the issue?
import * as azure  from 'azure-storage';

this.blobService = azure.createBlobService(azure_account_name, azure_account_key)

this.blobService1.doesContainerExist('uploads', (error, result, response) => {
      if (error) {
        console.log('Couldn\'t create container', response);
        console.error(error);
      } else if (result) {
        console.log(`Container "${azure_container_name}" created`);
      } else {
        console.log(`Container "${azure_container_name}" already exists`);
      }
    });

### Have you found a mitigation/solution?
Need community support for this issue.

**Comment by jiacfan** [comment]
Hi, @dineshPallapa 

Thanks for reaching us, the error message shows crypto could be not imported correctly, would you check if crypto is imported correctly, is the correct version with createHmac function imported.

At same time, FYI, we have new arch client library being preview, which has clear dependencies, and worth trying, [Storage SDK v10 for JavaScript](https://github.com/Azure/azure-storage-js).

Best Regards,
Jiachen

**Comment by dineshPallapa** [comment]
Can you help me in finding crypto path using for azure-storage-node.
