### ISSUE TITLE
how to cancel uploading using createBlockBlobFromBrowserFile?

### ISSUE THREAD

**Issue by mrcnw** [Azure/azure-storage-node#544]
is there any possible idea to solution to cancel uploading?

**Comment by mrcnw** [comment]
@XiaoningLiu , thank you for your answer.
Please correct me if I'm wrong but the solution of Cancel Upload which you refered to, cancels all blob / chunks requests.
 
My need is slightly different.
Let's say that my application uploads 10 files in parallel. For some reason, the end user would like to stop uploading of one particular file.
How can I cancel chunk requests related only to this file without stopping other files from uploading?
 
I would be very grateful for the advice on this matter.

**Comment by XiaoningLiu** [comment]
@mrcnw My recommendation is to use the new Azure Storage SDK https://github.com/Azure/azure-storage-js/issues/24 , it's much easier.

For legacy SDK, you need to implement a customized filter mentioned in #317 . In this filter you could cancel a uploading. But the filter is 1:1 mapping to `blobService` object. If you want to cancel only one of all uploads, you could create different `blobService` objects per uploading and create some token or signal into the filter in #317. For example,

```javascript
var blobService = Azure.createBlobServiceWithSas();

var token1 = { cancel: false };
var blobService1 = blobService.withFilter(newCancelFilter(token1));

var token2 = { cancel: false };
var blobService2 = blobService.withFilter(newCancelFilter(token2));

function newCancelFilter(token) {
    return {
    handle: (requestOptions, next) => {
      if (token.cancel) {
        return;
      }

      // Call next filter
      if (next) {
        next(requestOptions, function(
          returnObject,
          finalCallback,
          nextPostCallback
        ) {
          if (token.cancel) {
            return;
          }

          if (nextPostCallback) {
            nextPostCallback(returnObject);
          } else if (finalCallback) {
            finalCallback(returnObject);
          }
        });
      }
    }
  }; 
}
```
