### ISSUE TITLE
Can't pass null as continuation token (typing issue)

### ISSUE THREAD

**Issue by WonSong** [Azure/azure-storage-node#545]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the SDK was used?
2.10.2

### What's the Node.js/Browser version?
10.13.0

### What problem was encountered?
Typing issue

### Steps to reproduce the issue?
Try to pass null as continuation token

### Have you found a mitigation/solution?
No

![screen shot 2018-11-19 at 10 57 41 am](https://user-images.githubusercontent.com/5981331/48728497-f7142500-ebe9-11e8-8cd2-643cadbc8ec3.png)

while the comment says:

```
A continuation token returned by a previous listing operation. 
Please use 'null' or 'undefined' if this is the first operation.
```

**Comment by glister** [comment]
Also related to this is you can't pass `null` or the callback for the next parameter `options: TableService.TableEntityRequestOptions` either which is optional according to the actual function signature `function (table, tableQuery, currentToken, optionsOrCallback, callback)`

**Comment by jiacfan** [comment]
Thanks for reaching us, and thanks @glister  for providing work around. We'll try to fix this issue in next major release.

**Comment by OlivierKamers** [comment]
Hi @jiacfan do you have an update on this issue?
