### ISSUE TITLE
Upload image - createblockblobfromtext from Bot framework

### ISSUE THREAD

**Issue by esanchezlMBT** [Azure/azure-storage-node#546]
### Issue
I'm working on a bot to __upload an image__ to azure-blob, I'm using the method __createBlockBlobFromText__ to encoded a base64 image, when I test my code from the bot framework emulator (v4) it's successful, but when I publish the code in azure instead of upload an image file, __it uploads an html file.__ I wonder how it is possible. Even when I'm using the __content-settings: image / jpeg__ in the function .
Here is the code.

`var base64Img = require(base64-img);`
`var azurest = require('azure-storage');`
`var blobService = azurest.createBlobService('storageaccount', 'accesskey');`

`base64Img.requestBase64(url, function(err, res, body) { `
` if (!err) {`
`var matches = body.split(','); `

`//Here start the issue`
`//body: In Emulator returns data:application/octet-stream;base64`
`//body: In Azure returns data:text/html; charset=UTF-8;base64` __why?__
`console.log(body);`

`console.log(matches[0]);`
`var buffer = new Buffer(matches[1], 'base64');`
`blobService.createBlockBlobFromText(blobcontainer, "image.jpg", buffer, { contentSettings: { contentType: image/jpeg } }  function(error, result, response) {
`
### Does anyone have an idea of a solution?

Thanks & Regards,
Emiliano Sánchez

**Comment by XiaoningLiu** [comment]
Hi @esanchezlMBT 

The `body` is generated by `base64Img.requestBase64`. Should you debug with `base64Img`?

**Comment by esanchezlMBT** [comment]
Hi @XiaoningLiu Thanks for answering, it does not have to be necessary to debug with **base64Img**, actualy I have decided to change from library to **image-to-base64**, this library saves me the step of split the response and it has worked perfectly for me. Here is the solution:

`var image2base64 = require('image-to-base64');`
`var azurest = require('azure-storage');`
`var blobService = azurest.createBlobService('storageaccount', 'accesskey');`

`image2base64(url)`
`.then(`
`(response) => {`

`// Here is the magic, the answer does not bring data: text / html, etc. just the chunk`
`// console.log(response); //iVBORw0KGgoAAAANSwCAIA...`

`var buffer = new Buffer(response, 'base64');`
`blobService.createBlockBlobFromText(config.blobcontainer,  session.dialogData.ticket+'_Resguardo.'+ctype, buffer,  function(error, result, response) {`
`if (!error) {`
`console.log('El archivo ${session.dialogData.ticket}_${attachment.name}.${ctype} se ha subido correctamente');`
   `                         
}
else{
console.log('Hubo un error: '+ error);
}
});
}
)
.catch(
(error) => {
console.log(error); //Exepection error....
}
);`

**Oooooh can do!!**
Emiliano Sánchez
