### ISSUE TITLE
Wrong regex expression in validator

### ISSUE THREAD

**Issue by itpropro** [Azure/azure-storage-node#547]
Deployment to static sites or logs is not possible, as the target container is called $web (or $logs). The name check throws "Container name format is incorrect." as the regex doesn't include a dollar sign.

**Possible Fix**
Add a dollar sign to the regex:
/^([$a-z0-9]+(-[a-z0-9]+)*)$/

https://github.com/Azure/azure-storage-node/blob/0557d02cd2116046db1a2d7fc61a74aa28c8b557/lib/common/util/validate.js#L185

**Comment by XiaoningLiu** [comment]
@itpropro which version SDK are you using? please update to latest and try again, $web and $logs container names are already supported.

**Comment by itpropro** [comment]
I am using the most current version, directly pulled with npm.

**Comment by XiaoningLiu** [comment]
Please share your code for us to re-produce, because following line of code has been updated to accept $root $log and $web.

```javascript
exports.containerNameIsValid = function (containerName, callback) {
  var fail;
  initCallback(callback, function (f, cb) {
    fail = f;
    callback = cb;
  });

  var nameError = getNameError(containerName, 'Container');

  if (!nameError || containerName.match(/^(\$root|\$logs|\$web)$/)) {
    callback();
    return true;
  } else {
    return fail(nameError);
  }
};
```

**Comment by XiaoningLiu** [comment]
Will close this issue for long time no response, please re-open when you have code for re-producing.
