### ISSUE TITLE
'request' dep version no longer matches node API for tunneling

### ISSUE THREAD

**Issue by tcbeutler** [Azure/azure-storage-node#55]
The `request` dependency has been updated to use a newer version of `tunnel-agent`.

This fix implements a change in node's http function signature: 
https://github.com/mikeal/tunnel-agent/commit/7abb63b49ab0b30c35f224f2966d34c163b0505c

Trying to use a proxy ends up with request passing bad parameters to node't _http_client, which in turn passes bad paramters to `TunnelingAgent.prototype.addRequest`

**Comment by tcbeutler** [comment]
I'm currently on node 0.12.2 for which _http_client.js is up to date. Reproducing this using some sample code from your examples:

```//optionally set a proxy
var proxy = {
  protocol: 'http:',
  host: '127.0.0.1',
  port: 8888
};

blobService.setProxy(proxy);

blobService.getBlobToLocalFile(...
```

**Comment by slepox** [comment]
@tcbeutler , 'request' module is updated in 0.4.5. Please take a check.

**Comment by yaxia** [comment]
"rquest" dependency was updated to "~2.57.0" in 0.4.5. Thanks.
