### ISSUE TITLE
createBlockBlobFromBrowserFile not detecting network cancellation after putting computer to sleep

### ISSUE THREAD

**Issue by s3ncha** [Azure/azure-storage-node#550]
### Which service(blob, file, queue, table) does this issue concern?

Blob

### Which version of the SDK was used?

Azure Storage JavaScript Client Library 2.10.102

### What's the Node.js/Browser version?

Chrome  Version 71.0.3578.80 (Official Build) (64-bit) running on Windows 7 (confirmed on MacOs too)

### What problem was encountered?

I'm using  `createBlockBlobFromBrowserFile`  to upload files to Blob storage. If during upload I put my computer to sleep and then wake it up, my upload stalls. In dev console - network, I can see a number of cancelled PUT requests with combination of statues -  (cancelled) or (failed  with net::ERR_NETWORK_CHANGED)
However library does not detect that and I never receive call back in my function
```
...createBlockBlobFromBrowserFile(...
function (error, result, response) { }
   
);
```

### Steps to reproduce the issue?

Use `createBlockBlobFromBrowserFile` to upload a file to blob storage. Put computer to sleep mid way. Wake up and observe reported issue.

### Have you found a mitigation/solution?

No

**Comment by jiacfan** [comment]
Hi, @s3ncha 

Thanks for reaching us. 

As description the callback of the method hasn't been called, Would you help to execute an experiment to see if browser in your environment can handle resume case good? 

The experiment could simply sleep for e.g. 15 minutes, and return an error with specific message after wake up. Please sleep the system immediately after sleep functions is called. And the target is to see if there would be error get correctly(with specific message) after the OS wake-up.

Please share the experiment result, and we can investigate further accordingly,

Thanks,
Jiachen

**Comment by s3ncha** [comment]
Hi, @jiacfan 
Yes no problem, would you send me the test code to execute?

**Comment by jiacfan** [comment]
Hi, @s3ncha 

Please use any similar logic for the experiment, e.g. the simplest one, print wake up after specified seconds. In the following the example, print wake up successfully in browser's console after 5 seconds, you can customize the experiment as your wish:
`setTimeout(function(){console.log("Wake up successfully")}, 5000)`

Thanks,
Jiachen
