### ISSUE TITLE
Provide sample for connection pooling

### ISSUE THREAD

**Issue by prashanthmadi** [Azure/azure-storage-node#552]
Could you please improve documentation showing sample with connection pooling + setting max connections in it.

**Comment by XiaoningLiu** [comment]
@prashanthmadi 

If `enableGlobalHttpAgent` set to `true` for `blob|queue|file|tableService` object, global HTTP agent will be used.  Otherwise, http(s).Agent({keepAlive:true}) will be used.

https://nodejs.org/api/http.html#http_agent_maxsockets
```javascript
http.globalAgent.maxSockets = <some_value>;
```
