### ISSUE TITLE
on data event fires only when all data has been downloaded

### ISSUE THREAD

**Issue by ronysha** [Azure/azure-storage-node#554]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
 Azure Storage JavaScript Client Library 2.10.102

### What's the Node.js/Browser version?
chrome Version 70.0.3538.110 (Official Build) (64-bit)

### What problem was encountered?
  readStream.on('data', function (data) {
                                for (i = 0; i < data.length; i++) chunks.push(data[i]);                                 
                                   totalLength += data.length;                           
                               });

I am reading ~24Mbytes of data. I get them in 6 chunks. It takes me ~150 seconds, but I get them all at once.
Is there a way in which the data event gets fired whenever data is ready, i.e. every ~40 seconds?
Thanks
### Have you found a mitigation/solution?
not yet

**Comment by jiacfan** [comment]
Hi, @ronysha 

Thanks for reaching use, would you share more about what's the API you are using? Is it `createReadStream`? If that's the case, for blob whose size is <= 32MB, all data will be fetched by one request, and so you would feel that all data get at once.

Best Regards,
Jiachen

**Comment by ronysha** [comment]
Yes. I am using blobService.createReadStream.
Is there a way in which I can get the data from the blob in chunks?
Thanks for the answer

**Comment by jiacfan** [comment]
Hi, @ronysha 

What's your typical data sample? Would you also try blob whose size is > 32MB, which would be downloaded chunk by chunk in parallel? For small blob <= 32MB, getting it with one HTTP request is to save additional HTTP requests, and it also can help to provide good performance in most of cases.

Best Regards,
Jiachen

**Comment by jiacfan** [comment]
Hi, @ronysha 

I see the concern, for `createReadStream` there is options.rangeStart and options.RangeEnd which could help you to get data by range. Would you try it?

Thanks,
Jiachen

**Comment by ronysha** [comment]
Sure.
Can you show me how to use the options?

**Comment by jiacfan** [comment]
Hi, @ronysha

A simple example could be as following which downloads first 4MB:

```
var downloadOptions = {rangeStart: 0, rangeEnd: 4194304};
var writable = fs.createWriteStream(downloadFileName);
blobService.createReadStream(containerName, blobName, downloadOptions, function (error) {
                      // ...
}).pipe(writable);
```

For more details, please check the document [here](http://azure.github.io/azure-storage-node/BlobService.html) for createReadStream.

Best Regards,
Jiachen
