### ISSUE TITLE
XML parsing dependency migration

### ISSUE THREAD

**Issue by amitguptagwl** [Azure/azure-storage-node#555]
I would like to propose to migrate to [fast-XML-parser](https://github.com/NaturalIntelligence/fast-xml-parser).

Benchmark

![FXP vs xml2js](https://raw.githubusercontent.com/NaturalIntelligence/fast-xml-parser/master/static/img/fxpv3-vs-xml2jsv0419_chart.png)

**Comment by XiaoningLiu** [comment]
Thanks @amitguptagwl ! What does the Y-axis mean?

Will evaluate the changes need to be done.

At the same time, you can open another issue to @azure/ms-rest-js repo, which is the dependency package for V10 versions Azure Storage JS SDKs. Currently, for new features, we are more focusing on V10 version SDKs in https://github.com/azure/azure-storage-js

**Comment by amitguptagwl** [comment]
The graph in above comment is the comparison of both packages to parse XML data. X-axis is about XML data size, and Y-axis is for throughput or parsing per second. Here is the tabular representation.

file size | fxp 3.0 parser (rps) | xml2js 0.4.19 (rps)
-- | -- | --
1.5k | 14032.09323 | 4615.930805
1.5m | 13.23366098 | 5.90682005
13m | 1.135582008 | -1
1.3k with CDATA | 43160.52342 | 8398.556349
1.3m with CDATA | 52.68877009 | 7.966000795
1.6k with cdata,prolog,doctype | 41433.98547 | 7872.399268
98m | 0.2600104004 | -1
