### ISSUE TITLE
Node Js - Azure video streaming very slow

### ISSUE THREAD

**Issue by dkrockcom** [Azure/azure-storage-node#556]
I have use node azure-storage plugin for streaming videos from azure storage.

Created a Node controller which is use for stream video from azure and pipe the data for web video player.

Here is the demo code for the steaming.

`global.blobService.getBlobProperties(config.azure.container, filename, function (err, blobResult, headers) {
  if (!err) {
	const fileSize = Number(params.contentLength);
	if (range) {
	  const parts = range.replace(/bytes=/, "").split("-");
	  const start = parseInt(parts[0], 10);
	  const end = parts[1]
		? parseInt(parts[1], 10)
		: fileSize - 1
	  const chunksize = (end - start) + 1;
	  const stream = global.blobService.createReadStream(config.azure.container, filename, { rangeStart: start, rangeEnd: end, highWaterMark: 256 * 1024 });
	  const head = {
		'Content-Range': 'bytes ${start}-${end}/${fileSize}',
		'Accept-Ranges': 'bytes',
		'Content-Length': chunksize,
		'Content-Type': params.contentType,
	  }

	  res.writeHead(206, head)
	  stream.pipe(res)
	} else {
	  const head = {
		'Content-Length': fileSize,
		'Content-Type': 'video/mp4',
	  }
	  res.writeHead(200, head)
	  global.blobService.createReadStream(config.azure.container, filename, null).pipe(res);
	}
  }
});`

**Comment by XiaoningLiu** [comment]
@jiacfan can you take a look at this issue?

**Comment by jiacfan** [comment]
Hi, @dkrockcom 

Thanks for reaching us! 

Could you share the typical size of file when using createReadStream? 

And is the network condition good? What's the geo location of your test machine, and what's the region of storage account?  

At same time would you try [JsV10 Blob SDK](https://github.com/azure/azure-storage-js) as well, as our testing JsV10 has enhancement on download speed.

Thanks,
Jiachen

**Comment by dkrockcom** [comment]
> Hi, @dkrockcom
> 
> Thanks for reaching us!
> 
> Could you share the typical size of file when using createReadStream?
> 
> And is the network condition good? What's the geo location of your test machine, and what's the region of storage account?
> 
> At same time would you try [JsV10 Blob SDK](https://github.com/azure/azure-storage-js) as well, as our testing JsV10 has enhancement on download speed.
> 
> Thanks,
> Jiachen

Hi Fan Jiachen,

Issue occurred while multiple request on my server for dynamic thumbnails that's why selected azure video load very slow from my custom node controller, But now I have fixed, and thanks for the initiative

You can close this ticket.  

Thanks,
Devesh

**Comment by jiacfan** [comment]
Hi, dkrockcom:

Thanks for the update! And great to hear this news!

Best Regards,
Jiachen
