### ISSUE TITLE
Add documentation for authenticating with Azure Active Directory

### ISSUE THREAD

**Issue by tdmalone** [Azure/azure-storage-node#560]
### Which service(blob, file, queue, table) does this issue concern?

blob (but probably others too)

### Which version of the SDK was used?

2.10.0

### What's the Node.js/Browser version?

node v11.6.0

### What problem was encountered?

I couldn't find clear documentation on, or work out how to, authenticate with the blob service using an Active Directory Service Principal.

https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad states that:

> The Azure Storage client libraries that currently support Azure AD integration include:
> ...
> Node.js [links to this package]

I tried the following, adapted from an example I found at https://docs.microsoft.com/en-us/javascript/azure/node-sdk-azure-get-started:

```
const azure = require( 'ms-rest-azure' ),
      azureStorage = require( 'azure-storage' ),
      azureStorageManagement = require( 'azure-arm-storage' );

const fs = require( 'fs' );

const container = 'xxxxxxxxxxxxxxxxxx';
const filename = 'sample-file.txt';

const size = fs.statSync( filename ).size;
const source = fs.createReadStream( filename );

const client_id = 'xxxxxxxxxxxxxxxxxx',
      client_secret = 'xxxxxxxxxxxxxxxxxx',
      tenant_id = 'xxxxxxxxxxxxxxxxxx',
      subscription_id = 'xxxxxxxxxxxxxxxxxx';

const resource_group_name = 'xxxxxxxxxxxxxxxxxx',
      storage_account_name = 'xxxxxxxxxxxxxxxxxx';

azure.loginWithServicePrincipalSecret( client_id, client_secret, tenant_id, ( err, credentials ) => {
  if ( err ) throw err;

  const client = new azureStorageManagement( credentials, subscription_id );
  client.storageAccounts.listKeys( resource_group_name, storage_account_name, ( err, result ) => {
    if ( err ) throw err;

    const azureBlobs = azureStorage.createBlobService( storage_account_name, result.keys[0].value );

    azureBlobs.createBlockBlobFromStream( container, filename, source, size, () => {
      console.log( 'Done.' );
    });
  });
});
```

This works, but suffers from the service principal needing access to `Microsoft.Storage/storageAccounts/listkeys/action`, which allows it to access the 'root' access keys for the storage account - effectively making RBAC useless.

Ideally I would like to avoid having to allow this service principal access to `Microsoft.Storage/storageAccounts/listkeys/action`, and instead only allow certain data actions (such as `Microsoft.Storage/storageAccounts/blobServices/containers/blobs/write`).

### Steps to reproduce the issue?

As above - fully working example, providing each instance of xxxxxxxxxxxxxxxxxx is replaced with valid values.

### Have you found a mitigation/solution?

As above - it's part way to a solution, perhaps, but makes RBAC moot as the service principal gets full access.

**Comment by jiacfan** [comment]
Hi, tdmalone 

Thanks for reaching us.

Would you try [JsV10 SDK](https://github.com/Azure/azure-storage-js/), where [tokenCredential](https://github.com/Azure/azure-storage-js/blob/e084d30146555365ee1d3c4d84c1888d8e0db01f/blob/samples/basic.sample.js#L26-L27) is supported, and can be used for authentication with AAD.

In this case, key is not necessary, and you can get valid accessToken, and set to tokenCredential.

Best Regards,
Jiachen
