### ISSUE TITLE
upload file from browser to azure function

### ISSUE THREAD

**Issue by dagda1** [Azure/azure-storage-node#561]
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the SDK was used?

2.10.2

### What's the Node.js/Browser version?

8.11.1

### What problem was encountered?

No docs to tell how to upload to an azure function and then persist to blob storage.

Is there any guidance about uploading to a node azure function and then persisting to blob storage.

I cannot fin anything.

### Have you found a mitigation/solution?

I cannot find

**Comment by jiacfan** [comment]
Hi, dagda1 

Would you share more about your scenario about "upload to an azure function, and then persist to blob storage"?

For upload from browser, would you try [JsV10 SDK](https://github.com/azure/azure-storage-js), which provides better user experience, and has smaller bundle size.

Best Regards,
Jiachen

**Comment by dagda1** [comment]
yes, I need to go straight from the browser.  Uploading to an azure function will not end well
