### ISSUE TITLE
azure-storage-node vs azure-storage-js

### ISSUE THREAD

**Issue by samkelleher** [Azure/azure-storage-node#562]
Both the [azure-storage-node](https://github.com/Azure/azure-storage-node) ("azure-storage") and [azure-storage-js](https://github.com/Azure/azure-storage-js) ("@azure/storage-blob") have similiar APIs in terms of loading blob services and reading / writing etc.

But is one deprecated over the other, is one newer? I notice that the azure-storage-js has async functions. Which should I be using?

**Comment by XiaoningLiu** [comment]
@samkelleher You should use @azure/storage-blob which is our next generation JS SDK.
