### ISSUE TITLE
Incorrect type for generateSharedAccessSignature

### ISSUE THREAD

**Issue by mt35-rs** [Azure/azure-storage-node#567]
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the SDK was used?

2.10.2

### What's the Node.js/Browser version?

10.15.0 (but doesn't matter)

### What problem was encountered?

[Documentation](https://azure.github.io/azure-storage-node/BlobService.html) says that `generateSharedAccessSignature` takes an **optional** `blob` argument.  Even the type definition *comments* imply this argument is optional.  But the actual function signature requires `blob` as an argument.

### Steps to reproduce the issue?

Compare documentation with `.d.ts` files.

### Have you found a mitigation/solution?

I suppose I could do some type casting and force the system to work, but I haven't resorted to that yet.

I realize that I could use the `@azure/storage-blob` (preview) package.  The [documentation](https://docs.microsoft.com/en-us/javascript/api/%40azure/storage-blob/iblobsassignaturevalues?view=azure-node-preview#blobname) there confirms what I mentioned here, that the `blob` argument is optional.  But I see three issues with that.  First, it is just a preview release.  Second, the API is (to me at least) *very confusing*.  It is full of type definitions and classes but not much explanation as to how to actually use all those bits together (*e.g.,* the documentation lacks use cases).  Third, the documentation seems to have errors (*e.g.,* the `blobName` argument [is described](https://docs.microsoft.com/en-us/javascript/api/%40azure/storage-blob/iblobsassignaturevalues?view=azure-node-preview#blobname) as "The name of the container the SAS user may access." which is completely wrong (it appears somebody copied and pasted the documentation for the `containerName` argument and never updated it).

**Comment by XiaoningLiu** [comment]
@mt35-rs 

Thanks for reporting!

@azure/storage-js has been GA released since 10.3.0. Here is a sample to generate SAS for a container.

https://github.com/Azure/azure-storage-js/blob/e084d30146555365ee1d3c4d84c1888d8e0db01f/blob/tests/node/sas.test.ts#L164
