### ISSUE TITLE
Content type for .wasm files should be application/wasm

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/azure-storage-node#568]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
2.10.2

### What's the Node.js/Browser version?
8.12.0

### What problem was encountered?
.wasm files are being uploaded with contentType = application/stream, but it should be application/wasm (see https://webassembly.github.io/spec/core/binary/conventions.html)

**Comment by jiacfan** [comment]
Hi, @StephenWeatherford 

Thanks for reaching us! 

The .wasm is not involved in the browserify-mime package version 1.2.9 used by SDK. Would you try to use option e.g. `options.contentSettings.contentType` to customize contentType temporarily?

Thanks,
Jiachen

**Comment by StephenWeatherford** [comment]
Okay, thanks.
