### ISSUE TITLE
Include OrderBy clause for Azure CosmosDB Tables API

### ISSUE THREAD

**Issue by freakyfriday** [Azure/azure-storage-node#571]
### Which service(blob, file, queue, table) does this issue concern?
Tables service for CosmosDB Tables API

### Which version of the SDK was used?
Feature request

### What's the Node.js/Browser version?
Feature request

### What problem was encountered?
Feature request

### Steps to reproduce the issue?
Feature request

### Have you found a mitigation/solution?
The Azure CosmosDB Tables API now supports the OrderBy clause. It has been implemented in the Dot Net library. Can we please include this functionality in the Azure Storage NodeJS library - see Dot Net Example: https://github.com/Azure-Samples/azure-cosmos-table-dotnet-core-getting-started/blob/f5b352fec591a4ce702cfc7ef333480bdbd4b366/CosmosTableSamples/AdvancedSamples.cs#L390

**Comment by jiacfan** [comment]
Hi, freakyfriday:

Thanks for reaching us! Would you contact askcosmosdb@microsoft.com for cosmos related requirements?

Thanks,
Jiachen
