### ISSUE TITLE
How to decode Table API Buffer (Edm.Binary) data

### ISSUE THREAD

**Issue by sudishrrao** [Azure/azure-storage-node#574]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the SDK was used?
"azure-storage": "^2.10.2"

### What's the Node.js/Browser version?
v10.2.1

### What problem was encountered?
We have a Cosmos Table API DB where Bot Activities are stored using .net TableLoggerModule . We have now migrated the Bot Framework to Node JS and would like to access the Activity data but the data is in encoded/compressed form which we are not able to read/decompress using zlib library. We were accessing the data in .net using the solution provided in https://stackoverflow.com/questions/49483278/how-to-get-the-encrypted-bot-data-from-the-azure-datatable-in-decrypted-format. Tried the same approach here using zlib but getting undefined error. How can we convert the encoded/compressed Buffer data to readable String format?

**Comment by XiaoningLiu** [comment]
Hi @sudishrrao Thanks for reaching us, but this question is not related to storage SDK features or issues. 

The .net solution provided in stackoverflow seems simple, after get the activity0 binary date, uncompress it with gzip, then transfer it to string, finally deserilize it to JSON.

I believe Node.js could do the same thing. Will this https://stackoverflow.com/questions/7625251/compression-and-decompression-of-data-using-zlib-in-nodejs/39800991 help?

**Comment by sudishrrao** [comment]
Thank you for the reply. I was able to decode it using zlib.gunzipSync(queryResult.Activity0._).toString('utf8')
