### ISSUE TITLE
Syntax Error on both queue bundle js : azure-storage.queue.js, azure-storage.queue.min.js

### ISSUE THREAD

**Issue by doopedia** [Azure/azure-storage-node#575]
### Which service(blob, file, queue, table) does this issue concern?
creating queue message

### Which version of the SDK was used?
**azurestoragejs.queue-2.10.102** downloaded from https://dmrelease.blob.core.windows.net/azurestoragejs/azurestoragejs-2.10.102.zip

### What's the Node.js/Browser version?
chrome lasted

### What problem was encountered?
The bundle JS occurs SyntaxError below :
[azure-storage.queue.min.js:4]
Uncaught SyntaxError: Invalid regular expression: /^[Î‘-Ï‰]+$/: Range out of order in character class
[azure-storage.queue.js:43885] Uncaught SyntaxError: Invalid regular expression: /^[Î‘-Ï‰]+$/: Range out of order in character class

### Steps to reproduce the issue?
just import "azure-storage.queue.js" or "azure-storage.queue.min.js"

### Have you found a mitigation/solution?
no

**Comment by doopedia** [comment]
I'm reffering [this](https://dmrelease.blob.core.windows.net/azurestoragejssample/samples/sample-queue.html) to create queue message.

**Comment by jiacfan** [comment]
Hi, @doopedia:

Thanks for reaching us, could you try latest release 2.10.103, we validate the scenario you mentioned with latest chrome browser, and it can work well.

Best Regards,
Jiachen

**Comment by PiRXlv** [comment]
I found this while looking for solutions to same issue with `azure-storage.tables.js` file. It seems that when you are using local files directly in browser Unicode characters get mangled because of some encoding issues.

Using `http-server` to serve local files and accessing them through HTTP instead of `file:///` links solved the issue for me.

**Comment by jiacfan** [comment]
@PiRXlv, Thanks for proposing your ideas. BTW, what's the browser and SDK version you are using?

**Comment by PiRXlv** [comment]
@jiacfan SDK is 2.10.103, tried with Edge and Chrome, same behavior.

Also can confirm that this is encoding related issue, because it re-appeared when I uploaded my project to my hosting. 

After adding UTF-8 encoding in `.htaccess` file and then it was working without problem.
