### ISSUE TITLE
listQueues doesn't return continuation token when REST API call returns no queues

### ISSUE THREAD

**Issue by mheggeseth** [Azure/azure-storage-node#576]
### Which service(blob, file, queue, table) does this issue concern?
queue

### Which version of the SDK was used?
2.10.2

### What's the Node.js/Browser version?
Node.js 10.15.2

### What problem was encountered?
Calling [`listQueues`](https://github.com/Azure/azure-storage-node/blob/master/lib/services/queue/queueservice.js#L284) (`listQueuesSegmented` or `listQueuesSegmentedWithPrefix`) doesn't return the continuation token (if there is one) when no queues are returned. 

This is not a problem with the new v10-preview APIs because they seem to convey REST API results more directly instead of trying to interpret them.

### Steps to reproduce the issue?
I know of no way to get a storage account queue backend into this situation (mine is, not surprisingly). But it's not difficult to see how the code makes an incorrect assumption (and is even inconsistent with [`listContainers`](https://github.com/Azure/azure-storage-node/blob/master/lib/services/blob/blobservice.core.js#L442) for blob).

### Have you found a mitigation/solution?
Yes. Make `listQueues` look more like [`listContainers`](https://github.com/Azure/azure-storage-node/blob/master/lib/services/blob/blobservice.core.js#L442) where the absence of items in the response has no other side effects.

**Comment by XiaoningLiu** [comment]
Thanks for the late response! @mheggeseth I believe this is a potential risk needs to be improved! Before we take actions, PRs are welcome! Also new GA published V10 SDK is also recommended.
