### ISSUE TITLE
Type declarations are missing property `host` on `BlobService`, `QueueService`, etc.

### ISSUE THREAD

**Issue by unindented** [Azure/azure-storage-node#581]
### Which service(blob, file, queue, table) does this issue concern?

Blob, Queue, probably all services.

### Which version of the SDK was used?

2.10.3

### What's the Node.js/Browser version?

10.15.1

### What problem was encountered?

Property `host` is missing from interfaces `BlobService`, `QueueService`, etc.

### Steps to reproduce the issue?

```ts
const queue = azureStorage.createQueueService();
const host = queue.host;
//                 ^ Property 'host' does not exist on type 'QueueService'.
```

### Have you found a mitigation/solution?

Casting to `any`, which is obviously not ideal:

```ts
const host = (queue as any).host as StorageHost;
```

**Comment by XiaoningLiu** [comment]
Thanks @unindented ! That's a type bug in TS definition files. PR is also welcome!

**Comment by unindented** [comment]
@XiaoningLiu here you go: https://github.com/Azure/azure-storage-node/pull/582
