### ISSUE TITLE
Stream error: uncaughtException: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by RodyRafa** [Azure/azure-storage-node#583]
I am trying to use blobService.createReadStream from (azure-storage).
with a stream video.
Ex of code
```javascript
blobService.getBlobProperties(containerName, pathVideo, [], function(error, result, response) {
  if (error) {
    res.send(502, "Error fetching file: %s", error.message);
  } else if (!response.isSuccessful) {
    res.send(404, "The file %s does not exist", fileName);
  } else {
    const fileSize = response.headers['content-length'];
    const range = req.headers.range
    if (range) {
      const parts = range.replace(/bytes=/, "").split("-")
      const start = parseInt(parts[0], 10)
      const end = parts[1] 
        ? parseInt(parts[1], 10)
        : fileSize-1
      const chunksize = (end-start)+1
      res.set({
        'Content-Range': `bytes ${start}-${end}/${fileSize}`,
        'Accept-Ranges': 'bytes',
        'Content-Length': chunksize,
        'Content-Type': 'video/mp4',
      })
      res.status(206);
      const streamBlob = blobService.createReadStream(containerName, pathVideo, {rangeStart: start, rangeEnd: end}).pipe(res);

    } else {
      const head = {
        'Content-Length': fileSize,
        'Content-Type': 'video/mp4',
      }
      res.writeHead(206, head)
      const streamBlobInitial = blobService.createReadStream(containerName, pathVideo).pipe(res);
    }
  }
})
```

The video works normally, but after 2 min i get this error every time.

```
error: uncaughtException: ESOCKETTIMEDOUT
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/Jobs/conhecerEAD/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at TLSSocket.emitTimeout (_http_client.js:708:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket.Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) {"error":{"code":"ESOCKETTIMEDOUT","connect":false},"stack":"Error: ESOCKETTIMEDOUT\n    at ClientRequest.<anonymous> (/Jobs/conhecerEAD/node_modules/request/request.js:816:19)\n ...
```
version "azure-storage": "^2.10.3"

node: v8.9.4
chrome:  73.0.3683.103

**Comment by jiacfan** [comment]
Hi, RodyRafa

Thanks for reaching us! What's the file/range size used when the issue happen? Have you tried to catch package during the issue repro? Any additional trace about the failure would be helpful for further investigation.

Best Regards,
Jiachen

**Comment by RodyRafa** [comment]
Hi, @jiacfan !
The file size is: 27778826
Tks.

**Comment by jiacfan** [comment]
Thanks for the info! Are all the issues repro with file size/range size smaller than 32MB, if so, it could be timeout in blob service-side is triggered, for more details please refer to [here](https://docs.microsoft.com/en-us/rest/api/storageservices/setting-timeouts-for-blob-service-operations):

> Calls to get a blob, get page ranges, or get a block list are permitted 2 minutes per megabyte to complete. If an operation is taking longer than 2 minutes per megabyte on average, it will time out.

In this case, it seems the network condition is not good enough.

Would you get a recent repro, and provide requestId to me for double check?

Best Regards,
Jiachen

**Comment by jiacfan** [comment]
Close as no feedback is collected for months.
