### ISSUE TITLE
uploadStreamToBlockBlob is taking more than 30 sec randomly for small file

### ISSUE THREAD

**Issue by mmakkena** [Azure/azure-storage-node#584]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
latest

### What's the Node.js/Browser version?
v10.14.2

### What problem was encountered?
We have the following node code. we are calling  `uploadStreamToBlockBlob` 25 times in parallel with file data ranging from 2 kb to 7 kb.  The file data is tiny. Most of the requests are getting processed within 1 sec . But randomly few of the requests are taking more than 30 sec and our web request is timing out and getting 503 errors (Heroku has 30 sec time out for web dyno)

### Have you found a mitigation/solution?
NO

`
async putfile(fileName, fileData, contentType) {
const stream = new Readable();
const bufferSize = FOUR_MEGABYTES;
stream._read = function (bufferSize) {
stream.push(fileData);
stream.push(null);
}
return await uploadStreamToBlockBlob(
aborter,
stream,
this.blockBlobURL(fileName),
FOUR_MEGABYTES,
5
);
}`

**Comment by jiacfan** [comment]
Hi, mmakkena

Thanks for reaching us! Could you get a recent repro and provide the requestId for the requests which is slow to us?

Best Regards,
Jiachen

**Comment by mmakkena** [comment]
How do I get requestid  from azure portal?

**Comment by jiacfan** [comment]
Hi, mmakkena:

Could you get the result object for uploadStreamToBlockBlob API call? There is requestId inside the result object. Or would you do package catching, and provide the requestId in the raw request/response which last long and has problem?

Best Regards,
Jiachen

**Comment by mmakkena** [comment]
Here is the result object
Response from catch put : {"eTag":"\"0x8D6D55866763C5E\"","lastModified":"2019-05-10T15:01:37.000Z","contentMD5":{"type":"Buffer","data":[42,153,151,139,104,127,209,48,70,24,118,181,18,96,99,46]},"requestId":"9658e1b5-701e-00e6-1741-0774de000000","version":"2018-03-28","date":"2019-05-10T15:01:37.000Z","isServerEncrypted":true,"transfer-encoding":"chunked","server":"Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0","connection":"close"}

Response from catch put : {"eTag":"\"0x8D6D5587586590E\"","lastModified":"2019-05-10T15:02:02.000Z","contentMD5":{"type":"Buffer","data":[105,130,126,86,72,44,92,148,39,201,65,239,24,74,30,179]},"requestId":"51a8c3b1-b01e-0078-3041-070d99000000","version":"2018-03-28","date":"2019-05-10T15:02:02.000Z","isServerEncrypted":true,"transfer-encoding":"chunked","server":"Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0","connection":"close"}

Response from catch put : {"eTag":"\"0x8D6D5587D7BF74A\"","lastModified":"2019-05-10T15:02:15.000Z","contentMD5":{"type":"Buffer","data":[216,14,60,173,51,180,95,117,14,161,60,130,115,67,77,211]},"requestId":"070eaa86-901e-0009-4141-077fa0000000","version":"2018-03-28","date":"2019-05-10T15:02:15.000Z","isServerEncrypted":true,"transfer-encoding":"chunked","server":"Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0","connection":"close"}

**Comment by mmakkena** [comment]
Result-
Response from catch put : {"eTag":"\"0x8D6D55866763C5E\"","lastModified":"2019-05-10T15:01:37.000Z","contentMD5":{"type":"Buffer","data":[42,153,151,139,104,127,209,48,70,24,118,181,18,96,99,46]},"requestId":"9658e1b5-701e-00e6-1741-0774de000000","version":"2018-03-28","date":"2019-05-10T15:01:37.000Z","isServerEncrypted":true,"transfer-encoding":"chunked","server":"Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0","connection":"close"}

Response from catch put : {"eTag":"\"0x8D6D5587586590E\"","lastModified":"2019-05-10T15:02:02.000Z","contentMD5":{"type":"Buffer","data":[105,130,126,86,72,44,92,148,39,201,65,239,24,74,30,179]},"requestId":"51a8c3b1-b01e-0078-3041-070d99000000","version":"2018-03-28","date":"2019-05-10T15:02:02.000Z","isServerEncrypted":true,"transfer-encoding":"chunked","server":"Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0","connection":"close"}

Response from catch put : {"eTag":"\"0x8D6D5587D7BF74A\"","lastModified":"2019-05-10T15:02:15.000Z","contentMD5":{"type":"Buffer","data":[216,14,60,173,51,180,95,117,14,161,60,130,115,67,77,211]},"requestId":"070eaa86-901e-0009-4141-077fa0000000","version":"2018-03-28","date":"2019-05-10T15:02:15.000Z","isServerEncrypted":true,"transfer-encoding":"chunked","server":"Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0","connection":"close"}

**Comment by mmakkena** [comment]
HI Jiachen, Just wondering if can get the request ids now

**Comment by jiacfan** [comment]
Yes, thanks! There are requestId fields in the provided log, will check the service log, and update here later.

**Comment by jiacfan** [comment]
I checked all of the above 3 requests, and no issue found:

requestId":"9658e1b5-701e-00e6-1741-0774de000000" => PutBlockList operation fulfilled in 7ms

requestId":"51a8c3b1-b01e-0078-3041-070d99000000"=> PutBlockList operation fulfilled in 11ms

requestId":"070eaa86-901e-0009-4141-077fa0000000" => PutBlockList operation fulfilled in 6ms

@mmakkena would you ensure the provided requests are the ones with issue mentioned?

Thanks,
Jiachen

**Comment by jiacfan** [comment]
Close as no feedback is collected for months.
