### ISSUE TITLE
etag is not enclosed with double quotes in listBlobsSegmented

### ISSUE THREAD

**Issue by JaydenLiang** [Azure/azure-storage-node#586]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
2.10.2

### What's the Node.js/Browser version?
8.11.1

### What problem was encountered?
The the data entries returned by BlobService.listBlobsSegmented contain a malformed etag.

### Steps to reproduce the issue?
you could simple use the listBlobsSegmented and check the etag of any returned data entry.

### Have you found a mitigation/solution?
It seems a problem deep in the storage service instead of a node sdk specific issue. I don't think it can be fixed here. However, I propose a solution as: returning the etag enclosed with double quotes in listBlobsSegmented in the storage service.

@XiaoningLiu I found your answers to the similar issue here in:
https://github.com/Azure/Azurite/pull/143

I believe the etag by definition must be enclosed with double quotes.
Microsoft also states it the same in the documentation. please refer to the to documentation here:
https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-properties

**Comment by jiacfan** [comment]
Hi, @JaydenLiang:

Thanks for reaching us! I checked the API, and what you described is true that the service directly returns ETag without quotes for list blobs currently, and this might be a point to optimize. I'll forward this to service team. Please work around in client side temporarily for it.

Best Regards,
Jiachen
