### ISSUE TITLE
API  to change existing container access level 

### ISSUE THREAD

**Issue by wkk91193** [Azure/azure-storage-node#587]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
2.10.2
### What's the Node.js/Browser version?
Nodejs 8.1.4

### What problem was encountered?
Can't seem to find an API endpoint to change existing anonymous users permissions of containers to private

### Have you found a mitigation/solution?
None

**Comment by gmantri** [comment]
> Can't seem to find an API endpoint to change existing anonymous users permissions of containers to private

The REST API for this is [`Set Container ACL`](https://docs.microsoft.com/en-us/rest/api/storageservices/set-container-acl) and the SDK method you would want to call is `setContainerAcl`. Please note that you will have to call this method on each container separately.

**Comment by XiaoningLiu** [comment]
@gmantri is correct, thanks!

**Comment by wkk91193** [comment]
Thanks @gmantri..  found it,closing this issue
