### ISSUE TITLE
TableQuery is replacing characters in "where" clause when it should not.

### ISSUE THREAD

**Issue by gmantri** [Azure/azure-storage-node#588]
### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the SDK was used?
2.10.2

### What's the Node.js/Browser version?
10.15.2

### What problem was encountered?
If the where clause in my table query contains `!` character, the SDK is converting it to `not`. The problem is in `TableQuery._replaceOperators` method in `tablequery.js` file.

```
TableQuery._replaceOperators = function (whereClause) {
  var encodedWhereClause = whereClause.replace(/ == /g, ' ' + QueryComparisons.EQUAL + ' ');
  encodedWhereClause = encodedWhereClause.replace(/ != /g, ' ' + QueryComparisons.NOT_EQUAL + ' ');
  encodedWhereClause = encodedWhereClause.replace(/ >= /g, ' ' + QueryComparisons.GREATER_THAN_OR_EQUAL + ' ');
  encodedWhereClause = encodedWhereClause.replace(/ > /g, ' ' + QueryComparisons.GREATER_THAN + ' ');
  encodedWhereClause = encodedWhereClause.replace(/ <= /g, ' ' + QueryComparisons.LESS_THAN_OR_EQUAL + ' ');
  encodedWhereClause = encodedWhereClause.replace(/ < /g, ' ' + QueryComparisons.LESS_THAN + ' ');
  encodedWhereClause = encodedWhereClause.replace(/ \&\& /g, ' ' + TableOperators.AND + ' ');
  encodedWhereClause = encodedWhereClause.replace(/ \|\| /g, ' ' + TableOperators.OR + ' ');
  encodedWhereClause = encodedWhereClause.replace(/!/g, TableOperators.NOT);

  return encodedWhereClause;
};

```

Because of this, if I specify a query like `PartitionKey eq 'te!st'`, it is actually sent to Table Service as `PartitionKey eq 'tenotts'`.

### Have you found a mitigation/solution?
No

**Comment by gmantri** [comment]
This happens with .Net SDK as well: https://github.com/Azure/azure-storage-net/issues/893.

**Comment by jiacfan** [comment]
Thanks for reaching us and reporting the issue! It looks like a client-side issue, and we'll check it further. At same time, welcome contribution if you are interested in it! 

Best Regards,
Jiachen
