### ISSUE TITLE
Upload of cloud files using createBlockBlobFromBrowserFile throws errors

### ISSUE THREAD

**Issue by Koenyn** [Azure/azure-storage-node#590]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
Azure Storage JavaScript Client Library 2.10.102

### What's the Node.js/Browser version?
Microsoft Edge Version 76.0.167.1 (Official build) dev (64-bit)
Firefox 67

### What problem was encountered?
* Uncaught Error: Unhandled "error" event. ([object ProgressEvent])
    at s.r.emit (azure-storage.blob.min.js:3)
    at FileReader._fileReader.onerror (azure-storage.blob.min.js:3)
* Uncaught TypeError: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
    at s (azure-storage.blob.min.js:3)
    at Function.f.from (azure-storage.blob.min.js:3)
    at FileReader._fileReader.onloadend (azure-storage.blob.min.js:3)

### Steps to reproduce the issue?
Using onedrive, stop syncing of your files. then drag and drop a remote file in a file upload control. Once the upload starts, the above errors are thrown.

### Have you found a mitigation/solution?
If you can catch the error and the return it as an error in the callback

**Comment by jiacfan** [comment]
Hi, Koenyn 

Thanks for reaching us! Can this issue be repro with latest version 2.10.103? And would you share more details about how the library is invoked?

Best Regards,
Jiachen

**Comment by jpalten** [comment]
I have the same problem, even with v 2.10.103. It happens when I try to upload a specific file. Always this file causes the problem. It happens on Safari (v 12.1.1  14607.2.6.1.1) not when using Chrome Versie 75.0.3770.142 (64-bits).

**Comment by jiacfan** [comment]
Thanks for reaching us!

We've moved to [Storage SDK v10 for JavaScript](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage) for latest SDK support(which no more deps on request module). That repro is with agile service and latest features.

Welcome to take a look. And please feel free to let us know if there is any issue with using it.
