### ISSUE TITLE
StorageError: Cannot create property 'ServiceEndpoint' on string ''

### ISSUE THREAD

**Issue by alpha128** [Azure/azure-storage-node#593]
### Which service(blob, file, queue, table) does this issue concern?
Storage Blob

### Which version of the SDK was used?
Javascript SDK: Azure Storage JavaScript Client Library 2.10.103
from the below site:
https://dmrelease.blob.core.windows.net/azurestoragejssample/samples/sample-blob.html

### What's the Node.js/Browser version?
Node.js v10.15.3
Vue v3.5.5
Quasar Framework v0.17

### What problem was encountered?
When trying to AzureStorage - listBlobsSegmented it return such error, has no problem to upload file and get the file directly.

![blob error](https://user-images.githubusercontent.com/7401865/59997794-79892980-9690-11e9-90b9-ea600d5b76ad.png)

### Steps to reproduce the issue?
I follow exactly what the sample page provided for upload and list, upload working fine but listBlobsSegmented not working, perhaps webpack or latest node js compatibility issue?

### Have you found a mitigation/solution?
No

**Comment by jiacfan** [comment]
Hey, @alpha128 

Thanks for reaching us! Would you try [Azure Storage V10 SDK for JavaScript](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage) which latest architecture? It has cleaner dependencies, smaller footprint, and better compatibility with webpack. And should work well for your scenario.

Best Regards,
Jiachen

**Comment by alpha128** [comment]
Hi @jiacfan 

Thanks for the response, I tried the Azure Storage v10 SDK for Javascript but I unable to make it work, always throw me error back SharedKeyCredential is not a constructor even though I installed and using it like the site mentioned...

**Comment by XiaoningLiu** [comment]
SharedKeyCredential is not supported in browsers. Storage team recommends using SAS or OAuth token  authentication in V10.

We will update doc for V10 and make it more clearer.

**Comment by alpha128** [comment]
> 
> 
> SharedKeyCredential is not supported in browsers. Storage team recommends using SAS or OAuth token authentication in V10.
> 
> We will update doc for V10 and make it more clearer.

Appreciate it, I actually trying to referring it as NodeJS too but not working, if I tried UMD way I keep getting error with the azblob, i not sure what i had left out to be include.

My way of reffering:
import azblob from "@/assets/js/azure-storage.blob.v10";

**Comment by jiacfan** [comment]
Hi, @alpha128 

For [v12 SDK](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). the documents have been optimized. Welcome new comments.

Thanks,
Jiachen
