### ISSUE TITLE
The value for one of the HTTP headers is not in the correct format

### ISSUE THREAD

**Issue by gilm123** [Azure/azure-storage-node#594]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
2.10.3

### What's the Node.js/Browser version?
node 8.11.0

### What problem was encountered?
getting `StorageError: The value for one of the HTTP headers is not in the correct format.` when trying to copy an existing blob from one folder to another in the same container.
I know to tell the blobService instance I created is working and authenticated, since I got a list of the files before actually performing the copy task using `listBlobsSegmentedWithPrefix`, I also used `createBlockBlobFromLocalFile` so I know read-write should work.

digging into node_modules, i tried to see what headers are actually sent
```
x-ms-access-tier undefined
x-ms-lease-id undefined
x-ms-source-lease-id undefined
```
with no metadata headers.

### Steps to reproduce the issue?
`blobService.startCopyBlob(<some-existing-blob-path>, <container>, <destination-blob--path>, <callback>);` 
I'm using `AZURE_STORAGE_ACCOUNT` and `AZURE_STORAGE_ACCESS_KEY` environment variables. I tried using connection string instead and got the same error.

### Have you found a mitigation/solution?
tried to look over issues here / stackoverflow and couldn't find any.

**Comment by XiaoningLiu** [comment]
Hi @gilm123 Is there any other response information in the err object you got? Usually server will return which header is invalid in the returned response body. Or at least, can you provide me the `x-ms-request-id` in the err object?

**Comment by gilm123** [comment]
Hii @XiaoningLiu , yes, the error received in the callback isn't contain much, I added a print in the azure_storage package:
```
{"error":{"name":"StorageError","message":"The value for one of the HTTP headers is not in the correct format.\nRequestId:d4dd4c80-801e-00fd-7423-2f1e7b000000\nTime:2019-06-30T09:08:14.4000908Z","code":"InvalidHeaderValue","headername":"x-ms-copy-source","headervalue":"builds/v0/0.0.16/10000/anywhere-expert-sdk.css","statusCode":400,"requestId":"d4dd4c80-801e-00fd-7423-2f1e7b000000"},"response":{"isSuccessful":false,"statusCode":400,"body":{"Error":{"Code":"InvalidHeaderValue","Message":"The value for one of the HTTP headers is not in the correct format.\nRequestId:d4dd4c80-801e-00fd-7423-2f1e7b000000\nTime:2019-06-30T09:08:14.4000908Z","HeaderName":"x-ms-copy-source","HeaderValue":"builds/v0/0.0.16/10000/anywhere-expert-sdk.css"}},"headers":{"content-length":"368","content-type":"application/xml","server":"Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0","x-ms-request-id":"d4dd4c80-801e-00fd-7423-2f1e7b000000","x-ms-version":"2018-03-28","x-ms-error-code":"InvalidHeaderValue","date":"Sun, 30 Jun 2019 09:08:13 GMT"}},"operationEndTime":"2019-06-30T09:08:14.485Z","targetLocation":0,"outputStreamSent":false}

RequestId:d4dd4c80-801e-00fd-7423-2f1e7b000000
```
`builds/v0/0.0.16/10000/anywhere-expert-sdk.css` is the source file i want to copy 

thanks
