### ISSUE TITLE
Setting immutable blob storage policy

### ISSUE THREAD

**Issue by ycryptx** [Azure/azure-storage-node#597]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
Latest

### What's the Node.js/Browser version?
Latest

### What problem was encountered?
I can't seem to find documentation as to how to set up immutable blob storage policy for a container.

**Comment by jiacfan** [comment]
Hi, @ycryptx 

Thanks for reaching us! As immutable storage's [document](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-immutable-storage), it's exposed through package [azure-arm-storage](https://www.npmjs.com/package/azure-arm-storage), and here is the [src code](https://github.com/Azure/azure-sdk-for-node/tree/master/lib/services/storageManagement2) for the package.
And generally, this package provides client API which wraps [REST API](https://docs.microsoft.com/en-us/rest/api/storageservices/) for data operations, and immutable blob storage policy is much related to managing the storage policy, and is maintained in resource management package.

Thanks,
Jiachen

**Comment by ycryptx** [comment]
@jiacfan Thanks a lot for the help. I've looked through the package you linked, and I still can't find the wrapper for creating immutable blob storage access policy. I also can't find the REST API call for this functionality. LMK if I'm missing something in the REST API. Really appreciate the help!!

**Comment by jiacfan** [comment]
Hey, @ycryptx 

I see code for immutable policy can be found [here](https://github.com/Azure/azure-sdk-for-node/blob/d70b9d8d6641a297f3adf150042adbd0c7073863/lib/services/storageManagement2/lib/operations/blobContainers.js#L3817) in this [repo](https://github.com/Azure/azure-sdk-for-node/). If detailed samples are wished, suggest to post an question on the repro, and they should be happy to help further! 

Thanks,
Jiachen

**Comment by jiacfan** [comment]
Close as no feedback is collected for months.
