### ISSUE TITLE
Can not read zip files from blob service

### ISSUE THREAD

**Issue by sergioRozenszajn** [Azure/azure-storage-node#598]
### Which service(blob, file, queue, table) does this issue concern?
Blob service

### Which version of the SDK was used?
2.10.2

### What's the Node.js/Browser version?
^10.0.0

### What problem was encountered?
I'm able to store blobs containing zipped content (.zip files) using createWriteStreamToBlockBlob or createBlockBlobFromText (preferred) however when reading this blob with getBlobToStream or getBlobToText the zip file content is returned as a string and can not be downloaded correctly.
Note that when working with streams we create custom strings. For example we create a writable stream for getBlobToStream with: const writableStream = new Stream.Writable({ decodeStrings: false });

### Steps to reproduce the issue?
Store a zip file into blob store. Read it back, download via browser to local PC and try to unzip it.
### Have you found a mitigation/solution?
No

**Comment by jiacfan** [comment]
Hi, @sergioRozenszajn 

Thanks for reaching us!

Would you try `createBlockBlobFromStream` and `getBlobToStream` when operating binary files like .zip. `createBlockBlobFromText` and `getBlobToText` by default use utf8 for encoding/decoding text, and might involve additional encoding/decoding to raw data bytes in your case.

At same time, really suggest to try latest [JS V10 SDK](https://github.com/azure/azure-storage-js) with latest architecture.

Best Regards,
Jiachen

**Comment by sergioRozenszajn** [comment]
Hi Jiachen,

In the fetch I'm already using getBlobToStream. In the insert I'm using createWriteStreamToBlockBlob. Is there a difference between createWriteStreamToBlockBlob and createBlockBlobFromStream?
I prefer createWriteStreamToBlockBlob because I don't need to deal with stream length.

Best Regards
Sergio

**Comment by jiacfan** [comment]
Hi, @sergioRozenszajn 

In your case, are you using `createWriteStreamToBlockBlob` with piping or with pattern stream.write(content[,encoding])? If it's piping the logic should be same for both methods. 
When using `getBlobToStream` would you try to keep options all as default value, i.e. `decodeStrings`:`true`?

Thanks,
Jiachen

**Comment by sergioRozenszajn** [comment]
Hi Jiachen,

After switching to createBlockBlobFromStream the issue is solved. 
Thank you!.
Sergio
