### ISSUE TITLE
The generateAccountSharedAccessSignature does not provide a valid token

### ISSUE THREAD

**Issue by kavitha1991dhiman** [Azure/azure-storage-node#599]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
"azure-storage": "^2.10.3"

### What's the Node.js/Browser version?
10.6

### What problem was encountered?
Without SDK - (working)
sv=2018-03-28&ss=b&srt=co&sp=rwdlac&se=2019-07-20T00%3A00%3A00Z&st=2019-07-19T00%3A00%3A00Z&spr=https&sig=i6lWiTGqPolcRwpEYsmg05%2B5ngSFxp%2BVmo%2BlPtOj59E%3D

With SDK - (Not Working)
sv=2018-03-28&ss=b&srt=sco&sp=rwc&st=2019-07-19T00%3A00%3A00Z&se=2019-07-20T00%3A00%3A00Z&spr=https&sig=%2FId7%2B%2Bmf8z671rUaJhbnLkw1HdJIfCWeuU2gN161v8E%3D

### Steps to reproduce the issue?
Create a token using the SDK generateAccountSharedAccessSignature  method and the token will be displayed.

generateSASToken(){
        const start = new Date('2019-07-19');
        const end = new Date('2019-07-20');
        
        const sharedAccessPolicy: azurestorage.common.SharedAccessPolicy = {
			AccessPolicy: {
				Permissions: 'rwc',
				Services: 'b',
				ResourceTypes: 'sco',
				Start: start,
				Expiry: end,
				Protocols: 'https'
			}
		};

      return azurestorage.generateAccountSharedAccessSignature(config.AZUREBLOBCONNECTIONSTRING, config.AZUREBLOBACCESSKEY, sharedAccessPolicy);
    }

### Have you found a mitigation/solution?
Created the string based on the encrytion.
 generateSASToken() {
        const crypto = require('crypto');
        const start = new Date(new Date().getTime() - (15 * 60 * 1000));
        const end = new Date(new Date().getTime() + (30 * 60 * 1000));
        const accountname = config.BLOBACCOUNTNAME;
        const signedpermissions = 'rw';
        const signedservice = 'b';
        const signedresourcetype = 'co';
        const signedstart = this.truncateIsoDate(start);
        const signedexpiry = this.truncateIsoDate(end);
        const signedIP = '';
        const signedProtocol = 'https';
        const signedversion = '2018-03-28';

        const StringToSign =
            accountname + '\n' +
            signedpermissions + '\n' +
            signedservice + '\n' +
            signedresourcetype + '\n' +
            signedstart + '\n' +
            signedexpiry + '\n' +
            signedIP + '\n' +
            signedProtocol + '\n' +
            signedversion + '\n';

        const key = new Buffer(config.BLOBACCOUNTKEY, 'base64');
        const sig = crypto.createHmac('sha256', key).update(StringToSign, 'utf8').digest('base64');
        const resultToken =
            'sv=' + signedversion +
            '&ss=' + signedservice +
            '&srt=' + signedresourcetype +
            '&sp=' + signedpermissions +
            '&se=' + encodeURIComponent(signedexpiry) +
            '&st=' + encodeURIComponent(signedstart) +
            '&spr=' + signedProtocol +
            '&sig=' + encodeURIComponent(sig);
        return resultToken;
    }

    truncateIsoDate(date: Date): string {
        return date.toISOString().substring(0, date.toISOString().lastIndexOf('.')) + 'Z';
    }
}

**Comment by jiacfan** [comment]
Hi, @kavitha1991dhiman

Thanks for reaching us! 

In the given example, fields **srt**=sco&**sp**=rwc&**st**=2019-07-19T00%3A00%3A00Z&**se**=2019-07-20T00%3A00%3A00Z are different, have you tried to generate SAS with same fields, and validate if the SAS can work properly? What's the detailed response you get when trying SAS generated with SDK?

At same time, please well protect your credentials during posting new discussions. 

Best Regards,
Jiachen

**Comment by jiacfan** [comment]
Close as no feedback is collected for months.
