### ISSUE TITLE
Accessing to response entities object is a little bit confusing

### ISSUE THREAD

**Issue by ghost** [Azure/azure-storage-node#60]
Hello all,

When I try to access returned row objects, I always should do something like "object._" to get value. Is there any workaround to override this situation ?

    tableSvc.queryEntities('Likes', query, null, function(error, result, response) {
        if(!error) {
            var returnedLikeCount = result.entries[0].likeCount._;
        }
    });

Thanks

**Comment by yaxia** [comment]
It is by-design for now the object['_'] indicates the property value and object['$'] indecates the value EDM type.
