### ISSUE TITLE
Generating SAS for uploading a file to blob storage 

### ISSUE THREAD

**Issue by tudor33sud** [Azure/azure-storage-node#600]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?

10.3.0
### What's the Node.js/Browser version?
v10.16.0

### What problem was encountered?
I cannot generate upload URL signed with SAS

### Steps to reproduce the issue?
Old SDK has plenty of examples into how to upload a file to azure blob directly from the browser by generating a blob SAS on the backend. However, with the new SDK, I cannot find anything related to how to do this.

There is this method in API reference 
function generateBlobSASQueryParameters(
  blobSASSignatureValues: IBlobSASSignatureValues,
  sharedKeyCredential: SharedKeyCredential
): SASQueryParameters

However, I'm not aware how to generate an object implementing that interface in the new SDK. 
Can you please provide me some directions? The scenario is to simply generate an upload URL for a file to be uploaded in blob storage.

### Have you found a mitigation/solution?
There is a similar issue here (however for account SAS, not blob SAS for a single upload)  https://github.com/Azure/azure-storage-node/issues/572 . This one seems to me that involves lots of manual work, is there another way to achieve the same result? Thanks!

**Comment by tudor33sud** [comment]
Also, can you please let me know if there's any way of adding Metadata to this upload url that I will serve to the frontend? I cannot find documentation related to how to use SAS to upload files from the frontend, but have the blob files to already have set some Metadata given by the server when the url was generated.

Thank you very much, and sorry if I'm asking stupid questions, since I'm new to the Azure SDK and I'm trying to replicate what we previously had on AWS ( presigned url for uploads, which also contained file metadata which could be used later on)

**Comment by jiacfan** [comment]
Hi, @tudor33sud 

Thanks for reaching us!

For 10.3.0, please check [here](https://github.com/Azure/azure-storage-js/blob/a1b7084089bf85dd166aa8e89745964ea263d13a/blob/tests/node/sas.test.ts) for `generateBlobSASQueryParameters` for usages.

e.g.: Generate SAS for a blob
```
    const blobSAS = generateBlobSASQueryParameters(
      {
        <blobName>,
        cacheControl: "cache-control-override",
        <containerName>,
        contentDisposition: "content-disposition-override",
        contentEncoding: "content-encoding-override",
        contentLanguage: "content-language-override",
        contentType: "content-type-override",
        expiryTime: <expiryTime>,
        ipRange: { start: "0.0.0.0", end: "255.255.255.255" },
        permissions: BlobSASPermissions.parse("racwd").toString(),
        protocol: SASProtocol.HTTPSandHTTP,
        startTime: <startTime>,
        version: "2016-05-31"
      },
      sharedKeyCredential as SharedKeyCredential
    );

    const sasURL = `${blobURL.url}?${blobSAS}`;
    const blobURLwithSAS = new PageBlobURL(
      sasURL,
      StorageURL.newPipeline(new AnonymousCredential())
    );

    const properties = await blobURLwithSAS.getProperties(Aborter.none);
```

Thanks,
Jiachen

**Comment by tudor33sud** [comment]
Hi Jiacfan, thank you for your answers. Could you please let me know if there is any option to add some metadata to blobs on backend side that will be appended to the blob when it's uploaded?
AWS provided signed metadata which was encoded in presigned URL, and I'm not sure if Azure provides something similar for Blobs.

I saw that the general purpose of metadata is that when user will upload the data is responsible for setting metadata on http headers. The thing is that I would have wanted to store information like the user who uploaded data into the blob metadata, which for me currently seems not possible with Azure API. Am I right? Are there any best practices to do so ? (I would like to avoid to encode userId in the Blob Key)

**Comment by jiacfan** [comment]
Hi, @tudor33sud 

Thanks for providing the context!

Currently, Azure provides several system-defined metadata during signing, [link](https://docs.microsoft.com/en-us/rest/api/storageservices/constructing-a-service-sas#specifying-query-parameters-to-override-response-headers-blob-service-and-file-service-only). And user-defined metadata during signing could be a good feature to add, while not supported yet! I will forwarded this idea to service team.

At same time, in AWS will you control user's permission to change metadata during upload data? If they have permission to change metadata and do change the metadata, the statistics could be inaccurate?

For the scenario, I wish to know if your customer is invoking API you provided or directly using the SAS you provided with their own APIs/SDKs. If customer is using the API provided by you, is it possible to provide a shim, where user defined metadata is set during API call?  If it's the later case, is it possible to let different customer use different container(with container Name mapping to customer), and provide service SAS bind to specific container to specific customer?

Just FYI :) And welcome discussion.

Best Regards,
Jiachen

**Comment by jiacfan** [comment]
Close as no feedback is collected for months.

**Comment by johnkwaters** [comment]
I am also interested in supplying user defined metadata that is part of the shared access signature for upload of a file from a js client, and tamper proof.
The scenario is to emulate what happens in AWS = API generates a presigned URL with guid in metadata, stores some info about the upload in a table indexed by the guid,  js client uploads file, s3 sends notification to q, lambda gets event, lambda reads metadata, looks up record with guid. So the guid gets round tripped.
In Azure: API generates a SAS with guid in metadata, stores some info about the upload in a table indexed by the guid,  js client uploads file, storage sends notification to eventgrid, az function gets event, function reads metadata, looks up record with guid. So the guid gets round tripped.
The key here is including some tamper proof custom metadata that follows through the whole process.
