### ISSUE TITLE
GenerateBlobSasQueryParameters doesn't add permissions

### ISSUE THREAD

**Issue by tudor33sud** [Azure/azure-storage-node#601]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?

10.3.0
### What's the Node.js/Browser version?

10.0.16
### What problem was encountered?
I cannot get permissions to be embedded in the SAS

### Steps to reproduce the issue?

    const serviceUrl = getBlobServiceUrl();
    const now = new Date();
    now.setMinutes(now.getMinutes() - 5);
    const timer = new Date();
    timer.setDate(timer.getDate() + 1);
    const sasToken = generateBlobSASQueryParameters({
        containerName: params.Bucket,
        blobName: params.Key,
        contentType: params.ContentType,
        startTime: now,
        expiryTime: timer,
        ipRange: { start: '0.0.0.0', end: '255.255.255.255' },
        permissions: BlobSASPermissions.parse('cr'),
        protocol: SASProtocol.HTTPS,
        contentDisposition: `attachment=${params.Metadata.fileName}`
    }, credentials);
    const tokenString = sasToken.toString();
    return `${serviceUrl.url}${params.Bucket}/${params.Key}?${tokenString}`;

 
This results in generating an url for uploading a file to the specified blob. When trying to use the resulted url, I get authentication error because of service permissions being mandatory. According to docs of the function, if identifier is missing ( I don't want to use a stored policy ), expiry date and permissions are mandatory. However, there's no sp in parameters.
Sample url:
https://example.blob.core.windows.net/example/8/f7914353-fc1e-4975-ab34-b2c0b30c9d3c.txt?sv=2018-03-28&spr=https&st=2019-07-24T11%3A42%3A40Z&se=2019-07-25T11%3A47%3A40Z&sip=0.0.0.0-255.255.255.255&sr=b&sig=Sm2%2BLgqI5AXxCL93dzIwipMXSwRg%2BLoKv%2BTXxQiWPxg%3D&rscd=attachment%3DmyFile.txt&rsct=multipart%2Fform-data
Error message:
`<?xml version="1.0" encoding="utf-8"?>
<Error>
    <Code>AuthenticationFailed</Code>
    <Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:24d15c18-a01e-0038-6e15-42e97e000000
Time:2019-07-24T11:48:11.5671183Z</Message>
    <AuthenticationErrorDetail>sp is mandatory. Cannot be empty</AuthenticationErrorDetail>
</Error>`

### Have you found a mitigation/solution?
No.. I can only use account sas successfully, but that allows the user to create as many blobs as they want. My use case is to allow uploading only one file per signed url, and with the enforced naming from the server.

**Comment by jiacfan** [comment]
Hi, @tudor33sud 

Thanks for reaching us!

Please check answer here #600 

The permission field accepts string: 
permissions: **BlobSASPermissions.parse("racwd").toString()**

Best Regards,
Jiachen

**Comment by tudor33sud** [comment]
Oh, such a stupid question. Thank you, I was probably too tired to see that I forgot to call toString. I will close this for now. 

However, I think it will be a good idea to update docs on the new SDK to illustrate how SAS works with new SDK, I found it pretty hard as a new user to go through the classes and methods with no real examples.
