### ISSUE TITLE
eTag contains double quotes

### ISSUE THREAD

**Issue by sergioRozenszajn** [Azure/azure-storage-node#603]
### Which service(blob, file, queue, table) does this issue concern?
Blob service

### Which version of the SDK was used?
2.10.2

### What's the Node.js/Browser version?
^10.0.0

### What problem was encountered?
The returned eTag contains double quotes

### Steps to reproduce the issue?
Read a blob using getBlobToStream
See current result:
contentSettings: {contentType: "application/octet-stream", contentMD5: "0lwUulKzqTvKn0FuR/6WHQ=="}
creationTime: "Wed, 06 Feb 2019 14:04:13 GMT"
**etag: ""0x8D68C3BF91FBBF2""**
lastModified: "Wed, 06 Feb 2019 14:04:13 GMT"

**Comment by XiaoningLiu** [comment]
Hi @sergioRozenszajn This is by design for etags returned by Azure Storage.

**Comment by sergioRozenszajn** [comment]
Thank you for the feedback!
