### ISSUE TITLE
Best practice for multiple uploads

### ISSUE THREAD

**Issue by avivklas** [Azure/azure-storage-node#605]
I can't find in the documentation whether it's recommended to reuse a `BlobService` or to create a new one per operation in case of a long-running process with multiple periodic uploads (serial).

I'll appreciate if someone has an answer or an experience to share.

Thanks!

**Comment by XiaoningLiu** [comment]
@jiacfan Please take a look. CRI seems failed to noticy this due to TFS issue.

If you need to have multi `BlobService` instances with different settings (such like different retry settings), then feel free to have multi instances. Otherwise, I think one instance should be enough.

**Comment by avivklas** [comment]
Understood. Thanks for the quick response :)
