### ISSUE TITLE
How do you group and/or in an Azure Table query?

### ISSUE THREAD

**Issue by securityvoid** [Azure/azure-storage-node#606]
What is the proper way to do the following Azure Table Storage query utilizing the NodeJS library?

`TYPE eq 'MYTYPE' and (PartitionKey eq '1' or PartitionKey eq '2')`

e.g. How do you create the equivalent of parenthesis utilizing the library, or is there anyway to manually create the query rather than utilizing the "where", "and" "or"?

If its currently possible to do this, the following documentation should probably be updated to make it more clear how its done:
https://azure.github.io/azure-storage-node/TableQuery.html

**Comment by XiaoningLiu** [comment]
@securityvoid 

I believe you could do this by using combine filters. Just like https://azure.github.io/azure-storage-node/TableQuery.html#.combineFilters__anchor

```javascript
var filter1 = TableQuery.stringFilter('Name', QueryComparisons.EQUAL, 'Person');
var filter2 = TableQuery.booleanFilter('Visible', QueryComparisons.EQUAL, true);
var combinedFilter = TableQuery.combineFilters(filter1, TableUtilities.TableOperators.AND, filter2);
```

**Comment by securityvoid** [comment]
@XiaoningLiu Thank-you! I don't know how I missed that in looking through the documentation!
