### ISSUE TITLE
feature request: support Copy Blob From URL

### ISSUE THREAD

**Issue by JianqinWang** [Azure/azure-storage-node#607]
Service: blob
Version of SDK: 2.10.2
Node.js version: v10.16.0

Attempting to use the API call `Copy Blob From URL` with the node client:
https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url

In the node docs, the `startCopyBlob` does not seem to take a parameter such as `requiresSync` to enable synchronous blob copies.

I'm able to access this functionality via `az cli`, and it looks to be supported in the python sdk. 

Thanks!

**Comment by jiacfan** [comment]
Hi, @JianqinWang 

Thanks for reaching us. `Copy Blob From URL` is supported as [syncCopyFromURL](https://github.com/Azure/azure-sdk-for-js/blob/470c11f9bb4e7f2b2d5adc37e91a806f2a87a1c7/sdk/storage/storage-blob/src/BlobURL.ts#L634) in our latest SDK for Js with new architecture, and here is [sample](https://github.com/Azure/azure-sdk-for-js/blob/a0e833897ebe89267eb4c04697cdf9c5f68c8e79/sdk/storage/storage-blob/test/node/bloburl.spec.ts#L41) for using it.

Best Regards,
Jiachen

**Comment by JianqinWang** [comment]
Are there plans for sync copy to be added here in [`azure-storage`](https://www.npmjs.com/package/azure-storage), or should we move away from using this library as a dependency and instead use [`@azure/storage-blob`](https://www.npmjs.com/package/@azure/storage-blob)?

**Comment by jiacfan** [comment]
Hi, @JianqinWang 

Yes, we would encourage to move to [@azure/storage-blob ](https://www.npmjs.com/package/@azure/storage-blob), it has other optimizations like footprint, clear dependency, better TS supports, and New features are planned to be add in [@azure/storage-blob ](https://www.npmjs.com/package/@azure/storage-blob).

Best Regards,
Jiachen

**Comment by JianqinWang** [comment]
Do you have a link to documentation for @azure/storage-blob similar to https://azure.github.io/azure-storage-node/BlobService.html? It's nice that there are many sample scripts in the repository, they are helpful for demonstration but do not provide enough detail to account for all functionality and use cases.

**Comment by jiacfan** [comment]
Yes. Thanks for trying! [Here](https://docs.microsoft.com/en-us/javascript/api/@azure/storage-blob/?view=azure-node-preview) is Js V10 API doc, [Here](https://github.com/Azure/azure-sdk-for-js/tree/a2976ef30901fa1192bb567e70740c437332a9ca/sdk/storage/storage-blob/samples) is some samples. At same time, we are continuously optimizing the documents, and will add more useful samples recently.

Thanks,
Jiachen

**Comment by JianqinWang** [comment]
Thanks so much! That is very helpful information. Closing :)
