### ISSUE TITLE
Blob: Additional bytes added to binary data when retrieving from store

### ISSUE THREAD

**Issue by dhensby** [Azure/azure-storage-node#608]
### Which service(blob, file, queue, table) does this issue concern?

blob

### Which version of the SDK was used?

2.10.3

### What's the Node.js/Browser version?

10.6.0

### What problem was encountered?

When retrieving binary data (PNG images in this case) the following error is thrown:

```
Error: An incorrect number of bytes was read from the connection. The connection may have been closed.
    at BlobService._validateLengthAndMD5 (./node_modules/azure-storage/lib/services/blob/blobservice.core.js:5422:28)
    at processResponseCallback (./node_modules/azure-storage/lib/services/blob/blobservice.core.js:1879:12)
    at Request.processResponseCallback [as _callback] (./node_modules/azure-storage/lib/common/services/storageserviceclient.js:329:13)
    at Request.self.callback (./node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (./node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (./node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
```

### Steps to reproduce the issue?

```js
const { promisify } = require('utils');
const { createBlobService } = require('azure-storage');

const blobSvc = createBlobService();
const createBlob = promisify(blobSvc.createBlockBlobFromText.bind(blobSvc));
const getBlob = promisify(blobSvc.getBlobToText.bind(blobSvc));

async function example() {
    await createBlob('container', 'test.png', Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), {
        contentSettings: {
            contentType: 'application/json',
        },
    });
    await getBlob('container', 'test.png'); // this will throw
}
```

### Have you found a mitigation/solution?

Use `getBlobToStream` instead. I understand that the blob is not text data, but if we can send and successfully store buffers representing non-text based data, why can we not retrieve it with the corresponding API. The response from the server seems to be corrupted in the server side as the text data gets 2 additional bytes added to it.

My debugging has found that the data response appears to be correct, but it has some additional trailing whitespace, which adds 2 additional bytes causing the length comparison to fail. Is there a better way to get a `Buffer` returned?

**Comment by jiacfan** [comment]
Hi, @dhensby 

Thanks for reaching us! 

The data in server side should be same as the bytes you uploaded, with exactly 8 bytes length.

The problem here could be, when `createBlockBlobFromText` with Buffer content, raw bytes will be uploaded without encoding, while during downloading with `getBlobToText`, the result will be decoded with utf8, and this would cause the length mismatch issue. 

And if using `createBlockBlobFromText` with string(text) content, it will be uploaded with utf8 encoded, and then during downloading with `getBlobToText`, it will be decoded properly. 

At same time, suggest to try latest [SDK ](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage/storage-blob) for JS with new architecture, [here](https://github.com/Azure/azure-sdk-for-js/blob/a2976ef30901fa1192bb567e70740c437332a9ca/sdk/storage/storage-blob/samples/javascript/advanced.js#L90) for example on downloading to buffer.

Best Regards,
Jiachen

**Comment by dhensby** [comment]
Thanks for the reply, is there any way to have `getBlobToText` handle non UTF-8 encoding?

**Comment by jiacfan** [comment]
You are welcome. `getBlobToStream` would be suggested to be used if custom encoding is used during uploading. In that case, we can create writeStream with wished encoding. 
Hope this could help.

Thanks,
Jiachen

**Comment by dhensby** [comment]
OK - thanks, so this seems to be an expected limitation of `getBlobToText` (which makes sense, really, you wouldn't expect a binary payload back from that) but it is failing due to a length mismatch which I can only imagine is because the assumptions made when decoding.

Feel free to close this issue if it's expected behaviour

**Comment by jiacfan** [comment]
Welcome discussion.

**Comment by GagandeepBajwa** [comment]
Hi, I have the same issue when downloading .tif images from the azure storage.
I am using Node Version: v10.16.0
SDK Version: 2.10.3

I am using getBlobToStream but still getting the same error mentioned above.

I am trying to download multiple images from azure blob storage and when the image number is large this error is thrown at random images. (Almost all images are close to 1 MB size)

Number of images truing to download is close to 900

Thanks,

**Comment by jiacfan** [comment]
Hi, @GagandeepBajwa 

Welcome reaching us! Would you please let me know how you upload the images?

Thanks,
Jiachen

**Comment by dhensby** [comment]
>I am using getBlobToStream but still getting the same error mentioned above.

This issue is specifically about getBlobToText, I suggest you open an new issue rather than tag onto a closed one
