### ISSUE TITLE
ChunkStream not emitting 'error' until after emitting 'close'

### ISSUE THREAD

**Issue by smanousos** [Azure/azure-storage-node#609]
blob service / azure-storage 2.10.3 

1. use createBlobServiceWithSas to create a blob service instance.  The Sas policy should have read-only permissions so as to force a write error.
2. create a write stream using that service instance with createWriteStreamToBlockBlob.
3. attempt to pipe a read stream to that write stream.

Expected behavior: 
The write stream should emit the 'error' event.

Observed behavior: 
The write stream first emits the 'close' event then emits the 'error' event.  Reproducible 100%

According to the node.js doc, nothing should be sent after 'close': 
https://nodejs.org/api/stream.html#stream_event_close

This is a show stopper.  'close' without 'error' indicates success. Stream management packages like end-of-stream use .once on the callback so the 'error' event is hidden.

What appears to be happening is:

BatchOperation.RestOperation is calling chunkStream.stop(), which in turn is calling ChunckStream.destroy().  destroy() emits the 'close'.  

The error isn't emitted until all batch operations are complete in tryEmitEndEvent().

**Comment by XiaoningLiu** [comment]
Hi @smanousos Thanks for the detailed investigation. Why "The write stream should emit the 'error' event.", which kind of error is expected?

`createWriteStreamToBlockBlob` supports a callback and only triggers only when uploads finishes or failed. You can leverage this callback for upload end status checking.

You can also try using `createBlockBlobFromStream", which accept a Readable Stream and doesn't need a pipe.

BTW, recommend to switch to our next generation of Azure Storage JS SDK with async & promise support. Try with global method `https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage/storage-blob` for stream uploading. 

See here: https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage/storage-blob

**Comment by smanousos** [comment]
Hello @XiaoningLiu ,
"Which kind of error is expected?"  I expected the standard nodejs stream 'error' event that you currently emit in the situation I described, but in the correct sequence according to the specification. This occurs for any network error.

I'll try one of the other apis you mention as a short term fix and consider moving to the next generation longer term.

**Comment by XiaoningLiu** [comment]
@smanousos Sorry for the inconvenience. We are currently more focusing on next generation storage JS SDK (V10), such as @azure/storage-blob package. V10 has been GAed last year, and V12 will come soon too. Recommend to switch to `@azure/storage-blob` package which has less footprint and higher performance.

Here is the sample for V10 to upload from a stream without knowing about stream length.
https://github.com/Azure/azure-sdk-for-js/blob/33f6a066a6f9dd4e660c7280908d36624d22cc61/sdk/storage/storage-blob/samples/javascript/advanced.js#L63

`azure-stroage` will be here, will almost no new storage featuers update, besides critical security issues, bugs fixing frequencey maybe slow down.
