### ISSUE TITLE
Security vulnerabilities with the 'request' module

### ISSUE THREAD

**Issue by jbinard** [Azure/azure-storage-node#61]
Hello,

Could you update the 'request' module to fix the security vulnerabilities reported by the 'nsp' tool (https://nodesecurity.io/advisories/qs_dos_extended_event_loop_blocking and https://nodesecurity.io/advisories/qs_dos_memory_exhaustion). 
The issue is with the submodule 'qs' which is in version 0.6.6 in 'request' 2.27.0. This issue is fixed in 'request' 2.40.0 (the version 2.45.0 is currently used in the azure main module).

Thank you in advance.

**Comment by slepox** [comment]
0.4.5 is released with 'request' module updated.
