### ISSUE TITLE
Cannot read property 'protocol' of undefined

### ISSUE THREAD

**Issue by zzzxtreme** [Azure/azure-storage-node#611]
hello guys. I'm trying to use table service with cloudflare workers.

`    var azure = require('azure-storage');

    var tableSvc = azure.createTableService('storageaccountname', 'storageaccesskey');

    var s = '';

    try {

        tableSvc.createTableIfNotExists('mytable', function (error, result, response) {

            if (!error) {

                //Table exists or created

            }

        });

    } catch (eee) {

        s = eee;

    }`

I'm getting error _TypeError: Cannot read property 'protocol' of undefined_ when creating table.
I've tried azure.createTableService(connectionstring)  and also azure.createTableService(name,key,endpoint)

any help would be greatly appreciated.

**Comment by XiaoningLiu** [comment]
@zzzxtreme Can you reproduce this issue in your local Node.js environment?

**Comment by thetre97** [comment]
I get the exact same issue, using cloudflare workers as well.
I did ensure I was specifying the protocol in the endpoint - e.g. `https://<account name>.queue.core.windows.net`

@zzzxtreme Did you manage to get this to work at all?

**Comment by zzzxtreme** [comment]
> I get the exact same issue, using cloudflare workers as well.
> I did ensure I was specifying the protocol in the endpoint - e.g. `https://<account name>.queue.core.windows.net`
> 
> @zzzxtreme Did you manage to get this to work at all?

hi there I kinda give up on cloudflare worker.
in another instance, some aws apis didn't work. we found out that it is because cloudflare didn't support xmlhttp which is used by many sdks. we had to find the particular sdk file which uses xmlhttp, and change it to using fetch, which cloudflare supports.

so if you do really need to use cloudflare and azuresdk, check if azuresdk contains any xmlhttp code and change it to fetch. 

you can google "cloudflare aws xmlhttp fetch"

**Comment by thetre97** [comment]
Thanks @zzzxtreme - that's helpful, I'll have a look at it.
I also tried using the new V10 SDK, but came up with a `document is not defined` error 🙄
