### ISSUE TITLE
Hi, I have anissue when downloading large number of .tif images from the azure storage.

### ISSUE THREAD

**Issue by GagandeepBajwa** [Azure/azure-storage-node#612]
Hi, I have the same issue when downloading .tif images from the azure storage.
I am using Node Version: v10.16.0
SDK Version: 2.10.3

I am using getBlobToStream but still getting the same error mentioned above.

I am trying to download multiple images from azure blob storage and when the image number is large this error is thrown at random images. (Almost all images are close to 1 MB size)

Number of images trying to download is close to 900

Thanks,

_Originally posted by @GagandeepBajwa in https://github.com/Azure/azure-storage-node/issues/608#issuecomment-521733864_

**Comment by GagandeepBajwa** [comment]
Hi! I actually uploaded images manually to the azure storage after I started getting the issue and read about the issue #608. Before I was uploading files using createBlobFromFile.

**Comment by XiaoningLiu** [comment]
`ECONNRESET` means TCP connection breaks. Please try to control the upload/download concurrency, instead of invoking lots of `getBlobToStream` at the same time. You can leverage `async` module for concurrency control.

**Comment by GagandeepBajwa** [comment]
Thanks, @XiaoningLiu. I think I got an answer here because I am trying to download the images concurrently. Actually, before I solved this error by just trying again every time it threw an error.

Thanks for the suggestion to do concurrency control, I think, that will be the ideal solution.

**Comment by rohitkhatri** [comment]
Any example on how I can apply concurrency using `async`, because I'm already using `async`, here's my code:

```
static async uploadFromBuffer(fileBuffer, file_path, params) {
        const stream = getStream(fileBuffer);
        const streamLength = fileBuffer.length;

        return new Promise((resolve, reject) => {
            try {
                blobService.createBlockBlobFromStream(process.env.AZURE_STORAGE_CONTAINER_NAME, file_path, stream, streamLength, params, (err, result) => {
                    if (err) {
                        reject(err);
                    } else {
                        resolve(result);
                    }
                });
            } catch (e) {
                reject(e);
            }
        });
    }
```

And It still gives me error while uploading:

```
{ Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
```

**Comment by XiaoningLiu** [comment]
> Any example on how I can apply concurrency using `async`, because I'm already using `async`, here's my code:
> 
> ```
> static async uploadFromBuffer(fileBuffer, file_path, params) {
>         const stream = getStream(fileBuffer);
>         const streamLength = fileBuffer.length;
> 
>         return new Promise((resolve, reject) => {
>             try {
>                 blobService.createBlockBlobFromStream(process.env.AZURE_STORAGE_CONTAINER_NAME, file_path, stream, streamLength, params, (err, result) => {
>                     if (err) {
>                         reject(err);
>                     } else {
>                         resolve(result);
>                     }
>                 });
>             } catch (e) {
>                 reject(e);
>             }
>         });
>     }
> ```
> 
> And It still gives me error while uploading:
> 
> ```
> { Error: read ECONNRESET
>     at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
> ```

I don't see any concurreny control related code, missing it?

**Comment by rohitkhatri** [comment]
ok, then I must be wrong, can you give me an example with concurrency?

**Comment by XiaoningLiu** [comment]
You can do concurrency control by yourself or by 3rd party modules like `async`

https://www.npmjs.com/package/async
https://caolan.github.io/async/v3/docs.html#parallelLimit
...

```javascript
var async = require("async");
 
// ...or ES2017 async functions
async.mapLimit(urls, 5, async function(url) {
    const response = await fetch(url)
    return response.body
}, (err, results) => {
    if (err) throw err
    // results is now an array of the response bodies
    console.log(results)
})
```

**Comment by rohitkhatri** [comment]
Thank you so much, I will try and update here.

**Comment by suryamishraXO** [comment]
What's the latest update on this? Were you able to resolve it after controlling the concurrency?
In Node.js, I'm trying to download 4 files at once using `await Promise.all([]);`

If I do it sequentially, shall I assume this will be resolved? Because that will increase my function's execution time very much.
