### ISSUE TITLE
 CosmosDB Table Name with  '_'  not supported 

### ISSUE THREAD

**Issue by sasahoo** [Azure/azure-storage-node#614]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?
CosmosDB TableAPI with NodeJS type

### Which version of the SDK was used?
All

### What's the Node.js/Browser version?
All

### What problem was encountered?
In case of CosmosDB Table Name with '_' not supported in case of NodeJS. But it is supported with other API types such as Java and Python.

### Steps to reproduce the issue?
Create table with name "Test_Table" fails with Table format syntax error.

### Have you found a mitigation/solution?
Not yet.

**Comment by XiaoningLiu** [comment]
Hi @sasahoo According to https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-the-table-service-data-model#table-names

`Test_Table` is not a valid table name.

>These rules are also described by the regular expression "^[A-Za-z][A-Za-z0-9]{2,62}$".

**Comment by sasahoo** [comment]
Hi @XiaoningLiu , I checked the regex validation in Validate.js. But it is incompatible with other API types such as python, java and other fromats, where this naming is allowed for CosmosDb. I would like to propose a solution to pass a parameter (boolean flag) for CosmosDb, so that we can skip the regex validation. Also I tried to comment out the regex validation and created a pull request. As obvious, test cases failed. I understand. I removed the pull request. This azure-storage nodejs library used for both Storage services aand CosmosDb services. Please let me know whether the solution could be fit in. Even I am unaware with these changes, which test cases might be failed. Please analyse the above case and advise.

Regards,
Sandip

**Comment by XiaoningLiu** [comment]
@sasahoo 

Is there any official document from CosmosDB about table naming? If `-` is valid char in CosmosDB table name, PR is welcome. Tests cases may need update too to pass the CI.

You can also considering hack the `tableNameIsValid` method in your code base before calling into table related operations.

https://github.com/Azure/azure-storage-node/blob/4bffbc9920b9252b373cd0f6ff1ecde988b17d30/lib/common/util/validate.js#L321

**Comment by sasahoo** [comment]
Hi @XiaoningLiu ,

I found, no official document specifying the table name convention. Probably I need to ask the azure customer support folks to provide the details.

Anyway I have made the changes and created a pull request. (https://github.com/Azure/azure-storage-node/pull/615). Locally it works for me with the changes.

I am not sure, why it is failing. Would you please check? Probably that would be fast

Regards,
Sandip

**Comment by XiaoningLiu** [comment]
Hi,

Please go ahead and just update regex defined in tableNameIsValid() without touching other components. It’s a breaking change to add a parameter in createTableService, cases will be failed.

Before merging and release happens, please try to hack tableNameIsValid() directly in your code calling into storage SDK.

Best,
Xiaoning

**Comment by sasahoo** [comment]
Any change in regex validation still failing the test cases. I tried the same earlier. I created the PR and removed the same. Passing (skip regex) a flag to Table Service (CosmosDB specific) thatz the hack I could think of, takes care required validation, which  as mentioned in this PR #615. Any regex check also shouldn't fail test cases for storage services. The changes I made here, is working locally fine for CosmosDb, behaving same as java and python platform. Once you approve the merge, we can consider of putting separate regex validation for CosmosDb as well.  

I am aware of PR #616. The same is just the repeat of another PR, which I had withdrawn 2 days back. If you would like to keep that regex validation, thatz also fine, given all test cases for storage service (https://docs.microsoft.com/en-us/rest/api/storageservices/Understanding-the-Table-Service-Data-Model?redirectedfrom=MSDN) face no-regression.

> Hi, Please go ahead and just update regex defined in tableNameIsValid() without touching other components. It’s a breaking change to add a parameter in createTableService, cases will be failed. Before merging and release happens, please try to hack tableNameIsValid() directly in your code calling into storage SDK. Best, Xiaoning From: sasahoo <notifications@github.com> Sent: Tuesday, September 3, 2019 2:10 PM To: Azure/azure-storage-node <azure-storage-node@noreply.github.com> Cc: Xiaoning Liu <Xiaoning.Liu@microsoft.com>; Mention <mention@noreply.github.com> Subject: Re: [Azure/azure-storage-node] CosmosDB Table Name with '_' not supported (#614) Hi @XiaoningLiu<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FXiaoningLiu&data=02%7C01%7CXiaoning.Liu%40microsoft.com%7Cf8e6e614cc6b40ee4db508d730356565%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637030878203953876&sdata=%2B%2FcXC8Zye5ptwHcbiX9M%2FqMB2nKPibaeYy%2Fksq2VZBo%3D&reserved=0> , I found, no official document specifying the table name convention. Probably I need to ask the azure customer support folks to provide the details. Anyway I have made the changes and created a pull request. (#615<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-storage-node%2Fpull%2F615&data=02%7C01%7CXiaoning.Liu%40microsoft.com%7Cf8e6e614cc6b40ee4db508d730356565%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637030878203963871&sdata=ndO3rOdV16GM4K5bPVwlCrGGN8O5Ziof2GjVgPXqtsc%3D&reserved=0>). Locally it works for me with the changes. I am not sure, why it is failing. Would you please check? Probably that would be fast Regards, Sandip — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-storage-node%2Fissues%2F614%3Femail_source%3Dnotifications%26email_token%3DABUR5SGOCRGZOBZIUU45LS3QHX5UVA5CNFSM4ISMJYOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5XD3MI%23issuecomment-527318449&data=02%7C01%7CXiaoning.Liu%40microsoft.com%7Cf8e6e614cc6b40ee4db508d730356565%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637030878203973869&sdata=7Du%2FtEyvSu0Iz1KemrToXMQIexhg9Y1lcOAEMk7kytI%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABUR5SCF6A6ESZIZSQXR4A3QHX5UVANCNFSM4ISMJYOA&data=02%7C01%7CXiaoning.Liu%40microsoft.com%7Cf8e6e614cc6b40ee4db508d730356565%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637030878203973869&sdata=aJQdIn4UE363Hzh32AWmJnOtKto16UiAz4PJfk3S8as%3D&reserved=0>.

**Comment by sasahoo** [comment]
Hi @XiaoningLiu, Please review the recent changes in **7c896a5**. 



> Any change in regex validation still failing the test cases. I tried the same earlier. I created the PR and removed the same. Passing (skip regex) a flag to Table Service (CosmosDB specific) thatz the hack I could think of, takes care required validation, which as mentioned in this PR #615. Any regex check also shouldn't fail test cases for storage services. The changes I made here, is working locally fine for CosmosDb, behaving same as java and python platform. Once you approve the merge, we can consider of putting separate regex validation for CosmosDb as well.
> 
> I am aware of PR #616. The same is just the repeat of another PR, which I had withdrawn 2 days back. If you would like to keep that regex validation, thatz also fine, given all test cases for storage service (https://docs.microsoft.com/en-us/rest/api/storageservices/Understanding-the-Table-Service-Data-Model?redirectedfrom=MSDN) face no-regression. As per the above document storage services table naming convention suffices the validation, which is already there. But the same wont work for CosmosDb table naming convention.
> 
> > Hi, Please go ahead and just update regex defined in tableNameIsValid() without touching other components. It’s a breaking change to add a parameter in createTableService, cases will be failed. Before merging and release happens, please try to hack tableNameIsValid() directly in your code calling into storage SDK. Best, Xiaoning From: sasahoo [notifications@github.com](mailto:notifications@github.com) Sent: Tuesday, September 3, 2019 2:10 PM To: Azure/azure-storage-node [azure-storage-node@noreply.github.com](mailto:azure-storage-node@noreply.github.com) Cc: Xiaoning Liu [Xiaoning.Liu@microsoft.com](mailto:Xiaoning.Liu@microsoft.com); Mention [mention@noreply.github.com](mailto:mention@noreply.github.com) Subject: Re: [Azure/azure-storage-node] CosmosDB Table Name with '_' not supported (#614) Hi @XiaoningLiuhttps://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FXiaoningLiu&data=02%7C01%7CXiaoning.Liu%40microsoft.com%7Cf8e6e614cc6b40ee4db508d730356565%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637030878203953876&sdata=%2B%2FcXC8Zye5ptwHcbiX9M%2FqMB2nKPibaeYy%2Fksq2VZBo%3D&reserved=0 , I found, no official document specifying the table name convention. Probably I need to ask the azure customer support folks to provide the details. Anyway I have made the changes and created a pull request. (#615https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-storage-node%2Fpull%2F615&data=02%7C01%7CXiaoning.Liu%40microsoft.com%7Cf8e6e614cc6b40ee4db508d730356565%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637030878203963871&sdata=ndO3rOdV16GM4K5bPVwlCrGGN8O5Ziof2GjVgPXqtsc%3D&reserved=0). Locally it works for me with the changes. I am not sure, why it is failing. Would you please check? Probably that would be fast Regards, Sandip — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHubhttps://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-storage-node%2Fissues%2F614%3Femail_source%3Dnotifications%26email_token%3DABUR5SGOCRGZOBZIUU45LS3QHX5UVA5CNFSM4ISMJYOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5XD3MI%23issuecomment-527318449&data=02%7C01%7CXiaoning.Liu%40microsoft.com%7Cf8e6e614cc6b40ee4db508d730356565%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637030878203973869&sdata=7Du%2FtEyvSu0Iz1KemrToXMQIexhg9Y1lcOAEMk7kytI%3D&reserved=0, or mute the threadhttps://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABUR5SCF6A6ESZIZSQXR4A3QHX5UVANCNFSM4ISMJYOA&data=02%7C01%7CXiaoning.Liu%40microsoft.com%7Cf8e6e614cc6b40ee4db508d730356565%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637030878203973869&sdata=aJQdIn4UE363Hzh32AWmJnOtKto16UiAz4PJfk3S8as%3D&reserved=0.

**Comment by sasahoo** [comment]
Thanks @XiaoningLiu , 

This is done with the recent commit. I made a minor change in validate.js and merge the code from #616 as well. All test cases are through.
Please review and approve.

Regards,
Sandip

> Hi, Please go ahead and just update regex defined in tableNameIsValid() without touching other components. It’s a breaking change to add a parameter in createTableService, cases will be failed. Before merging and release happens, please try to hack tableNameIsValid() directly in your code calling into storage SDK. Best, Xiaoning

**Comment by XiaoningLiu** [comment]
Looks good. @jiacfan Please take a look as well.

**Comment by sasahoo** [comment]
Hi @XiaoningLiu,

Thanks for the review.
It would be highly appreciated, if you merge the changes into master. Would you please do that?

Regards,
Sandip

**Comment by XiaoningLiu** [comment]
Practice is to merge PR to dev branch, take to master branch when next release happens. It stills some time before next release happens. you can inject the validateTableName func in runtime, or refering SDK to your own repo. Sorry for the convenience.

**Comment by jiacfan** [comment]
@XiaoningLiu It looks good to me as well.
