### ISSUE TITLE
Get Blob (Image.png) and convert to Base64 String

### ISSUE THREAD

**Issue by alexfromgalax87** [Azure/azure-storage-node#618]
Hello,

I try to save Base64 String as Image.png to Blob storage:

/**
* Save image to blob storage
*/
const saveBase64ImageToBlob = (base64String, pictureName) => {
    let rawdata = base64String;
    let matches = rawdata.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/);
    let type = matches[1];
    let buffer = new Buffer(matches[2], 'base64');
    blobService.createBlockBlobFromText(config.blob.containerName, pictureName, buffer, {contentType:type}, (error, result, response) => {
        (error) ? console.log(error) : console.log(result);
    });
}

This code works fine and the Base64 string is saved as Image.png to blob storage.

Now i want to get the Image.png and convert it back to Base64:

/**
* List all blobs in container
*/
const listBlobsInContainer = (containerName, prefix) => {
    blobService.listBlobsSegmentedWithPrefix(containerName, prefix, null, function(err, result) {
        if (err) {
            console.log("Couldn't list blobs for container %s", containerName);
            console.error(err);
        } else {
            console.log('Successfully listed blobs for container %s', containerName);
            console.log(result.entries);
            result.entries.forEach(item => {
                blobService.getBlobToText(containerName, item.name, (error, text) => {
                    console.log(text);
                });
            })
        }
    });
};

So first i list all Blobs with the right prefix, that returns an array of blobs. Next i try to getBlobToText from each blob, which works aswell but returns a strange looking string which i can't use after on. Any idea how i could read the blob and convert it to Base64? Any help would be very appreciated.

Thank you in advance.

**Comment by XiaoningLiu** [comment]
@alexfromgalax87 Few suggestions here. Can you try with `getBlobToBuffer` to download raw buffer of the blob and check it's same with the buffer you uploaded in `createBlockBlobFromText`?

**Comment by alexfromgalax87** [comment]
Solution:

I use createReadStream now and convert the resulting data to base64:

blobService.createReadStream(config.blob.containerName, item.name).on('data', (data) => {
    let base64String = data.toString('base64');
});

**Comment by XiaoningLiu** [comment]
> Solution:
> 
> I use createReadStream now and convert the resulting data to base64:
> 
> blobService.createReadStream(config.blob.containerName, item.name).on('data', (data) => {
> let base64String = data.toString('base64');
> });

Looks good. Just pay attention to that, `data` event may be triggerred more than once if the payload is large.

**Comment by shubham1144** [comment]
Follow the steps provided in the official documentation as follows : 
```
https://docs.microsoft.com/en-gb/azure/storage/blobs/storage-quickstart-blobs-nodejs
```
and change the function provided as follows : 
```

const streamToString = async (readableStream) => {
  return new Promise((resolve, reject) => {
    const chunks = [];
    readableStream.on("data", (data) => {
      chunks.push(data);
    });
    readableStream.on("end", () => {
      let imageBuffer = Buffer.concat(chunks); 
      resolve(imageBuffer.toString('base64'));
    });
    readableStream.on("error", reject);
  });
}
```

Please note that the purpose of the above implementation is to get the blob image -> pass the blob to a read stream -> merge the chunks received -> convert to base 64 encoded string
