### ISSUE TITLE
Connection string contains unrecognized key: ""DefaultEndpointsProtocol"

### ISSUE THREAD

**Issue by Tiago-Altus** [Azure/azure-storage-node#619]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
latest version

### What's the Node.js/Browser version?
v10.16.3

### What problem was encountered?
when running a custom api call that uses blobService, console displays error Connection string contains unrecognized key: ""DefaultEndpointsProtocol" for the AZURE_STORAGE_CONNECTION_STRING environment variable

### Steps to reproduce the issue?
n/a

### Have you found a mitigation/solution?
no

**Comment by XiaoningLiu** [comment]
Please double check quotes is there additional `"` in the connection string.

**Comment by Tiago-Altus** [comment]
I have double quotes in the connection string:
AZURE_STORAGE_CONNECTION_STRING = "DefaultEndpointsProtocol=https;AccountName=name;AccountKey=key==;EndpointSuffix=core.windows.net";
