### ISSUE TITLE
accessing file share using azure-storage-file.js in an angular app

### ISSUE THREAD

**Issue by NtierDev** [Azure/azure-storage-node#620]
hi @XiaoningLiu

I got the same issue importing azure/storage-file from npm. 
After downloading the azure-storage-file.js and using in an angular web-app -- having issues implementing - on the lines of browser based samples.
Any pointers using the azure-storage-file.js with an Angular based browser app will help.

thanks in advance.

--------------------------------------------------------
hi @bastoune 

Do you import azure-storage from npm package? Currently, please download our JS bundled files to be used in your browser applications.

https://aka.ms/downloadazurestoragejs

_Originally posted by @XiaoningLiu in https://github.com/Azure/azure-storage-node/issues/496#issuecomment-409438088_

**Comment by jiacfan** [comment]
Hi, @NtierDev, 

Thanks for reaching us! 

To optimize the experience for developing browser app, we have a [new arch JS SDK](https://github.com/Azure/azure-storage-js/tree/master/file) with better browser app support. 

At same time, it's being continuously optimized in Azure SDK [repo](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage/storage-file-share), which target to provide a consistent user experience across Azure SDKs.

Welcome try and any kinds of suggestions under Azure SDK repo.

**Comment by jiacfan** [comment]
Close this issue as we don't get reply for months.

**Comment by NtierDev** [comment]
Hi,

Sorry didn't get back on this earlier.

We were able to use the new Azure Storage JS SDK successfully with the angular application.

thanks.
