### ISSUE TITLE
Not able to download File to local from an Nodejs web app hosted on Azure

### ISSUE THREAD

**Issue by lumayara** [Azure/azure-storage-node#624]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?
File

### Which version of the SDK was used?
latest

### What's the Node.js/Browser version?
latest

### What problem was encountered?
I am not getting any errors anymore but the file is not downloading.

### Steps to reproduce the issue?
```
app.get('/download/:name', (req, res) => {
    return new Promise((resolve, reject) => {
        fileService.getFileToStream(shareName, directoryName, req.params.name, fs.createWriteStream(req.params.name), function(error, serverFile) {
            if (error) {
                console.log("error");
                console.log(error);
                reject(error);
            } else {
              console.log("foooiii");
                resolve(req.params.name);
            }
        });
    });
```

### Have you found a mitigation/solution?
No

**Comment by XiaoningLiu** [comment]
I believe the downloading is started. Did you get output from `console.log("foooiii");`?

**Comment by XiaoningLiu** [comment]
A useful answer https://stackoverflow.com/questions/59935873/azure-file-download-from-my-node-application-hosted-on-azure-not-working
