### ISSUE TITLE
"socket hang up" for large files zipped and piped to blobService

### ISSUE THREAD

**Issue by cburatto** [Azure/azure-storage-node#626]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
2.10.3

### What's the Node.js/Browser version?
12.13.0

### What problem was encountered?
socket hang up for large files piped to blobService

### Steps to reproduce the issue?
Use node archiver (https://www.archiverjs.com/)
pipe folder contents to archiver (zip is not written to disk)
pipe archiver to `azure.createBlobService().createWriteStreamToBlockBlob(...)`
Goal is to do all in-memory without creating a zip in disk
After some time processing, it fails if the zipped content reaches several GBs
The error persists if you write the zip to disk and readStream it to azure.
-- this process worked for other archives

`Error: socket hang up     at connResetException (internal/errors.js:570:14)     at TLSSocket.socketOnEnd (_http_client.js:440:23)     at TLSSocket.emit (events.js:215:7)     at endReadableNT (_stream_readable.js:1183:12)     at processTicksAndRejections (internal/process/task_queues.js:80:21) { code: 'ECONNRESET' }`

### Have you found a mitigation/solution?
No

**Comment by jiacfan** [comment]
Hi, @cburatto 

Thanks for reaching us. 

We have switch to new generation of JS storage SDK which has got GA and is actively served and maintained. For uploading stream would you try this [function](https://github.com/Azure/azure-sdk-for-js/blob/1ad2e0d07d4cb062b2a38bcdb244964e6ed7b93d/sdk/storage/storage-blob/src/Clients.ts#L3688)?

For the issue, it should be related to underlayer request module, here is an active issue [link](https://github.com/request/request/issues/2047).

Thanks,
Jiachen

**Comment by jiacfan** [comment]
Close as no reply for 4 months, please feel free to let us know if more helps are wanted.
