### ISSUE TITLE
Copy Blob between storage accounts

### ISSUE THREAD

**Issue by amit12cool** [Azure/azure-storage-node#627]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
2.10.3

### What's the Node.js/Browser version?
Node.js v8.10.0

### What problem was encountered?
Copy blob between storage accounts

### Steps to reproduce the issue?
```startCopyBlob``` doesn't take destination storage account connection string, it seems it only copies the blob with the same storage account. If so, how can I achieve copying blob between storage accounts.?

### Have you found a mitigation/solution?
No solution found on the web.

**Comment by amit12cool** [comment]
@jiacfan Any idea of this?

**Comment by XiaoningLiu** [comment]
@amit12cool You can provide **source** blob's uri in `startCopyBlob` method. Source blob could be in different storage account.

**Comment by amit12cool** [comment]
Still not clear.How can I tranfer the blob from source to destination storage account.At present I can only mention source storage account.Can you please provide me an example?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by ramandeep-singh-1983** [comment]
> @amit12cool You can provide **source** blob's uri in `startCopyBlob` method. Source blob could be in different storage account.

@jiacfan you have mentioned about sourceUri argument only. The question is about destination storage account and how to specify it in the API. Here's the signature of startCopyBlob:

`startCopyBlob(sourceUri, targetContainer, targetBlob [, options], callback)`

sourceUri argument is fine. Where do we specify the destination storage account connection string or URI? Can targetContainer argument above contain target container URI along with container name?

**Comment by ramandeep-singh-1983** [comment]
@amit12cool

Here's the signature of startCopyBlob:

`startCopyBlob(sourceUri, targetContainer, targetBlob [, options], callback)`

This function belongs to the [BlobService](https://azure.github.io/azure-storage-node/BlobService.html) class. So, you need to instantiate the BlobService object using connection string of destination storage account and then provide the source URI in the sourceUri argument to copy it from source to destination storage account.

**Comment by amit12cool** [comment]
That helps.Thanks Raman.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
