### ISSUE TITLE
container name format  is incorrect 

### ISSUE THREAD

**Issue by PradneshShinde** [Azure/azure-storage-node#629]
Is there any specific format to name the Container in Azure Blob Storage.
I'm creating the container in blob runtime
Example : 

1. `myCotainer`  -> This gives format `error`.
2. `mycontainer` -> This `works well `and the container is created.

I wonder **camelCase** formatting not allowed? if yes I have curiosity in knowing more about it.
Thanks in advance.

My development Environment :
1. Node JS 
2. npm the [azure-storage lib](https://www.npmjs.com/package/azure-storage)

**Comment by PradneshShinde** [comment]
@XiaoningLiu  can anyone from your end help me know more on this

**Comment by jiacfan** [comment]
@PradneshShinde 

Here is detailed [doc](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names):

> A container name must be a valid DNS name, conforming to the following naming rules:
> Container names must start with a letter or number, and can contain only letters, numbers, and the dash (-) character.
> Every dash (-) character must be immediately preceded and followed by a letter or number; consecutive dashes are not permitted in container names.
> All letters in a container name must be lowercase.
> Container names must be from 3 through 63 characters long.
