### ISSUE TITLE
request is deprecated

### ISSUE THREAD

**Issue by Richienb** [Azure/azure-storage-node#630]
See https://github.com/microsoft/appcenter-cli/issues/761

**Comment by jiacfan** [comment]
Hi, Richienb:

Thanks for reaching us! 

We've moved to [Storage SDK v10 for JavaScript](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage) for latest SDK support(which no more deps on request module). That repro is with agile service and latest features.

Welcome to take a look. And please feel free to let us know if there is any issue with using it.

Thanks,
Jiachen

**Comment by gwh-cpnet** [comment]
@Richienb Moving to v10 is not as easy as you said if table service is left behind.

**Comment by jiacfan** [comment]
@gwh-cpnet Thanks for reply. Yes, table service is not yet supported in v10-v12 SDK, and we're actively bringing feedbacks collected in github to the team.

**Comment by jiacfan** [comment]
@JonSilver Thanks for reply, and sorry for inconvenience. I'll for sure escalate the voice here. And I fully understand the feelings here as a developor.

**Comment by JonSilver** [comment]
@jiacfan this morning [this response](https://github.com/Azure/azure-sdk-for-js/issues/5655#issuecomment-621654247) was posted over in the _azure-sdk-for-js_ repo, saying work was underway and to expect previews in the next couple of months.

**Comment by jiacfan** [comment]
Close the issue. And please feel free to let us know if there is other topics wish to be followed.

**Comment by joheredi** [comment]
Hello everyone! We are happy to announce that we have released the first Beta of the new [Azure Tables SDK](https://www.npmjs.com/package/@azure/data-tables). It conforms to our new [guidelines on writing JS SDKs for Azure services](https://azure.github.io/azure-sdk/general_introduction.html) which ensure it will remain idiomatic, consistent and diagnosable.

You can install it with `npm install @azure/data-tables`

Please share your feedback on the new design at [#11179](https://github.com/Azure/azure-sdk-for-js/issues/11179) and/or report any problems you find in a new GitHub issue. Looking forward to hear from you!
