### ISSUE TITLE
createBlockBlobFromLocalFile with Error: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by daixianfeng-zz** [Azure/azure-storage-node#631]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
"azure-storage": "^2.10.3",

### What's the Node.js/Browser version?
v12.16.1

### What problem was encountered?
Call Promise to upload image file with createBlockBlobFromLocalFile function.
ESOCKETTIMEDOUT error often appear at the second time or third time.
20s~50s apart with each call
Image file size is about 100KB.

### Steps to reproduce the issue?
```
return new Promise(resolve => { 
//     resolve(); 
    blobService.createBlockBlobFromLocalFile("workspace-portal-image-diff-actual", blobName, actualFileName, error => { 
      if (!error) { 
        blobService.createBlockBlobFromLocalFile( 
          "workspace-portal-image-diff-expect", 
          blobName, 
          expectFileName, 
          expectFileUploadError => {
            if (!expectFileUploadError) { 
              blobService.createBlockBlobFromLocalFile( 
                "workspace-portal-image-diff", 
                blobName, 
                diffFileName, 
                resFileUploadError => { 
                  if (resFileUploadError) { 
                    console.error(resFileUploadError); 
                  } 
                  console.log(`diff & mail use time: ${Date.now() - diffStartTime}ms`); 
                  resolve(); 
                } 
              ); 
            } else {
              console.error(expectFileUploadError);
              resolve(); 
            }
          } 
        ); 
      } else {
        console.error(error); // error log here.
        resolve(); 
      }
    }); 
```

 console.error tests-e2e/image-diff/run.js:66
      Error: ESOCKETTIMEDOUT
          at ClientRequest.<anonymous> (C:\Users\xiandai\project\workspace-portal\node_modules\request\request.js:816:19)
          at Object.onceWrapper (events.js:417:28)
          at ClientRequest.emit (events.js:311:20)
          at ClientRequest.EventEmitter.emit (domain.js:482:12)
          at TLSSocket.emitRequestTimeout (_http_client.js:714:9)
          at Object.onceWrapper (events.js:417:28)
          at TLSSocket.emit (events.js:311:20)
          at TLSSocket.EventEmitter.emit (domain.js:482:12)
          at TLSSocket.Socket._onTimeout (net.js:478:8)
          at listOnTimeout (internal/timers.js:549:17)
          at processTimers (internal/timers.js:492:7) {
        code: 'ESOCKETTIMEDOUT',
        connect: false
      }

**Comment by ljian3377** [comment]
Found some related page with the same issue of the request module by searching "ESOCKETTIMEDOUT":
https://stackoverflow.com/questions/35387264/node-js-request-module-getting-etimedout-and-esockettimedout
https://github.com/request/request/issues/2738
https://github.com/request/request/issues/2676

Please let us know if these help. Also I would suggest switch to our new SDK which do not depend on the request module as it has been deprecated: https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage
