### ISSUE TITLE
error FeatureNotYetSupportedForHierarchicalNamespaceAccounts

### ISSUE THREAD

**Issue by a8775** [Azure/azure-storage-node#632]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
@azure/storage-blob": "^12.1.1

### What's the Node.js/Browser version?
10.17.0

### What problem was encountered?
error FeatureNotYetSupportedForHierarchicalNamespaceAccounts

similar problem: https://stackoverflow.com/questions/60023148/i-need-to-append-logs-to-auditlog-csv-file-in-blob-storage-of-datalake-gen-2-fro

### Steps to reproduce the issue?
The blob storage with enabled ADLS2
```
await blob.appendBlock(contents,contents.length) // error FeatureNotYetSupportedForHierarchicalNamespaceAccounts
```

**Comment by XiaoningLiu** [comment]
If your storage account enables HierarchicalNamespace (an option when you creating the storage account), then some of features in blob SDK is not supported.

Recommend you to use @azure/storage-file-datalake which is designed for HNS enabled storage account.
