### ISSUE TITLE
SharedAccessPermissions typings are out of sync with actual code

### ISSUE THREAD

**Issue by AlenPelin** [Azure/azure-storage-node#636]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
2.10.3

### What's the Node.js/Browser version?
10.16.3

### What problem was encountered?
Typings for BlobUtilities.SharedAccessPermissions misses two options that exist in js code:
    ADD: 'a',
    CREATE: 'c',

Typings:  
https://github.com/Azure/azure-storage-node/blob/master/typings/azure-storage/azure-storage.d.ts#L3257

Actual Code:  
https://github.com/Azure/azure-storage-node/blob/66d24e89eeedf77ab83356c69fe5a39ed03b73b9/lib/services/blob/blobutilities.js#L31

### Steps to reproduce the issue?
The following code won't compile:
```ts
import azure from 'azure-storage';
const policy = {
    AccessPolicy: {
        ServiceVersion: '2019-02-02',
        // the order of permissions must be: read add create write delete list
        Permissions: azure.BlobUtilities.SharedAccessPermissions.READ + azure.BlobUtilities.SharedAccessPermissions.ADD + azure.BlobUtilities.SharedAccessPermissions.CREATE + azure.BlobUtilities.SharedAccessPermissions.WRITE + azure.BlobUtilities.SharedAccessPermissions.DELETE + azure.BlobUtilities.SharedAccessPermissions.LIST,
        Start: new Date(),
        Expiry: new Date(Date.now() + 10 * 60 * 1000),
        Protocols: 'https'
    }
}
```

### Have you found a mitigation/solution?
Yes, disable ts check with // @ts-ignore

**Comment by ljian3377** [comment]
Thanks for the info but we probably won't fix it as this repository is now in maintenance mode.

New feature will only be available on [V12](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage) while only critical bugs will be fixed in this legacy SDK. We strongly encourage customers to upgrade.
