### ISSUE TITLE
Uploading image to Blob storage via SAS url

### ISSUE THREAD

**Issue by hoangpham95** [Azure/azure-storage-node#637]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
12.1.0

### What's the Node.js/Browser version?
Node 10.19.0

### What problem was encountered?
I have a Node.js server that generates a signed URL with SAS key and a client (React Native) can request such link. The link is of the form:
```
https://<app name>.blob.core.windows.net/<folder name>/<file name>?<sas query params>;
```
Example:
```
https://<my app>.blob.core.windows.net/<my folder>/<filename>?sv=2019-07-07&ss=bf&srt=co&st=2020-04-17T07%3A15%3A31Z&se=2020-04-18T07%3A15%3A31Z&sp=rwc&sig=AcucnN%2BhvE%2Fy49UXn%2FMB5KcgzOLxWphT96L5pEkeRJ0%3D
```
I used existing brower's api like `fetch` or `xhr` but none of them is working.  Here's the HTTP request
```typescript
fetch(url, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/octet-stream',
          'Content-Length': base64Image.length,
          'x-ms-blob-type': 'BlockBlob',
          'x-ms-blob-content': 'image/jpeg'
        },
        body: base64Image // this is where my image is being converted to base64 string
      });
```
Could you suggest on how to work around this problem?

### Have you found a mitigation/solution?
No.

**Comment by XiaoningLiu** [comment]
Recommend to use our latest package @azure/storage-blob which supports browser scenario.

Like 
```javascript
const blockBlobClient = new BlockBlobClient(<sasurl>);
await blockBlobClient.uploadxxx();
```
