### ISSUE TITLE
inconsistent error handling in blobservice: error-event vs callback

### ISSUE THREAD

**Issue by Lhdang88** [Azure/azure-storage-node#638]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
2.10.3

### What's the Node.js/Browser version?
v10.15.0

### What problem was encountered?
in /lib/services/blob/blobservice.core.js:4363

```javascript
self._uploadBlobFromStream(createNewBlob, container, blob, blobType, stream, null, options, function (error, blob, response) {
        if (error) {
          stream.emit('error', error);
        }

        if (callback) {
          callback(error, blob, response);
        }
      });
```
In my opinion this is inconsistent event-handling:
stream.emit('error', error) requires the client to handle with stream.on('error', error), while also providing an error-handling callback. Just use one channel of error-handling.
 
this is i.e. not handled properly in another lib: [azure-kusto-ingest](https://github.com/Azure/azure-kusto-node/blob/master/azure-kusto-ingest/source/ingestClient.js#L49) causing client applications to crash, because it's not handled there.

### Steps to reproduce the issue?
n/a

### Have you found a mitigation/solution?
```javascript
self._uploadBlobFromStream(createNewBlob, container, blob, blobType, stream, null, options, function (error, blob, response) {
        if (callback) {
          callback(error, blob, response);
        } 
      });
```

**Comment by XiaoningLiu** [comment]
Thanks for reporting this! azure-storage package is in matinaince mode only for security issues. Recommend try with next generation storage SDK @azure/storage-blob which provides async methods for better user experience.
