### ISSUE TITLE
Is there are a way to Pause/Resume/Cancel blockBlobClient.uploadStream?

### ISSUE THREAD

**Issue by 1c7** [Azure/azure-storage-node#639]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?
`@azure/storage-blob`

### Which version of the SDK was used?
`"@azure/storage-blob": "^12.1.1"`

### What's the Node.js/Browser version?
Node v12.11.0

### What problem was encountered?
How can I pause/resume file upload with `uploadStream`? (in Node.js)

### Steps to reproduce the issue?
```javascript
const ONE_MEGABYTE = 1024 * 1024;
const uploadOptions = {
  bufferSize: 4 * ONE_MEGABYTE,
  maxBuffers: 20
};

var readStream = fs.createReadStream(file_path);
await blockBlobClient.uploadStream(readStream,
  uploadOptions.bufferSize, uploadOptions.maxBuffers, {
    onProgress: (ev) => {
      onProgress(ev);
    }
  });
```

### Have you found a mitigation/solution?
No

**Comment by jiacfan** [comment]
Hi, @1c7 

Thanks for reaching us!
The package @azure/storage-blob is maintained [here](https://github.com/Azure/azure-sdk-for-js), and it's the latest v12 SDK under agile maintaining. I see you already opened an related issue [7661](https://github.com/Azure/azure-sdk-for-js/issues/7661) there, we'll follow up in that thread continuously.
At same time close this issue as duplicated.

Best Regards,
Jiachen
