### ISSUE TITLE
Documentation linked in readme.md is ancient

### ISSUE THREAD

**Issue by phairoh** [Azure/azure-storage-node#64]
The [documentation](http://dl.windowsazure.com/nodedocs/index.html) linked in readme.md is incredibly old (January 2014).  Some methods (i.e. blobservice.listContainers) completely do not exist.  The link needs to be updated to the [current docs for 0.4.4](http://azure.github.io/azure-storage-node/).

Old URL: http://dl.windowsazure.com/nodedocs/index.html
Current URL: http://azure.github.io/azure-storage-node/

**Comment by slepox** [comment]
@phairoh , if you mean the link in the note under the title:

> If you are looking for documentation for the Azure SDK for Node.js, see http://dl.windowsazure.com/nodedocs/index.html or visit https://github.com/Azure/azure-sdk-for-node. While the Azure SDK for Node.js provides support for working with Azure Storage, you should consider using the Azure Storage SDK as it supports features not available in the Azure SDK for Node.js

Here is to refer to the legacy Azure SDK for node.js, not for this project, and we suggest you turn to this one for latest features and more proactive maintenance.

**Comment by phairoh** [comment]
I understand now, although it is incredibly unclear and the wording should be changed.  The names "Azure SDK for Node.js" and "Azure Storage SDK" are far too similar and even looking at both of them now I have trouble knowing which is which even though I know the answer.  I'm uncertain the best way to fix that but perhaps given that this library has superseded the old one perhaps it's time to remove this block of text completely.
