### ISSUE TITLE
Download file in chunks

### ISSUE THREAD

**Issue by care2achieve** [Azure/azure-storage-node#640]
### Which service(blob, file, queue, table) does this issue concern?
File

### Which version of the SDK was used?
2.10.3

### What's the Node.js/Browser version?
Node.js v8.10.0

### What problem was encountered?
trying to download large files in chunks. seems REST APIs supporting this feature(https://docs.microsoft.com/en-us/rest/api/storageservices/get-file). But i didn't see any option to specify these options in headers. 

### Steps to reproduce the issue?
Need to download the file in chunks

### Have you found a mitigation/solution?
Nope

**Comment by XiaoningLiu** [comment]
File download methods option includes parameters like rangeStart to specific ranges. Refer to http://azure.github.io/azure-storage-node/FileService.html#getFileToStream__anchor
