### ISSUE TITLE
Support react-native

### ISSUE THREAD

**Issue by shaman-apprentice** [Azure/azure-storage-node#646]
### What's the Node.js/Browser version?
[react-native](https://reactnative.dev/) provides a further JS environment for native mobile apps. I believe for small applications it is best practice to have a "thick client" and let it communicate with azure storage directly, without adding a server in between (to minimize the code / development and maintaining costs, as well as the running cloud costs). 

### What problem was encountered?
Unfortunately this package is not compatible with react-native, due to missing `util`, `fs` in react-native environment and maybe something else. Adding support for react-native in addition to nodejs and the browser would be awesome 😍

**Comment by jiacfan** [comment]
Hi, @shaman-apprentice :

Thanks for reaching us!

We've moved to [Storage SDK v12 for JavaScript](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage) for latest SDK support(which has clean dep tree). That repro is with agile service and latest features.

Welcome to take a look. And please feel free to let us know if there is any issue with using it.

Thanks,
Jiachen

**Comment by shaman-apprentice** [comment]
I tried to use this version, as table storage is not (yet) supported in v12. Digging a little deeper I have hope, that v12 will support it very soon :) So I guess just waiting is totally reasonable.

For reference:
https://github.com/Azure/azure-sdk-for-js/issues/5655
https://github.com/Azure/azure-sdk-for-js/issues/8946

**Comment by EmmaZhu** [comment]
@azure/data-tables has been added to repository [https://github.com/Azure/azure-sdk-for-js](url). You may have already tried with it.

Does this resolve your requirement?

**Comment by shaman-apprentice** [comment]
Thanks for pointing out! Unfortunately I will probably have no time in the near future to try it out. But on first sight it looks good. So I would vote for closing this issue and if I or someone encounters issues with v12 of @azure/data-tables we can create a more concrete ticket.

Thanks again for coming back!
