### ISSUE TITLE
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

### ISSUE THREAD

**Issue by pmosconi** [Azure/azure-storage-node#648]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?
blobService

### Which version of the SDK was used?
2.10.3

### What's the Node.js/Browser version?
node.js 12.13.1

### What problem was encountered?
node api creates sas token that browser uses to upload blob; upload fails with error in title.
This stopped working in the last few days. 

### Steps to reproduce the issue?
Following is server side code that creates the token:

`
  createToken(file) {

    const startDate = new Date();

    const minutes = startDate.getMinutes();

    // startDate.setMinutes(minutes - 5);

    const expiryDate = new Date(startDate);

    expiryDate.setMinutes(minutes + 180);

    const permissions = azure.BlobUtilities.SharedAccessPermissions.WRITE + azure.BlobUtilities.SharedAccessPermissions.CREATE;

    const sharedAccessPolicy = {

      AccessPolicy: {
        Permissions: permissions,
        Start: startDate,
        Expiry: expiryDate
      }

    };

    const token = blobService.generateSharedAccessSignature(storageConfig.container, file, sharedAccessPolicy);

    return token;

  }
`

And this is the upload performed by browser:

`
https://capcostimport.blob.core.windows.net/capcost/CG_ActvalueVOD_SAIPEM20B2.csv?comp=block&blockid=NjAzNGFlNGQtMDAwMDAx&st=2020-06-24T14%3A52%3A29Z&se=2020-06-24T17%3A52%3A29Z&sp=wc&sv=2018-03-28&sr=b&sig=MEBK17t0Q%2Fn6JQ%2Bxg2M1X0H%2FcuZq9nxqigQx0nXAdM0%3D&api-version=2017-07-29
`

Code:

`
const upload = (file, filename, azToken) => {

  return new Promise((resolve, reject) => {

    const blobService = window.AzureStorage.createBlobServiceWithSas(storage.host, azToken);

    const customBlockSize = file.size > 1024 * 1024 * 32 ? 1024 * 1024 * 4 : 1024 * 512;

    blobService.singleBlobPutThresholdInBytes = customBlockSize;

    blobService.createBlockBlobFromBrowserFile(storage.container, filename, file, {blockSize : customBlockSize}, function(error, result, response) {

      if (error) {

          return reject(error);

      } else {

          return resolve(response);

      }

    });

  });

};

`

### Have you found a mitigation/solution?
No

**Comment by ljian3377** [comment]
Sorry for the delay. Will look into it.

**Comment by ljian3377** [comment]
The permission need to follow specified order, create should be before write.
`Permissions: BlobUtilities.SharedAccessPermissions.CREATE + BlobUtilities.SharedAccessPermissions.WRITE`.
