### ISSUE TITLE
Unable to install azure-storage package in Azure Function

### ISSUE THREAD

**Issue by thebernardlim** [Azure/azure-storage-node#654]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?
Table

### Which version of the SDK was used?
v12

### What's the Node.js/Browser version?
12.18.0

### What problem was encountered?
Unable to install azure-storage package for Azure function.
2 WARN errors occured
![image](https://user-images.githubusercontent.com/4549340/92004598-fb84e000-ed74-11ea-9a4b-96c191b03998.png)

### Steps to reproduce the issue?
npm install azure-storage

### Have you found a mitigation/solution?
No

**Comment by XiaoningLiu** [comment]
Hi @thebernardlim, please upgrade to latest storage packages like `azure-storage-blob`. azure-storage package will not have features updates.

**Comment by thebernardlim** [comment]
Hi @XiaoningLiu , does it apply to Table Storage as I am only using Table Storage

**Comment by XiaoningLiu** [comment]
Next generation table package is under development and will be release soon.

**Comment by thebernardlim** [comment]
Noted. Thanks
