### ISSUE TITLE
The CorsRule type is of type CorsRule array, but when getProperties is called on a blob service client with no Cors rules it returns an empty string instead of an empty array.

### ISSUE THREAD

**Issue by avenmia** [Azure/azure-storage-node#655]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
"@azure/storage-blob": "^12.2.0-preview.1"

### What's the Node.js/Browser version?
v12.18.3

### What problem was encountered?
When calling getProperties() on a BlobServiceClient it returned a Cors property with the value: '' (empty string). When I modify the a different property (deleteRetentionPolicy) and try to call setProperties I get an error stating that cors needs to be of type array. 

"{"message":"blobServiceProperties.Cors must be of type Array.","stack":"Error: blobServiceProperties.Cors must be of type Array.\n    at serializeSequenceType "

### Steps to reproduce the issue?

1. Have a BlobServiceClient with no Cors settings
2. Call BlobServiceClient.fromConnectionString to retrieve the blob service client
3. Call getProperties() on that service client to retrieve the properties
4. Modify a different property such as deleteRetentionPolicy
5. call setProperties with the modified service properties
6. Receive error on how cors needs to be of type array

```
const storageConnectionString = config.storageConnectionString;

    // Create the BlobServiceClient object which will be used to create a container client
    const blobServiceClient = BlobServiceClient.fromConnectionString(storageConnectionString);
    
    if (config.enableSoftDeletes)
    {
        const blobServiceProperties = (await blobServiceClient.getProperties())._response.parsedBody;
        blobServiceProperties.deleteRetentionPolicy =  { enabled: true, days: 10 };
        await blobServiceClient.setProperties(blobServiceProperties);    
    }
```

After calling getProperties()
![image](https://user-images.githubusercontent.com/17712276/92328796-e041fb00-f028-11ea-9d8d-64d8deb5ea35.png)

### Have you found a mitigation/solution?

My current workaround is to add a ts-ignore and a check for the empty string, if it is then use an empty array.
![image](https://user-images.githubusercontent.com/17712276/92328813-010a5080-f029-11ea-8ce2-201dc15c3388.png)

**Comment by jiacfan** [comment]
@avenmia 

Thanks for reaching us! This is a good catch! We'll investigate and fix ti.

At same time, latest v12 SDK is maintained in [this](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage) repository. To keep trace of your contribution and for ease of problem tracking, would you help to fork this question to the latest repository?

Thanks,
Jiachen

**Comment by avenmia** [comment]
@jiacfan 

Sounds good, I'm new to issue reporting. What do you mean by "fork this question." Are you saying I should also create this issue in [this](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage) repository?

**Comment by jiacfan** [comment]
Sorry for causing confusion. Please create a new issue in v12 SDK repository([link](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage)) and link this issue.

Thanks,
Jiachen

**Comment by jiacfan** [comment]
Thanks! Closing this issue and tracing with v12 SDK repro.
