### ISSUE TITLE
Blob ClientSide Encryption issue

### ISSUE THREAD

**Issue by tudor33sud** [Azure/azure-storage-node#656]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?

Blob
### Which version of the SDK was used?
12.2.0

### What's the Node.js/Browser version?
Nodejs 12

### What problem was encountered?

Cannot decrypt client side encrypted data from .NET
### Steps to reproduce the issue?
In our team, there's a service written in .NET which encrypts data client-side before uploading it to BlobStorage. Data downloaded from blob storage explorer evidently cannot be used locally without decrypting. 

We are trying to have a nodejs process to download the data, decrypt it and do some processing on it. Encryption on blob storage setting is set to microsoft managed key, however the data is encrypted on top of it before uploading. 

Looking at the blob metadata, I have found that the algorithm used by .net library is AES256(CBC version). I tried using a decryption tool with the secret key that I know it is used when encrypting the data, I added the IV from the blob metadata, however data still cannot be decrypted correctly. I assume I am missing something on the EncryptedKey property of the blob metadata, which is not the secret key that we use for encryption, so I don't know how to add it up in the mix.

The question is: **does the NodeJS sdk supports decryption in any way for client side encrypted data? If so, how can I use it? Attaching now the JSON metadata for further reference.**

> {"$type":"Microsoft.WindowsAzure.Storage.Blob.BlobEncryptionData, Microsoft.Azure.Storage.Blob","EncryptionMode":"FullBlob","WrappedContentKey":{"$type":"Microsoft.WindowsAzure.Storage.WrappedKey, Microsoft.Azure.Storage.Common","KeyId":"BlobEncryptionKey",**"EncryptedKey":{"$type":"System.Byte[], System.Private.CoreLib","$value":"y7nfy5hUfq26ZIcZUygfROALGeR5aYUZ0liUCokknp+EgWWCs2Ej3A=="},"Algorithm":"A256KW"}**,"EncryptionAgent":{"$type":"Microsoft.WindowsAzure.Storage.EncryptionAgent, Microsoft.Azure.Storage.Common","Protocol":"1.0","EncryptionAlgorithm":"AES_CBC_256"},"ContentEncryptionIV":{"$type":"System.Byte[], System.Private.CoreLib","$value":"Jog2eGL92m+08sBFeowcew=="},"KeyWrappingMetadata":{"$type":"System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.String, System.Private.CoreLib]], System.Private.CoreLib","EncryptionLibrary":".NET 9.4.2"}}

I will also attach the options that you can pass to .net sdk (there is this field called encryptionPolicy, which I didn't find an equivalent to for Node), where encryptionKey is actually the AES256 secret key 32 bit.
```
            if (encryptionKey != null)
            {
                BlobEncryptionPolicy policy = new BlobEncryptionPolicy(encryptionKey, null);
                myBlobRequestOptions = new BlobRequestOptions {EncryptionPolicy = policy};
            }
```

### Have you found a mitigation/solution?

1. I tried using SDK downloadToFile method for NodeJS and I found out there's the option customerProvidedKey where I can fill in some properties. https://docs.microsoft.com/en-us/javascript/api/%40azure/storage-blob/blobdownloadoptions?view=azure-node-latest 

I tried using it with no success, because encryption setting on blob storage is not set to customerprovidedkey, and I receive 409 status code since the container is not encrypted using a customer provided key. 

2. Looking at the client side encryption docs, I can only see configure clientside encryption with .net, java, and python. I couldn't find any NodeJS related info https://docs.microsoft.com/en-us/azure/storage/common/storage-client-side-encryption?toc=/azure/storage/blobs/toc.json 

Thank you in advance for your help! Please let me know if you need further information from me.

**Comment by XiaoningLiu** [comment]
Hi @tudor33sud Azure Storage JS SDK doesn't support client encryption. This repo is not updating with new features, please open issue as feature request in https://github.com/azure/azure-sdk-for-js
