### ISSUE TITLE
dead link on read me file.

### ISSUE THREAD

**Issue by anirugu** [Azure/azure-storage-node#659]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Have you found a mitigation/solution?

On the readme file, this link is mentioned https://docs.microsoft.com/en-us/javascript/api/azure-storage/?view=azure-node-latest this is dead and not working. 

Need fix!

**Comment by ljian3377** [comment]
Will ask our doc team about the reason and take action accordingly.
The current fix in https://github.com/Azure/azure-storage-node/pull/657 isn't suitable.

**Comment by ljian3377** [comment]
Fixed via #657
