### ISSUE TITLE
Chunked stream writing methods do not accept string

### ISSUE THREAD

**Issue by davazp** [Azure/azure-storage-node#66]
The stream created by `blobService#createWriteStreamToBlockBlob` does not work properly with strings. I can pass a `Buffer`, but when I pass a string it fails with a `undefined function` error. I have written a self-contained example to reproduce the problem.

```javascript
var azure = require('azure-storage');

var blobService = azure.createBlobService();

blobService.createContainerIfNotExists('test', function(error, result){
  if (error) return console.log(error);

  var stream = blobService.createWriteStreamToBlockBlob('test', 'myblob');  

  // Replace the write operation with this one and it will work:
  // stream.write(new Buffer("abcabc"));
  stream.write('abcabc', 'utf-8');

  stream.on('error', function(){
    console.log('failed'); 
  });

  stream.end(function(){
    console.log('passed'); 
  });
    
});
```

I had a quick look to the code, and the problem seem to be in the chunked stream implementation. The `.write` method accept encoding and pass it to a helper function

https://github.com/Azure/azure-storage-node/blob/eb037435e27c79ddd534662efa751a4a7320f606/lib/common/streams/chunkstream.js#L118

but this function does not declare or use the argument at all. I imagine is a problem with other services, not just blob. Ideally the chunkedStream module could be rewritten to define streams like in

https://nodejs.org/api/stream.html#stream_class_stream_writable_1

in such a case, the `decodeString` option (default to true) is the desired one.

Best Regards.

**Comment by yaxia** [comment]
@davazp Thanks for providing the issue details. We are working on a fix and will have it in an upcoming release.

**Comment by yaxia** [comment]
Please get the latest release (0.7.0) for the fix. Thanks.
