### ISSUE TITLE
Can I upload file to blob file not container?

### ISSUE THREAD

**Issue by stefaner1** [Azure/azure-storage-node#661]
### Which service(blob, file, queue, table) does this issue concern?
blob

### Which version of the SDK was used?
Azure Storage JavaScript Client Library 3.0.100

### What's the Node.js/Browser version?
Version 86.0.4240.198 (Official Build) (64-bit)

### What problem was encountered?
After creating SAS_URL in python for blob file 
blob_client.make_blob_url(
          container_name,
          blob_name,
          sas_token=sas_token)

I got this error:
Signature did not match. String to sign used was racwd

I know the example code was writen for container SAS_TOKEN not blob file:
https://dmrelease.blob.core.windows.net/azurestoragejssample/samples/sample-blob.html
but is there way to upload to specifed file name?

### Steps to reproduce the issue?
            ```
            var blobUri = 'https://' + 'something' + '.blob.core.windows.net';
            var blobService = AzureStorage.Blob.createBlobServiceWithSas(blobUri, SAS_TOKEN);

            // If one file has been selected in the HTML file input element
            var file = $('#FileInput').get(0).files[0];

            var customBlockSize = file.size > 1024 * 1024 * 32 ? 1024 * 1024 * 4 : 1024 * 512;
            blobService.singleBlobPutThresholdInBytes = customBlockSize;

            var finishedOrError = false;
            var speedSummary = blobService.createBlockBlobFromBrowserFile('upload_here', file.name, file, { blockSize: customBlockSize }, function (error, result, response) {
                finishedOrError = true;
                if (error) {
                    alert('Error');
                } else {
                    displayProcess(100);
                }
            });
```

**Comment by ljian3377** [comment]
Didn't quite get you. A Blob must be created within an existing Container.
For the sas issue you run into, check that you generated the right sas token. If the blob name may change, you may consider to generate the sas on the container level.

Would you consider switching to our latest Blob SDK? https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage/storage-blob
This repo is going to be depreciated in favor of the new one, which is the focus of us now.
