### ISSUE TITLE
When blob container is not present, calling `blobServiceClient.getContainerClient("xyz")` crashing node app.

### ISSUE THREAD

**Issue by vasRK** [Azure/azure-storage-node#662]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### When blob container is not present, calling, 

`blobServiceClient.getContainerClient("xyz");`

making node app to crash, I have wrapped inside a try catch block also, control never went into catch block.

```
try {
            containerClient = blobServiceClient.getContainerClient("xyz");
        }
        catch (err) {
            _logger.trace('blob client err - ', err)
        }

```

### When blob container is not present, calling `blobServiceClient.getContainerClient("xyz")` crashing node app.

Note: when container is present there is no issue,

**Comment by jiacfan** [comment]
Hi, @vasRK 

Thanks for reaching us!

Would you help to share the containername you're using and the error details? 
At same time, would you help to create a new incident in latest SDK's repro [Azure Storage JavaScript SDK V12](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage) and link this issue, we're tracing v12 items in latest repro, and will follow up this issue agilely.

Thanks,
Jiachen

**Comment by jiacfan** [comment]
<Status update>

Linked incident https://github.com/Azure/azure-sdk-for-js/issues/12642

**Comment by jiacfan** [comment]
Close this issue as duplicated and it's related to v12 SDK.
