### ISSUE TITLE
GH Page site still up there

### ISSUE THREAD

**Issue by jongio** [Azure/azure-storage-node#664]
I googled 'azure nodejs samples' and this GH pages site was in list with no mention of new libs

https://github.com/Azure/azure-storage-node/blob/gh-pages/index.html

https://azure.github.io/azure-storage-node/

@ramya-rao-a

**Comment by ramya-rao-a** [comment]
@XiaoningLiu,  Can we update this page to point to v12 storage packages instead of v10?

On second thoughts, what is the purpose of https://azure.github.io/azure-storage-node/ when we have the npm landing page for the azure-storage package and this repo readme have the same information?

**Comment by jiacfan** [comment]
Thanks for the info @jongio and @ramya-rao-a. We've sent PR for doc update and will update the doc soon.
As discussion with @XiaoningLiu, the plan is to keep existing page for ease of serving v2 SDK users, and later we may consider to
 deprecate it after all existing services in v2(including Table service) get GA in v12 repo.

**Comment by ramya-rao-a** [comment]
Thanks @jiacfan 
We can close this issue
