### ISSUE TITLE
Memory leak in TableService.queryEntities

### ISSUE THREAD

**Issue by mbacon-edocs** [Azure/azure-storage-node#67]
I recently discovered a memory leak in a Node app of ours which I eventually tracked down to being related to the queryEntities method on a TableService instance. After pulling the code out and completely stripping it down the problem still existed, the basic setup I have to reproduce this issue is below:

``` javascript

var AzureSvc = require('azure-storage');

var azure = {
    eventsTable: 'eventtable',
    tableService: AzureSvc.createTableService('{name}','{key}'),
    eventsQuery: (new AzureSvc.TableQuery()).where('Sent eq ?', 'false'),
    eventCheckTimeout: 5000
};
azure.checkEvents = function Azure_CheckEvents() {
    azure.tableService.queryEntities(azure.eventsTable, azure.eventsQuery, null, function(error, result) {
        if(!error)
        {
            setTimeout(Azure_CheckEvents, azure.eventCheckTimeout);
        }
        else
        {
            setTimeout(Azure_CheckEvents, azure.eventCheckTimeout);
        }
    });
};
azure.tableService.createTableIfNotExists(azure.eventsTable, function(error) {
    if(!error)
    {
        setTimeout(azure.checkEvents, azure.eventCheckTimeout);
    }
});
```

**Comment by yaxia** [comment]
@mbacon-edocs Thanks for raising the issue. Could you please provide more information about the version of azure-storage and how do you identify the memory leak? I tried with node-inspector and cannot see the object count or retained size keep growing. Thanks.

**Comment by mbacon-edocs** [comment]
Hi @yaxia, thanks for getting in touch - it was quite a while ago obviously but this issue is present in at least version 0.4.4. Every time the checkEvents function is called the process memory usage in my task manager goes up, if the function is only called once rather than repeatedly, the memory usage is steady and stays level. Hope this clears things up.

**Comment by XiaoningLiu** [comment]
@mbacon-edocs Do you still have the memory leak issue on the latest version library?

**Comment by Pentiado** [comment]
I've been observing memory issues in 2.10.3. I'm running the app in production already so it's quite concerning. 

<img width="1702" alt="Screenshot 2020-01-08 at 14 29 54" src="https://user-images.githubusercontent.com/1911020/71981958-ce9f1e00-3223-11ea-81cf-61fcd27bc252.png">
