### ISSUE TITLE
26 errors while trying to import in default Azure Typescript Function

### ISSUE THREAD

**Issue by defenestrant** [Azure/azure-storage-node#670]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?
NA

### Which version of the SDK was used?
2.10.3

### What's the Node.js/Browser version?
Typescript version 4.1.3

### What problem was encountered?

When trying to import like this: import { createTableService } from "azure-storage"
I get 26 errors while trying to import in default Azure Typescript Function while running the typescript build command tsc
errors here: https://pastebin.com/puTpMBS5

### Steps to reproduce the issue?
see above

### Have you found a mitigation/solution?
no

**Comment by jiacfan** [comment]
Hi, @defenestrant  Thanks for reaching us!

Latest table SDK is maintained in https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/tables/data-tables

Would you have a try? Welcome feedbacks. (Please open issue in https://github.com/Azure/azure-sdk-for-js if you find any problem)

Thanks
