### ISSUE TITLE
Upload a same single blob parallelly into two different containers which resides in two different storage account

### ISSUE THREAD

**Issue by DVGY** [Azure/azure-storage-node#672]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### What's the Node.js/Browser version?
Node JS 12

### What problem was encountered?
I want to upload file parallelly in two containers each of are in different storage account.

Ex: StorageAccount1: container_xyz 
     StorageAccount2: container_abc

### Steps to reproduce the issue?
Here is what my code looks like
 
// index.js

```
module.exports = async function (context, req) {
  const UserID = "";
  let rawDataQuery = "";
  let rawData = "";

  try {
  // Do some task and store data in buffer

 context.bindings.myReportFile = buffer;


  }
 catch(err){
 }
```

// function.json
```
{
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": ["get"],
      "webHookType": "genericJson",
      "route": "reports/{id:guid}"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    },
    {
      "name": "myReportFile",
      "direction": "out",
      "type": "blob",
      "path": "reports/{reportInitialNameFormat}_{reportID}.{reportExt}",
      "connection": "XYZ_STORAGE"
    },
   
  ]
}
```

The above code uploads my file directly to reports container which resides at storage account (Location/Region 1)

If I add a line after the `context.bindings.myReportFile = buffer;` , i.e
`context.bindings.myReportFileSecond = buffer;`  **and**  add following json in `function.json`

```
{
      "name": "myReportFileSecond ",
      "direction": "out",
      "type": "blob",
      "path": "reports/{reportInitialNameFormat}_{reportID}.{reportExt}",
      "connection": "ABC_STORAGE"
    }
```
Will it upload the both blob file parallelly ? or It will upload sequentially.? 
I am interested to in knowing how to upload a same blob parallelly into two different container, each container resides in two different storage account.

**Comment by EmmaZhu** [comment]
Hi @DVGY,

Apologize for the late response. We are deprecating this repository, may not pay enough attention on it.

Your question should not be a storage issue, azure-functions-host should know more about it. Functions host  repository is here: https://github.com/Azure/azure-functions-host 

Thanks
Emma
