### ISSUE TITLE
Package "underscore" ~1.8.3 Has a Security Vulnerability

### ISSUE THREAD

**Issue by guy-microsoft** [Azure/azure-storage-node#676]
Should be updated to 1.12.1 to resolve it.
https://snyk.io/vuln/npm:underscore

**Comment by mhassan1** [comment]
This would be resolved by https://github.com/Azure/azure-storage-node/pull/677

**Comment by goelankit** [comment]
Can someone please publish the updated azure-storage package as well. 

We are dependent on the azure-storage package and are getting component governance alert for the same.

**Comment by GuillermoBlanco** [comment]
#677 Version update has been merged and it's ready to release.

Wondering if there's a programmed release cadence, or any urgency to release security patches.

**Comment by phawxby** [comment]
Table Storage is feeling more and more like a dead product. The only lib that supports it hasn't been updated in 2 years :-/

**Comment by EmmaZhu** [comment]
A new version 2.10.4 has been published with upgrading to underscore 1.12.1, which should be able to fix this issue.

Thanks
Emma
