### ISSUE TITLE
Blob copy between different storage accounts no success callback received

### ISSUE THREAD

**Issue by amit12cool** [Azure/azure-storage-node#678]
Hi,

I'm trying to copy blob from storage account A to storage account B. 
I'm using this method to accomplish above functionality:-

```https://docs.microsoft.com/en-us/javascript/api/azure-storage/azurestorage.services.blob.blobservice.blobservice?view=azure-node-legacy#startCopyBlob_string__string__string__CopyBlobRequestOptions__ErrorOrResult_BlobResult__```

But the above method just accepts the request and there is no callback for success or failure when blob is copied or not.

Is there anything I'm missing?

### What's the Node.js/Browser version?
Latest 

### What problem was encountered?
Blob copy callback not received for success or failure

### Steps to reproduce the issue?
Copy blob from storage account A to B using startCopyBlob method of azure nodejs sdk

### Have you found a mitigation/solution?
No

**Comment by EmmaZhu** [comment]
@amit12cool 

The startCopyBlob method is used to send a request to start the copy in storage service, the actual content copy can take some according to the source and destination blob/file location and the blob size. 

You can call following method to query the copy status/progress:
`https://docs.microsoft.com/en-us/javascript/api/azure-storage/azurestorage.services.blob.blobservice.blobservice?view=azure-node-legacy#getBlobProperties_string__string__BlobRequestOptions__ErrorOrResult_BlobResult__`

The detailed copy status can be found in BlobResult.copy properties, copy has following members:
`  'copyId': 'copy.id',
  'copyStatus': 'copy.status', // This is to show whether copy is still pending or completed.
  'copySource': 'copy.source',
  'copyProgress': 'copy.progress', // With this you can get how many bytes has been copied.
  'copyCompletionTime': 'copy.completionTime',
  'copyStatusDescription': 'copy.statusDescription',
  'copyDestinationSnapshot': 'copy.destinationSnapshot',`

Thanks
Emma

**Comment by amit12cool** [comment]
Ok..Thanks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by JuneQuev** [comment]
Any update on when this will be fixed?  npm audit is reporting it as an issue

=== npm audit security report ===                        
37                                                                                
38                                                                                
39                                 Manual Review                                  
40             Some vulnerabilities require your attention to resolve             
41                                                                                
42          Visit https://go.npm.me/audit-guide for additional guidance           
43                                                                                
44                                                                                
45  High            Arbitrary Code Execution                                      
46                                                                                
47  Package         underscore                                                    
48                                                                                
49  Patched in      >=1.12.1                                                      
50                                                                                
51  Dependency of   azure-storage                                                 
52                                                                                
53  Path            azure-storage > underscore                                    
54                                                                                
55  More info       https://npmjs.com/advisories/1674                             
56                                                                                
57found 1 high severity vulnerability in 600 scanned packages
58  1 vulnerability requires manual review. See the full report for details.
59>>>> npm audit --json --registry https://registry.npmjs.org

**Comment by EmmaZhu** [comment]
@JuneQuev 

We just release a new version: 2.10.4 which upgraded to a newer version underscore. Could you like to have a try?
