### ISSUE TITLE
Error when using the file service

### ISSUE THREAD

**Issue by ulrikaugustsson** [Azure/azure-storage-node#68]
Getting this error when I try to use the `var fileService = azure.createFileService();` to create shares and directories.
```js
{ [Error: getaddrinfo ENOTFOUND contoso.file.core.windows.net contoso.file.core.windows.net:443]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'contoso.file.core.windows.net',
  host: 'contoso.file.core.windows.net',
  port: '443' }
```
Obviously I use my storage account and not `contoso`.

When checking on azure I can't see any url for file.core.windows.net only blob, table and queue, I feel like that is the actual problem.

**Comment by yaxia** [comment]
@ulrikaugustsson, if you don't provide a connection string or account name + key when you create the service client, it will read from the environment variables. Could you please check whether you have AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_ACCESS_KEY environment variables or the AZURE_STORAGE_CONNECTION_STRING environment variable?

**Comment by ulrikaugustsson** [comment]
I havet those set as environment variabels. I think it is saying that there is no endpoint for files.

**Comment by ulrikaugustsson** [comment]
Maybe I should just use blob storage..

**Comment by yaxia** [comment]
Would you please check whether your subscription has the file preview enabled? If yes, is your account created before the file service is enabled?

**Comment by ulrikaugustsson** [comment]
@yaxia Sorry for the late response, I can't see anything about file preview on my account so I guess that is the problem. I went with blob storage instead and it works great.
