### ISSUE TITLE
Underscore vulnerability

### ISSUE THREAD

**Issue by skhilliard** [Azure/azure-storage-node#683]
We are currently using the latest version (2.10.3) of the azure-storage library (https://www.npmjs.com/package/azure-storage).   There is now an underscore vulnerability (via the paths azure-storage > underscore) that needs to be addressed (https://npmjs.com/advisories/1674).

Are there any plans to update this library to patch this?

Thanks,
Kelly

**Comment by lucioperca** [comment]
Looks like a PR was merged to fix this, but the change is waiting on a release: https://github.com/Azure/azure-storage-node/pull/677

**Comment by chauri09** [comment]
@lucioperca when can we expect #677 release? 

Is there any alternative for azure-storage v2 (for azure table storage) as this is marked as legacy?

**Comment by mikeshimkus** [comment]
Also waiting on this for azure-storage.

**Comment by lucioperca** [comment]
@chauri09 According to the PR, it was estimated "in the next two weeks" about four days ago.

I'm not personally involved in this package's development and maintenance. I was just sharing what I'd found poking around this repo after I encountered the same advisory.

**Comment by goelankit** [comment]
Is there a way to find out any particular team in Microsoft who owns this package, to get some traction.

**Comment by skhilliard** [comment]
It looks like there may be another vulnerability too with its browserify-mime dependency....

https://ossindex.sonatype.org/component/pkg:npm/browserify-mime@1.2.9?utm_source=dependency-check&utm_medium=integration&utm_content=6.1.6

**Comment by Rich-MSR** [comment]
azure-storage 2.10.4 was just published, and it resolves the underscore vulnerability.

**Comment by Rich-MSR** [comment]
@skhilliard I'm not aware of any such plans, but maybe @HarshaNalluru is since he made the fix for azure-storage.

**Comment by ramya-rao-a** [comment]
We will be using https://github.com/Azure/azure-sdk-for-node/issues/5208 to track the need to update the dependency in azure-sb
