### ISSUE TITLE
Losing internet connection leaves non-called callback upon blob download

### ISSUE THREAD

**Issue by sedouard** [Azure/azure-storage-node#69]
Try downloading a sizable blob (tested on a blob of size 137.9mb).

```js
blobService.getBlobToStream(model.get('container_id'), model.get('name'), stream, options,  function (err) { 
  console.log('I am never called with: ' + err);
});
```

During the download, cut your internet connection. We expect the callback to be called with `err`. Actual: its never called back.

**Comment by yaxia** [comment]
@sedouard  Thanks for reporting the issue. We've confirmed this is a bug in the library. We will have the fix in an upcoming release.

**Comment by sedouard** [comment]
Thanks for taking a look!

**Comment by billbuckley** [comment]
We've hit this issue in our testing as well, so just another vote to keep this issue high on the priority list.

**Comment by yaxia** [comment]
Please get the latest release (0.7.0) for the fix. Thanks.
