### ISSUE TITLE
Could you help remove the vulnerabilities introduced in azure-storage ?

### ISSUE THREAD

**Issue by vincentsum777** [Azure/azure-storage-node#691]
Hi, @XiaoningLiu @jiacfan,
### Issue Description

   I noticed that four vulnerabilities are introduced in **_azure-storage@2.10.4_**:
   Four ulnerabilities affect package **_validator_** (versions:<13.6.0):  [**SNYK-JS-VALIDATOR-1090600**](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090600),  [**SNYK-JS-VALIDATOR-1090599**](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090599), [**SNYK-JS-VALIDATOR-1090602**](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090602) and [**SNYK-JS-VALIDATOR-1090601**](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090601)
  The above vulnerable package is referenced by **_azure-storage@2.10.4_** via:
`azure-storage@2.10.4 ➔ validator@9.4.1`

Since **_azure-storage@2.10.4_** ([61,618 downloads per week](https://www.npmjs.com/package/azure-storage/v/2.10.4?activeTab=versions)) is referenced by **1,320** downstream projects (e.g., [@microsoft/sp-build-core-tasks 1.12.1](https://www.npmjs.com/package/@microsoft/sp-build-core-tasks) (latest version), [@microsoft/sp-build-web 1.12.1](https://www.npmjs.com/package/@microsoft/sp-build-web) (latest version), [@cinerino/domain 10.16.0](https://www.npmjs.com/package/@cinerino/domain) (latest version), [@microsoft/generator-sharepoint 1.12.1](https://www.npmjs.com/package/@microsoft/generator-sharepoint) (latest version)), the vulnerabilities can be propagated into these downstream projects and expose security threats to them via the following package dependency paths:
(1)`@0cfg/rpc-common@0.0.9 ➔ @0cfg/stubs-common@0.0.6 ➔ azure-storage@2.10.4 ➔ validator@9.4.1`
(2)`@onboardmobility/whatsapp@6.0.0 ➔ @onboardmobility/azure@6.0.0 ➔ azure-storage@2.10.4 ➔ validator@9.4.1`
(3)`@pagopa/io-functions-commons@20.6.6 ➔ azure-storage@2.10.4 ➔ validator@9.4.1`
  **......**

If **_azure-storage_** removes the vulnerable package from the above version, then its fixed version can help downstream users decrease their pain.

**Given the large number of downstream users, could you help update your package to remove the vulnerability from azure-storage@2.10.\* ?**

### Fixing suggestions

In **_azure-storage@2.10.5_**, you can kindly perform the following upgrade :
`validator ~9.4.1 ➔ ~13.6.0`; 

**Note:**
_validator@13.6.0(>=13.6.0) has fixed the vulnerabilities ([**SNYK-JS-VALIDATOR-1090600**](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090600),  [**SNYK-JS-VALIDATOR-1090599**](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090599), [**SNYK-JS-VALIDATOR-1090602**](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090602) and [**SNYK-JS-VALIDATOR-1090601**](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090601))_
Of course, you are welcome to share other ways to deal with the issue.

Thank you for your attention to this issue.^_^

**Comment by vincentsum777** [comment]
@XiaoningLiu @EmmaZhu Thanks again.

**Comment by EmmaZhu** [comment]
Hi @vincentsum777 ,

Thanks for reminding us about the issue. 

We'll look into it and make plan for the fixing.

Thanks
Emma

**Comment by codestellar** [comment]
@vincentsum777 
I was facing the same issue, however, I added the latest version of validator i.e. **13.6.0** in my package.json explicitly and ensured that package.lock.json is updated and that fixed the issue for me.

However, there is another package that is request 2.88.2 which this library is using the latest otherwise. The request package is deprecated and SYNK reports Insecure Encryption in that https://snyk.io/vuln/SNYK-JS-REQUEST-1314897

**Comment by abea** [comment]
Is there any update on this? It is now throwing an npm audit warning.

**Comment by abea** [comment]
Nevermind, that's a new one. https://github.com/advisories/GHSA-qgmg-gppg-76g5

**Comment by EmmaZhu** [comment]
We have released a new version 2.10.5 to upgrade validator to 13.6.0.

Thanks
Emma

**Comment by abea** [comment]
Thanks!

**Comment by EmmaZhu** [comment]
We have released a new version 2.10.6 to upgrade validator to 13.7.0 to address this issue.

Thanks
Emma
