### ISSUE TITLE
Is there a migration documentation to the azure-sdk-for-js lib?

### ISSUE THREAD

**Issue by romayalon** [Azure/azure-storage-node#693]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?
Blob

### What problem was encountered?
I could not find documentation that describes migration to the suggested lib for js.

**Comment by EmmaZhu** [comment]
You can find migration guide here: 

For blob service: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/storage/storage-blob/MigrationGuide.md
For file service: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/storage/storage-file-share/MigrationGuide.md
For queue service: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/storage/storage-queue/MigrationGuide.md

Thanks
Emma

**Comment by romayalon** [comment]
@EmmaZhu Thank you, we already migrated but I'll take a look to check that we are compatible with the provided doc.
