### ISSUE TITLE
Concurrent operations

### ISSUE THREAD

**Issue by chafey** [Azure/azure-storage-node#70]
I noticed that this library is setting http.globalAgent.maxSockets to 1 which happens via BatchOperation.setConcurrency() which is set based on  Defaults.DEFAULT_PARALLEL_OPERATION_THREAD_COUNT which equals 1

A few comments:
1) I understand this will limit the number of concurrent blob requests to 1.  This seems like a very low limit for the default - what is the rationale for such a low default limit?
2) If a default limit is required, the library should create its own http.Agent instead of setting this in the globalAgent as that will impact other http requests the application will make!  This behavior impacted our application and was completely unexpected - I consider this a major bug.

**Comment by yaxia** [comment]
@chafey Thanks for raising the issue. We are working on the fix and will have it in an upcoming release.

**Comment by yaxia** [comment]
Please get the latest release (0.7.0) for the fix. Thanks.
