### ISSUE TITLE
Vulnerability - JSONSCHEMA-1920922 

### ISSUE THREAD

**Issue by naveentej** [Azure/azure-storage-node#701]
azure-storage@2.10.5 => request@2.88.2 => http-signature@1.2.0 => jsprim@1.4.1 => json-schema@0.2.3
**request is now deprecated** and http-signature has an update that addresses this vulnerability (fixed by json schema @0.4.0)
https://security.snyk.io/vuln/SNYK-JS-JSONSCHEMA-1920922

**Comment by EmmaZhu** [comment]
@naveentej ,

We leverages 'request' packages to performing REST request and we are deprecating `azure-storage` package, so we cannot make such basic change to move to other dependencies for REST request. 

We can upgrade `json-schema`

Thanks
Emma

**Comment by naveentej** [comment]
Thanks for the update @EmmaZhu 
When can we expect the mitigated package update?

**Comment by EmmaZhu** [comment]
@naveentej ,
We just published azure-storage@2.10.6 which upgrades to json-schema@0.4.0. 

Thanks
Emma
