### ISSUE TITLE
Crashes node JS application on DNS failure

### ISSUE THREAD

**Issue by Rajendiran1905** [Azure/azure-storage-node#704]
> For latest features support, please switch to [Azure Storage JavaScript SDK V10](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage). 

### Which service(blob, file, queue, table) does this issue concern?
blob service

### Which version of the SDK was used?
2.10.5

### What's the Node.js/Browser version?
Node JS 14.15.1

### What problem was encountered?
Application crash. (Node exited with code 1).

### Steps to reproduce the issue?
failure on DNS lookup

### Have you found a mitigation/solution?
No

**Comment by EmmaZhu** [comment]
Hi @Rajendiran1905 , 

Could you share the code when you met the error and detailed error message?

BTW, we are deprecating this package, will only fix security bugs. 

We'd suggest to upgrade to "azure/storage-*" packages. You can find migration guide here: 

> For blob service: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/storage/storage-blob/MigrationGuide.md
> For file service: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/storage/storage-file-share/MigrationGuide.md
> For queue service: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/storage/storage-queue/MigrationGuide.md 

Thanks
Emma

**Comment by EmmaZhu** [comment]
@Rajendiran1905 ,

We are deprecating this package.  Please upgrade to "azure/storage-*" packages. Any issue found, please open an issue on repository:  https://github.com/Azure/azure-sdk-for-js
