### ISSUE TITLE
Can't see tables in my storage account in new portal.

### ISSUE THREAD

**Issue by garimakhulbe** [Azure/azure-storage-node#77]
My problem is, I am using below code to create table in the storage account:

var azure = require('azure-storage');
var tableSvc = azure.createTableService(accountname, key);
tableSvc.createTableIfNotExists('mytable1', function (error, result, response) {
    if (!error) {
        console.log(result);
    }
});
It is working as expected .i.e. in first run, it creates a new table with name 'mytable1' and returns result as 'true', and when I execute the same again, it returns false as table already exists. But the issue is I can't see the tables in my storage account in the new portal, it showing zero table. Do I need to enter entities then only I could see the table? My storage is in resource group which is in a subscription which is under tenantId and has a service principal. Is it related to role access? I have contributor role set in the service principal.
In ARM, we use service principal clientID and password to generate token for the API calls. How does it happen in storage? In my project, I am using an ARM template to deploy VMs and storage accounts in a resource group. My service will run inside the VM which will read entities from the table storage in continuous internal. Some posts mentioned about creating a sharedKey and signature and some used the access_key. Do I need both for table or blob operations? Do I need to set roles before doing storage operations? Do I need anything from service principal to access the storage? I guess no. Also, Storage API did not change to v2 like classicCompute changed to Compute. Right? 
Just learnt about SP, ADAL and token for ARM calls and thought now I know about authentication/authorization in Azure and started working on storage and Facepalm! Storage has different story to tell. Its not bad and but confusing :). Note: New user.

**Comment by yaxia** [comment]
@garimakhulbe Thanks for inquiry. In general, we don't have any constrain to show your storage table in the new portal when the table is created. I cannot reproduce the issue at my side. Would you please check the subscription Id and the storage account are correct and refresh the portal?

**Comment by garimakhulbe** [comment]
Its resolved now. Thanks for the reply.
