### ISSUE TITLE
Blobstorage v0.5.0 maybe leaks TLS sockets and fd's on node v0.12.7

### ISSUE THREAD

**Issue by ashelley** [Azure/azure-storage-node#79]
Hello I am investigating an issue where this module causes node to hang indefinitely and not be able to be killed forcing the computer to reboot.  

Also sometimes the network sockets are never released and you are unable to rebind to the same network port (sometimes reproducible).

Here is the source code for the test case:

```
var config = require('./config.json');
var express = require('express');
var app = express();
process.env.AZURE_STORAGE_CONNECTION_STRING = config.AZURE_STORAGE_CONNECTION_STRING;
var azure = require('azure-storage');
var blobService = azure.createBlobService();
app.get('/upload', function (req, res) {
    blobService.createBlockBlobFromLocalFile('adam-static', 'test/smiley.png', './smiley.png', function (error, result, response) {
        res.send(JSON.stringify({
            date: new Date(),
            error: error,
            result: result,
            response: response
        }, null, 2));
    });
});
app.get('/hello', function (req, res) {
    res.send('hello');
});
app.listen(process.env.PORT || 3001, function () {
    console.log('listenning');
});
```

To reproduce this issue start the server using node v0.12.7

![image](https://cloud.githubusercontent.com/assets/3195045/9414967/f981dbfc-47f0-11e5-8c1b-5e5eda55a4bd.png)

Check the pid of the server and make sure the server is running.  

```
Adam@DEVELOPER-03 MINGW64 ~
$ tasklist | grep node
node.exe                      1240 Console                    1     46,188 K
Adam@DEVELOPER-03 MINGW64 ~
$ curl http://localhost:3002/hello
hello
```

Make a network request to the upload endpoint:

```
$ curl http://localhost:3002/upload
{
  "date": "2015-08-21T17:32:17.435Z",
  "error": null,
  "result": "test/smiley.png",
  "response": {
    "isSuccessful": true,
    "statusCode": 201,
    "body": "",
    "headers": {
      "transfer-encoding": "chunked",
      "content-md5": "NvKvHi6FtAOiR/UseOrOjQ==",
      "last-modified": "Fri, 21 Aug 2015 17:32:17 GMT",
      "etag": "\"0x8D2AA4E75B30D30\"",
      "server": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "eac634d2-0001-00cf-7237-dca17f000000",
      "x-ms-version": "2015-02-21",
      "date": "Fri, 21 Aug 2015 17:32:15 GMT",
      "connection": "close"
    }
  }
}
```

Try to kill the server in the command prompt by pressing ctrl+c, it won't exit.  Try making a network request to show that the process is not longer listenning but is still running:

```
Adam@DEVELOPER-03 MINGW64 ~
$ curl http://localhost:3002/hello
curl: (7) Failed to connect to localhost port 3002: Connection refused

Adam@DEVELOPER-03 MINGW64 ~
$ tasklist | grep node
node.exe                      1240 Console                    1    116,848 K
```

```
C:\WINDOWS\system32>taskkill /F /im node*
ERROR: The process "node.exe" with PID 1240 could not be terminated.
Reason: There is no running instance of the task.
```

Try to kill the process with process hacker:

![image](https://cloud.githubusercontent.com/assets/3195045/9415113/e5d3b9c6-47f1-11e5-8e0d-01af4945627f.png)

Right now the only way I can get rid of my process is to reboot my computer.

Using io.js v3.1.0 the results of the crashing process is the same but also the callback for the module is never called.

This issue may also be related:

https://github.com/Azure/azure-storage-node/issues/51

I am using Windows 10.  However, before I updated I believe windows 8 was having similar issues but I didn't realize the problem until after I updated so I cannot reproduce right now.

Any insight is appreciated.

**Comment by ashelley** [comment]
Hello I have just tested kubuntu v14.04 and the code doesn't have the same problem. 

However with io.js v3.1.0 this module does not call the callback same as in windows (does not work).

**Comment by ashelley** [comment]
Node version: v0.12.7

- azure-storage@0.5.0 crashes on exit after upload

- azure-storage@0.4.5 works

I'll try to git bisect this

**Comment by ashelley** [comment]
It looks like the module is leaking TLS Sockets

![image](https://cloud.githubusercontent.com/assets/3195045/9418022/cee20222-4805-11e5-820a-811fd9e7982c.png)

**Comment by ashelley** [comment]
Okay so these are my findings so far:

azure-storage 0.4.5 works on node v0.12.7 and greater (doesn't crash node on exit and doesn't leak TLS sockets

azure-storage 0.5.0 only works on node v0.10.40 or less (doesn't crash on exit and doesn't leak TLS sockets)

**Comment by ashelley** [comment]
Okay, I shutdown my virus scanner (Kaspsersky) and all my node processes shut down!

Sorta feel stupid now.  I still think there is an issue with leaking sockets as mentioned above but I can no longer crash node on exit with the virus scanner not running :(

**Comment by ashelley** [comment]
I've updated my test case to further show that there is an issue with 0.5.0 leaking resources. 

The module also maintains references to fd's (I think) so that files are never closed until the process dies.  Here is an example test case:

```
var express = require('express'),
    os = require('os'),
    path = require('path'),
    fs = require('fs'),
    app = express(),
    azure = require('azure-storage'),
    blobService = azure.createBlobService();

app.get('/upload', function(req, res) {
    var time = (new Date()).getTime();
    //var filename = 'hellotempfile-' + time + '.txt';
    var filename = 'hellotempfile.txt';
    var tempfilepath = path.resolve(os.tmpdir(), filename);
    fs.writeFileSync(tempfilepath, 'hello tempfile' + time);
    blobService.createBlockBlobFromLocalFile('existing-container', filename, tempfilepath, function(error, result, response) {
        res.send(JSON.stringify({
            date: new Date(),
            error: error,
            result: result,
            response: response
        }, null, 2));
        fs.unlink(tempfilepath, function(err) {
            if (err) {
                console.log('Error deleting', tempfilepath, err);
            } else {
                console.log(tempfilepath, 'deleted');
            }
        });
    });
});
app.listen(process.env.PORT || 3001, function() {
    console.log('listenning');
});
```

Steps to reproduce:

1) make sure you have AZURE_STORAGE_CONNECTION_STRING in your environment and a container called 'existing-container' setup in your storage account.

2) start the program 

3) make a single request to the server to /upload

```
$ curl http://localhost:5000/upload
{
  "date": "2015-08-25T17:06:36.560Z",
  "error": null,
  "result": "hellotempfile.txt",
  "response": {
    "isSuccessful": true,
    "statusCode": 201,
    "body": "",
    "headers": {
      "transfer-encoding": "chunked",
      "content-md5": "2C2TOdH2bgn0jFwYsPDe6g==",
      "last-modified": "Tue, 25 Aug 2015 17:06:34 GMT",
      "etag": "\"0x8D2AD6F8808AB9A\"",
      "server": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0",
      "x-ms-request-id": "8f7d9710-0001-005c-7c58-df3734000000",
      "x-ms-version": "2015-02-21",
      "date": "Tue, 25 Aug 2015 17:06:33 GMT",
      "connection": "close"
    }
  }
}
```

You will notice in the console of the running server that the file is successfully deleted:
```
C:\Users\Adam\AppData\Local\Temp\hellotempfile.txt deleted
```

4) Observe the fact that the file is still open by the process and locked still.

![image](https://cloud.githubusercontent.com/assets/3195045/9473757/69ea09c8-4b11-11e5-95f5-a926cd9c0bdf.png)

```
C:\Users\Adam\AppData\Local\Temp>dir hellotempfile.txt
 Volume in drive C has no label.
 Volume Serial Number is 5E05-BBDC

 Directory of C:\Users\Adam\AppData\Local\Temp

08/25/2015  10:06 AM                27 hellotempfile.txt
               1 File(s)             27 bytes
               0 Dir(s)  405,986,099,200 bytes free

C:\Users\Adam\AppData\Local\Temp>type hellotempfile.txt
Access is denied.

C:\Users\Adam\AppData\Local\Temp>dir hellotempfile.txt
 Volume in drive C has no label.
 Volume Serial Number is 5E05-BBDC

 Directory of C:\Users\Adam\AppData\Local\Temp

08/25/2015  10:06 AM                27 hellotempfile.txt
               1 File(s)             27 bytes
               0 Dir(s)  405,986,095,104 bytes free

C:\Users\Adam\AppData\Local\Temp>
```

5) Stop the server from running and show that the temp file is released:

```
C:\Users\Adam\AppData\Local\Temp>dir hellotempfile.txt
 Volume in drive C has no label.
 Volume Serial Number is 5E05-BBDC

 Directory of C:\Users\Adam\AppData\Local\Temp

File Not Found

C:\Users\Adam\AppData\Local\Temp>
```

6) Restart the server to begin a second test, make two requests to the upload endpoint.  The second request will crash the server  because the fd remains locked (leaked) by the azure-storage module:

```
C:\Users\Adam\AppData\Local\Temp\hellotempfile.txt deleted
Error: EPERM, operation not permitted 'C:\Users\Adam\AppData\Local\Temp\hellotempfile.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at C:\inetpub\wwwroot\azure-storage-crash-test\new.js:14:8
    at Layer.handle [as handle_request] (C:\inetpub\wwwroot\azure-storage-crash-test\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\inetpub\wwwroot\azure-storage-crash-test\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\inetpub\wwwroot\azure-storage-crash-test\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\inetpub\wwwroot\azure-storage-crash-test\node_modules\express\lib\router\layer.js:95:5)
    at C:\inetpub\wwwroot\azure-storage-crash-test\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\inetpub\wwwroot\azure-storage-crash-test\node_modules\express\lib\router\index.js:330:12)
```

Tested using node Version 0.12.7. 

Note: When running on linux this code will not throw.  However I've tested on Windows 10 and Azure Websites and it crashes.  Here is the same crash results from running on an azure website:
```
listenning
D:\local\Temp\hellotempfile.txt deleted
Error: EPERM, operation not permitted 'D:\local\Temp\hellotempfile.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at D:\home\site\wwwroot\app.js:14:8
    at Layer.handle [as handle_request] (D:\home\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\home\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (D:\home\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\home\node_modules\express\lib\router\layer.js:95:5)
    at D:\home\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (D:\home\node_modules\express\lib\router\index.js:330:12)
```

In otherwords, linux and windows have problems leaking resources but windows will crash because of file system locks on the leaked resources.

**Comment by yaxia** [comment]
@ashelley Thanks for the details. We will look into it.

**Comment by mulyoved** [comment]
Any updates on this? any workarounds?

**Comment by ashelley** [comment]
@mulyoved I ended up using the REST api and rolling my own module to work around the issue.

**Comment by yaxia** [comment]
Please get the latest release (0.7.0) for the fix. Thanks.
