### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by stev-0** [Azure/azure-storage-node#81]
The docs could do with a bit of an update. 

I discovered that [this page](https://azure.microsoft.com/en-gb/documentation/articles/storage-nodejs-how-to-use-blob-storage/) (which looks rather official) is out of date as the `getBlobToFile` has been renamed `getBlobToLocalFile` but this doesn't seem to have been documented anywhere. 

Happy to submit a patch - where is the best place?

**Comment by gangsir** [comment]
Thanks for reporting this. I have created a doc update request to fix this. It should be online soon.

**Comment by yaxia** [comment]
The page has been updated.
