### ISSUE TITLE
BadRequest

### ISSUE THREAD

**Issue by mauricionr** [Azure/azure-storage-node#82]
I'm trying to use the file service, but only badrequest.

![image](https://cloud.githubusercontent.com/assets/2263551/9673406/4cdcb5fe-527a-11e5-965d-d5903b92a74e.png)

Thanks

**Comment by yaxia** [comment]
Azure Storage File service is in preview, would you please check at the management portal whether your storage account has the File service enabled?

**Comment by austindavies** [comment]
@yaxia You get the same error when using the blob service too.

**Comment by gangsir** [comment]
File Service is in GA now. All storage accounts including the existing ones are provisioned with file endpoints. Please retry.

**Comment by mauricionr** [comment]
Thanks!

now it works!
