### ISSUE TITLE
Can't Publish to Azure - Module Copy Error

### ISSUE THREAD

**Issue by krusk** [Azure/azure-storage-node#83]
Hi all,

I am attempting to publish my node.js site with Azure Storage via Visual Studio to my Azure Website but it is throwing the error:

>Copying file .\node_modules\azure-storage\node_modules\request\node_modules\form-data\node_modules\combined-stream\node_modules\delayed-stream\test\integration\test-delayed-http-upload.js to obj\Release\Package\PackageTmp\.\node_modules\azure-storage\node_modules\request\node_modules\form-data\node_modules\combined-stream\node_modules\delayed-stream\test\integration\test-delayed-http-upload.js failed. The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

How can I fix this? 

Thanks,

K.

**Comment by caleteeter** [comment]
Possible options here.  http://stackoverflow.com/questions/13318364/how-to-deploy-node-js-application-with-deep-node-modules-structure-on-windows

**Comment by yaxia** [comment]
The topic on npm is https://github.com/npm/npm/issues/3697. Quoted the recommendation for a quick option:
npm@3 makes the install "maximally flat" by hoisting everything it can to the top level node_modules. This means nesting only occurs on conflicts and as such, trees should never get very deep. As such, the windows path length limitation shouldn't be run into.
