### ISSUE TITLE
TableService: Expose rawEntityProperties.Timestamp or Change Edm.DateTime serialization to support microseconds

### ISSUE THREAD

**Issue by maxwellb** [Azure/azure-storage-node#90]
Suppose an entity's record in a Table contains a Timestamp of "2015-10-02T20:43:11.0834316Z". There is no reliable way to query the least significant time components of the value.

`Date()` has only fidelity to milliseconds, and would reserialize as "2015-10-02T20:43:11.0830000Z". As a workaround, one can currently inspect `entity[".metadata"].etag`, but as noted in the [Remarks section](https://msdn.microsoft.com/library/azure/dd179427#Anchor_3) of the Table Service Rest API Operations documentation,

> The ETag value is opaque and should not be read or relied upon.

Possible resolutions:
1. Store the `entity[entityPropertyName][Constants.TableConstants.ODATA_VALUE_MARKER]` as the full ISO-format date string.
   This would be undoubtedly a breaking change for anyone relying on the type of the value. Even `azure-storage-node` implements type checking during serialization as `_.isDate` which checks `Object.prototype.toString.call(value) == '[object Date]'`, so anyone looking for similar would break if this were to be a string or object.
   Mitigation: maybe just do this for `'Timestamp'`, and not affect other fields with type `Edm.DateTime`.
2. Add a property to `entity` similar to `'.metadata'` which allows access to values from `rawEntityProperties` (properly `Buffer`ed and stringified where appropriate).
   This would only break anyone who has written code against esoteric column names. As according to the [Table Service Data Model](https://msdn.microsoft.com/library/azure/dd179338.aspx) dashes (-) are not allowed for property names, something like `"-RawProperties" or`"-Timestamp"` might suffice. Or, it might be safe to assume property names are following the guideline to adhere to C# identifiers, and thus leading with a dot (.) would be safe.

**Comment by maxwellb** [comment]
If, however, it is safe to assume that the ETag value can be relied upon, and the format is "locked in", then the workaround should be sufficient.

**Comment by yaxia** [comment]
Although it is an aged issue, I'd like to clarify.

The ETag can be used for concurrency scenarios, which means users can rely on it in the condition header to make sure there is no change between last fetch and current update, i.e. If the ETag has no change, it indicates there is no update on the entity.

If the entity need be used after a period of time, the timestamp can be used, as the precision to milliseconds is sufficient.

In other cases, if more precision of timestamp is required, a workaround is to  add a customer property in string format storing the full information such as "2015-10-02T20:43:11.0834316Z".
