### ISSUE TITLE
Use createBlockBlobFromLocalFile many times and get error: "Error: EMFILE, too many open files"

### ISSUE THREAD

**Issue by daxianji007** [Azure/azure-storage-node#91]
Hello everyone,

I used this lib to write a tool for uploading a whole directory to an azure storage.To be detailed, I call **createBlockBlobFromLocalFile()** for every file in the directory.

However, I will got error "Error: EMFILE, too many open files" after uploading 2000 files. Firstly I thought I call it with too much concurrency, but when I changed my logic to upload file **one by one**, it still happened. It seems that the code opened an file and did not close it.

Finally I looked into the code, and changed the code(in lib/services/blib/blobservice.js, line 3897) from
```javascript
      var stream = new FileReadStream(localFileName, { calcContentMd5: options.storeBlobContentMD5 });
      self._uploadBlobFromStream(true, container, blob, blobType, stream, size, options, callback);
```
to
```javascript
      var stream = new FileReadStream(localFileName, { calcContentMd5: options.storeBlobContentMD5 });
      self._uploadBlobFromStream(true, container, blob, blobType, stream, size, options, function(){
		  stream.finish();
		  callback();
	  });
```

And this worked for me at last. Now I want to know if I use the lib in the wrong way? Or it is really an issue of this lib? Or maybe someone can provide a better solution?

Thanks!

**Comment by yaxia** [comment]
Thanks for reporting the issue. It is an issue in the library. We have been aware it and the fix will be in the coming release.

**Comment by yaxia** [comment]
Please get the latest release (0.7.0) for the fix. Thanks.
