### ISSUE TITLE
Request: BlobService Abort Method

### ISSUE THREAD

**Issue by jgainfort** [Azure/azure-storage-node#92]
I think it would be great to have a way to cancel a upload/download request. Something similar to s3's MangedUpload.abort()

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html

**Comment by yaxia** [comment]
@jgainfort  Could you please describe a bit more about your scenario? Do you need to just cancel the requests or also want to free up the previous uploaded blocks? Thanks.

**Comment by jgainfort** [comment]
Lets say I have a multi tasked workflow, and for someone reason a high priority task fails and I want to abort previous or current tasks because of it. If a previous or current task is an upload/download that hasn't finished I would like to abort the process to free up bandwidth and storage.

**Comment by XiaoningLiu** [comment]
Here is a workaround based on filter https://github.com/Azure/azure-storage-node/issues/317
