### ISSUE TITLE
Expose edmHandle to external user

### ISSUE THREAD

**Issue by lijunle** [Azure/azure-storage-node#93]
The helper functions in [edmhandler.js](https://github.com/Azure/azure-storage-node/blob/fade01a1889e2b7899b17375fea985753c578a44/lib/services/table/internal/edmhandler.js) is quite useful. Why not expose them?

Currently, I am using `require('azure-storage/lib/services/table/internal/edmhandler')` as a hack.

**Comment by hasonmsft** [comment]
@lijunle , currently we are not planning to expose them. But you can reference our implementation for your problems. Close it for now.

**Comment by lijunle** [comment]
Got it, thanks!
