### ISSUE TITLE
listTablesSegmentedWithPrefix with maxResult Option Throws Exception @ Line 273

### ISSUE THREAD

**Issue by JakeRad** [Azure/azure-storage-node#94]
var query = TableQuery.top(options.maxResults); 

should be 

var query = new TableQuery()
.top(options.maxResults);

**Comment by yaxia** [comment]
@JakeRad Good catch! Thanks for reporting the issue. We are working on the fix and will have it in an upcoming release.

**Comment by yaxia** [comment]
Please get the latest release (0.7.0) for the fix. Thanks.
