### ISSUE TITLE
Table Storage : bad performance for simplest retrieveEntity

### ISSUE THREAD

**Issue by fklingler** [Azure/azure-storage-node#95]
I'm having what I think really bad performances on my server for a simple retrieveEntity on Table Storage.

On a EUWEST storage account (servers are in France), with this really simple table with only one record:
![image](https://cloud.githubusercontent.com/assets/282439/10815694/f56a1692-7e2d-11e5-8616-73a3fda28728.png)

And this simple test code:

``` js
var azureStorage = require('azure-storage');
var tableService = azureStorage.createTableService();

var hrstart;
var startTimer = function() {
  hrstart = process.hrtime();
}
var consoleTimerDuration = function(prefixString) {
  console.log(prefixString + process.hrtime(hrstart)[1]/1000000 + "ms");
}

startTimer();
tableService.retrieveEntity('test', 'test', 'testtest', function(error, result, response) {
  if (!error) {
    consoleTimerDuration("retrieve: ");
    console.log(result);
  }
});
```

I'm having an average response time of 275ms. This is very slow, as I intent to make 2 of these retrieveEntity requests for each of my user web requests (using https://github.com/jamesdixon/node-ember-cli-deploy-azure-tables/).

Is this kind of response time normal? Am I doing something wrong? Should I use something else than Table Storage?

**Comment by freakyfriday** [comment]
François try repeat your test on a server within the same Azure data center
as your Azure tables. The latency you're experiencing may relate to your
internet connection.

A query based on exact PartitionKey and RowKey is the fastest query you can
do on Azure tables. I usually get results back in under 100ms maximum with
Azure tables EastUS from a nodejs server within the same data center.

Francesco

**Comment by fklingler** [comment]
I'm not really using Azure for the web servers, I'm using Scalingo, an Heroku equivalent, based in Europe with servers I believe in France. The response time with this retrieveEntity is approximately the same on their servers as on my PC.
I shouldn't have 200 or more ms to reach EU West Azure servers from a high speed datacenter in France, this is really problematic. I will reach my server provider to know what they think of this.

**Comment by freakyfriday** [comment]
200ms between Azure EU West servers and a data centre in France does sound
really slow. Hopefully someone else here can give you some pointers.

In the mean time maybe try another Azure data centre for your table storage
and see if there's any change.

**Comment by yaxia** [comment]
@fklingler Does the issue still exist? I tried your code for 10 time and the results are:
```
retrieve: 66.8331ms
retrieve: 75.6887ms
retrieve: 101.8536ms
retrieve: 66.3101ms
retrieve: 65.25ms
retrieve: 77.1002ms
retrieve: 66.4318ms
retrieve: 64.9832ms
retrieve: 65.7914ms
retrieve: 106.386ms
```
Could you share some information of your environment? Thanks.

**Comment by fklingler** [comment]
Yes, this issue still exist. I'm still having 200-250-300ms response times when I run the script in the datacenter container

The Azure container is set as local redundant, in the Western Europe region.
What other infos do you need?

**Comment by XiaoningLiu** [comment]
@fklingler, do you still have the issue? Most likely it's related to the network connection speed to the Azure Storage server.
