### ISSUE TITLE
Copy Container of blobs

### ISSUE THREAD

**Issue by CrackerakiUA** [Azure/azure-storage-node#96]
I didn't find anywhere in the code a function which will copy whole container with blobs to new container. This is really must have if we don't have it yet, if we have, point me to some part of code that i can read about it.

**Comment by yaxia** [comment]
@CrackerakiUA We don't have a API to copy a whole container yet, but you can list all the blobs in the container and copy them to another container. Could it resolve your problem?

**Comment by CrackerakiUA** [comment]
@yaxia, yes i have done it this way. But we must have a way to do this :)

**Comment by vinjiang** [comment]
@CrackerakiUA Thanks for your feedback, we've put the request in our tracking list. Upon customers' feedback, will evaluate it.
