### ISSUE TITLE
getContainerProperties Do not return size of container.

### ISSUE THREAD

**Issue by CrackerakiUA** [Azure/azure-storage-node#97]
I search this function but couldn't find this info inside result or add any option to show it. Generally it is possible to get size of an blob container without reading each blob in it?

**Comment by yaxia** [comment]
The only option here is to enumerate all blobs and add up their lengths. Please note that if you are looking for billable size then this will not return an accurate number as snapshots are only billed for unique blocks/pages data. You can find more information about how the billable size is calculated in this blogpost: http://blogs.msdn.com/b/windowsazurestorage/archive/2010/07/09/understanding-windows-azure-storage-billing-bandwidth-transactions-and-capacity.aspx 
If you want to get capacity for blob overall (not per container), you might refer to: https://msdn.microsoft.com/en-us/library/azure/hh343264.aspx
