### ISSUE TITLE
Typo for name of `exports.generateDevelopmentStorageCredendentials`

### ISSUE THREAD

**Issue by nadinengland** [Azure/azure-storage-node#99]
It appears that Credentials has been spelt incorrectly, this also appears in the annotated documentation.

https://github.com/Azure/azure-storage-node/blob/master/lib/azure-storage.js#L29

**Comment by yaxia** [comment]
@nadinengland Thanks. The issue has been noted and will be fixed in a later release.

**Comment by yaxia** [comment]
Please get the latest release (0.7.0) for the fix. Thanks.
